### ISSUE TITLE
Do not assemble the temperature matrix if the problem is temperature independent 

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#1002]
For temperature independent problem, current linear solver will skip solving the temperature system once we know that the RHS is zero. However since we only know the RHS until we assemble the system and RHS at the same time, which still costs a lot of time. 

A better way will be to add some global parameter to show that it is a temperature independent problem, so the solver can totally bypass the matrix assembling and solving...

**Comment by bangerth** [comment]
Can't you already achieve this by using the "Stokes only" solver option?

**Comment by gassmoeller** [comment]
I agree with Wolfgang's comment. The nonlinear solver scheme should determine, which equations to assemble and solve. I think you were looking for a scheme that only assembles and solves composition and stokes, but not temperature. That currently does not exist, but could be created, and in particular when we finally tackle #972 and #1279 this should be easy. I am closing this issue for now.
