### ISSUE TITLE
FreeSurface: use manifolds

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1006]
We currently detach the manifold after the initial refinement. I think with the new MappingQ1Eulerian we should be able to keep the manifold attached.

Can we get a test that verifies, that things work and if yes remove ``detach_manifolds()``?

@ian-r-rose ?

**Comment by ian-r-rose** [comment]
This can be closed.

**Comment by bangerth** [comment]
Great. Can't you close things yourself?

**Comment by ian-r-rose** [comment]
It wasn't my issue.
