### ISSUE TITLE
Link cookbooks/tutorials to the examples in Turcotte/Schubert, "Geodynamics"

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1027]
This would more closely track what typical geodynamics courses do. It would require someone who has gone through such a course and make the necessary connections.

**Comment by egpuckett** [comment]
I will add one example perhaps called 

  "2D Convection_Rolls.prm

This requires the BA equations.

**Comment by lkellogg** [comment]
I can help with this.

**Comment by jdannberg** [comment]
I think in general, our cookbooks are quite different from the examples in Turcotte and Schubert. If we want to add specific cookbooks that correspond to examples from their "Geodynamics" book, I think it would be more useful to add them to our list of future cookbooks in issue #2110.
