### ISSUE TITLE
Clarify the description of 'box' model

### ISSUE THREAD

**Issue by spco** [geodynamics/aspect#1033]
The 'box' model in the manual, for both Boundary temperature model and Boundary composition model, has the description 

> ‘box’: A model in which the temperature is chosen constant on all the sides of a box.
> ‘box’: A model in which the composition is chosen constant on all the sides of a box.

This is not really consistent with the reality - it sets Neumann at any boundary that is not specified in the prm. The description should be updated to clarify this.

I'd do this myself, but I'm not sure exactly where to do this - is parameters.tex auto-generated from somewhere else, or is it sufficient to edit that directly?

**Comment by gassmoeller** [comment]
parameters.tex is automatically generated from the description string that is provided in in the declare_parameters() function, or the ASPECT_REGISTER_.... macro at the bottom of the .cc file. So feel free to improve the description in the box.cc files, and it will be updated in parameters.tex the next time Timo updates it (maybe it can be included in #1024).

**Comment by spco** [comment]
@tjhei - do you want this in #1024 or shall I do it separately?

**Comment by gassmoeller** [comment]
I would say prepare it separately, and we can ask @tjhei to update #1024 if it is not already merged at the time when your update is merged.

**Comment by tjhei** [comment]
We will update the parameters.tex again at some point after the hackathon. No need in trying to always keeping it in sync.

**Comment by gassmoeller** [comment]
Closed by #1043
