### ISSUE TITLE
SolKz Benchmark Error: Unknown CMake command "DEAL_II_INITIALIZE_CACHED_VARIABLES"

### ISSUE THREAD

**Issue by egpuckett** [geodynamics/aspect#1036]
When one tries to run the SolKz benchmark by running cmake in 

  aspect/benchmarks/solkz

cmake returns the error 

   CMake Error at CMakeLists.txt:32 (DEAL_II_INITIALIZE_CACHED_VARIABLES):
   Unknown CMake command "DEAL_II_INITIALIZE_CACHED_VARIABLES".

This error message is not very helpful.

In other words, 

  (master) $ cd benchmark/solkz
  (master) $ ls
  CMakeLists.txt  solkz.cc  solkz.prm
 (master) $ cmake .
  CMake Error at CMakeLists.txt:32 (DEAL_II_INITIALIZE_CACHED_VARIABLES):
  Unknown CMake command "DEAL_II_INITIALIZE_CACHED_VARIABLES".

-- Configuring incomplete, errors occurred!

cmake returns the error 

   cmake -D ASPECT_DIR=~/local/aspect-git/timo-build .
   CMake Error at CMakeLists.txt:32 (DEAL_II_INITIALIZE_CACHED_VARIABLES):
   Unknown CMake command "DEAL_II_INITIALIZE_CACHED_VARIABLES".

This error message is not very helpful.

**Comment by gassmoeller** [comment]
Gerry can you try running 'cmake -D ASPECT_DIR=your_aspect_dir .' and replace 'your_aspect_dir' by the path to your aspect.

**Comment by egpuckett** [comment]
Hi Rene,

That's what Timo had me do and it works.  The origin of this 'Issue' is that Timo asked me to submit the issue and I think he specifically asked me to write

  "This error message is not very helpful."

(I may have put more details in the Issue than necessary,)  I think Timo wanted a record of this particular 'feature' so that he or someone else would change it.

Do you want to see the output from when I ran

  cmake -D ASPECT_DIR=your_aspect_dir

**Comment by gassmoeller** [comment]
No you do not need to post the output. I was just thinking you were still struggling and wanted to give advice that might solve the problem, but if you have already solved it that is great.

**Comment by tjhei** [comment]
Yeah, it looks like cmake is finding an (incomplete?) version of ASPECT and then fails finding deal.II. Let me try to reproduce this.

**Comment by gassmoeller** [comment]
Since there have been no comments since more than half a year I suppose this issue is fixed? Feel free to reopen if it is still an issue.
