### ISSUE TITLE
Make active particles as simple to use as possible

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1069]
Main outcome of the discussion with @naliboff, @lkellogg and @cedrict.

When I implemented #1068 I also thought that maybe every particle property should be handled like a compositional field (in the sense that they use the same plugins for prescribing initial conditions, maybe even using the reaction_terms of the material model to do the update). This would make the switch between compositional fields and particles even easier. I need to think more about the structure for that, and need to make sure the particle properties are not diffused by going through the finite-element projection. This issue is mostly a reminder.

**Comment by naliboff** [comment]
@gassmoeller - Thanks again for your patience with the particle discussion :)!  I'm testing models now with the compositional fields advected via the normal field method vs 'tracer' method.  I'm curious as well to see about the diffusion issue as well as run time vs 'accuracy' as a function of particle density.  I will post relevant results here as they come up.  Huge thanks again for the entire particle implementation!

**Comment by gassmoeller** [comment]
I think this is partly addressed, and partly this issue is too generic to be of much use. I will close this, and reopen separate specific issues when the topic arises again.
