### ISSUE TITLE
add installation instructions for astyle

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1084]

**Comment by bangerth** [comment]
Should go to whatever place we have that discusses how to contribute patches.

**Comment by bjs2** [comment]
I just installed it on my laptop.

**Comment by gassmoeller** [comment]
Contributing.md now contains a link to the astyle software package, and they have installation instructions. I would prefer to not duplicate those instructions. Feel free to reopen, if you feel strongly about it.

**Comment by tjhei** [comment]
It is also available (but hidden) inside candi. Maybe that is worth mentioning.
