### ISSUE TITLE
Fix bibtex entries for ASPECT

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1097]
There are several bibtex entries in the tree for ASPECT. Where we say things such as "Advanced Solver for Problems in Earth ConvecTion", all capital letters have to be enclosed in braces to make sure they are also capitalized after bibtex runs.

**Comment by bangerth** [comment]
@egpuckett suggests that we use a style file, such as the Chicago Manual of Style.

**Comment by njinju** [comment]
I will work on fixing the bibtex entries for ASPECT

**Comment by bangerth** [comment]
Fixed by #2364.
