### ISSUE TITLE
Indenting of test .cc file

### ISSUE THREAD

**Issue by spco** [geodynamics/aspect#1117]
When calling `./doc/indent` from the main directory, this picks up the file `tests/resume_free_surface.cc` and indents that. This is a bit annoying as this gets picked up as a tracked file and a call to `git add -u`, my usual, stages this change. I'm bound to unintentionally add this to a commit at some point.

Could we tweak the .cc file to have the correct indentation, or is there a better fix/should I use a different workflow?

**Comment by bangerth** [comment]
#628 introduced this, I think.

**Comment by bangerth** [comment]
Actually, it was #1110.
