### ISSUE TITLE
Traction boundary conditions and periodic boundaries

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#1124]
There is no Assert/warning if both periodic boundary and traction boundary conditions are used for the same boundary. This is confusing, as the traction boundary condition is not applied at the given boundary.

**Comment by anne-glerum** [comment]
on it

**Comment by anne-glerum** [comment]
This can be closed now right?

**Comment by gassmoeller** [comment]
Yes, closed by #1512. Feel free to close issues yourself, if you think they are addressed (I am actually not quite sure if you can do that, or if you can only close you own issues, lets try this at some point).

**Comment by anne-glerum** [comment]
I can only close my own issues :)
