### ISSUE TITLE
Floating point exception thrown when dealii is built with PetSc

### ISSUE THREAD

**Issue by hlokavarapu** [geodynamics/aspect#1132]
@egpuckett 

After installing deal.ii (v8.4.1) using candi with PetSc enabled and building ASPECT with PetSc toggled off, a floating point exception is thrown during the building of Stoke's preconditioner. I have attached a bug_log.txt that contains the back trace as well as a parameter file to reproduce the bug.

[bug_log.txt](https://github.com/geodynamics/aspect/files/369588/bug_log.txt)

[solkz.prm.txt](https://github.com/geodynamics/aspect/files/369592/solkz.prm.txt)

**Comment by gassmoeller** [comment]
Please check if the model runs if you disable floating point exceptions while building ASPECT.
It might be that your system incorrectly triggers FPEs although there are none (also see #789 for a discussion). If the problem only occurs when adding PETSC to deal.II (without even using it), this sounds like a false alarm.

**Comment by bangerth** [comment]
I'd actually be interested in seeing where this happens. @hlokavarapu -- can you run this in a debugger and get a backtrace?

**Comment by hlokavarapu** [comment]
@gassmoeller, @bangerth:

I am unable to reproduce this bug on my local machine and do not have access to the cluster from which me and @egpuckett originally ran into this. Once I am back in the states, I will definitely follow up on this thread.

**Comment by bangerth** [comment]
@hlokavarapu -- can you still reproduce this? If not, maybe we should just close this. We can always re-open if we find that the problem persists.

**Comment by hlokavarapu** [comment]
Sounds good, Wolfgang. I'll attempt to reproduce this case and provide more details if issue persists.
