### ISSUE TITLE
Write manual entry on writing tests

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1140]
Probably mention how to run the tests as well.

**Comment by bangerth** [comment]
@gassmoeller  had a nice description about this in a recent email post:

"Take one of the existing parameter files in the tests/ directory, modify it to use the new feature, check that the new feature does what it is supposed to do, and then just add the parameter file to the tests directory. You will then need to add another folder to that directory that is named like the parameter file, and add the model output files that proof that the feature is working (in your case likely just the file log.txt, and statistics. rename log.txt to screen-output for historical reasons). The test and output files should be as small and quick to run as possible."

**Comment by class4kayaker** [comment]
Would it be useful for someone to write up a sparse skeleton entry to gather comments, or should a pull request on this issue wait until the entry is only likely to require proofreading?

**Comment by bangerth** [comment]
I think it could work either way. We could also engage in some collaborative writing. If I came up with an outline, would you like to run with it and market it into a regular section of the manual?

**Comment by class4kayaker** [comment]
I was asking because I had thought of and started throwing together a basic outline, but I felt that the current state was not anywhere near sufficient to actually be used and I am expecting to be rather busy in the near future. I will start a pull request with my current progress for collaboration then.

**Comment by bangerth** [comment]
Good plan.

**Comment by gassmoeller** [comment]
Addressed by #1168.
