### ISSUE TITLE
Call compute_current_constraints only once in Simulator::set_initial_temperature_and_compositional_fields()

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1145]
#1144 shows that we currently call `compute_current_constraints` for the temperature and each compositional field during initial value imposition. That is wasteful: it should be perfectly sufficient to do this only once at the very end, right before we copy all distributed vectors into the local vectors.

All this will require is moving the call to `compute_current_constraints` down below the loop over all compositional fields, as well as the calls to where we copy vector blocks. The latter requires breaking duplicating the loop header over all compositional fields below there as well.

**Comment by bangerth** [comment]
This would also reduce the code duplication introduced by #1144.

**Comment by gassmoeller** [comment]
Closed by #1154.
