### ISSUE TITLE
Periodic boundary condition implementation for the DG advection solver

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#1178]
Current DG implementation doesn't support the periodic boundary condition, which I guess is due to not initialize  any constraint matrix to the DG matrix during the setup dof. The new implemented make_flux_sparsity_pattern in deal.ii seems supporting the periodic boundary which I may wrong, so @bangerth , @tjhei , @gassmoeller , @spco , does any of you have suggestions on the possible extension?

**Comment by bangerth** [comment]
I think this should not be terribly difficult to implement. We just need to (i) make sure the sparsity pattern is set up correctly including the periodicity, and (ii) we build the DG terms at the periodic boundaries.

**Comment by gassmoeller** [comment]
Closed by #1522.
