### ISSUE TITLE
Testsuite directories

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1179]
Since the hackathon I get occasional (seemingly random) failures of some tests with the following ctest error message:

`262: /bin/sh: 1: cannot create /home/rengas/Software/Aspect-Versionen/aspect/debug/tests/output-particle_visualization_particle_count/solution/solution-00000.0000.gnuplot.cmp.notime: Directory nonexistent`

Is it possible that ctest sometimes does not create the right directory structure since we changed the output folder into solution/ and output/ subfolders? Does anyone else observe this behavior?

**Comment by bangerth** [comment]
Shouldn't ASPECT create that directory itself before starting to populate it with output files? Or do we create the `.cmp.notime` file from cmake before we even run ASPECT? In the latter case, creating the sub-directories of the `output-testname` directory needs to happen in the cmake script...

**Comment by tjhei** [comment]
yeah, I think this is a bug. This is my fault, but I am not sure how to reproduce it here. How often does this happen for you?

**Comment by gassmoeller** [comment]
It is a bit random, but one test that pretty consistently fails for me after deleting my build/tests folder and redoing cmake is `particle_visualization_particle_count`. After creating the according output-particle_visualization_particle_count/solution directory everything is fine and the test passes.
In general it does happen on maybe 5-10% of the tests for me, and I can not figure out why they are special (some of them are just copies of other tests that pass, having exactly the same reference solution and directory structure). Maybe it is a cmake version issue? I use 2.8.12.2.

**Comment by bangerth** [comment]
In `tests/CMakeFiles.txt`, we create the output directory in line 183. I think we probably need something along the lines (pseudocode)
```
  FOREACH (i in subdirectories of the source directory)
    FILE(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/output-${_test}/$i)
  ENDFOREACH()
```
right after it.
