### ISSUE TITLE
Further considerations for time step lengths etc

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1214]
#1210 updates the logic for which time steps are used when, based on the observation in #929 that we seem to be using different time step lengths at different points during a time step's computations.

The change in #1210 did not adjust what is being written to the `statistics` file, primarily because this would have caused changes to essentially all tests. But it would be nice to do anyway, just for consistency. For example, taking `tests/diffusion/statistics' as a representative, we have

```
#1: Time step number
#2: Time (seconds)
#3: Number of mesh cells
#4: Number of Stokes degrees of freedom
#5: Number of temperature degrees of freedom
#6: Iterations for temperature solver
#7: Iterations for Stokes solver
#8: Velocity iterations in Stokes preconditioner
#9: Schur complement iterations in Stokes preconditioner
#10: Time step size (seconds)
...
0 0.000000000000e+00 1024 9539 4225 12 26 27 26 2.388512299275e+06 -6.95209271e-17 5.20833333e-03 1.00000000e+00 5.20833333e-03 -3.39352455e-22 -3.68442745e-22 -3.65333948e-45 -9.60000000e-05 
1 2.388512299275e+06 1024 9539 4225 48 29 30 30 7.603813515720e+06  0.00000000e+00 4.38185361e-02 1.00000000e+00 4.38185361e-02 -2.12041692e-18 -2.98559321e-18  5.09335080e-15 -2.13724705e-05 
...
```

I interpret that as saying that the second column is the _start time_ of the time step, that 2.388e6 is the time step, and that all quantities that follow are evaluated at the _end_ of the time step. I find that awkward -- we should probably output the _same time_ as is used for evaluating the solution.

At the same time, I'm actually not clear whether what I say is correct. The current logic for computing looks like this:

```
    // start the principal loop over time steps:
    do
      {
        start_timestep ();

        // then do the core work: assemble systems and solve
        solve_timestep ();

        pcout << std::endl;

        // get new time step size
        // for now the bool (convection/conduction dominated)
        // returned by compute_time_step is unused, will be
        // added to statistics later
        const double new_time_step = termination_manager.check_for_last_time_step(
                                       std::min(compute_time_step().first,
                                                parameters.maximum_time_step));

        if (parameters.convert_to_years == true)
          statistics.add_value("Time step size (years)", new_time_step / year_in_seconds);
        else
          statistics.add_value("Time step size (seconds)", new_time_step);
    // start the principal loop over time steps:
    do
      {
        start_timestep ();

        // then do the core work: assemble systems and solve
        solve_timestep ();

        pcout << std::endl;

        // get new time step size
        // for now the bool (convection/conduction dominated)
        // returned by compute_time_step is unused, will be
        // added to statistics later
        const double new_time_step = termination_manager.check_for_last_time_step(
                                       std::min(compute_time_step().first,
                                                parameters.maximum_time_step));

        if (parameters.convert_to_years == true)
          statistics.add_value("Time step size (years)", new_time_step / year_in_seconds);
        else
          statistics.add_value("Time step size (seconds)", new_time_step);
```

What this suggests is that the quantity we put into the output file is not in fact the time step size that was used to compute the _current_ time step, because it is only evaluated _after_ we call `solve_timestep()`.

Opinions?

**Comment by bangerth** [comment]
That last statement would suggest that the time and postprocessed values in the statistics file are actually in sync, but that the time step size we output is in fact not the one used for the current time step, but the one for the *next one* instead. In that case, we should just output the *current* time step into the statistics file. In other words, shift the time step column down by one.

That would probably be zero for the first time step right now, as makes sense because we solve for the temperature/compositions first, before we even have a velocity field, so we can't yet advect along anything.

**Comment by tjhei** [comment]
> That last statement would suggest that the time and postprocessed values in the statistics file are actually in sync, but that the time step size we output is in fact not the one used for the current time step, but the one for the next one instead. In that case, we should just output the current time step into the statistics file. In other words, shift the time step column down by one.

Agreed. Maybe also move it further up in the code to be column 3?

**Comment by class4kayaker** [comment]
When I read through the current logic, it was obvious that the time reported is actually the time at the end of the update iteration, ie t^{n+1} if we start at t^n. Since dt=0 for the first iteration t^{n+1}=t^n and the initialization is done at the correct time.

You are correct that the time step reported is used for the following update iteration.

**Comment by bangerth** [comment]
So that sounds like we all agree that the time step column should just shift down one row?

I don't care much which column it occupies. This is determined by the order in which we write into columns from within the code, and we can't actively move this around.

**Comment by gassmoeller** [comment]
Well we can pretty actively move that around, because if we output the current timestep and not the new one, we might as well move that output into the `start_timestep()` function. I do not care much where it appears, but I would not be opposed to moving it there (it further simplifies the timestep loop, and I would appreciate that).

**Comment by gassmoeller** [comment]
I think this was adressed by #1213 and #1218.
