### ISSUE TITLE
CMake 2.8.11 fails for tests

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1219]
Since #1190 we create test output subdirectories and for that use the CMAKE command: `GET_FILENAME_COMPONENT(_dir ${_output} DIRECTORY)`
unfortunately this was changed between cmake 2.8.11 and 2.8.12, and versions <= 2.8.11 only accept:
`GET_FILENAME_COMPONENT(_dir ${_output} PATH)`
Now 2.8.11 is quite old (I use it, because it is preinstalled on a cluster), and I can easily replace it with an own build version, but we make no requirements on cmake for ASPECT itself, and the deal.II website states anything newer than 2.8.8 should work, so I was just wondering if we should do one or more of the following:
- mention this requirement? every desktop system from Ubuntu 14.04 on already has cmake 2.8.12 packaged, so it will only affect users from very conservative distributions and cluster systems with prepackaged old cmakes
- provide a better error message? Something like: require newer cmake version (current message is:  
`CMake Error at tests/CMakeLists.txt:182 (GET_FILENAME_COMPONENT):
   get_filename_component unknown component DIRECTORY)`
- Add a workaround to the CMakeLists.txt for older versions?

**Comment by bangerth** [comment]
Since the error message doesn't actually help users unless they upgrade cmake, you may as well require a newer cmake version in the top-level `CMakeLists.txt`. On the other hand, if you do a workaround, you may as well do it unconditionally.

What is the difference between `DIRECTORY` and `PATH`? Could we extract from the latter what we get from the former?

**Comment by tjhei** [comment]
I will take a look.

**Comment by bangerth** [comment]
https://cmake.org/cmake/help/v3.4/command/get_filename_component.html says that `PATH` is simply the legacy form of `DIRECTORY`. In other words, they should be interchangeable. Patch forthcoming.
