### ISSUE TITLE
shell_simple_3d crashes

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#123]
When running shell_simple_3d.prm with 32 processors, it works for 16 time steps but then I get this:

*** Timestep 15:  t=7.83037e+06 years
   Solving temperature system... 21 iterations.
   Solving Stokes system... 30+14 iterations.

   Postprocessing:
     RMS, max velocity:                  0.0434 m/year, 0.162 m/year
     Temperature min/avg/max:            973 K, 1409 K, 1973 K
     Heat fluxes through boundary parts: -7.917e+12 W, 3.016e+12 W
     Writing depth average               output/depth_average.vtu

Number of active cells: 74,324 (on 6 levels)
Number of degrees of freedom: 3,053,696 (2,213,988+101,712+737,996)

*** Timestep 16:  t=8.35066e+06 years
   Solving temperature system... 19 iterations.
   Rebuilding Stokes preconditioner...
   Solving Stokes system... 30+19 iterations.

   Postprocessing:
     Writing graphical output:           output/solution-00008
     RMS, max velocity:                  0.00439 m/year, 0.0298 m/year
     Temperature min/avg/max:            973 K, 1408 K, 1973 K
     Heat fluxes through boundary parts: -7.68e+12 W, 2.922e+12 W

*** Timestep 17:  t=1.00836e+07 years
   Solving temperature system...

--------------------------------------------------------
An error occurred in line <828> of file </u/bangerth/p/deal.II/3/install-bottom/include/deal.II/lac/solver_gmres.h> in function
    void dealii::SolverGMRES<VECTOR>::solve(const MATRIX&, VECTOR&, const VECTOR&, const PRECONDITIONER&) [with MATRIX = dealii::TrilinosWrappers::SparseMatrix, PRECONDITIONER = dealii::TrilinosWrappers::PreconditionILU, VECTOR = dealii::TrilinosWrappers::MPI::Vector]
The violated condition was: 
    false
The name and call sequence of the exception was:
    SolverControl::NoConvergence (this->control().last_step(), this->control().last_value())
Additional Information: 
Iterative method reported convergence failure in step 737996 with residual 3.30962e+26
--------------------------------------------------------

Does anyone else see this? I'm running with
mpirun -np 32 aspect ../Aspect/cookbooks/shell_simple_3d.prm

**Comment by tjhei** [comment]
good news: it looks like it is working with the recent manifold changes (my file, 42 timesteps and running). We need to do some more testing, though. :+1:

**Comment by bangerth** [comment]
Let's get a release out right now, quick, pronto, before anyone finds something that doesn't work!  ;-)

**Comment by bangerth** [comment]
Confirmed to work now. Not fast, but that's because it's a big model I suppose.
