### ISSUE TITLE
Non c++ scripts (python, etc) in ASPECT?

### ISSUE THREAD

**Issue by naliboff** [geodynamics/aspect#1234]
Hi all,

Is there a set of rules/standards/policy for including non c++ scripts within ASPECT?  For example in the folder benchmark/shear_bands there are a number of python post-processing scripts.  

I'm currently working on a cookbook for using CRUST1.0, which uses a pre-processing script (written in Julia) to make a compositional field initial condition ascii file from a CRUST1.0 data file.  Is this an acceptable use of a non c++ script?  Eventually this will be ported into an initial conditions option (similar to S20RTS), but that is a ways off.

Cheers,
John

**Comment by bangerth** [comment]
Yes, I think that's acceptable in general. For Julia in particular, you probably want to consider that it may not be available on every machine. On the other hand, it's probably not all that hard to install through package managers. 

In any case, I'm not too worried. Just go ahead.

**Comment by naliboff** [comment]
Great, I will continue as planned then.  Julia installation is indeed quite easy via package managers on linux or mac (also has binary install option). Cheers.

**Comment by tjhei** [comment]
I would prefer bash and python scripts over something like Julia. I, for example, am unlikely to bother an admin to install julia on the machines they manage for me.

**Comment by naliboff** [comment]
Thanks for the second data point.  I actually have versions of the script in matlab and python, but have simply found Julia a bit more readable and intuitive than both. I like scripting in bash as well, but this may be a bit too complex for that.  I'll think this over a bit more before doing any commits.  Thanks again.

**Comment by bangerth** [comment]
@naliboff -- did you get enough guidance? Or can we close this issue?

**Comment by gassmoeller** [comment]
Since this discussion seems resolved for now, I close this issue. Feel free to reopen when the need arises.
