### ISSUE TITLE
pure Neumann temperature solve fails

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1243]
If you prescribe no fixed boundary for the temperature, the solver fails. We should raise an error or make the solver work (by enforcing a mean value?).

[lev_solver_prob.prm.txt](https://github.com/geodynamics/aspect/files/514646/lev_solver_prob.prm.txt)

**Comment by bangerth** [comment]
That makes no sense to me. The equation has a time derivative which gives rise to a mass matrix that should make the system positive definite *even if no boundary conditions are given*. Why is this term not sufficient?

**Comment by spco** [comment]
So I had a play with this. 
Changing the `Temperature solver tolerance` parameter to 1e-9 gives some very strange behaviour. I ran it (one process, Aspect commit e516b9b8d2fccef, dealii branch from 6391774e3c10 with the periodic_neighbor_face_no fix (note this prm doesn't use dG anyway)) a number of times. 

Below is the table of iterations for the temperature solve. Some complete (this prm only requires 3 timesteps) while others fail to converge in the second step:

```
0 540 56
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 4.03885e-10.
0 260 56
0 456 56
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 3.57819e-09.
0 540 56
0 372 56
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 1.04768e-09.
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 2.09861e-09.
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 1.76357e-09.
0 Iterative method reported convergence failure in step 1000. The residual in the last step was 8.50476e-09.
0 764 55
0 988 56
```
Evidently the convergence stalls around 1e-09, and from then on it's just fluke if we hit a vector with small enough residual.

My question is why do we see such variation? Is this simply a case of numerical sensitivity in the assembly or solve, which is then blown up by the fact that the convergence stalls at a value that's close to the tolerance?

I'm not sure what this means for the problem of why this fails to converge, other than identifying that the convergence seems to stall around 1e-09.

**Comment by spco** [comment]
I'm currently leaning towards the idea that this may be due to not explicitly initializing the values of `solution` and `old_solution` on the first timestep: this is then transferred into `current_linearization_point` at `core.cc:1924`, then `distributed_solution.block(block_idx)` in `solver.cc:441` which (I believe) is used for the initial guess for the temperature solve.

**Comment by bangerth** [comment]
What happens if you just initialize to zero? (But this should happen automatically, I would suppose, just by initializing the vector's size.)

**Comment by spco** [comment]
That's a good point. Makes no difference.

**Comment by spco** [comment]
Hmm yes, I've found that now. So we _do_ initialize `distributed_solution.block(block_idx)` on the first timestep, my mistake. Still no idea where the variability comes from then.

**Comment by tjhei** [comment]
> That makes no sense to me. The equation has a time derivative which gives rise to a mass matrix that should make the system positive definite even if no boundary conditions are given. Why is this term not sufficient?

Don't we start with dt=0 in the first timestep?

**Comment by bangerth** [comment]
Yes, which would mean that we have to solve *only* for the mass matrix :-)
