### ISSUE TITLE
compute_derived_quantities_vector warnings

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1284]
I am getting dozens of warnings from our postprocessors with the development version of deal.II
```
warning: ‘void dealii::DataPostprocessor<dim>::compute_derived_quantities_vector(const dealii::DataPostprocessorInputs::Vector<dim>&, std::vector<dealii::Vector<double> >&) const [with int dim = 3]’ was hidden [-Woverloaded-virtual]
```

@bangerth This is caused by the change to deal.II where you introduced an overload to that function, see https://github.com/dealii/dealii/pull/3333

I know we can silence the warning in ASPECT by adding ``using DataPostprocessor<dim>::compute_derived_quantities_vector;`` in every class deriving from ``DataPostprocessor``, but this doesn't seem like an elegant solution. Maybe we should have introduced the new function in deal.II under a different name? Other suggestions?

**Comment by bangerth** [comment]
Yes, I've seen this too. I'm a bit bummed that I didn't think of this.

I can change the function names -- it's only bee a couple of months or so since the names were introduced, not backward compatibility issues. What do you suggest?

**Comment by tjhei** [comment]
> What do you suggest?

One can argue that it is okay because 1) it is just a warning and 2) it will go away after we remove the deprecated functions. Sadly this is going to take a while, I think.

> I can change the function names

I don't think they have been used much (if at all), so this is the cleanest solution. So I am in favor if you don't mind going back and changing that. Now the question is what name to give them...

**Comment by bangerth** [comment]
I might be able to do it, but I'm so completely jetlagged that doing intellectual work such as coming up with names is entirely out of my scope today. If someone tells me a new name, I can implement this tomorrow.

**Comment by tjhei** [comment]
I don't have a great suggestion for the name, but maybe ``compute_quantities_vector``? Or we could highlight that this is the local operation on a cell by using something like ``compute_local_quantities_vector`` or ``cellwise_quantities_vector``. Finally, I am not sure that the distinction between scalar/vector is really that helpful or if we should always work with the vector version to make the interface much easier to understand.

**Comment by bangerth** [comment]
The fact that things are cellwise is actually not even exposed to these functions. They just get a bunch of points, wherever they may be. (Might be faces, or maybe batches of cells, or sub-cells.) So maybe `compute_quantities_vector` as you suggest? I could also suggest `evaluate_vector_data` and `evaluate_scalar_data`. I actually kinda like these names.

An alternative could be to just pass `-Wno-overloaded-virtual` to the ASPECT compilation....

**Comment by tjhei** [comment]
> The fact that things are cellwise is actually not even exposed to these functions.

But one of the reasons we did the reorganization was to be able to pass a cell iterator, I thought?

**Comment by tjhei** [comment]
> evaluate_vector_data

I like the "evaluate" part, but "vector/scalar" is confusing because it makes it sounds like the data you evaluate is scalar or vector valued.

**Comment by bangerth** [comment]
Good point. `evaluate_to_scalar` and `evaluate_to_vector`? `transform_into_scalar` and `transform_into_vector`?

**Comment by tjhei** [comment]
> Good point. evaluate_to_scalar and evaluate_to_vector? transform_into_scalar and transform_into_vector?

The name indicates if the input is scalar or vector, so shouldn't it be ``evaluate_from_scalar`` or something?

Naming things is hard. :-(

**Comment by bangerth** [comment]
On 12/04/2016 11:00 AM, Timo Heister wrote:
> The name indicates if the input is scalar or vector, so shouldn't it be
> |evaluate_from_scalar| or something?

Yes, you are right. I get confused about this every time, whether the 
scalar/vector is inputs or outputs. So maybe `evaluate_scalar_field` and 
`evaluate_vector_field`?

> Naming things is hard. :-(

Yes, but that's why we discuss these things in detail these days, so that we 
get it right. I wished we had put the same amount of diligence into this 10 or 
15 years ago. We could have avoided many an issue.

**Comment by tjhei** [comment]
> So maybe `evaluate_scalar_field` and
> `evaluate_vector_field`?

I like it!

> I wished we had put the same amount of diligence into this 10 or
> 15 years ago.

Oh, you don't have to go that far back. I have been committing horrible stuff that was not thought out just a few years ago. :-)

**Comment by bangerth** [comment]
Let's call it progress then :-)

**Comment by bangerth** [comment]
Fixed by https://github.com/dealii/dealii/pull/3664
