### ISSUE TITLE
Visualization postprocessor does not check for unique plugins

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1349]
When selecting the same visualization plugin more than once in release mode there is no error message, and the paraview output files are corrupted. Deal.II has an internal Assert, but since this is an issue in the input file, we should add an AssertThrow to catch it. This is mostly a reminder for me to come back to the issue.

**Comment by bangerth** [comment]
Is this an issue everywhere we use `MultipleSelection` as the pattern of parameters? Do we need to make the list unique in other places as well?

**Comment by gassmoeller** [comment]
I think we have the same issue in many places, it might not always lead to crashes, but it might cause a number of bugs. I will try to add a utility function that deals with it. Something like 'check_list_items_are_unique' and throw an assertion if there is a duplication.

**Comment by gassmoeller** [comment]
It is a bit creepy that Github now closes issues automatically when they are associated with a merged pull request. I wonder how it would decide if a PR only fixes part of an issue?

**Comment by bangerth** [comment]
Not creepy at all. If you specifically say "closes #abcd" or "fixes #abcd" in a pull request, then that automatically closes issue #abcd. It's the specific way in which you reference #abcd that makes that happen, not that you just reference it at all.

**Comment by gassmoeller** [comment]
I did not know. Clever :smile:.

**Comment by bangerth** [comment]
https://github.com/blog/1506-closing-issues-via-pull-requests
