### ISSUE TITLE
cookbooks/composition-active-tracers.prm fails

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1376]
```
Exception on processing:

--------------------------------------------------------
An error occurred in line <151> of file <../source/particle/world.cc> in function
    const std::multimap<types::LevelInd, Particle<dim> > &aspect::Particle::World<2>::get_ghost_particles() const [dim = 2]
The violated condition was:
    update_ghost_particles == true
Additional information:
    A part of the model has requested access to the ghost particles, but the parameter 'Update ghost particles' has not been set, therefore no ghost particles are available.
```

@gassmoeller is it okay to set this to true? I wonder why you query ghost particles even without running in parallel...

**Comment by gassmoeller** [comment]
This should not happen. `source/particle/interpolator/cell_average.cc:41` can be skipped in serial computations, the code paths that need the ghost particles will never be reached in this case (there are no ghost cells). Feel free to fix that, or I will do in a bit (currently working on #1329).

**Comment by gassmoeller** [comment]
Additionally we will also need to set the input parameter. The parameter was added after the introduction of the cookbook.

**Comment by tjhei** [comment]
Can you do that please? I have a bunch of other small fixes coming.

**Comment by gassmoeller** [comment]
Sure, no problem. See #1377.
