### ISSUE TITLE
Tracking material properties (viscosity, density, etc) through tracers 

### ISSUE THREAD

**Issue by naliboff** [geodynamics/aspect#1394]
Currently, there is a notable difference between the methods in most particle-in-cell "tectonics" codes (mantle convection, lithospheric deformation) and ASPECT's handling of material properties through active tracers.

In ASPECT, one can track the initial composition through active tracers, which is then mapped to quadrature points where material properties (density, viscosity, etc) are calculated and then averaged if the model contains more than one compositional field.  With this method, each distinct material has it's own compositional field and is initially assigned a value of 0 or 1.

In other codes, each distinct material is typically tracked with a single tracer property (composition) that has a user-specified range of values (i.e 1 = rock type 1, 2 = rock type 2, etc).  These codes also compute and store material properties on the tracers, which are then interpolated to quadrature points.

This second method can be advantageous when one is tracking a large number of rock types (saves memory) and when additional rock types are introduced through the course of the simulation (ex: sedimentation). Certainly there are downsides to this approach in terms of accuracy, although others ( @egpuckett, @yinghe) are much better equipped to address this point.

The primary reason for bringing this up is I currently have a material model for "instantaneous" (e.g. one time step) deformation arising variations in lithospheric structure.  In this model, I track the numerous rock types in CRUST1.0 with a single compositional field.  As the model only runs one time step, accurate tracking of the rock type interfaces through time is not an issue.  To calculate material properties at the quadrature points, I'm using a very crude scheme to enforce the compositional value to be a integer value (i.e. it can only be one rock type).

As this is certainly introducing a good deal of inaccuracy, my original plan was to calculate material properties on the tracers and then interpolate these values onto the quadrature points (more accurate).  

My question is whether the developers have any objection to a material model that functions in this fashion or if there is a different strategy I should consider?

**Comment by egpuckett** [comment]
Let's talk about this tomorrow, with Julianne as well.On Feb 27, 2017 8:32 PM, naliboff <notifications@github.com> wrote:Currently, there is a notable difference between the methods in most particle-in-cell "tectonics" codes (mantle convection, lithospheric deformation) and ASPECT's handling of material properties through active tracers.
In ASPECT, one can track the initial composition through active tracers, which is then mapped to quadrature points where material properties (density, viscosity, etc) are calculated and then averaged if the model contains more than one compositional field.  With this method, each distinct material has it's own compositional field and is initially assigned a value of 0 or 1.
In other codes, each distinct material is typically tracked with a single tracer property (composition) that has a user-specified range of values (i.e 1 = rock type 1, 2 = rock type 2, etc).  These codes also compute and store material properties on the tracers, which are then interpolated to quadrature points.
This second method can be advantageous when one is tracking a large number of rock types (saves memory) and when additional rock types are introduced through the course of the simulation (ex: sedimentation). Certainly there are downsides to this approach in terms of accuracy, although others ( @egpuckett, @yinghe) are much better equipped to address this point.
The primary reason for bringing this up is I currently have a material model for "instantaneous" (e.g. one time step) deformation arising variations in lithospheric structure.  In this model, I track the numerous rock types in CRUST1.0 with a single compositional field.  As the model only runs one time step, accurate tracking of the rock type interfaces through time is not an issue.  To calculate material properties at the quadrature points, I'm using a very crude scheme to enforce the compositional value to be a integer value (i.e. it can only be one rock type).
As this is certainly introducing a good deal of inaccuracy, my original plan was to calculate material properties on the tracers and then interpolate these values onto the quadrature points (more accurate).
My question is whether the developers have any objection to a material model that functions in this fashion or if there is a different strategy I should consider?

**Comment by jdannberg** [comment]
As @gassmoeller is the one who knows most about the tracers, I think he should be the one answering this question. I don't see a problem with tracking viscosities instead of compositional fields on the tracers, but maybe there's something I didn't think of.

**Comment by naliboff** [comment]
@jdannberg - I also don't see any underlying technical obstacle to tracking the material properties on the tracers and then interpolating these values to the quadrature points.  

I think my main concern is that a material model doing this breaks from the current elegant architecture where one can switch seamlessly between tracking composition with the "standard" field method and active tracers.  

What I have in mind would deviate from this flexibility and require one to use only active tracers.  Much of the normal material model sections of code (i.e. calculating viscosity, etc) would also be hosted within the tracer properties section.

**Comment by gassmoeller** [comment]
I would be fine adding a material model that requires particles to be used. However that should be made explicitly clear by adding assertions that this material model is only used with the (to be written) particle property material model.
I agree that this particle property could do a more sophisticated material property computation (e.g. computing viscosities on the particles and averaging that to the quadrature point), but I do not think the memory footprint is an important argument. When using particles we do not create the system matrix (which needs far more memory than the solution vector). I have not checked, but I would guess that even 10 compositional fields advected on particles need less memory than a single one advected by a field method.
One obstacle that we should think about is issue #829 and the open pull request #881. At the moment particles are advected and updated in the postprocessing stage, i.e. after the nonlinear iteration finishes. This means for nonlinear material properties like viscosity you will currently not update in each nonlinear iteration. This will probably need to be sorted out before your particle property works correctly.

**Comment by naliboff** [comment]
Good to know that the memory cost for compositional fields advected by particles is that much lower.  I've used a mix of active tracers and  field methods for composition in 3D, but have not compared the memory usage yet.  For high particle densities (~ 100 per cell) in 3-D, I imagine handling multiple compositions with a single field would still be advantageous.

Good point about particles only updating after the end of the non-linear iterations. The material model I'll use initially is linear (only T-P dependent), but eventually would need to include non-linear relationships.

**Comment by egpuckett** [comment]
I'm coming into this discussion in the middle; i.e., I haven't read all of what's written above. But I read @jdannberg remark

>  I don't see a problem with tracking viscosities instead of compositional fields on the tracers, but maybe there's something I didn't think of.

. However, with regard

**Comment by naliboff** [comment]
I'm closing this issues as updates to the compositional field handling significantly reduced memory requirements. As such, there is no significant to tracking lots of different 'rock types' with different compositional fields as opposed to handling all material properties on the tracers.
