### ISSUE TITLE
Fix logo on every doxygen page

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1399]
Every doxygen page has, at the bottom, a broken link to the deal.II logo -- see the bottom left of http://aspect.dealii.org/doc/doxygen/changes_between_1_84_80_and_1_85_80.html or http://aspect.dealii.org/doc/doxygen/index.html for example.

I don't know where this comes from, but the ASPECT source tree doesn't seem to contain a reference to the `logo200.png` image. I suspect it is inherited from the deal.II sources through the deal.II tag file somehow. Either way, we should figure out how to fix this.

**Comment by bangerth** [comment]
For reference, in deal.II, this comes in via the doxygen options file:
```
dealii/doc> grep -r logo200 *
doxygen/options.dox.in:PROJECT_LOGO           = @CMAKE_CURRENT_SOURCE_DIR@/images/logo200.png
```

**Comment by tjhei** [comment]
No, the footer is replaced on the webserver after generating. I emailed Guido about it.

**Comment by bangerth** [comment]
Hm, you are right -- adding the PROJECT_LOGO line makes no difference apparently.... Let's see what Guido says about this then.

**Comment by bangerth** [comment]
@tjhei -- Can you ping @guidokanschat again?

**Comment by gassmoeller** [comment]
As far as I can see this has been fixed (maybe during the transition of the website).
