### ISSUE TITLE
Document which geometry models can initially be deformed with topography

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1405]
As the title says. How would we do this consistently? Make notes in each geometry models description?

**Comment by bangerth** [comment]
Yes, I think that is the right place for it.

**Comment by alarshi** [comment]
I looked into the geometry models and to me, it seems that only box and ellipsoidal chunk could be deformed with initial topography. In the manual, we have a line at the end in box geometry that tells the users about it.

**Comment by anne-glerum** [comment]
We only added it for the ellipsoidal chunk and the box geometry yet. I have it setup for the chunk geometry too, but I wanted to finish #1361 first.

**Comment by gassmoeller** [comment]
Closed by #1497. We will it in the other places as soon as it is implemented.
