### ISSUE TITLE
Particle compositions don't seem to respect boundary composition model.

### ISSUE THREAD

**Issue by jperryhouts** [geodynamics/aspect#1411]
New particles are always generated using interpolation scheme, even when they appear because of inflow through a boundary with a fixed composition.

**Comment by gassmoeller** [comment]
You are right, but this issue is already tracked in #1294, so I will close this one. I do not have the time to fix it in the next one or two months, but let me know if you want to discuss how to address it. We can discuss it in the other issue.

**Comment by jperryhouts** [comment]
Oops! I posted that mostly to document that this is the case, without even checking first whether it had been mentioned before! Sorry about that. I might work on it at some point, but I'll let you know first (in the other thread) and see how you'd like to proceed.
