### ISSUE TITLE
Copy deal.II's workflow for changes.h

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1441]
Every time a branch is merged that contains a new entry in changes.h, it creates a conflict for every other open pull request with an entry. We should copy deal.II's way of dealing with this. (see #1418 for a PR that was significantly more work than required, because of several rebases).

**Comment by bangerth** [comment]
Yes, I think that's the right thing to do. I think we ought to be able to basically copy the entire `doc/news/changes` directory from the current deal.II dev to ASPECT. (And because it's open source, we're even allowed to do that! ;-)
