### ISSUE TITLE
One benchmark "buiter_et_al_2008" was not moved to the new "benchmarks" folder

### ISSUE THREAD

**Issue by naliboff** [geodynamics/aspect#1445]
In renaming the benchmark folder, it looks like the newest benchmark `buiter_et_al_2008` was left behind in the original folder.

Should I open a pull request to move this folder from `benchmark` over to `benchmarks`?

**Comment by tjhei** [comment]
Yes, please.

**Comment by naliboff** [comment]
:+1:

**Comment by gassmoeller** [comment]
Closed by #1446
