### ISSUE TITLE
Require deal.II 8.5.0

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1448]
We decided that we want to require 8.5.0 for ASPECT 2.0 if I remember correctly.

To make this work, I have to switch the tester images from 8.4 to 8.5, which introduces test failures (~40 or so) due to slightly different output. Should we do this before or after the hackathon?

I would have moved forward with this ASAP, but I see the issue with hackathon participants being forced to update their installations might not be ideal.

**Comment by bangerth** [comment]
I would say let's do it now. Maybe we can get the email to participants out today (it's on my list) and then they still have almost two weeks. If we have a couple of people who haven't done it yet by the time the hackathon rolls around, we can deal with that.

**Comment by gassmoeller** [comment]
I would say lets do it before the hackathon, whenever is convenient for you. It will cost us a bit of time for helping people upgrade their installations, but it might be better to do it there then letting everyone run into problems when they are back home. Also it allows us to set up nice beginner projects (remove old code).

**Comment by tjhei** [comment]
Okay, I have a 8.5 testing image working. I need a few days to test and to prepare a PR to modify the test output.

One argument against enforcing 8.5. right now: The 8.5. mac osx binary bundle is not complete yet and I am stuck with it.

On additional option that just occurred to me:
We could allow for alternative test output and make the current version run with 8.4 and 8.5. Of course we are then unable to help people migrate and work on beginner projects immediately. Thoughts?

**Comment by gassmoeller** [comment]
Oh, yes we should definitely wait until the mac bundle is available (I remember last hackathon quite a number of people used mac for their development). In my view it is not crucial to switch before the hackathon, it is a nice to have type of thing.

**Comment by naliboff** [comment]
@tjhei - I recently downloaded what is listed as the 8.5 deal.II mac bundle (http://dealii.org/download.html) and ASPECT compiled successfully. Should we avoid this bundle for now?

**Comment by bangerth** [comment]
@gassmoeller -- but then we can't accept any patches during the hackathon that require deal.II 8.5. I do like the idea of accepting such cleanups...

**Comment by tjhei** [comment]
> Should we avoid this bundle for now?

If it works for you then that is great. The two problems with it are:
- optimization levels cause it to fail to work on older machines (hard error when the compiler is run)
- it is currently not cryptographically signed, so you get warnings about "untrusted developer" stuff

**Comment by tjhei** [comment]
closed by #1456
