### ISSUE TITLE
cmake: remove ctest dependency to aspect target

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1462]
We currently have a dependency from each test target to ``aspect``. The motivation is that a test needs to re-run whenever the ``aspect`` binary changes (because it was rebuilt). Sadly, cmake does not add a dependency to the binary ``aspect`` but to the target to build ``aspect`` instead. This means that for every test cmake will check all dependencies recursively over and over again, which is very slow.

Another consequence of this is that when you run ``ctest -j 8`` and aspect is out of date (maybe because one source file of aspect is newer), we try to compile ``aspect`` 8 times at the same time. This has brought down my machine a couple of times over the years.

This first problem (slowness) is not visible if you use ninja instead of make, because ninja is very efficient in checking dependencies. The problem is that using ninja for the testsuite is somewhat broken (we disable ninja for the deal.II testsuite, see https://github.com/dealii/dealii/pull/2767 ).

I am not sure how to tell cmake that a target should depend on the aspect binary instead of the aspect target. Maybe breaking the tests into a separate project like we do in deal.II is enough to make this work. This would have the advantage that we can reliably use ninja to compile again.

**Comment by gassmoeller** [comment]
Sounds great, 7min is much better than 21. I do know too little about make to make suggestions about how to improve the 4s, but this seems like a nice speedup already. Wouldnt the tests need to be rerun for every pull request anyway, so that the 4s case usually only applies if you work on aspect on your machine? Or does the tester keep files between different PRs?

**Comment by tjhei** [comment]
> Wouldnt the tests need to be rerun for every pull request anyway, so that the 4s case usually only applies if you work on aspect on your machine? Or does the tester keep files between different PRs?

Well, most important is for normal development, but the tester currently does the following:

1. make -j $NPROC
2. ctest -j $NPROC
3. ASPECT_GENERATE_REFERENCE_OUTPUT=1 ctest -j $NPROC

Step 3 will rerun all the tests a second time. The current tester uses ninja for step 2&3, which causes it to rerun the examples in 3) (taking the additional 7 minutes or so). I can fix this by using make, but then I am still paying 4s*400 tests / 16 cores = 1.5 minutes.

Maybe I can fold 2&3 into a single computation...

**Comment by bangerth** [comment]
Would there be a way to create one sub-project per test, rather than a subproject for all tests? In that case, we could use `ninja` for them again. Or does `ctest` not like this?

**Comment by tjhei** [comment]
I think Matthias would have tried that if this makes sense. I assume that we would get a really large overhead in ``setup_tests`` as a result.

**Comment by bangerth** [comment]
Yes, I suspect you're right.

**Comment by tjhei** [comment]
done in #1466
