### ISSUE TITLE
ASPECT throws assertion during runtime with most recent deal.II master

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1465]
dealii/dealii#4307 removed functions from DataOut that we widely use in ASPECT's visualization postprocessors. Somehow we never got the deprecation warnings for them, but anyway we should fix this (best before the hackathon) to make sure also people with recent development version of deal.II can run ASPECT.

**Comment by gassmoeller** [comment]
This is essentially the same as #1268, only that it is more urgent now.

**Comment by jperryhouts** [comment]
Hm, bummer. Of all the days to update deal.ii I chose today. Is this an easy fix (if so I can do it right now), or should I just revert to an earlier deal.ii commit for now?

**Comment by tjhei** [comment]
Ironic that @bangerth removed them without testing ASPECT first. ;-)

> should I just revert to an earlier deal.ii commit for now?

I would recommend sticking with v8.5.0 for now. You can always just do ``git checkout v8.5.0`` in your source folder and compile again.

**Comment by bangerth** [comment]
Yes, let's just put into the record that that wasn't very smart of me :-( I'll see that I get to fix it this afternoon.

**Comment by gassmoeller** [comment]
Fixed by #1467
