### ISSUE TITLE
Simple 'make test' broken 

### ISSUE THREAD

**Issue by heronphi** [geodynamics/aspect#1479]
After compiling deal.ii 8.5 and then ASPECT pre2.0, the quick mpi test 'make test' is unable to be completed. 

When in aspect/build, 'make test' produces: 

"make: *** No rule to make target `test'."

**Comment by bangerth** [comment]
If you say `make`, does that succeed? In other words, did compiling ASPECT succeed?

**Comment by bangerth** [comment]
I'm also not 100% sure that there really is a `test` target in ASPECT. Did I miss this somewhere? In other words, can you point out where you read about it? We may want to fix that place.

**Comment by heronphi** [comment]
Yes, ASPECT compiled correctly. 

Ah, I was just going on how I tested ASPECT previously. Checking the current manual, it does not say to perform this 'make test'. With previous versions, this is how I quickly tested if my executable had been made correctly.

**Comment by tjhei** [comment]
I probably broke this in #1466.

@heronphi can you go into the ``test`` directory inside your build directory and run make test there?

**Comment by heronphi** [comment]
@tjhei - actually yes! Inside the build/tests the 'make test' runs (and passes the quick_mpi test in this instance).
