### ISSUE TITLE
Modify cookbooks to have different output directories

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1482]
It would be convenient if every cookbook would prescribe an output directory identical to its name, so that you can run them in the same directory without overwriting their respective results.

**Comment by tjhei** [comment]
I find it confusing if it is just the name of the cookbook, but something like ``output-<cookbookname>`` would be great.

**Comment by hlokavarapu** [comment]
Currently working on this enhancement.

**Comment by hlokavarapu** [comment]
This issue can be closed.

**Comment by bangerth** [comment]
Thanks, @hlokavarapu !
