### ISSUE TITLE
Clarify the number of fields in the multicomponent material model and similar plugins

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1489]
The `multicomponent` material model allows three modes of computations of material properties:
1. If the user inputs one number it is equally applied to all fields
2. If the user inputs N+1 numbers (where N is number of compositional fields), and the compositional fields add up to 1 or larger it computes N properties (and ignores the first number for the background material).
3. If the user inputs N+1 number, and the compositional fields add up to less than 1 it fills the missing fraction by background material, that is supposed to have the first composition of the list.

I would really prefer if option 2 and 3 could be more cleanly separated. In particular I dislike:
- That the user inputs the same list of properties, but in case 2 one entry of this list is ignored
- There is no explicit switch (like based on the number of properties) between case 2 and 3

**Comment by ian-r-rose** [comment]
How would you want to clarify this? I wanted to avoid requiring N>=2 for all cases, and so allowing for a "background" material seemed to accomplish that. This makes a number of benchmarks pretty simple.

**Comment by gassmoeller** [comment]
I think the Steinberger material model covers the three cases as follows:
```
if (list.size() == 1)
        {
just one property, use it
        }
      else if (list.size() == compositional_fields.size() + 1)
        {
first entry is background material
        }
      else
        {
each entry is one compositional field
        }
```

**Comment by ian-r-rose** [comment]
So what if `n_compositional_fields = 2`, the number of entries in the list is two, and there is a region of the simulation with values of zero (or nearly so) for all of the compositional fields? To which value should we assign that region?

**Comment by pmbremner** [comment]
This has been addressed by #2405. Can this be closed now?

**Comment by bangerth** [comment]
@pmbremner -- are you asking someone to close this issue, or are you asking whether it should be closed?

**Comment by pmbremner** [comment]
@bangerth I feel it can be closed, but I am actually asking if it can be in case it needed to be open for another reason.

**Comment by bangerth** [comment]
If you think it can be closed, then it should be.
