### ISSUE TITLE
[Poll] Does precompiling headers reduce your compile time?

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1491]
ASPECT tends to take a long time to compile from scratch. We have included two options that should reduce compile times, which might help everyone trying to develop a new feature (faster compile time -> lower turnaround time in the edit-compile-test cycle). Unfortunately, there is no guarantee that these options succeed with arbitrary C++ code. We tried to make ASPECT compatible with it, but we would like to get more data about possible problems. I would like everyone to give these two options a try and report in this issue whether they work on their machine. Bonus points if you add a `time` in front of the `make` commands and report the speedup you get compared to a normal compile cycle. Please note that both options increase the amount of RAM that is needed by the compiler. For the second option you might get into memory problems if your machine has less than 8 GB of RAM (8 GB should be fine for both options). 

1. Use precompiled headers: please run the following command in your build directory, recompile ASPECT, and post below whether it compiles for you. This should reduce your compile time by a factor of 2.
```
cmake -D ASPECT_PRECOMPILE_HEADERS=ON .
```

2. Make a unity build: Run the following cmake command, where `X` is the number of cores you usually use to compile ASPECT. This should speedup your build by another factor of 2 or more:
```
cmake -D ASPECT_PRECOMPILE_HEADERS=ON -D COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES="-jX" .
make -jX aspect_unity
```

**Comment by gassmoeller** [comment]
Point 2. will only work consistently when #1487 is merged, so wait with that test for a while.

**Comment by ian-r-rose** [comment]
Point 1: With six processors I go from seven minutes to 3.5. Fantastic!

**Comment by bangerth** [comment]
Standard build on my laptop:
```
> time ninja
[229/229] Linking CXX executable aspect

real    6m12.201s
user    44m38.724s
sys     1m33.300s
```

With the flag:
```
real    2m59.593s
user    16m49.112s
sys     1m10.240s
```
That is a VERY NICE improvement!

But I also get this warning when running cmake with the precompiled header flag:
```
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   aspect_CXX_cotire.cmake

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
I wished the warning would tell me where this is happening :-(

**Comment by class4kayaker** [comment]
Tested on my laptop (I use zsh, so the time output is slightly different, I
modified the presentation slightly for better comparison)

WITHOUT PRECOMPILED

````
ninja
2450.40s user
95.58s system
712% cpu usage (on i7-6820HQ CPU @ 2.70GHz)
5:57.21 total
````


WITH PRECOMPILED

````
ninja
1001.78s user 
61.62s system
659% cpu usage (on i7-6820HQ CPU @ 2.70GHz)
2:41.25 total
````

I have the same warning as Wolfgang, and looking into the documentation the
BYPRODUCTS option was specified (added in CMAKE 3.2, warning will occur with
CMAKE 3.3). I did a search, and found that the recommended approach was to
include the following to specify the new behavior

````
if(POLICY CMP0058) 
    cmake_policy(SET CMP0058 NEW) 
endif() 
````

I did some local tests, and including this before including cotire appears to
have fixed the issue (The project probably tests the policy to determine behavior). The resultant changed setup was then timed for a negligible variation in time (easily attributable to user behavior variation).

NEW MODIFICATION

````
[233/233] Linking CXX executable aspect
ninja
1013.03s user
63.59s system
649% cpu
2:45.66 total
````

The I have created a pull request with the modification at #1506.

**Comment by ian-r-rose** [comment]
I  get a compiler warning with the unity build that I do not get with the normal build:

```bash
In file included from /home/ian/aspect/include/aspect/simulator_access.h:44:0,
                 from /home/ian/aspect/include/aspect/simulator.h:47,
                 from /home/ian/aspect/source/simulator/helper_functions.cc:22,
                 from /home/ian/aspect/debug/cotire/aspect_CXX_unity_0_37.cxx:8:
/home/ian/aspect/source/boundary_traction/interface.cc: In instantiation of ‘dealii::Tensor<1, dim> aspect::BoundaryTraction::Interface<dim>::boundary_traction(dealii::types::boundary_id, const dealii::Point<dim>&, const dealii::Tensor<1, dim>&) const [with int dim = 2; dealii::types::boundary_id = unsigned char]’:
/home/ian/aspect/source/boundary_traction/interface.cc:196:5:   required from here
/home/ian/aspect/include/aspect/boundary_traction/interface.h:100:53: warning: unused parameter ‘boundary_indicator’ [-Wunused-parameter]
         boundary_traction (const types::boundary_id boundary_indicator,
                                                     ^~~~~~~~~~~~~~~~~~
/home/ian/aspect/source/boundary_traction/interface.cc: In instantiation of ‘dealii::Tensor<1, dim> aspect::BoundaryTraction::Interface<dim>::boundary_traction(dealii::types::boundary_id, const dealii::Point<dim>&, const dealii::Tensor<1, dim>&) const [with int dim = 3; dealii::types::boundary_id = unsigned char]’:
/home/ian/aspect/source/boundary_traction/interface.cc:196:5:   required from here
/home/ian/aspect/include/aspect/boundary_traction/interface.h:100:53: warning: unused parameter ‘boundary_indicator’ [-Wunused-parameter]
```

**Comment by bangerth** [comment]
Patch coming.

**Comment by bangerth** [comment]
Current timing with precompiled headers:
```
real    3m19.023s
user    18m38.236s
sys     1m19.188s
```
With unity build:
```
real    1m27.020s
user    4m36.840s
sys     0m9.268s
```
Really nice. I'll have to test how large the release builds are -- I bet they are also significantly smaller with unity builds as well as possibly faster (because of increased opportunities for interprocedural optimizations).

**Comment by class4kayaker** [comment]
My current timings (using my BYPRODUCTS branch, rebased to master)

PRECOMPILE

````
[234/234] Linking CXX executable aspect
ninja  1017.22s user 64.88s system 655% cpu 2:45.15 total
````

UNITY

````
[17/17] Linking CXX executable unity/aspect
ninja aspect_unity  316.29s user 8.85s system 355% cpu 1:31.34 total

[234/234] Linking CXX executable aspect
ninja  1007.77s user 65.32s system 659% cpu 2:42.67 total
````

**Comment by alarshi** [comment]
I tried it on my laptop with 4 processors. The times are : 

a) Without any flags - 

```
real	13m34.304s
user	44m29.847s
sys	1m33.319s

```
b) Precompiled headers (Point 1) -

```
real	7m14.258s
user	19m34.454s
sys	1m13.354s

```
c) Unity Build (Point 2) - 

```
real	9m24.257s
user	18m25.408s
sys	1m13.523s

```

**Comment by anne-glerum** [comment]
Standard build on laptop (make -j2):
real    21m59.951s
user    40m48.810s
sys     1m59.161s
 
With ASPECT_PRECOMPILE_HEADERS=ON:
real    11m51.115s
user    21m19.804s
sys     1m16.123s

**Comment by jaustermann** [comment]
The precompiling worked on my local machine but caused problems on the cluster (see below). The same code compiles fine if I don’t set the precompile flag. 


[jaustermann@rclogin05 aspect-build]$ cmake -D ASPECT_PRECOMPILE_HEADERS=ON .
-- ====================================================
-- ============ Configuring ASPECT ====================
-- ====================================================
-- Found deal.II version 8.5.0 at '/n/home09/jaustermann/bin/dealii-8.5.0-install/lib/cmake/deal.II'
-- Using ASPECT_USE_PETSC = 'OFF'
-- Setting up test project, see setup_tests.log for details.
-- Enabling dynamic loading of plugins from the input file
-- Enabling checking of compatible deal.II library when loading plugins
-- Autopilot invoked
-- Run   $ make info  to print a detailed help message
-- Enabling cotire to precompile external header files.
-- cotire 1.7.9 loaded.
-- CXX target aspect cotired.
-- Parameter GUI not found: install and provide a hint using -D PARAMETER_GUI_DIR or set -D PARAMETER_GUI_EXECUTABLE directly.
-- Writing config into detailed.log...
-- Configuring done
-- Generating done
-- Build files have been written to: /n/home09/jaustermann/aspect_new/aspect-build


[jaustermann@rclogin05 aspect-build]$ make -j8
[  0%] Generating CXX unity source cotire/aspect_CXX_unity.cxx
[  0%] Generating CXX prefix header cotire/aspect_CXX_prefix.hxx
-- Result 2 scanning includes of /n/home09/jaustermann/aspect_new/aspect-build/cotire/aspect_CXX_unity.cxx.
-- 4 line(s) skipped, see /n/home09/jaustermann/aspect_new/aspect-build/cotire/aspect_CXX_prefix.hxx.log
Scanning dependencies of target aspect
[  1%] Building CXX object CMakeFiles/aspect.dir/source/simulator/helper_functions.cc.o
/n/sw/intel-cluster-studio-2015/composer_xe_2015.0.090/compiler/include/math.h(19): internal error: null pointer
  # include_next <math.h> /* utilize and expand sys header */
                                                             ^

compilation aborted for /n/home09/jaustermann/aspect_new/aspect/source/simulator/helper_functions.cc (code 4)
make[2]: *** [CMakeFiles/aspect.dir/source/simulator/helper_functions.cc.o] Error 4
make[1]: *** [CMakeFiles/aspect.dir/all] Error 2
make: *** [all] Error 2

**Comment by tjhei** [comment]
The (slow) tester says (before and after):
```
real	5m21.906s
real	2m48.589s
```

**Comment by gassmoeller** [comment]
So to conclude our experiences: Enabling precompiling headers and using unity build both reduce the compile speed consistently and significantly, but there are a few cases where it fails. Thus, we should keep the current state and keep it optional. I will close this issue.
