### ISSUE TITLE
The Manual's Appendix numbers are overwriting the section titles

### ISSUE THREAD

**Issue by egpuckett** [geodynamics/aspect#1494]
For appendices numbered >= 100 the table of contents is not working correctly, at least with my LaTeX compiler on Ubuntu 16.04:

> A.100Parameters in section Mesh refinement/Boundary . . . . . . . . . . . . . . . . . . . . . . . . 348

See the following PDF file:

[Manual_Appendix.pdf](https://github.com/geodynamics/aspect/files/981910/Manual_Appendix.pdf)

**Comment by bangerth** [comment]
Correct. We need to figure out how to teach `\tableofcontents` how to properly size the first column.

**Comment by egpuckett** [comment]
@bangerth I just noticed that some of the titles are simply too long; e.g., 

> A.14 Parameters in section Boundary temperature model/Ascii data model . . . . . . . . . . . 236
A.15 Parameters in section Boundary temperature model/Box . . . . . . . . . . . . . . . . . . . . 238
A.16 Parameters in section Boundary temperature model/Box with lithosphere boundary indicators238

Is it reasonable to make 

> Box with lithosphere boundary indicators

a subsection of

> A.16 Parameters in section Boundary temperature model

Otherwise,  perhaps there is a way to make A 16 occupy two lines?

**Comment by bangerth** [comment]
That may be a separate problem. But we also can't do as you suggest -- these titles are automatically generated from the parameter handler object that manages input files. We will just need to find a way to teach latex to deal with this.

**Comment by egpuckett** [comment]
I'm willing to work on in when I'm too tired to do 'real' work, but I'll have to have you give me a quick overview of how the titles are automatically generated from the parameter handler object that manages input files.

**Comment by bangerth** [comment]
There's nothing to it. Just look at the file `doc/manual/parameters.tex` to see how they look. How they are generated is not actually important -- some class in deal.II does it. The only relevant thing is that given how they are, how can we trick latex into making them look nice.

**Comment by tjhei** [comment]
here is how to do it: https://tex.stackexchange.com/a/33842

**Comment by egpuckett** [comment]
I just made a PR to fix this problem, but some lines are still too long; e.g., see A.10.  Should I close this issue and open another?

**Comment by bangerth** [comment]
Yes, if there is a secondary issue, then open a second github issue. We try not to hijack issues for follow-up discussions.

You can always reference the current issue in the new one you open.
