### ISSUE TITLE
Don't use 'remap' as variable names

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1503]
We have a number of places where we use `remap` as the name of solution-type vector variables. This name is entirely unintuitive. Specifically, it is a verb, not a noun, and so really doesn't describe at all what the variable is used for. We should give these variables a better name that is, in particular, a noun.

**Comment by class4kayaker** [comment]
Fixed in #1531?

**Comment by bangerth** [comment]
Yes.
