### ISSUE TITLE
Rename prescribed traction boundary indicators

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#1513]
Rename prescribed_boundary_traction_indicators parameter to prescribed_traction_boundary_indicators for consistency with prescribed_velocity_boundary_indicators.

**Comment by gassmoeller** [comment]
What is the name for the boundary temperature indicators? Lets see how they look as well

**Comment by bangerth** [comment]
Nice starter project!

**Comment by anne-glerum** [comment]
Temperature and composition boundary indicators are called 
fixed_temperature_boundary_indicators and
fixed_composition_boundary_indicators,
so consistent with velocity boundary indicators.

**Comment by gassmoeller** [comment]
Then lets use that naming convention.

**Comment by hlokavarapu** [comment]
Neat, looks like this has already been implemented. The issue can be closed.

A recent run produced the output/parameters.prm file which contains:
`  set Prescribed traction boundary indicators = `

**Comment by gassmoeller** [comment]
I think this was closed by #1612
