### ISSUE TITLE
Prepopulate aspect GUI filename when saving file

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1530]
When saving a file in the aspect GUI, it offers no default filename. Can we pre-populate the filename field with the name of the file that the GUI was opened with?

**Comment by tjhei** [comment]
Difficult. The GUI will always be opened with "temp.xml". We would need to pass additional information to the parameter gui.

**Comment by gassmoeller** [comment]
Not very difficult. The `aspect-gui` script could rename the temp.xml output file into the name of the given parameter file, and we can prepopulate the filename field of the gui with the name of the xml file that was used to open it. The ending would be wrong, but we can also choose to modify that ending to whatever type the user selects in the "Write file..." dialog. Not perfect, but better than at the moment. I can take a look after the hackathon, or in a quiet minute here.

**Comment by bangerth** [comment]
Fixed now.
