### ISSUE TITLE
Install Qt4.x on a Mac with Mac OS 10.12.4 through macport or home brew, and install dealii.parameter gui 

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#1532]
Just to share some information of installing Qt on a mac in order to use aspect paramter gui.
I tried to install Qt5.x from the Qt website, and also the early version Qt4.8.X from here 
http://download.qt.io/official_releases/qt/4.8/4.8.7/
The installation of Qt5.x was successful however current dealii paramter gui doesn't support this.  
The installation of Qt4.8.x was failed due to the incompatible of newest Mac OS 10.12.4

**Comment by anne-glerum** [comment]
For me (Mac OS 10.12.4) the parameter gui works when installing qt4-mac (4.8.7_4) through macports.

**Comment by yinghe616** [comment]
Thanks Anne. Now I am able to install dealii.parameter.gui in my mac :) 

For mac users with Mac OS 10.12.4 who wants to install aspect parameter gui, here are what I did:

1) intall macport if you haven't 
https://guide.macports.org/chunked/installing.macports.html
2) install qt4-mac
sudo port install qt4-mac
2) download dealii parameter gui
https://github.com/dealii/parameter_gui
3) Intall dealii parameter gui
 Before calling cmake  you need to either pass the path of qt4 and specify the value of variable QT_LIBRARIES in CMakeList.txt
or add those information into your ~/.bashrc
On my laptop, I added the following lines
export PATH="$PATH:/opt/local/libexec/qt4"
export QT_LIBRARIES="/opt/local/libexec/qt4"
then cmake and make in your dealii parameter gui directory
4) When 3) finished, add the directory of PARAMETER_GUI_DIR into ~/.bashrc again 
export PARAMETER_GUI_DIR="xxxxxxxxxxx/parameter_gui/bin"
5) in aspect directory, cmake and make again

**Comment by gassmoeller** [comment]
@yinghe616 would you mind adding the instructions that you posted above to a new subsection in the manual (inside of subsection "4.8.1 Installing parameter-GUI")?

**Comment by yinghe616** [comment]
sure. I'll do that.

**Comment by gassmoeller** [comment]
Closed. We have a section about installing Qt4 in the manual now, and also the newest version of parameter-gui runs also runs with Qt5.
