### ISSUE TITLE
Support different timescales

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1542]
There is currently no way to accurately solve dynamics faster than the viscous time step. Cases where this would be useful are (i) fast reactions between compositional fields, (ii) rapid decay of quantities (that are not necessarily coupled) such as elastic stresses in a viscoelastic model, (iii) elasticity forces in a viscoelastic model.

Between @tjhei , @jdannberg , @cedrict , @naliboff , and @bangerth, we discussed how best to address these. A useful approach would be to implement something like a Strang-style operator splitting that allows treating fast dynamics and viscous (Stokes-style) transport separately. The advantage of these approaches would be that one can do the fast dynamics as an ODE for each node point separately, using just an ODE solver that could even use an adaptive time stepping method. (Could we get that from Trilinos, for example?)

That would also be a useful topic for an ASPECT 3 or 4 paper.

**Comment by tjhei** [comment]
@jdannberg is working on it.

**Comment by gassmoeller** [comment]
As far as I know this has been addressed by #1825. We can improve that further by using better ODE solvers (like Sundials), but that would be a separate issue. Can this issue be closed?

**Comment by jdannberg** [comment]
As far as I am concerned, this has been addressed (and we have #1867 for the technical improvements). But I don't know if @bangerth had something else in mind for the elasticity problems he mentions.

**Comment by gassmoeller** [comment]
I think we also thought of using the elastic strains of the last timestep, or using fields for them. Both approaches are now possible, so I will close this for now. Feel free to reopen if something is not addressed yet.

**Comment by bangerth** [comment]
No, this was it. Thanks for closing!
