### ISSUE TITLE
Use new MaterialModelInputs constructor

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1558]
In #1537, @pmbremner implemented a neat way to let a `MaterialModelInputs` initialize itself from a solution vector and a few auxiliary variables. This provides a way to remove a lot of boiler plate code in places where we have to set up these objects. We should use the new constructor wherever appropriate.

One of the issues worth investigating in this regard is whether really *all* fields that the new constructor initializes need to in fact be initialized in a particular place.

**Comment by yinghe616** [comment]
I'll work on this sometime today.

**Comment by ian-r-rose** [comment]
You may want to check in with @pmbremner , since I think he has some work-in-progress on this as well.

**Comment by yinghe616** [comment]
I haven't stated yet. just wanted to work on this when changing topic :-) @pmbremner, let me know if you are working on this.

**Comment by pmbremner** [comment]
Working on it now, actually

**Comment by pmbremner** [comment]
I'm happy to collaborate :)

**Comment by bangerth** [comment]
There is now also a second constructor for viz postprocessors that can be used there, see #1722 .

**Comment by gassmoeller** [comment]
Addressed by #1596, #1689, and #1722. Thanks @pmbremner and @ian-r-rose.
