### ISSUE TITLE
Rename data directories in alignment with source directories

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#1579]
Maybe we should rename some of the directories in `/data` to match the dirs in `/source`?
e.g.
`boundary-velocity` instead of `velocity-boundary-conditions`
and
`initial-composition` instead of `compositional-initial-conditions`

**Comment by gassmoeller** [comment]
Yes. I forgot that when renaming the sources. Anyone Feel free to go ahead, but leave a note here so that we avoid double effort. Renaming also involves changing the default values for the parameters that set the directories.

**Comment by gassmoeller** [comment]
I will go ahead with this. After all I created the mess.
