### ISSUE TITLE
use this->introspection().polynomial_degree.velocities instead of  this->get_fe().base_element(this->introspection().base_elements.velocities).degree+2) when necessary

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#1582]
In class introspection, we already defined the polynomial degree for each field, so we should
use
this->introspection().polynomial_degree.velocities
instead of 
this->get_fe().base_element(this->introspection().base_elements.velocities).degree+2)
whenever necessary. For example, initialize the QGauss quadrature

**Comment by bangerth** [comment]
Yes, this seems entirely reasonable.

**Comment by class4kayaker** [comment]
Working on this

**Comment by yinghe616** [comment]
I have been working on this... and almost done.

**Comment by class4kayaker** [comment]
Never mind then, thanks for letting me know.

**Comment by yinghe616** [comment]
This issue has been addressed at #1584
