### ISSUE TITLE
Document Utilities::Coordinates::CoordinateSystem

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1631]
#1563 adds an enum `Utilities::Coordinates::CoordinateSystem`, and #1629 adds some documentation to a related function, but the enum itself remains undocumented. We should add documentation explaining what the enum does, and what the individual values correspond to.

@mbweller -- want to give this a shot after #1629 is merged?

**Comment by mbweller** [comment]
Sure. I'll take care of it.

**Comment by bangerth** [comment]
#1629 is now merged.

**Comment by gassmoeller** [comment]
Was fixed by #1636.
