### ISSUE TITLE
Governing equation approximations

### ISSUE THREAD

**Issue by ian-r-rose** [geodynamics/aspect#166]
Hi all,

So we have discussed this in one form or another a couple of times, but I thought that I would bring it up again.  As we know, there are several approximations to the equations for mass, momentum, and energy that are commonly used in mantle convection (Boussinesq, anelastic, etc).  Some are more thermodynamically consistent than others.  Discussing this with Juliane and Rene this week, I think we agreed that this could be clarified in Aspect.  This recently reared its head when trying to reproduce the Zhong et al 2008 benchmark, as the "simple" material model is **not** Boussinesq in the strictest sense (does not use the reference density for thermal diffusivity, as I recall?  I have not verified, but this is what Rene indicated to me).  I think it is important to be able to use these approximations with confidence.

I see two different ways of addressing this:

1) The easier solution.  Try to introduce a Boussinesq material model which does exactly that and nothing more.  The reference density is used everywhere except for the terms which multiply gravity.  Additionally, it would be nice for Aspect to query the material model about its compressibility, look at whether viscous heating and adiabatic heating are included, and then infer which approximation is being used.  This would be useful output information at the start of a run.

2) Fully support the relevant approximations that are used (Boussinesq, extended Boussinesq, anelastic) so that it can be specified in a parameter file.  This would require some extensive changes to the assembly of the matrix, as well as some checks for compressibility in the material model, but it may be worth it.

I am willing to work on this, but I'd like to hear thoughts from people as to what would be most appropriate before starting.

**Comment by gassmoeller** [comment]
Closed by #1275. Just took 2 and a half years since opening this issue :smile:.

**Comment by bangerth** [comment]
:+1:
