### ISSUE TITLE
Specify boundary velocity components along spherical unit vectors

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#1661]
@mbweller It would be really cool if we could not only use the spherical coordinates to specify where we want which velocity, but also specify the velocity itself in spherical coordinates. I.e. prescribe the velocity components wrt spherical unit vectors instead of cartesian unit vectors.

**Comment by mbweller** [comment]
On it

**Comment by bartniday** [comment]
Also working on this one!

**Comment by anne-glerum** [comment]
This has been implemented in #2361, so I'm closing the issue.
