### ISSUE TITLE
Create a diagram about ASPECT's architecture

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1667]
@ljhwang asked whether there is a diagram that explains the structure of the ASPECT. There isn't, but it should not actually be very difficult to generate one.

In essence, we have the following structure:
* There is a "core", which consists of the `Simulator` class
* There is class that allows querying some information from the `Simulator` class, called `SimulatorAccess`. So there would be an arrow from `Simulator` to `SimulatorAccess`.
* There are a number of "Interfaces" for plugins (e.g., for mesh refinement, material model, boundary temperature, etc). They provide information to the `Simulator`, so there should be an arrow from each of these interfaces to the `Simulator`.
* There are a number of implementations of each of these interfaces in the various classes. So there should be arrows from each implementation to their corresponding interface.
* Some of these implementations need information from `SimulatorAccess`, so there may be an arrow from the latter to the former.

@ljhwang -- I guess this is too abstract to draw a graph? Or is it good enough?

**Comment by ljhwang** [comment]
@bangerth I think @jdannberg has done something like this in her tutorial slides "Modularity".  Can someone review and modify as per above?
![screen shot 2017-05-14 at 8 20 15 pm](https://cloud.githubusercontent.com/assets/4493407/26041599/dffc3b48-38e2-11e7-8cff-e260a6aa9203.png)

**Comment by bangerth** [comment]
This is not a bad graph, but there are about a dozen plugin systems that are responsible for the "Model setup" part. Some of them also require feedback from the simulator.

**Comment by ljhwang** [comment]
Julianne does have a  more complicated version of this but I think there is a middle ground of something that gives the user a general overview as well as enough detail about the “parts”

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D.
Associate Director, CIG
530.752.3656

**Comment by bangerth** [comment]
If I have a fifteen minute break today, I may just come up with a way to create the graph from ASPECT internals. Each plugin system should be able to tell about itself what we need for this graph.

**Comment by ljhwang** [comment]
![modularity2](https://cloud.githubusercontent.com/assets/4493407/26117315/f3e5b736-3a1a-11e7-9d63-55ba90bb7d50.png)

**Comment by bangerth** [comment]
@jdannberg -- how did you make this graph? Do you still have the sources? I'd like to put something like this into the manual.

**Comment by bangerth** [comment]
This can now be closed.
