### ISSUE TITLE
Refine right away at first timestep

### ISSUE THREAD

**Issue by jaustermann** [geodynamics/aspect#1690]
It would be nice if we could check whether the refinement strategy depends on the solution of the first timestep and if it doesn't (e.g. boundary, topography) refine right away without calculating the solution first. This only matters for the initial refinement.

**Comment by gassmoeller** [comment]
Hi Jacky,
if you are still interested in this, I think it should not be too hard to implement. I could imagine a parameter in the mesh refinement section called `Skip initial adaptive refinement solves`, which contains documentation that it is only save to set this to true if the refinement criteria are independent of the solution. Then one would only need to modify core.cc:2309-2314 to include a loop that calls `maybe_do_initial_refinement` until no more initial refinement is done, and then one final `goto start_time_iteration` to actually solve for the final mesh. Do you want to give this a try?

**Comment by jaustermann** [comment]
Hi Rene, thanks for the pointers! I will give this a try.

**Comment by bobmyhill** [comment]
@jaustermann do you want to assign this to yourself?

**Comment by jaustermann** [comment]
@bobmyhill I haven't worked on this yet so feel free to tackle it if you want

**Comment by bobmyhill** [comment]
Ok, this is mine!

**Comment by jaustermann** [comment]
This is addressed by #2409.
