### ISSUE TITLE
Dynamic friction model has funny code

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1774]
More about the dynamic friction model. In `compute_viscosities()`, it has this piece of code around line 123:
```
          if ( viscous_stress[i] >= strength[i]  )
            {
              viscosities[i] = strength[i] / (2.0 * edot_ii);
            }
          else
            {
              viscosities[i] = background_viscosities[i];
            }

          // Rescale the viscosity back onto the yield surface
          viscosities[i] = strength[i] / ( 2.0 * std::sqrt(strain_rate_dev_inv2) );
```
Here, in the `if`-`else` branches, we set `viscosities[i]`. But then, we immediate overwrite the just-computed values with something else. Is this really what we want?

Related to #1728. @alarshi / @naliboff ?

**Comment by naliboff** [comment]
The original intent was to have an option where the user can select to rescale the viscosity at all points onto the yield surface ( `viscosities[i] = strength[i] / ( 2.0 * std::sqrt(strain_rate_dev_inv2) )` ) or only rescale points that that are above the yield strength. Thank you for the reminder ;). For now I've removed the option for modifying viscosities only above the yield strength, but this can be added in later if someone would like the option. For now, this material model will probably serve the purpose of basic testing (e.g. similar to `drucker_prager`), but the rheological mechanism will likely be added to other material models down the road.
