### ISSUE TITLE
Download page is outdated

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1791]
http://aspect.dealii.org/download.html still links to https://github.com/geodynamics/aspect/releases/download/v1.4.0/aspect-1.4.0.tar.gz as the latest ASPECT release. It should probably link to https://github.com/geodynamics/aspect/releases/latest instead, that way we do not need to update it every release.

**Comment by bangerth** [comment]
Fixed version should be up in a few minutes.

**Comment by gassmoeller** [comment]
Thanks!
