### ISSUE TITLE
sort items in plugin-graph

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1801]
When running ``update_parameters`` a large diff shows up, because the entries inside the dot file are not sorted and depend on the order of static initialization. This makes it hard to see if there were any changes that need to be committed. Maybe we can sort the plugin list by name?

**Comment by tjhei** [comment]
Also see #1795 for a comment about this issue.

**Comment by tjhei** [comment]
While we are working on this: I am not happy with having a 4mb .png binary inside the repository that we need to update regularly (monthly?) and that will generate a large diff each time. This will blow up the size of the repo significantly. Options around this:
1. regenerate when compiling the manual from the .dot (all users would need graphviz installed)
2. choose a graphics format that is text based (sadly, .svg is not natively supported by pdflatex, but we could convert .svg to .tex using inkscape. Complicated, yes)
3. choose a format that produces smaller files (sadly still binary, but .pdf is 67k instead of 4mb and can be produced directly by graphviz)

**Comment by bangerth** [comment]
`graphviz` can generate both pdf and svg, but I haven't found a way to include the svg into the manual. But that doesn't matter much because the svg is also larger:
```
-rw-r--r-- 1 bangerth fac   87515 Jun  1 10:42 plugin_graph.dot
-rw-r--r-- 1 bangerth fac   70154 Jun  1 10:42 plugin_graph.pdf
-rw-r--r-- 1 bangerth fac 4190202 Jun  1 10:32 plugin_graph.png
-rw-r--r-- 1 bangerth fac  305736 Jun  1 10:31 plugin_graph.svg
```
(It is plain text, but mostly numbers that will change everytime we re-create the svg; so the diff will still be large.) Patch coming up soon.

**Comment by bangerth** [comment]
I'll add that there appear to be ways to include svg into latex, but they seem to require calling pdflatex with additional options, require packages outside latex to be installed, etc. Not a good solution apparently.

**Comment by tjhei** [comment]
> I'll add that there appear to be ways to include svg into latex, but they seem to require calling pdflatex with additional options, require packages outside latex to be installed, etc. Not a good solution apparently.

Yes, the only other option is converting svg using inkscape (https://tex.stackexchange.com/a/2107) but this still generates a pdf with the shapes (that turns out to be larger than the directly written .pdf). Not great.

**Comment by bangerth** [comment]
Yes, that's what I meant. But it implies that you have to have inkscape on your system, and that you have to call pdflatex with a special flag.
