### ISSUE TITLE
Possible inconsistency between polynomial degree of topo in geoid code and dynamic_topography code?

### ISSUE THREAD

**Issue by Shangxin-Liu** [geodynamics/aspect#1812]
This has been discussed with Rene during GRC. In dynamic topography code, the stress_support_values which is used to calculated topography uses temperature polynomial degree (cf line 223 in dynamic topography code). However, in geoid code topo_values is set up from veolocity polynomial degree (cf line 181 in geoid code).  Will this cause a certain inaccuracy in the later interpolation from dynamic topo to geoid (cf line 254 in geoid code) when the polynomial degree of temperature is different than velocity? Should we make them both use either velocity or temperature polynomial degree? @gassmoeller @bangerth @ian-r-rose

**Comment by ian-r-rose** [comment]
I think I discussed this with Rene during the Hackathon. My feeling was that as long as they are both interpolating elements, it should be fine. The accuracy is probably limited by the pressure solution, so I as long as the velocity and temperature elements are at least the same order as that, then accuracy should not suffer too much.

I placed the dynamic topography solution in the temperature component for no other reason than that it was a convenient place for a scalar variable (and the stress values were already stored in the velocity components).

**Comment by ian-r-rose** [comment]
That being said, I have not performed much testing on the accuracy of that choice, and would be curious to see some if you feel compelled to do so.

**Comment by bangerth** [comment]
That should be easy to try out -- by default both the velocity and temperature use quadratic elements, but it is easy to reduce the temperature element to linear polynomials. Give that a shot and see whether it makes any kind of difference.

Conceptually, the stress is a derivative of the velocity, so it should be of one polynomial degree less than the velocity. In other words, my intuition would be that it is sufficient to use the temperature field *as long as the temperature polynomial degree is at least the velocity polynomial degree minus one*. That is always the case if the velocity is uses a quadratic element. But it could be forced by using cubic elements for the velocity and linears for the temperature.

**Comment by Shangxin-Liu** [comment]
It seems that if we really want to make a change, the most convenient way is to set the topo_values in geoid code also from temperature polynomial degree to be consistent with Ian's topography code. I'll firstly give a trial to see how different if the velocity and temperature use different polynomial degree in the current code.

**Comment by gassmoeller** [comment]
I agree with Shangxin. Because the degree of quadrature for the geoid postprocessor is somewhat arbitrary, we might as well choose the same degree as the dynamic topography postprocessor to make it consistent. So using the temperature_degree instead of the velocity_degree for the geoid postprocessor makes sense (and they are the same most of the time anyway). @Shangxin-Liu: do you want to open a pull request for this?

**Comment by Shangxin-Liu** [comment]
Yes. Since the density also comes from temperature terms, I guess it would be better if we can also change the polynomial degree of density contribution part to use temperature instead of velocity, yes? @gassmoeller

**Comment by gassmoeller** [comment]
Closed by #1842
