### ISSUE TITLE
Problems when install trilinos with BLAS!!!

### ISSUE THREAD

**Issue by wkillers** [geodynamics/aspect#1832]
Hi,

**I download the trilinos-11.4.3 which is required according to the ASPECT manual. When I configured it with cmake there is a problem arise:**
`[wangym@ln01 build]$ cmake -DTrilinos_ENABLE_Amesos=ON -DTrilinos_ENABLE_Epetra=ON -DTrilinos_ENABLE_Ifpack=ON -DTrilinos_ENABLE_Aztec00=ON -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Teuchos=ON -DTrilinos_ENABLE_MueLu=ON -DTrilinos_ENABLE_ML=ON -DTrilinos_VERBOSE_CONFIGURE=OFF -DTPL_ENABLE_MPI=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=/home/wangym/software/trilinos-11.4.3 ../`
```
......
Getting information for all enabled TPLs ...
-- Processing enabled TPL: Pthread
-- Processing enabled TPL: MPI
-- Processing enabled TPL: BLAS
--   Searching for library 'blas' ...
--   Searching for library 'blas_win32' ...
--   Warning: Could not find a library in the set "blas blas_win32" for the TPL BLAS!  Please manually set BLAS_LIBRARY_DIRS and/or BLAS_LIBRARY_NAMES or just TPL_BLAS_LIBRARIES to point to the BLAS libraries!
CMake Error at cmake/tribits/package_arch/TribitsTplDeclareLibraries.cmake:326 (MESSAGE):
  Could not find the BLAS Library! Please manually set BLAS_LIBRARY_DIRS
  and/or BLAS_LIBRARY_NAMES or just TPL_BLAS_LIBRARIES to point to the BLAS
  libraries!
Call Stack (most recent call first):
  cmake/TPLs/FindTPLBLAS.cmake:69 (TRIBITS_TPL_DECLARE_LIBRARIES)
  cmake/tribits/package_arch/TribitsGlobalMacros.cmake:1101 (INCLUDE)
  cmake/tribits/package_arch/TribitsProjectImpl.cmake:236 (TRIBITS_PROCESS_ENABLED_TPLS)
  cmake/tribits/package_arch/TribitsProject.cmake:75 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:88 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
See also "/home/wangym/software/source/trilinos-11.4.3-Source/build/CMakeFiles/CMakeOutput.log".

```
**It look like that I don't have blas installed. So I downloaded lapack-3.7.0 which contained blas in it, and install it by "make" in my downloaded lapack directory. But I only got "librefblas.a", "liblapack.a" files and there is no "lib" directory that I can point to it. So I change to the following command:**
`[wangym@ln01 build]$ cmake -DTrilinos_ENABLE_Amesos=ON -DTrilinos_ENABLE_Epetra=ON -DTrilinos_ENABLE_Ifpack=ON -DTrilinos_ENABLE_Aztec00=ON -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Teuchos=ON -DTrilinos_ENABLE_MueLu=ON -DTrilinos_ENABLE_ML=ON -DTrilinos_VERBOSE_CONFIGURE=OFF -DTPL_ENABLE_MPI=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -DCMAKE_BUILD_TYPE=RELEASE -DBLAS_LIBRARY_NAMES:STRING=/home/wangym/software/lapack-3.7.0/librefblas.a -DLAPACK_LIBRARY_NAMES:STRING=/home/wangym/software/lapack-3.7.0/liblapack.a -DCMAKE_INSTALL_PREFIX:PATH=/home/wangym/software/trilinos-11.4.3 ../`

But I got the same error message. How to solve such problems?

BTW: My computer uses intel2017 compilers that contain mkl. It seems that the mkl incorporates blas/lapack within it. How can I use it instead of install lapack/blas myself?

**Comment by bangerth** [comment]
@wkillers -- did you figure it out yourself?

**Comment by wkillers** [comment]
yes, I just change "-DBLAS_LIBRARY_NAMES:STRING=/home/wangym/software/lapack-3.7.0/librefblas.a" to "-DTPL_BLAS_LIBRARIES:FILEPATH="/home/wangym/software/lapack-3.7.0/librefblas.a"", and also similar change for lapack library path, and then every goes well.

Thanks.
