### ISSUE TITLE
adding one parameter in the S20RTS.prm makes mistake

### ISSUE THREAD

**Issue by Lydia823** [geodynamics/aspect#1834]
After just adding one parameter that 'set Output data in geographical coordinates = true' followed after the parameter 'set List of postprocessors =...', there appeared errors, like this
`dell.19851hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
dell.19848hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
dell.19850hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
dell.19849hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.0.0-pre
--     . running in DEBUG mode
--     . running with 4 MPI processes
--     . using Trilinos
-----------------------------------------------------------------------------

    Line <118> of file <input string>: No entry with name <Output data in geographical coordinates> was declared in the current subsection.

----------------------------------------------------
Exception 'dealii::ExcMessage ("Invalid input parameter file.")' on rank 0 on processing: 

--------------------------------------------------------
An error occurred in line <343> of file </home/crh/src/aspect-master/source/main.cc> in function
    void parse_parameters(const string&, dealii::ParameterHandler&)
The violated condition was: 
    false
Additional information: 
    Invalid input parameter file.
--------------------------------------------------------

Aborting!
----------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5774,1],1]
  Exit code:    1
--------------------------------------------------------------------------
`
So what's the reason for this?

**Comment by tjhei** [comment]
This is the problem:
``
Line <118> of file <input string>: No entry with name <Output data in geographical coordinates> was declared in the current subsection.
``
You are setting a parameter that doesn't exist. It needs to be in the correct subsection (``Geoid`` I believe).

**Comment by tjhei** [comment]
I am closing the issue. Feel free to open it or ask on the mailing list if you have further problems.
