### ISSUE TITLE
Error when using an error function for temperature!!!

### ISSUE THREAD

**Issue by wkillers** [geodynamics/aspect#1846]
hi,

I am trying to set an initial temperature field with an error function like this:

> if(x<1050.e3 && z>=800.0e3,T0+DT*erf(z/2.0/sqrt(kappa*t1*year)), \
>                                  T0+DT*erf(z/2.0/sqrt(kappa*t2*year)))

but when I run aspect, this is an error:

> An error occurred in line <400> of file </home/wangym/software/source/dealii-8.5.0/source/base/function_parser.cc> in function
>     double dealii::FunctionParser<dim>::value(const dealii::Point<dim>&, unsigned int) const [with int dim = 2]
> The violated condition was:
>     false
> Additional information:
>     Parsing Error at Column 1. The parser said: Unexpected token "erf" found at position 33.

I am not sure how to solve this problem? Anyone can help?

Thanks.

**Comment by tjhei** [comment]
``erf`` is not available in the deal.II ``FunctionParser`` (see http://www.dealii.org/developer/doxygen/deal.II/classFunctionParser.html ). It is probably easiest to write an initial temperature plugin and use the c function.

**Comment by tjhei** [comment]
I am closing this issue because it is not really a bug. Feel free to comment or open another issue.

**Comment by jperryhouts** [comment]
> erf is not available in the deal.II FunctionParser

erfc is though! I added it a while ago for exactly this reason. https://github.com/dealii/dealii/pull/1769
