### ISSUE TITLE
doc/update_prm_files_to_2.0.0.sed does not work on Macs

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1857]
See #1741, the update script for prm files uses GNU extension of `sed` that is Mac incompatible. Find a Mac compatible command.

**Comment by tjhei** [comment]
option 1: ask people to install gnu sed (``brew install gsed``)
option 2: understand why your command is illegal, because it looks like it should, see https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/sed.1.html
option 3: use something like perl instead of sed.
