### ISSUE TITLE
Density issues with continental extension cookbook

### ISSUE THREAD

**Issue by heronphi** [geodynamics/aspect#1866]
Hello, I'm just playing around with the continental extension cookbook. 

The model has four compositional fields: 

subsection Compositional fields
  set Number of fields = 4
  set Names of fields = upper, lower, mantle, seed
end

In the cookbook, the density is set within the visco plastic setup: 

    set Thermal diffusivities = 1.333333e-6, 1.190476e-6, 1.149425e-6, 1.333333e-6, 1.333333e-6
    set Heat capacities       =        750.,        750.,        750.,        750.,         750.
    set Densities             =        3300,        2800,        2900,        3300,         3300
    set Thermal expansivities =        2e-5,        2e-5,        2e-5,        2e-5,         2e-5

I assumed that the first input is for the background rheology, however I obtain a density of 3300 for the upper crust. I can only obtain correct density for the whole model by switching the first and second inputs - the second input being the background. 

Is this correct? Is the density of the upper crust being 3300 something that other people have seen? Or is there something wrong my end? 

If other people do see the 3300 for the upper crust, then I think the cookbook should be modified.

**Comment by naliboff** [comment]
@heronphi - I just checked the density and composition structure from the recent update of the cookbook and everything looks correct. The first field is indeed for the background material and the second is for the upper crust. 

Did you run the cookbook without modification or was something altered?

**Comment by heronphi** [comment]
Hi John, 

Yep - the density is fine in the cookbook. I do apologize - this was an oversight. I had changed something in the subsequent models which seems to have caused an issue. I added strain weakening and it changed the upper crustal density. 

I'll close this now and look into what is going on with the strain weakening. Sorry for the issue! 

Phil

**Comment by naliboff** [comment]
@heronphi - no worries and glad to hear there was not a density inversion in the cookbook! If you have questions about strain weakening, just send an email to aspect-devel or contact me directly for very specific questions about setting up new extension models.
