### ISSUE TITLE
Why were the two same parameters set different values in pages 368-369 of the manual?

### ISSUE THREAD

**Issue by Lydia823** [geodynamics/aspect#1870]
In page 368, the parameter 'Density below' was set to 9900 km/m^3. However, in next page, the parameter 'Density below' was set to 8000. Why is there a difference?

**Comment by jaustermann** [comment]
Hi Ronghua, 

The density below is set separately for the calculation of the bottom dynamic topography and the geoid. In a consistent model these should be the same though, good catch! I submitted a pull request to make those two default values the same, it might take some time until this update reaches the manual (not sure how often that is recompiled). 
While there will be a default value (which I set to 9900 km/m^3 for both postprocessors now) you might want to think about what value is most appropriate for you model (this depends on what you assume for the mantle temperature, whether the model is compressible etc.). When you manually set the ‘density below’ value in the parameter file (i.e. overwrite the default value), make sure to set this to the same value in both the dynamic topography and the geoid parameter section.

Best,
Jacky

**Comment by bangerth** [comment]
I think the online manual is updated every night. So it should show the new values soon after the patch is merged.

**Comment by Lydia823** [comment]
OK, i haven't downloaded the latest manual,thanks @jaustermann @bangerth

**Comment by bangerth** [comment]
Fixed by #1871.
