### ISSUE TITLE
Particle rewrite

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1897]
@gassmoeller is currently rewriting the particle system so that it can move into deal.II (or at least the generic parts). This is the meta-issue that tracks all of the relevant PRs.

**Comment by bangerth** [comment]
@gassmoeller -- is there anything that's left here, or can we close this?

**Comment by gassmoeller** [comment]
I would like to keep this open until I finish #1957, currently we still use the ASPECT version of the code instead of the one in deal.II.

**Comment by tjhei** [comment]
:clinking_glasses:

**Comment by gassmoeller** [comment]
Yay :tada:
