### ISSUE TITLE
make the cell object input argument in the constructor of material models inputs a reference instead of a pointer

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#1907]
This would be a follow-up to #1904, where we change the material model inputs structure to have the cell object (instead of a pointer to the cell) as a variable, so that it can be used in more places in the code.

**Comment by bangerth** [comment]
For the place where this came up, see https://github.com/geodynamics/aspect/pull/1904/files#r134359434

**Comment by gassmoeller** [comment]
Was this closed by #1910?

**Comment by jdannberg** [comment]
Yes.
