### ISSUE TITLE
Unify solver output

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#1964]
See #1850 and #1433:

I think we should also unify these outputs, so that it is easier to grep them. Some for example start with 'Total relative ... 'and others with 'Relative ... '. This could then for example become something like 'Nonlinear residual (Stokes) for iteration ... ' or 'Nonlinear residual (Total) for iteration ...' etc. And then always for every timestep end with Final residual for timestep ... . 

But as stated in #1850 this might be more complex then it looks and it will be a lot of work to update all the tests, so I think it is a good idea to first discuss here.

**Comment by jdannberg** [comment]
I think if we just want to change the output for the log file, that should not be too difficult. The main problem I had with unifying the output of the different solver schemes (after #1433) was the output for the statistics file. So I can have a look at this in the next few days. 

But of course it would be great if we could agree on a scheme for the output before. I like @MFraters suggestion 'Nonlinear residual (Total/Stokes/etc.) for iteration ...'. We could also leave in the 'relative', making it 'Relative nonlinear residual (Total/Stokes/etc.) for iteration ...', if we think that's important.

**Comment by gassmoeller** [comment]
Was this resolved by #1983?

**Comment by gassmoeller** [comment]
I think we resolved this with all the changes to the nonlinear solver schemes of the last months. Feel free to reopen if the problem persists.
