### ISSUE TITLE
Rename IMPES scheme to something more accurate

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1969]
As @bangerth pointed out in https://github.com/geodynamics/aspect/pull/1850#discussion_r147316231 IMPES is actually no longer an accurate name for our default solver scheme. Since we are reorganizing things for ASPECT 2.0 anyway, find a better name and replace the use of IMPES (we can allow legacy use of the term in parameter files, but remove it from the source code).

**Comment by bangerth** [comment]
We should really address this before the 2.0 release, though I don't know what better name we may want to choose.

We could just grandfather the name and carefully document what the name *actually* corresponds to today. What do you all think?

**Comment by gassmoeller** [comment]
Closed by #2162
