### ISSUE TITLE
[post deal.II 9.0.0] fix labels in manual.tex

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1987]
We need to fix annotate.pl, see https://github.com/dealii/dealii/pull/5385

**Comment by bangerth** [comment]
You mean we have to change annotate.pl because now the latex labels no longer match the parameter strings (which are escaped)? Could you give an example?

**Comment by tjhei** [comment]
Yes. For example:
```
-\phantomsection\label{parameters:First Class/First double}
+\phantomsection\label{parameters:First_20Class/First_20double}
```
so annotate.pl needs to mangle the label names (we already do this for section labels but not for parameter labels). Of course this is not backwards compatible, so we need to wait until we switch to 9.0.0 unconditionally.

**Comment by bangerth** [comment]
I'll comment on this in the deal.II PR, but I think that in labels, we only need to/should escape what really needs to be escaped (i.e., exclude spaces for example). That would make the transition easier because I suspect that we don't have any labels that currently contain percent signs.

**Comment by tjhei** [comment]
> but I think that in labels, we only need to/should escape what really needs to be escaped

Spaces are actually allowed inside labels but we have been escaping them for section names (but not for labels of parameter names!) in the past for some reason. Whatever you prefer, staying with the current idea doesn't make much sense. I will comment there...

**Comment by bangerth** [comment]
Yes, see my review there.

**Comment by tjhei** [comment]
After 1.5 years I have no recollection on what I was trying to say here. It seems that the deal.II PR added backwards compatibility (space as " " or as "_20"). This means things are correct and we don't need to do anything.

**Comment by gassmoeller** [comment]
The lets close the issue unless we find the problem again.
