### ISSUE TITLE
[deal 9.0.0] tests/ellipsoidal_chunk_noncoordinate_parallel.prm

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1990]
and and octagonal_initial_temperature_ellipsoidal_chunk.prm fail with a Floating point exception. Check what is going on...

**Comment by gassmoeller** [comment]
I am looking into this right now.

**Comment by gassmoeller** [comment]
Both tests run fine with dealii/dealii#5393

**Comment by gassmoeller** [comment]
Fixed by dealii/dealii#5393
