### ISSUE TITLE
compiling manual in LaTex issue (rerunfilecheck.sty?) *help wanted*

### ISSUE THREAD

**Issue by njinju** [geodynamics/aspect#2000]
Hello. I'm a new user to ASPECT and aim to submit a new cookbook, but I'm having trouble compiling the manual. Attached is a screenshot showing the place where compilation stops in TexShop on my Mac. I am using the most recent development version of ASPECT 2.0.0-pre.

Do you have any suggestions?

![screen shot 2017-11-08 at 10 22 01](https://user-images.githubusercontent.com/30853837/32557083-2cbf2e5a-c46f-11e7-99ab-a5977c696315.png)

**Comment by bangerth** [comment]
How do you compile the file? The intent is to go into the `doc/` folder and then just type `make manual.pdf`. Does that work for you?

**Comment by njinju** [comment]
It works perfectly thanks.

**Comment by bangerth** [comment]
OK, great. If the issue is resolved for you, can we close the issue?

**Comment by njinju** [comment]
Yes we can close the issue
