### ISSUE TITLE
assembler cleanup: Scratch::reinit()

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2010]
Introduce ``Scratch::reinit(cell)`` and ``Scratch::reinit(cell,face)`` that calls ``fe_values.reinit(...)`` and (re)sets internal properties like ``cell``, ``face_no``, etc.
We can than also move other common operations into this like computing the stokes DoFs.

**Comment by wanyingw** [comment]
@alarshi -- did this get completely fixed, or is there anything left to do?

**Comment by alarshi** [comment]
This issue is resolved after the pull request #2357.

**Comment by bangerth** [comment]
@alarshi -- thank you for checking!
