### ISSUE TITLE
solver parameters

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#2023]
During the last hackaton we created a parameter section for solvers parameters, so I could put my Newton parameters in there. I think the idea was that also the other solver parameters would move to there. I think it would a good idea to do this before the release of aspect 2.0, because it would again break parameters files.

**Comment by tjhei** [comment]
> so I could put my Newton parameters in there.

agreed.

> I think the idea was that also the other solver parameters would move to there.

I remember talking with @jdannberg about it last week. We have to balance breaking a lot of prm files with a neater layout, though. I think at least the less common things can go into that subsection.

**Comment by naliboff** [comment]
I'm working on this right now.  Here are the following "solver related" parameters that are **not** in the `Solver parameters` subsection:

- `Max nonlinear iterations`
- `Nonlinear solver scheme`
- `Nonlinear solver tolerance`
- `Use direct solver for Stokes system`
- `Linear solver tolerance`
- `Linear solver A block tolerance`
- `Linear solver S block tolerance`
- `Number of cheap Stokes solver steps`
- `Maximum number of expensive Stokes solver steps`
- `Temperature solver tolerance`
- `Composition solver tolerance`

The obvious candidates to go into the Solver parameters subsection are `Linear solver A block tolerance` and  `Linear solver S block tolerance`.  Moving these also would not require running the update script.

How about the other parameters? @jdannberg and @gassmoeller - I recall that we thought `Nonlinear solver scheme` and  `Nonlinear solver tolerance` should remain in the current (global section).

Thoughts?

**Comment by jdannberg** [comment]
Fixed by #2163 and #2174.
