### ISSUE TITLE
std::isnan() and pre C++11

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2024]
We currently don't require c++11 but we are using ``std::isnan`` in several places which got added in c++11: http://en.cppreference.com/w/cpp/numeric/math/isnan
We also have ``dealii::numbers::is_nan()`` but that is now deprecated in favor of ``std::isnan``.

Before I go change things, does anybody have a better idea than creating ``Utilities::is_nan()`` that uses ``std::is_nan`` or ``dealii::numbers::is_nan``, respectively?

**Comment by bangerth** [comment]
Do you have evidence of compilers that don't actually understand `std::is_nan()`? It may be that all compilers already supported this as part of including C99 functions, even though C++03 didn't require it.

Are these recently introduced places?

**Comment by tjhei** [comment]
> Are these recently introduced places?

No, pretty old. 

What compilers do we support that do not support c++11?

I played with compiler explorer ( https://godbolt.org/g/XnfNNV ) and got the following result:
It seems we are okay with clang >=3.4 (we say deal.II supports clang 3.3), MSVC, gcc with c++11 (>=4.4), recent ICC, recent MSVC

**Comment by bangerth** [comment]
If we had this code for a long time, then I would say let's just not worry about it.

C99 added a bunch of math functions that were not part of C++98 or C++03 (though were finally formally added in C++11), but that all compilers still had in their `<cmath>` header file. I bet `isnan` is one of them. That would explain why we used a function successfully that we strictly speaking could not use, and why nobody ever complained about it.

Any change we could make now is likely unnecessary in view of this, and will be obsolete after 2.0 anyway. So my instinct would be to just ignore things.

**Comment by tjhei** [comment]
agreed.
