### ISSUE TITLE
Post a list of possible output formats

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2055]
Post the list of supported output formats in the description of the Visualization/Output format input parameter.

**Comment by gassmoeller** [comment]
For reference: This would need to be added to the description of the parameter in `source/postprocess/visualization.cc` in the function `Visualization<dim>::declare_parameters`

**Comment by bangerth** [comment]
I'm sure there is a function in namespace `DataOutBase` that provides this.

**Comment by alarshi** [comment]
It is added in the manual currently.

**Comment by gassmoeller** [comment]
Oh, so it is listed as possible values, but not in the description. That is why it appears in the manual, but not in parameters.prm. #2366 adds some description about where to find the available options.
