### ISSUE TITLE
Add rms velocity to the velocity boundary statistics postprocessor

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2060]
It would be nice if the velocity boundary statistics postprocessor would also output the rms velocity on all boundaries. This is especially helpful for computing the mobility of the surface (which is often computed as rms-velocity of surface divided by rms velocity of whole domain).

**Comment by bangerth** [comment]
Would this be the rms of the total velocity, or only for the tangential component? (On most boundary descriptions, they are of course the same.)

**Comment by gassmoeller** [comment]
I suppose the tangential component would be better, but you are right, for most models it should not matter.

**Comment by pmbremner** [comment]
I'll take a look

**Comment by gassmoeller** [comment]
@pmbremner was this fixed by #2336?

**Comment by pmbremner** [comment]
Yes, #2336 addressed this issue. I didn't notice that the commit got a new number. I should have referenced this number in my commit.

**Comment by gassmoeller** [comment]
Ok, then lets close this issue. Thanks for fixing!
