### ISSUE TITLE
Allow more flexible surface movements

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2067]
We have several users that want to create models with more flexible surface deformation algorithms than just 'free surface'. Examples would be surface evolution models (erosion/deposition), or inner core models with a growing domain over time. For these models one would prescribe velocities for the mesh at the surface, but have some other type of boundary (tangential/traction) for the solution velocity. I have been thinking about how to properly incorporate that into our current scheme, and think our current `FreeSurfaceHandler` mixes functionalities that can be logically separated:

1. Calculate the mesh velocity of the boundary nodes.
2. Adjust the overall mesh according to the boundary mesh velocities.
3. Correct advection velocity according to mesh velocity.

Steps 2 and 3 are the same for all of these approaches, but step 1 can use different velocities (e.g. the solution velocity in the free surface case, a modified solution velocity in the erosion case, or a prescribed velocity in the inner core case). I would therefore go ahead and extend the `FreeSurfaceHandler` to handle different boundary velocities. Optionally, we could think about renaming `FreeSurfaceHandler` to `MovingSurfaceHandler` or something similar.

I mostly open this issue to collect opinions, but I can also make a WIP pull request and ask for comments there.

**Comment by ian-r-rose** [comment]
I think this makes good sense @gassmoeller. I could envision a new plugin structure where people can enable various "rules" for how to move the free surface. Some questions that would need to be answered:
1. Should only one rule be enabled at a time, or can people activate different rules (for instance, combining dynamic topography with erosion)?
2. If more than one rule can be active at the same time, how do we combine them? The simplest would be to do an operator-splitting approach, where we just apply the various rules one-by-one. The downside of this is that it probably would have unknown error and stability characteristics.
3. If there is an operator splitting approach, in what order would one apply the rules?
4. How would this interact with the free surface stabilization algorithm? The dynamic topography rule is simple enough that it can be made "quasi-implicit", allowing a boundary stress to be assembled on the LHS for stabilization purposes. Other rules are probably not as straightforward.

This is only tangentially (no pun intended) related, but I think that the step 3 (ALE velocity correction) could perhaps use some revisiting as well. When the motion of the free (or moving) surface is relatively large, this velocity correction can cause some difficulties for the advection solver. I think this is the cause of some instabilities in the advection solver that have been reported recently. There may some assumption in the preconditioner or extrapolation that is being violated by this ALE correction step.

**Comment by bangerth** [comment]
I don't have an opinion on the other issues but think that it would be useful to somehow allow different effects to act at the same time. The example of free surface + erosion is one case that's worth supporting. I don't know how to make this stable.

**Comment by gassmoeller** [comment]
Thanks for the input. I will create a preliminary PR and we can discuss details there.

1./2. I agree with Wolfgang, I would allow several to be active and simply add up contributions. This might lead to problems if they depend on each other, but I would worry about that when it actually occurs.
3. In the order the user supplies them. If somebody activates several of them, they need to be aware of what they are doing, and we can not guess what that is.
4. As far as I can see the stabilization is an additional assembler. I would suggest the future 'free surface' mesh deformation plugin can keep this assembler, any 'function' plugin will not need stabilization (because we prescribe it exactly), and if somebody implements something more complicated they can worry about writing better stabilization assemblers :smile:.

One more point: I will try to prepare everything also for the case somebody wants to prescribe the movement of 'every' mesh node, not just the surface. In that case we would not need to solve the Laplace problem.

**Comment by anne-glerum** [comment]
Discussion at the hackathon led to the following TODOs:

- [ ] Add multiple stages functions to the existing pr #2071. Right now the interface provides plugin the free surface DOFHandler and allows plugins to modify the constraint matrix. To allow for more conforming plugins, add functions that ask only for the mesh deformation of a given position. 
- [ ] Allow for traction boundary conditions set at the free surface.
- [ ] Check whether the free surface handler can be used _inside_ the iterative solver schemes (set current linearization point)
- [ ] Check what velocity (normal to the surface or vertical) is used in correcting the velocity in the advection equation assembly. 
- [ ] Prescribe Dirichlet boundary conditions for temperature and composition only on the part of the boundary where there is inflow
- [ ] Update the particle reference velocity with the mesh velocity.

**Comment by gassmoeller** [comment]
I think this was solved by #2964 and most of the issues in your last post have either been solved, or are now part of #3720. Can we close this issue?

**Comment by anne-glerum** [comment]
Yes this can be closed. I checked of the resolved issues.
