### ISSUE TITLE
Add instructions/a template for new cookbooks

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#2109]
This was a suggestion by @lkellogg: It would be easier to contribute cookbooks for people who start out with ASPECT, but have experience in a certain area of convection models, if we had a template and instructions for how to write a cookbook.

**Comment by naliboff** [comment]
As far as instructions go, it seems like the key steps are:

1.  Build off existing cookbooks or examples as much as possible.
2. The cookbook should use existing code or be submitted as a pull request that includes the new code. However, submitting the new code first in a separate pull request is preferable. 
3. Heavily document (comments) the parameter file in `aspect/cookbooks`.
4. Describe the relevant physics and any relevant previous studies in the manual.
5. Include figures and key portions of the parameter file in the manual.
6. Brief instructions on how to use annotate.pl for including portions of the parameter file in the manual.

Suggestions for other key steps or bits of information to include?

**Comment by jdannberg** [comment]
For 3, I would specifically include:
- what is the motivation of the model?
- what is the setup: initial conditions, boundary conditions, geometry, etc, anything that is special and that is the point of this cookbook
- what is the model evolution / show some type of result
- optional: how can the setup be modified or be played around with to make it more realistic or to do sensitivity tests?

For 6. I would explain in detail how to include code and cookbook snippets.

**Comment by bangerth** [comment]
I think the steps @jdannberg mentions in the previous comment for (3) should actually go into the manual, not into the .prm file as @naliboff suggests. So maybe her list should be a step (2a), with @naliboff's step (3) still in place.

**Comment by jdannberg** [comment]
I agree, and I actually totally forgot we had this issue and this discussion, I only remembered that we needed a guide for how to write cookbooks and did #2281. 
Do you want me to add all of the things mentioned here and that I missed to the pull request #2281?

**Comment by jdannberg** [comment]
We can add also add a note to the existing section in the manual that explains that one should use perceptually uniform colour scales, and recommend some color scales for certain outputs, like temperature, velocity etc.

**Comment by jdannberg** [comment]
This was addressed by #2281 and #2472.
