### ISSUE TITLE
New test setup

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2143]
As discussed with @tjhei a while ago in an email chain, CIG would like to help with setting up testers for software projects. Our current setup works well for normal development, but it is often overwhelmed during hackathons, it is not scalable, and it depends on one of the maintainer being able to run a machine with root access (for the docker containers). An earler try was Jenkins (http://blofeld.geodynamics.org/), but that got little attention, because it is not directly integrated into Github.
We are currently discussing a new approach. No decision has been reached yet, but I would like to put it out here just to let everyone know what is going on. The current plan is to keep the existing docker containers with small modifications to run the different test setups (the dockerfiles could move into our main repository), and set up a free drone server here at CIG (https://drone.io/) to start and manage the tests. Drone comes with native support for containers and integrates immediately with Github. A first glimpse of how that could look like can be seen here: https://github.com/gassmoeller/aspect/pull/9.
When we have finished the drone setup a click on 'Details' will bring you to a page similar to what we have at the moment that details what went wrong during the build (it outputs the screen output of the tester during the build). The nice thing about this approach is that we can parallelize testing different builds or prs by adding many machines as so called drone 'agents'. Also every user can easily run the test suite on their own (by running the docker containers with certain environment variables), and if at some point the drone server should go offline, it is free software and somebody else (e.g. one of the maintainers) can set up a new server. Also all of the configuration has to be part of the main repository, which makes reproducing all of this simpler.

I will update this issue as soon as we have more to show, but feel free to give feedback already.

**Comment by tjhei** [comment]
> and it depends on one of the maintainer being able to run a machine with root acces

not true. I am using docker-machine and run the stuff inside virtualbox.

> earler try was Jenkins [...] it is not directly integrated into Github.

The important part is testing pull requests and posting commit status messages. This can be done using the github status plugin in jenkins, so we can use a jenkins setup. This can be the server run at Davis or mine at jenkins.tjhei.info (play ground for deal.II related testing for now).

> The nice thing about this approach is that we can parallelize testing different builds or prs by adding many machines as so called drone

The same can be done with jenkins. What is your reason to go with drone instead of jenkins? Can drone support non-linux slaves? It looks like the slave is always running inside docker so testing OSX or windows is difficult. This means for deal.II I would prefer to go the jenkins route...

Maybe we should talk about pros & cons at some point.

**Comment by tjhei** [comment]
> Is the jenkins server what you plan on doing for deal.II?

Well, it is a playground to learn how it works for aspect, deal.II, etc. and we could also use it productively for all of them if we want. The deal.II and ASPECT integration testers are not using the jenkins machine yet.

**Comment by gassmoeller** [comment]
The CIG tester will receive an update by @tjesser-ucdavis-edu over the next days that will hopefully resolve the connection issues, but might cause it to be offline for a few days. It will be back asap.

**Comment by gassmoeller** [comment]
The CIG tester is back online for two weeks now and available under [jenkins.geodynamics.org](jenkins.geodynamics.org). So far it seems to be running smoothly thanks to @tjesser-ucdavis-edu. I will close this issue in the hope that we resolved the connection problems.
