### ISSUE TITLE
Spiegelman benchmark has no parameter file

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2167]
@MFraters Was this supposed to get a parameter file some time? Currently, it is a bit confusing to have a cc file but not a prm file.

**Comment by MFraters** [comment]
Yes, I will have to think of a way to structure it correctly since it consists of 27 different settings of which I reproduce 18 with all kinds of parameters. Will do this after we have submitted the paper.

**Comment by gassmoeller** [comment]
Would you be ok if we move this to the tests/ for the release, and until we have the complete benchmark description?  As far as I can see it is only used in tests/spiegelman_material.prm. Otherwise users might be confused.

**Comment by jdannberg** [comment]
We could also move it to the cookbooks/future folder, if there is not prm file to run it at the moment...

**Comment by MFraters** [comment]
I am fine with both options.
