### ISSUE TITLE
failing quick test (clang 6)

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2210]
I get
```
Loading shared library <./libquick_mpi.so>
ERROR: Uncaught exception in MPI_InitFinalize on proc 0. Skipping MPI_Finalize() to avoid a deadlock.


----------------------------------------------------
Exception 'ExcMessage (std::string("Could not successfully load shared library <") + shared_libs_list[i] + ">. The operating system reports " + "that the error is this: <" + dlerror() + ">.")' on rank 0 on processing: 

--------------------------------------------------------
An error occurred in line <237> of file <../source/main.cc> in function
    void possibly_load_shared_libs(const std::string &)
The violated condition was: 
    handle != NULL
Additional information: 
    Could not successfully load shared library <./libquick_mpi.so>. The operating system reports that the error is this: <./libquick_mpi.so: undefined symbol: _ZNK6aspect11Postprocess9InterfaceILi2EE29required_other_postprocessorsEv>.
--------------------------------------------------------
```
and I don't understand how this can happen. We need to investigate before releasing. Happens with clang 6 on ubuntu 14.04

**Comment by gassmoeller** [comment]
How did you install clang 6? On http://apt.llvm.org/ they mention that they need some backported libstdc++ for 14.04. Could that be the issue?

**Comment by gassmoeller** [comment]
I do not have clang 6 available to check. Is clang 6 the default for the new Ubuntu 18.04? Then we should probably check if it happens there as well (I can do that in a docker container later today). If it is only the combination of ubuntu 14.04 and clang 6 then I am not too worried (I do not know many users who manually update their compilers on older ubuntu versions).

**Comment by gassmoeller** [comment]
I could reproduce this and #2211 on my ubuntu 14.04. Will try next with 18.04 in a docker container. Still need to check if the libstdc++ backport will work.

**Comment by gassmoeller** [comment]
Ok, so I followed the instruction on http://apt.llvm.org/ and now I can not longer enable FP exceptions in cmake (apparently the test fails). Unfortunately now my linker fails (because it no longer finds fortran) and I can not check if I can run the test without exceptions. On ubuntu 18.04 with clang-6 this error does not happen (so maybe it is just the binary of clang-6 that does not work with ubuntu 14.04).

**Comment by tjhei** [comment]
yes, I used the binaries on 14.04. Let's ignore it!
