### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2215]
I haven't found an issue to discuss the release planning for 2.0. Let's have the conversation in here.

Open issues: https://github.com/geodynamics/aspect/milestone/4

Things to consider to put in:
- [x] #2214
- [x] #2212 -> delay 
- [x] #2213

**Comment by tjhei** [comment]
@gassmoeller can you think about the open PR's and let me know when I can branch off of master?

**Comment by gassmoeller** [comment]
I would say lets keep #2212 out of the release. It is nice to have, but it requires retesting too many things.
#2213 might be important though, since one of our tests creates divisions by zero with deal.II 9.0. I will maybe have to update the results once more, but after that it should be ready to go.

My vote: Include #2213 and then branch of 2.0.

**Comment by bangerth** [comment]
You all have thought this through much more than I have, but this choice seems reasonable. #2212 only adds a test. If the process we've been going through over on the deal.II side right now indicate anything, then it's that there ought to be a point where only absolutely critical things should go in. #2212 doesn't seem critical.

**Comment by tjhei** [comment]
I will be offline for a bit (flight to Europe), but I will branch off for the release soon.

**Comment by gassmoeller** [comment]
I think #2227 and #2225 are the last missing pieces for the release. It would be great if we had a tagged and uploaded release until Thursday (when we give the webinar about it). No need to do everything until then, but a tar version on github would be great.

**Comment by tjhei** [comment]
> No need to do everything until then, but a tar version on github would be great.

I will do the release tomorrow, at least the branch + RC.

**Comment by gassmoeller** [comment]
Great, thanks!

**Comment by jdannberg** [comment]
Yes, thank you both for all your work!

**Comment by tjhei** [comment]
I think we are good with #2228 and #2229 if one of you wants to merge...

**Comment by bangerth** [comment]
Looks good to me as well!

**Comment by tjhei** [comment]
I tagged rc1: https://github.com/geodynamics/aspect/releases/tag/v2.0.0-rc1

anyone want to give this a spin?

**Comment by MFraters** [comment]
Compiles on a linux machine without warnings (deal.ii 8.5). I also ran the test, only a few failed. I didn't look at why they failed yet.

```
The following tests FAILED:
	 14 - adiabatic_initial_conditions_chunk (Failed)
	 15 - adiabatic_initial_conditions_chunk_3d (Failed)
	 54 - average_density_boundary_fluid_pressure (Failed)
	127 - compression_heating (Failed)
	196 - geoid_visualization (Failed)
	213 - graphical_output_hdf5 (Failed)
	216 - heat_advection_by_melt (Failed)
	217 - heat_advection_by_melt_operator_splitting (Failed)
	279 - matrix_nonzeros_4 (Failed)
	280 - matrix_nonzeros_5 (Failed)
	332 - nonlinear_channel_flow_tractions_iterated_IMPES (Failed)
	337 - nonlinear_channel_flow_velocities_iterated_IMPES (Failed)
	375 - particle_output_hdf5 (Failed)
	438 - refine_vel (Failed)
	453 - segregation_heating (Failed)
	533 - traction_ascii_data (Failed)
```

**Comment by tjhei** [comment]
> Compiles on a linux machine without warnings

great, thank you!

> only a few failed. I didn't look at why they failed yet.

That is to be expected as it depends on the precise system and library versions you are running.

**Comment by MFraters** [comment]
I now looked at them, and they all seem to be very minor changes in some values (usually in the order of 1e-4) or a small change in the iteration count. The hdf5 failed because hdf5 was not installed on this particular setup apparently :)

**Comment by tjhei** [comment]
If I don't hear otherwise, I will make the final 2.0.0 in the next 24 hours (whenever I have good enough internet).

**Comment by tjhei** [comment]
okay, here is the release: https://github.com/geodynamics/aspect/releases/tag/v2.0.0
here is the zenodo DOI: https://doi.org/10.5281/zenodo.592692

**Comment by tjhei** [comment]
figshare: https://doi.org/10.6084/m9.figshare.4865333.v4

**Comment by tjhei** [comment]
website is also updated. Things that are left to do: 
1. update http://geodynamics.org/cig/software/aspect/
2. announce the release vis email

**Comment by gassmoeller** [comment]
Thanks for all the work! I will talk to people here about geodynamics.org. Do you want  to send the release mail? Otherwise I can do that tomorrow.

**Comment by gassmoeller** [comment]
Release email is out. It might take a while to show up on the CIG mailing lists, because I used the ucdavis email for that (new address). I guess that means the deal.II users are first to be notified.
Anyway, I think we got everything. Time to celebrate :tada:

**Comment by tjhei** [comment]
Thanks!

**Comment by tjhei** [comment]
Let's plan to have the next release in a shorter time frame. 😉

**Comment by gassmoeller** [comment]
I agree. 2.1.0 before AGU?
