### ISSUE TITLE
html manual?

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2231]
We discussed generating an html version of the manual in the past. I have played with ``make4ht`` and have a preliminary version here: http://www.math.clemson.edu/~heister/aspect-manual/manual.html

While many things are broken, it is quite useful to link people to a specific section in the manual, which is difficult in a pdf. Does it make sense to continue working on this? Note that some of the images/links/references/etc. are currently broken.

**Comment by bangerth** [comment]
Neat. I think this is useful indeed, if you can get the currently broken parts going. 

If you want to link to individual sections, you also need stable links to sections. Does make4ht give you that?

**Comment by tjhei** [comment]
> If you want to link to individual sections,

Section names are ``manualseX.html`` where X is the section number, which should be somewhat stable. Subsections of course change, so that is an issue. I will play with this a bit.

**Comment by MFraters** [comment]
Looks cool Timo! Is this automatically loaded/linked from github every time you load a page, or do you have to compile it every now and then like the pdf?

**Comment by tjhei** [comment]
> automatically loaded/linked

right now it is generated manually.

> to compile it every now and then like the pdf?

the pdf is generated every night.

**Comment by tjhei** [comment]
how about this? http://www.math.clemson.edu/~heister/aspect-manual/nav.xhtml

One .html per chapter (otherwise the file is too big) and links are by name.

**Comment by jdannberg** [comment]
That's really nice!
How do you want to continue with this (fixing the figures, etc.)? Also let me know if you reach a point where you need someone to look through the document to see if the formatting looks good everywhere!

**Comment by tjhei** [comment]
> fixing the figures

It seems like embedded pdfs look terrible: http://www.math.clemson.edu/~heister/aspect-manual/ch006.xhtml#sec:finite-strain while other images looks mostly okay (except sizing issues).

> Also let me know if you reach a point where you need someone to look through the document to see if the formatting looks good everywhere!

Maybe it is a bit too early. I think we should decide if this is promissing enough, then merge it as is and put it online before we fix other stuff. Hackathon starter projects? ;-)

**Comment by bangerth** [comment]
Nice indeed!

Something also goes wrong with tables, see http://www.math.clemson.edu/~heister/aspect-manual/ch006.xhtml#sec:sinker-with-averaging and the latex formatting instructions that leak into the HTML. For the figures, one of the problems is that the PDF or PNG versions are in whatever size they come, and latex rescales them. I don't think this is happening here.

**Comment by jperryhouts** [comment]
This is great! The pdf version looks nice, but I doubt anyone prints it out, which is the only real benefit of a pdf.

Markdown with mathjax equations, served via github pages, might be a more natural format for the whole thing, and wouldn't require rebuilding every time the sources change.

**Comment by tjhei** [comment]
so, I have an alternative proposal that doesn't require compiling the manual as html: Use an online pdf viewer (pdfjs) that allows deeplinking of sections:
http://www.math.clemson.edu/~heister/aspect-pdf-manual/web/viewer.html#subsection.2.8

If we are happy with it we can start using it on the mailing list, website, etc..

Should we still merge this PR though? It doesn't do a lot of harm to allow html generation but it might break in the future.

**Comment by bangerth** [comment]
No longer relevant.
