### ISSUE TITLE
Add reference to Nimmo et al. (2014) to the 'dynamic core' boundary temperature model

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#2238]
The `source/boundary_temperature/dynamic_core.cc` file repeatedly refers to a paper by "Nimmo et al. (2004)", but this paper is not referenced in the manual and not in the bibtex file either.

**Comment by bangerth** [comment]
(Found in #2237.)

**Comment by geodynamics01** [comment]
I am going to work on this!
