### ISSUE TITLE
Post-2.0 cleanups

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#2244]
I can think of the following things we ought to do:
- [ ] Require deal.II 9.0 in `CMakeLists.txt`
- [ ] Document this where appropriate
- [ ] Switch the testers to use deal.II 9.0
- [ ]  Remove `#if DEAL_II_VERSION_GTE(9,0)` statements.

This means we are now allowed to use C++11 -- yay!

**Comment by bangerth** [comment]
We can also remove `#if DEAL_II_VERSION_GTE(9,0)` statements.

**Comment by tjhei** [comment]
Does this make sense to do before the hackathon?
Pro: 
- we can hand out starter projects to do c++11 related cleanups.
- we don't have to worry about 8.5 and 9.0 compatibility
Cons:
- Updating the test infrastructure (and test output) is a lot of work
- This forces everybody to install 9.0 on their machines.

**Comment by tjhei** [comment]
As a compromise: we could require c++11 (enforce in cmakelists.txt) and start using c++11 stuff today! This would give some nice starter projects...

**Comment by bangerth** [comment]
You mean continue to allow deal.II 8.5, but require C++11 anyway? That sounds fine with me.

**Comment by bangerth** [comment]
We are tracking the C++11 uses in #2375.

**Comment by bangerth** [comment]
We agreed to not require deal.II 9.0 at this time, so let's close this.
