### ISSUE TITLE
Fix grammar mistakes in simulator_access.h

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#2256]
As found in #2255, `simulator_access.h` contains text of the kind "this can then i.e. be used to get the names of the..." in a number of places.

This is grammatically incorrect. It should be "this can then, for example, be used to get the names of the..."

**Comment by SophieCoulson** [comment]
I will finish fixing this!

**Comment by bangerth** [comment]
@SophieCoulson -- great, thank you! You'll want to exclude the one place I've fixed in #2313, but you don't have to wait for that to be merged to get started!

**Comment by jdannberg** [comment]
As #2313 and #2317 are merged now, this should be fixed.
