### ISSUE TITLE
Deprecate find_plugin functions in favor of has_plugin and get_plugin

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2260]
Since #2148 the postprocessor interface already deprecates the `find_postprocessor` function and replaces it by `has_matching_postprocessor` and `get_matching_postprocessor`. The same should be done for the other interfaces:
- [ ] boundary composition
- [ ] boundary temperature
- [ ] boundary velocity
- [ ] heating model
- [ ] initial composition
- [ ] initial temperature

Also replace any usage of the old function by the new ones.

It should not be much work, mostly copy-paste.

**Comment by class4kayaker** [comment]
Note that tests should be added for these if only to avoid the type of error seen in #2261.

**Comment by joeschools** [comment]
I'm working on this issue

**Comment by gassmoeller** [comment]
And @diandianpeng will help

**Comment by gassmoeller** [comment]
Closed by #2255 #2261 #2387 and #2439.
