### ISSUE TITLE
2.0.1 Release

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2262]
During the last two weeks we found a few bugs in the 2.0.0 release that might make it necessary to do a 2.0.1, because they cause crashes of valid input files, or silently produce wrong results. Specifically, I am thinking of the following:

- #2258 
- #2253 
- the bug in heating_model/compositional_heating that is fixed in #2199 (we might need a different smaller fix for the old version, or just pull the whole thing into 2.0.1, no functional change, just refactoring)
- the fix to the bug reported in #2243 (yet to be implemented in ASPECT, part in dealii/dealii#6630)
- another bug that prevents combining particles and free surface in ASPECT 2.0.0 (I need to open an issue and PR for that)

We might also decide to just drop support for combining particles and free surface (the last two issues) by explicitly disabling that for the moment (I have not tested it, it is just not explicitly disabled).

Should we wait for a few weeks and do a 2.0.1 before the hackathon?

**Comment by jdannberg** [comment]
Yes, I think that makes sense.

**Comment by bangerth** [comment]
Is anyone likely to run into any of these bugs? Things that just fail with an error are annoying, but at least they lead to an error one can report and be told to use the dev sources instead. (Though they may scare people away from using ASPECT.) The ones that silently produce wrong results concern me more. #2199 is of that sort.

The alternative is to stabilize for a month after the hackathon and then put out a 2.1. The people who go to the hackathon will all use the dev sources anyway, so they're not a concern. I do wonder, however, whether we're going to be able to stabilize soon after the hackathon. We've usually had a very long tail of things from the hackathon...

**Comment by tjhei** [comment]
> that is fixed in #2199 (we might need a different smaller fix for the old version, or just pull the whole thing into 2.0.1

I think we can pull the whole thing...

**Comment by gassmoeller** [comment]
We should now have everything that is necessary for 2.0.1. Lets move forward with it.

**Comment by tjhei** [comment]
clang 6 with deal.II 9.1.0-pre fails with:
```
CMakeFiles/aspect.dir/source/mesh_refinement/temperature.cc.o:temperature.cc:function aspect::MeshRefinement::Temperature<3>::execute(dealii::Vector<float>&) const: error: undefined reference to 'void dealii::KellyErrorEstimator<3, 3>::estimate<dealii::TrilinosWrappers::MPI::BlockVector, dealii::DoFHandler<3, 3> >(dealii::Mapping<3, 3> const&, dealii::DoFHandler<3, 3> const&, dealii::Quadrature<2> const&, dealii::FunctionMap<3, dealii::TrilinosWrappers::MPI::BlockVector::value_type>::type const&, dealii::TrilinosWrappers::MPI::BlockVector const&, dealii::Vector<float>&, dealii::ComponentMask const&, dealii::Function<3, double> const*, unsigned int, unsigned int, unsigned int, dealii::KellyErrorEstimator<3, 3>::Strategy)'
```
(and a couple other). @bangerth have you seen that?

**Comment by tjhei** [comment]
Furthermore, I am getting deprecation warnings with 9.1.0-pre of course (ConstraintMatrix, tria_boundary_lib). Should we try to suppress those for 2.0.1?

**Comment by gassmoeller** [comment]
the tria_boundary_lib would be easy to fix by cherry picking #2292 and #2329, I prepare another one to fixup #2329.

**Comment by bangerth** [comment]
The linker errors are news to me.

**Comment by tjhei** [comment]
Left to do:
- [ ] announce
- [ ] update cig website
- [ ] update bib entries for zenodo, etc.

**Comment by tjhei** [comment]
@gassmoeller do you want to send the announcement (see release tasks)?

**Comment by gassmoeller** [comment]
Ok, announcement is out. The zenodo entries on the CIG website and on our website seem up-to-date as well. The only thing left would be a new figshare upload for the manual? Or is there something else?

**Comment by tjhei** [comment]
Thanks. The manual is identical except the version number on the title. I think @bangerth was proposing to ignore this and not upload a new file (and in the future put 2.0 instead of 2.0.0 as the title). I can upload it but then we need to update all the bib entries...

**Comment by gassmoeller** [comment]
Lets keep it as is then.
