### ISSUE TITLE
"Temperature" mesh refinement criteria in Stokes only solver?

### ISSUE THREAD

**Issue by Shangxin-Liu** [geodynamics/aspect#2268]
When I tested the pure Stokes flow problems with "Stokes only" nonlinear solver scheme, I noticed that "temperature refinement criteria" can also be used and takes effect (Two tests with and without temperature refinement criteria generate the different final mesh). Since the temperature strategy uses the "Kelly" refinement criteria based on the computed temperature field, the fact that this refinement strategy can still take effect with Stokes only solver makes me a little confused. When the temperature equation is ignored, how does "temperature" refinement strategy take effect? Is it operated from the initial temperature condition somehow?

**Comment by bangerth** [comment]
I am pretty sure that we still interpolate the initial temperature onto the mesh, even if we don't solve the temperature advection equation. This temperature field is then used to refine the mesh.

Now, this may not make very much sense in many situations, but I can come up with ideas for setups where this is still useful.

**Comment by Shangxin-Liu** [comment]
Thanks, Wolfgang, I'm now clear on this. feel free to close this issue.
