### ISSUE TITLE
clarify "Use years in output"

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2300]
Add a section to the manual (longer than the note in 2.3) about this setting. In particular that this influences the units for velocity boundary conditions and output of velocities but not much else.

Are we fully consistent?

Also, the part "in output" is not ideal...

(this came up at the tutorial)

**Comment by hfmarkp** [comment]
I can work on this

**Comment by bangerth** [comment]
Fixed by @hfmarkp in #2345.
