### ISSUE TITLE
Manual: mention FunctionParser/muparser

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2301]
in section 4.7.3 mention/link to the deal.II documentation of FunctionParser (http://www.dealii.org/developer/doxygen/deal.II/classFunctionParser.html#details)  to see the additional functions we allow. Maybe also expand how if and rand works?

**Comment by wanyingw** [comment]
I'll add the link and the if example.

**Comment by bangerth** [comment]
Closed by #2327.
