### ISSUE TITLE
parameters and descriptions in doxygen documentation

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2312]
If we want to improve/promote doxygen documentation, it would be helpful to have parameter description for example in material models: https://aspect.geodynamics.org/doc/doxygen/classaspect_1_1MaterialModel_1_1Simpler.html

**Comment by tjhei** [comment]
One idea would be to write a small script to parse parameters.xml and write out a latex table to be included into the doxygen documentation.

**Comment by bangerth** [comment]
I think this is the right idea, but we haven't made progress on it in 5 years so let me close it as something we won't tackle anytime soon.
