### ISSUE TITLE
cotire errors, warnings and slow compile with gcc 7.3.0

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#2314]
With precompiled headers enabled (`ASPECT_PRECOMPILE_HEADERS:BOOL=ON` in CMakeCache.txt), cotire no longer appears to work correctly (tested on machines of @gassmoeller, @jdannberg and myself). 

When CMakeFiles/ doesn't exist (i.e. on first compile), the following error appears
`CMake Error in CMakeLists.txt:`
`  Evaluation file to be written multiple times with different content.  This`
`  is generally caused by the content evaluating the configuration type,`
`  language, or location of object files:`

`   /home/bob/software/aspect_mainbranch/aspect_CXX_Debug_cotire.cmake`

After the first compile, compilation doesn't result in an error, but building every CXX object results in the following warning:
`cc1plus: warning: /home/bob/software/aspect/cotire/aspect_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2`

Compilation is very slow.

**Comment by tjhei** [comment]
what is your ``cmake --version`` ?

**Comment by bobmyhill** [comment]
cmake version 3.10.2

**Comment by tjhei** [comment]
cmake 3.11 with gcc 5.4 works for me. So is this related to your gcc version?

**Comment by tjhei** [comment]
@gassmoeller are you going to try a new cotire version?

**Comment by bobmyhill** [comment]
@tjhei I already tried the new cotire version; it didn't solve the problems. I assume this is an issue with gcc; it's difficult for me to check whether cmake 3.11 fixes the issue, as that would require I uninstall a lot of other software (including fenics) that I'd rather not reinstall.

**Comment by bangerth** [comment]
I don't think I understand how the `CMakeFiles` can or can not exist. It's a result of running cmake, so it should always be there.

**Comment by tjhei** [comment]
I get a different and funny error with gcc 7.3 and cmake 3.11:
```
error: ‘::fenv_t’ has not been declared
```
only if cotire is on.

**Comment by bangerth** [comment]
For the latter, you're probably missing an `#include` file somewhere. Which file is this for?

**Comment by tjhei** [comment]
helper_functions.cc but I assume this is cotire's fault.

**Comment by bangerth** [comment]
Can you show the whole error message?

**Comment by bangerth** [comment]
?? The error comes out of a system header? And I don't see `helper_functions.cc` making use of fp exceptions to begin with. I think you'll have to look into the file being compiled at the time (the combined one).

**Comment by bobmyhill** [comment]
@bangerth to answer your question to me, if that directory already exists when make is called, the error doesn't result. I haven't pinned down why that happened, because I then found this issue on the cotire github page: https://github.com/sakra/cotire/issues/120. See the last comment regarding the COMPILE_LANGUAGE:CXX generator expression. 

I don't know how to fix the problem, but I suspects that if the source of the error can be found, the warnings (which arise from the -ggdb flag not being used by cotire) will be resolved.

**Comment by tjhei** [comment]
I now have access to a machine with the same  error:
```
CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/aspect-git/build/aspect_CXX_Debug_cotire.cmake
```

I tried 1) different cmake versions, 2) updating cotire to the latest release both that did not help. @gassmoeller any ideas?

**Comment by gassmoeller** [comment]
No ideas on my side at the moment. I am aware of the issue, but I spend a day or two after the last hackathon and did not find a solution. Maybe we need to disable the whole thing again or look for a different solution.

**Comment by gassmoeller** [comment]
I think I have tracked this issue to its cause, but I do not completely undertand it. As described in the issue linked by Bob above, cotire has problems with generator expressions in cmake (apparently because it tries to write files several times). The offending lines are not in ASPECT's cmake system however, but in deal.II. https://github.com/dealii/dealii/blob/44c79ab4f665f968e0a5653b36ded140a6e53b59/cmake/macros/macro_deal_ii_setup_target.cmake#L125 is the line that causes trouble. There is a workaround already in the file for cmake version 3.9 and lower or MSVC, and when I comment out the line and just always use the workaround cotire works again. 

Unfortunately, I do not see an easy solution for this at the moment. I do not think the deal.II use of the generator expression is wrong, and we should not need to change deal.II just to adjust for ASPECT's use of cotire. The bug is liekly cotire's missing support for this use of generator expressions, but I know too little about it to have a guess for how hard it would be to fix. Only allowing the use of cotire for cmake version <3.9 seems like the simplest solution for now to remove the issue for the release. I have verified that cmake 3.8.2 works, while 3.9.6 and later (3.10.2 and 3.14.0) does not. 
@tjhei what do you think about disabling cotire for newer cmake versions?

**Comment by tjhei** [comment]
oh gosh, thanks for finding that! Wow!

That makes a lot of sense and explains why we only break for cmake >=3.9.

> what do you think about disabling cotire for newer cmake versions?

yes, that makes sense (even though it is unfortunate).

I could also try to make the change in deal.II to not use the compiler expression (but the workaround above).

**Comment by tjhei** [comment]
@tamiko We are trying to support https://github.com/sakra/cotire/ in ASPECT, but deal.II uses generator expressions like in https://github.com/dealii/dealii/blob/44c79ab4f665f968e0a5653b36ded140a6e53b59/cmake/macros/macro_deal_ii_setup_target.cmake#L125 
that break compilation.Do you feel strongly about these expressions or can we get rid of them?

**Comment by gassmoeller** [comment]
We have a workaround in #2877 that makes this not critical for the 2.1 release. Let's postpone it for a while. At some point we either need to make cotire work with cmake >3.8 or drop the support for it.

**Comment by bangerth** [comment]
@tamiko: Did you ever have time to take a look at this issue?

**Comment by bobmyhill** [comment]
@gassmoeller I found a potential patch from January this year: https://github.com/KratosMultiphysics/Kratos/commit/cc1ccc1c6c560e1930fcfcaa7f0823c805f11906

It certainly doesn't break anything on my system, but oddly, cotire now works with or without the patch. I'm still using deal.II 9.0.1 and cmake 3.10.2, and have upgraded to gcc 7.4.0.

Perhaps if the patch fixes cotire on your system, it might be worth adding?
