### ISSUE TITLE
Chunk Geometry Model - Error message for very small boundaries

### ISSUE THREAD

**Issue by SophieCoulson** [geodynamics/aspect#2331]
When running a chunk model for a region extending to 90 (or -90) degrees latitude the north (or south) boundary is a point, therefore the model will not run. The current error message for this is:

An error occurred in line <6072> of file </n/home08/slcoulson/newlib/dealii-8.5.0/include/deal.II
/numerics/vector_tools.templates.h> in function
    void dealii::VectorTools::compute_nonzero_normal_flux_constraints(const DoFHandlerType<dim, s
pacedim> &, unsigned int, const std::set<unsigned char, std::less<unsigned char>, std::allocator<
unsigned char>> &, dealii::FunctionMap<spacedim, double>::type &, dealii::ConstraintMatrix &, con
st dealii::Mapping<dim, spacedim> &) [with int dim = 3, int spacedim = 3, DoFHandlerType = dealii
::DoFHandler]
The violated condition was: 
    std::fabs(normal_vector.norm() - 1) < 1e-14

A more direct error message would be more helpful.

**Comment by SophieCoulson** [comment]
I'm working on this now

**Comment by bangerth** [comment]
Yes, nice idea. This should be easy enough to catch and give a good error message!

**Comment by gassmoeller** [comment]
Was this fixed by #2339? If so: @SophieCoulson can you close this issue?

**Comment by SophieCoulson** [comment]
Yes this is fixed!
