### ISSUE TITLE
number of Stokes iterations in statistics output does not work correctly with deal.II 8.5

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#2334]
I noticed this when writing a test for #2325. The test worked on my machine with deal.II 9.0, and I got Stokes iterations count of 1 or 0. When I ran the same test file on the official tester with deal.II 8.5, I got Stokes iterations counts of 4294967295 or 4294967294 in the statistics file. There has to be a bug somewhere that a variable that is used for this output in the statistics file is initialized with something like invalid unsigned int and not set correctly, but I couldn't figure out what it was.

**Comment by bangerth** [comment]
@gassmoeller might remember this -- I think he had fixed a bug in deal.II about this.

**Comment by tjhei** [comment]
no longer relevant
