### ISSUE TITLE
Creating an 'ascii data profile' plugin for composite initial temperature models

### ISSUE THREAD

**Issue by mnkajan** [geodynamics/aspect#2344]
I have been using my own initial temperature plugin that can read in different geotherms (depth and temperature values) and then add perturbations from a tomographic model (coordinates and temperature perturbation values). Since the "ascii data" initial temperature plugin already exists, and we can now create composite models, it seems unnecessary to have a totally separate model.

In fact, most of the initial temperature plugins (e.g., S40RTS perturbation, harmonic perturbation, etc.) add perturbations to a background temperature that is defined in the plugin. This is mainly limited to the adiabatic background temperature or a single constant reference temperature. I believe it would be simpler and more flexible to write a separate "ascii data profile" plugin for depth-dependent temperature input that could be combined with other plugins.

Let me know if you have any comments or suggestions to make this more useful for everyone!

**Comment by gassmoeller** [comment]
Yes, and @mnkajan and I talked about this. I think this is a good idea. One alternative approach that is already possible is to prescribe a `ascii data` profile in the adiabatic conditions, and then use the `adiabatic` initial temperature plugin, but that has the disadvantage that it forces everyone to also prescribe a pressure and density profile. Having a initial temperature plugin `ascii data profile` seems reasonable and useful to me. The structure of this plugin could look very similar to `AsciiData` in adiabatic conditions.

**Comment by mnkajan** [comment]
Addressed by #2360.
