### ISSUE TITLE
Deprecation warning in RotationStatistics postprocessor

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2355]
This should be a simple fix. The `statistics` parameter in line 50 in the `RotationStatistics::execute` function in source/postprocess/rotation_statistics.cc file is never used, which creates a compile warning. The parameter should be removed or commented out, like in the DepthAverage postprocessor.

**Comment by bangerth** [comment]
I think this is fixed by #2354, right?

**Comment by bangerth** [comment]
I'm afraid @jonpkay is going to come too late with his commits :-(

**Comment by gassmoeller** [comment]
Yes this was fixed by #2354.
