### ISSUE TITLE
ASCII data plugins have hard-coded subsection name

### ISSUE THREAD

**Issue by mnkajan** [geodynamics/aspect#2365]
This means that you cannot combine two plugins that call Utilities::AsciiDataBase::declare_parameters(). For example, you cannot create a composite initial temperature model that combines the 'ascii profile' and 'ascii data' plugins, because you can only define a single data file under the hard-coded subsection "Ascii data model" in the parameter file.

I've discussed this with @gassmoeller who suggested removing the hard-coded subsection name in utilities.cc. However, this would require entering section names for each plugin that uses the AsciiDataBase functions to declare and parse parameters.

Any alternative solutions or ideas are very welcome!

**Comment by gassmoeller** [comment]
This was fixed by #2370 so @mnkajan you should be able to use the new functionality. Let us know when this can be closed or if you have questions.

**Comment by mnkajan** [comment]
Yup, we can close this now!
