### ISSUE TITLE
Three empty lines between functions in utilities.cc

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#2404]
We generally abide by this rule in ASPECT, but this file got away from us. That should be easy enough to fix.

**Comment by bangerth** [comment]
@pmbremner ?

**Comment by jonpkay** [comment]
I will try this!

**Comment by pmbremner** [comment]
@bangerth What is the status of this issue? @jonpkay has this already been addressed?

**Comment by bangerth** [comment]
I took a look at that file and there are still plenty of places where we have fewer than 3 lines between functions. @pmbremner  Feel free to just go through the whole file and add them.

**Comment by pmbremner** [comment]
Okay! I'll tackle this one either today or over the weekend

**Comment by gassmoeller** [comment]
solved by #4785
