### ISSUE TITLE
Use curved mapping also in the interior

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#249]
From a mailing list thread today:

We create the mapping in core.cc like this:
   mapping (parameters.free_surface_enabled?1:4),
so this calls this constructor:
  MappingQ (const unsigned int p,
            const bool use_mapping_q_on_all_cells = false);
I think it still uses the straight mapping in the interior. Of course, this may well be a good target for a patch in itself

**Comment by tjhei** [comment]
Should we make it optional for performance reasons?

**Comment by bangerth** [comment]
I thought that we could ask the geometry whether it has curved cells (with a default to "yes"), and if so enable the mapping in the interior. Want to test whether it makes a significant difference in matrix assembly? I've come to realize that for the cases where run time really matters -- namely for the complicated, variable viscosity cases -- run time is entirely dominated by the solver and that assembly doesn't matter in those cases.

**Comment by tjhei** [comment]
Fixed, see 546de433
