### ISSUE TITLE
Add section to manual related to thermodynamic self-consistency

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#2504]
In ASPECT, material models can be implemented where the material properties are not compatible with each other. For example, one could implement a material model where thermal expansivity is constant, but the density formulation does not satisfy the expression alpha = -1/rho (d rho/d T)|P. There are both implicit and explicit constraints. 

We should add a section to the manual that covers the relations and potential pitfalls in designing material models.

**Comment by bobmyhill** [comment]
I'm working on this now...

**Comment by bangerth** [comment]
See also #2468.

**Comment by bobmyhill** [comment]
Addressed in #2513.
