### ISSUE TITLE
MacOS .dmg image produces errors about 'c++17'

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2583]
We tried to install ASPECT using the .dmg deal.II image and get the following error during compilation:
```
error: invalid value 'c++17' in '-std=c++17'
```
@tjhei: Do you know what is causing this? Is the .dmg image just not working at the moment? Should we try candi or spack instead?

**Comment by naliboff** [comment]
@gassmoeller - Is that for deal.II 9.0.0 and the latest version of OS X + Xcode? 

I vaguely recall seeing a similar (or the same error) when I tried to install the deal.II 9.0.0 dmg on my mac, which is not the latest (one behind) OS X release. I think the issue I saw was related to not being able to use the latest release of Xcode, but perhaps this is a different issue?

Having a relatively straightforward alternative to the .dmg binary would be really helpful for cases where there are .dmg compatibility issues.

**Comment by gassmoeller** [comment]
We were successful using candi instead. I suspect it was the XCode version. #2582 remains an open issue, but I can close this one.

**Comment by naliboff** [comment]
Unfortunately the version of XCode that supports `-std=c++17` is only available on the most recent version of OSX (High Sierra). At least this was the case before the Hackathon. Apologies, should have been a bit more specific in might original comment.
