### ISSUE TITLE
Eventually implement higher order output for paraview

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2601]
Just saw this by chance: Deal.II and paraview now support higher order output as discussed for example here: dealii/dealii#6931. We should implement the option to use this feature and at some point in the far future (when everyone uses at least paraview 5.5) make it the new default. It would save disk space and allow visualizations of larger models (less memory requirements for visualization).

**Comment by bangerth** [comment]
See also the discussion in #2841.
