### ISSUE TITLE
Recent master does not compile with deal.II-dev

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2602]
ASPECT (any version, the 2.0.1 release and any development version before or after) does not compile with any deal.II-dev version newer than dealii/dealii#6864 due to the API changes. We need to either implement the same changes that were implemented there (and the follow up pull requests), or finally finish #1957 to use the deal.II version of the particle functionality.

**Comment by bangerth** [comment]
I'm working on this.

**Comment by gassmoeller** [comment]
This was finally fixed by #1957. Sorry it took so long, it was one of the bigger issues to get all of this to run.
