### ISSUE TITLE
weird test failures in global_melt_parallel

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2603]
I have seen test repating failures on jenkins, see https://jenkins.tjhei.info/blue/organizations/jenkins/aspect/detail/PR-2599/1/pipeline/#step-60-log-452 
for example:
```
******* All of 41 lines of diffs are:

----------------

##240     <== 

##240     ==> *** Snapshot created!



##240           <==

##240     #>1   ==> *** Snapshot created!

@ Line 240 in file "/home/dealii/build-gcc-fast/tests/output-global_melt_parallel/screen-output.cmp.notime" is shorter than expected!
```
The test works on my machine. Any idea what is going on?

**Comment by gassmoeller** [comment]
Hmm, not sure, but the test writes a checkpoint after 1700 seconds (probably not a good idea), and if it sometimes finishes in less than 1700 seconds and sometimes not, it will only sometimes write the checkpoint. No single test should take 1700 seconds though (and dont we abort tests after 600 seconds?).

**Comment by gassmoeller** [comment]
Oh, and by the way I can not see your tester output. It asks me for a login, but my old account does not work anymore.
