### ISSUE TITLE
Changing the sign of ascii gravity and boundary velocity

### ISSUE THREAD

**Issue by bartniday** [geodynamics/aspect#2605]
The ascii data plugins for gravity and boundary velocity don't allow you to change the sign (for backward advection) without making a separate input file, since the built-in scale factor is required to be >= 0.

Checking that the scale factor is non-negative makes sense for other ascii data plugins, but it would be nice to have a way of inverting gravity and boundary velocity within the parameter file.

**Comment by gassmoeller** [comment]
I agree. In fact I do not think any of the ascii data plugins should have that limitation any more (even the temperature could be a perturbation to another temperature plugin and could contain negative values). Fixing this is as simple as changing `Double(0)` to `Double()` as pattern for the parameter in line 1765 in utilities.cc (in the call to `declare entry` for the parameter `Scale factor`). If you have the time please go ahead and submit this as a pull request. Bonus points if you update the documentation text for this parameter (or also the others) as it was originally written for boundary velocities, but is now used for arbitrary input data.

**Comment by bartniday** [comment]
I'll see what I can do.
