### ISSUE TITLE
test 1.2 release

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#262]
please test https://github.com/geodynamics/aspect/tree/aspect-1.2
and http://www.ces.clemson.edu/dealii/aspect-1.2.rc2.tar.gz
before I pull the trigger.

Any files we should remove from the tarball for this release?

**Comment by bangerth** [comment]
There are a bunch of script files in doc/ that probably don't need to be there but that also don't hurt very much. 

Other than that, everything seems in place to me. Pull over the PR I created earlier today and pull the trigger!
