### ISSUE TITLE
Should we automate indentation?

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2626]
I just had a look at #2585 and noticed that the indentation is broken. Of course I can ask to fix the indentation, but I realized for a while that it is essentially unnecessary work we put on our contributors. We automate indentation anyway, so why make contributors do it, instead of our continuous integration system? We should be able to modify the `Check indentation` stage of Jenkins into a `Fix indentation` stage, that just adds another commit to the PR (users with write access are allowed to do that by default), which fixes the indentation. I realize there are a few complications, e.g. if we test the merge into master instead of the PR itself this would not work, and if the user explicitly disabled the checkbox that allows maintainers to add commits to PRs it does not work either. Still I do not think it would be too complicated to do (we can always fail the test if the fix does not work), and it would lower the barrier for new contributors (no installing astyle, no explaining how to download patch files, no worries about forgetting to indent before uploading addressed comments).

What do you think? Is this a reasonable thing to set up?

**Comment by bangerth** [comment]
We had discussed this for deal.II before. The downsides were:
* A commit is automatically added to the branch on github, so the next `git push` the person attempts (for example after addressing comments) will fail: you now need to do `git push -f`.
* You'll end up with lots of commits in the history that just fix up indentation.

I don't know whether that outweighs the advantages of such a system. It may be worth just trying this and see what happens and how the pros/cons stack up.

**Comment by tjhei** [comment]
I am also a bit hesitant to enable something like this. Ideally, we want people to not create commits with wrong indentation because this creates an ugly history. I agree that this might help newcomers.

I also have an irrational fear of machines taking over. :-)

**Comment by tjhei** [comment]
Alternatively, we could update "make indent" to download an astyle binary if astyle is not found (similar to the download_clang_format scripts in deal.II).

**Comment by tjesser-ucdavis-edu** [comment]
You might want to look at using [git hooks](https://git-scm.com/docs/githooks). Every git repo has a set of examples even:

> tyler@Latitude:\~/Documents/CIG_Repositories/aspect$ ls -AX .git/hooks/
> applypatch-msg.sample  pre-applypatch.sample      pre-push.sample
> commit-msg.sample      pre-commit.sample          pre-rebase.sample
> post-update.sample     prepare-commit-msg.sample  update.sample

> tyler@Latitude:\~/Documents/CIG_Repositories/aspect$ head .git/hooks/pre-commit.sample 
> \#!/bin/sh
> \#
> \# An example hook script to verify what is about to be committed.
> \# Called by "git commit" with no arguments.  The hook should
> \# exit with non-zero status after issuing an appropriate message if
> \# it wants to stop the commit.
> \#
> \# To enable this hook, rename this file to "pre-commit".
> 
> if git rev-parse --verify HEAD >/dev/null 2>&1

**Comment by gassmoeller** [comment]
Hm, I see the complications that can arise from adding commits to users pull requests, always force-pushing is not a good behavior to teach. I agree with @tjhei, maybe adding a script like download_astyle is the best way to go.

**Comment by gassmoeller** [comment]
I think this is not worth keeping open as a discussion. The current process works reasonably well, and any alternative would have other issues.
