### ISSUE TITLE
Strain rate tensor visualization postprocessor not registered

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#2631]
The `strain_rate_tensor `postprocessor source file compiles, but when selecting `strain rate tensor` in the input file, an error is thrown that it does not match the given pattern of available output variables.

**Comment by bangerth** [comment]
Can you set up a little test that shows this?

**Comment by bangerth** [comment]
And did you list it among the *visualization* postprocessors?

**Comment by gassmoeller** [comment]
Maybe the problem is that the strain rate tensor postprocessor is only active with deal.II 9.0? Anne, did your error occur with 8.5?

**Comment by anne-glerum** [comment]
yep, that's it (deal.II 8.5). Sorry, totally should have seen that directive. 
I already thought it was strange that I couldn't find a test using this postprocessor, but I only grepped in the *.prm files, not the *.prm.deal.II.9.0 files :tired_face:

**Comment by tjhei** [comment]
Would it be less surprising if the postprocessor exists but fails with an AssertThrow if you try to use it?

**Comment by bangerth** [comment]
I think so. Then at least you get an error message about *why* this is so.

Of course, this may soon be moot if we just switch to a sufficiently new deal.II version as a prerequisite.
