### ISSUE TITLE
illegal instruction 4 on OSX binary image

### ISSUE THREAD

**Issue by mmelwani** [geodynamics/aspect#2655]
Compiled both debug and optimized ASPECT from git, and using:
--     . version 2.1.0-pre (master, ecdf8ce5b)
--     . using deal.II 9.0.0
--     . using Trilinos 12.12.1
--     . using p4est 2.0.0

Initially thought it was related to closed issue #1479, but the error message is different, and the Test project target appears to be correct. Running `make` works, so ASPECT appears to have compiled correctly. Here's the output of `make test` from the deal.II terminal:

> bash-3.2$ make test
> [ 98%] Built target aspect
> [ 98%] Running unit_tests ...
> 
> All tests passed (126 assertions in 11 test cases)
> 
> [ 98%] Built target run_unit_tests
> [100%] Running tests ...
> Running tests...
> Test project /Users/mohit/aspect/tests
>     Start 1: quick_mpi
> 1/1 Test # 1: quick_mpi ........................***Failed    2.67 sec
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) =   2.67 sec
> 
> The following tests FAILED:
> 	  1 - quick_mpi (Failed)
> Errors while running CTest
> make[4]: *** [test] Error 8
> make[3]: *** [CMakeFiles/run_tests] Error 2
> make[2]: *** [CMakeFiles/run_tests.dir/all] Error 2
> make[1]: *** [CMakeFiles/test.dir/rule] Error 2
> make: *** [test] Error 2

To follow up, I ran `ctest -V`:

> bash-3.2$ ctest -V
> UpdateCTestConfiguration  from :/Users/mohit/aspect/DartConfiguration.tcl
>  Add coverage exclude regular expressions.
> SetCTestConfiguration:CMakeCommand:/Applications/deal.II-9.0.0.app/Contents/Resources/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/cmake-3.11.1-t5c5kjxtmcqrw3luyshq6zxhl3dpvfjj/bin/cmake
> UpdateCTestConfiguration  from :/Users/mohit/aspect/DartConfiguration.tcl
> Test project /Users/mohit/aspect
> Constructing a list of tests
> Done constructing a list of tests
> Updating test list for fixtures
> Added 0 tests to meet fixture requirements
> Checking test dependency graph...
> Checking test dependency graph end
> test 1
>     Start 1: unit_tests
> 
> 1: Test command: /Users/mohit/aspect/aspect "--test"
> 1: Test timeout computed to be: 10000000
> 1: ===============================================================================
> 1: All tests passed (126 assertions in 11 test cases)
> 1: 
> 1/2 Test #1: unit_tests .......................   Passed    0.21 sec
> test 2
>     Start 2: quick_mpi
> 
> 2: Test command: /Applications/deal.II-9.0.0.app/Contents/Resources/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/cmake-3.11.1-t5c5kjxtmcqrw3luyshq6zxhl3dpvfjj/bin/cmake "-DBINARY_DIR=/Users/mohit/aspect/tests" "-DTESTNAME=tests.quick_mpi" "-DERROR="Test quick_mpi failed"" "-P" "/Users/mohit/aspect/tests/run_test.cmake"
> 2: Test timeout computed to be: 600
> 2: --------------------------------------------------------------------------
> 2: mpirun noticed that process rank 1 with PID 0 on node LMC-040345 exited on signal 4 (Illegal instruction: 4).
> 2: --------------------------------------------------------------------------
> 2: make[3]: *** [output-quick_mpi/screen-output] Error 132
> 2: make[2]: *** [CMakeFiles/quick_mpi.screen-output.diff.dir/all] Error 2
> 2: make[1]: *** [CMakeFiles/tests.quick_mpi.dir/rule] Error 2
> 2: make: *** [tests.quick_mpi] Error 2
> 2: *** "Test quick_mpi failed": ***
> 2: [ 22%] Built target quick_mpi
> 2: [ 33%] Generating output-quick_mpi/screen-output
> 2: 
> 2: CMake Error at run_test.cmake:14 (MESSAGE):
> 2:   *** Test aborted.
> 2: 
> 2: 
> 2/2 Test # 2: quick_mpi ........................***Failed    2.67 sec
> 
> 50% tests passed, 1 tests failed out of 2
> 
> Total Test time (real) =   2.89 sec
> 
> The following tests FAILED:
> 	  2 - quick_mpi (Failed)

On closer inspection, this output is more similar to closed issue #1936, so perhaps this is related to deal.II or CMake?

**Comment by naliboff** [comment]
@mmelwani - Hmm, I'm not sure what to make of the error message. 

I just tried running `quick_mpi` on my mac (same setup) and the test passed. However, I did compile in a separate directory from the directory (ex: aspect/debug) and I ran the test with `ctest -R quick_mpi` (had already done `make setup_tests`). 

The latter point should make no difference, but I recall there is an issue with the tests when compiling in the main aspect directory.

**Comment by tjhei** [comment]
How did you install deal.II? Can you run ``mpirun -n 2 hostname``?

**Comment by mmelwani** [comment]
@naliboff - I copìed the test folder into a separate directory from aspect, but obtained the same error as above when running `ctest -R quick_mpi` and `make test`.

@tjhei - I installed deal.II from the .dmg Mac OS package, and into my Applications folder. Running `mpirun -n 2 hostname` in the deal.II terminal gave me my hostname twice:

> LMC-040345
> LMC-040345

Changing the number of processors (-n 1 to 8 on my system) also returns my hostname the appropriate number of times. I imagine that this means that deal.II is installed and set up correctly.

If there are any other diagnostics you can think of, I would be happy to run them to figure out where the issue lies.

**Comment by tjhei** [comment]
Can you try ``mpirun -n 2 aspect cookbooks/convection-box.prm``? You need to be in the directory above cookbooks/ for that to work (and/or need to adjust the paths to aspect and the prm).

The error
```
mpirun noticed that process rank 1 with PID 0 on node LMC-040345 exited on signal 4 (Illegal instruction: 4).
```
means that some code you are running (likely deal.II) is not compatible with the CPU you are using. I assume this error is because you are using the deal.II dmg on an older processor. One option would be to install deal.II and dependencies manually.

**Comment by tjhei** [comment]
I opened an issue for this https://github.com/dealii/dealii/issues/7175

**Comment by mmelwani** [comment]
`mpirun -n 2 aspect cookbooks/convection-box.prm` (or for any other cookbook prm) gives me the same error:

> bash-3.2$ mpirun -n 2 aspect cookbooks/convection-box.prm 
> 
>  This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
>     . version 2.1.0-pre (master, ecdf8ce5b)
>      . using deal.II 9.0.0
>      . using Trilinos 12.12.1
>      . using p4est 2.0.0
>      . running in OPTIMIZED mode
>      . running with 2 MPI processes
> 
> 
> 
> -----------------------------------------------------------------------------
> The output directory <output-convection-box/> provided in the input file appears not to exist.
> ASPECT will create it for you.
> 
> 
> 
> -----------------------------------------------------------------------------
>  For information on how to cite ASPECT, see:
>    https://aspect.geodynamics.org/citing.html?ver=2.1.0-pre&sha=ecdf8ce5b&src=code
> 
> Number of active cells: 256 (on 5 levels)
> Number of degrees of freedom: 3,556 (2,178+289+1,089)
> 
> *** Timestep 0:  t=0 seconds
>    Solving temperature system... 0 iterations.
>    Rebuilding Stokes preconditioner...-------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> 
> --------------------------------------------------------------------------
> mpirun noticed that process rank 0 with PID 0 on node LMC-040345 exited on signal 4 (Illegal instruction: 4).

I will attempt a manual installation of deal.II and its dependencies (without using the .dmg), and report back.

**Comment by tjhei** [comment]
> I will attempt a manual installation of deal.II

I recommend using candi or spack as described at https://www.dealii.org/download.html

**Comment by gassmoeller** [comment]
@mmelwani did you solve the problem? Can this issue be closed?

**Comment by tjhei** [comment]
This is still a problem (deal.II OSX installer is built with optimization that breaks on many machines). I should tackle that at some point...

**Comment by tjhei** [comment]
I am closing this because this has been with an older version of deal.II that we no longer support. I hope 9.2 works better in this regard. If not, MacOS users need to manually install.
