### ISSUE TITLE
How could I get ‘composition’ in the prescribed_velocity.cc?

### ISSUE THREAD

**Issue by LeonLiu18** [geodynamics/aspect#2658]
Hi, All

I am a beginner to use the ASPECT. If I want to get the composition for every quadrature point in the ./cookbook/prescribed_velocity/prescribed_velocity.cc, is there someway I can do it?

Many thanks!

Leon

**Comment by jdannberg** [comment]
Hi Leon, 

it's great that you're using ASPECT, welcome to the community!
Can you be a bit more specific about what exactly it is you want do? The prescribed velocity cookbooks (corner_flow.prm and circle.prm) do not use compositional fields, and the prescribed_velocity.cc file just provides some code that allows it to constrain the velocities in certain parts of the domain. 

So do you want to set up a new model similar to the cookbook that uses compositional fields? 

In the future, if you have similar questions, it would be great if you could ask them on the [aspect-devel](http://lists.geodynamics.org/cgi-bin/mailman/listinfo/aspect-devel) mailing list instead of opening an issue on github. We generally use github for discussing the active development of ASPECT, and the mailing list for answering questions on e.g. the source code, installation or how to use ASPECT. 

Juliane

**Comment by LeonLiu18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, JulianeMany thanks for your reply!As you can see, I am a freshman for the community. I would be more than happy to learn how to ask the question properly:)Yes, you are right.  I want to set up a new model similar to the cookbook 'prescribed_velocity' that uses compositional fields? If I want to modify this file, could I get access to the compositions, i.e. the compositions and point coordinates, or compositions for the integration points. I am wondering, can I use simulator_access.get_material_model() or simulator_access.get_composition_values_at_q_point???Many thanks, Regards, Leon



        
    
     

    On 9/11/2018 18:38，Juliane Dannberg<notifications@github.com> wrote： 


Hi Leon,
it's great that you're using ASPECT, welcome to the community!
Can you be a bit more specific about what exactly it is you want do? The prescribed velocity cookbooks (corner_flow.prm and circle.prm) do not use compositional fields, and the prescribed_velocity.cc file just provides some code that allows it to constrain the velocities in certain parts of the domain.
So do you want to set up a new model similar to the cookbook that uses compositional fields?
In the future, if you have similar questions, it would be great if you could ask them on the aspect-devel mailing list instead of opening an issue on github. We generally use github for discussing the active development of ASPECT, and the mailing list for answering questions on e.g. the source code, installation or how to use ASPECT.
Juliane

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by jdannberg** [comment]
Hi Leon, 

my question was more: Why do you need the compositions at the quadrature points? What do you want to do with them? There might be an easier way than modifying prescribed_velocity.cc.

**Comment by LeonLiu18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, Juliane

What I want to do is to constrain a velocity for a certain phase of material, probably inside the numerical domain throughout the modelling (i.e. a ball surrounded by other materials, I want to constrain the velocity of this ball and to see the induced velocity of other materials). I agree that we don't have to modify the prescribed_velocity.cc. If possible, could you please give me some instructions on how to do this in other possible ways?

To constrain a velocity for a certain phase is not complex for my group's 2-d code. However, that code is not suitable for a 3-d modelling. I'm wondering that it should not be not very complex for ASPECT as well. As I am still not very familiar with the core part of the code, I cannot find a good way to implement this velocity soon enough...

Many thanks, 

Leon



        
    
     

    On 9/11/2018 20:52，Juliane Dannberg<notifications@github.com> wrote： 


Hi Leon,
my question was more: Why do you need the compositions at the quadrature points? What do you want to do with them? There might be an easier way than modifying prescribed_velocity.cc.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by jdannberg** [comment]
Hi Leon, 

I think constraining the velocity to for a certain composition throughout the whole model run is equivalent to not having a compositional field and just constraining the velocity in a certain part of the model domain (which could change over time). You've probably looked at the prescribed velocity cookbook .prm files, and they both have an "Indicator function". This function describes where in the domain the velocity should be prescribed. In the example files, this does not change throughout time, but you could change that (for example in corner_flow.prm, the variable names are already x,y,t, where t is the time, so you could easily add a time-dependence to the function expression). So as long as you can integrate the prescribed velocity in your separate phase easily (so that you know where, for example, a ball of material would be at every given point in time), you can use the code as it is. 

If you think that's not enough for what you want to do, let me know, and we can talk about how you would access the composition inside the `constrain_internal_velocities` function in prescribed_velocity.cc.

**Comment by jdannberg** [comment]
Hi Leon, 

did that fix your problem?
It would be great if you could let us know so that we can close the issue. 

Thank you!
Juliane

**Comment by LeonLiu18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, JulianeThank you for the following-up. I tried your suggested method without thinking too much about the phase. However, the time step became very small, let's say 10^-5 yr... I don't exactly know why this could occur, I am wondering if it was due to the induced pressure-perturbation. Should I use 'locally conservation discretization'? 

Except for this issue, if the time step issue can be fixed, could you also please help me to find a way to access the composition, which can be used as the reference for prescribing internal velocity?

I am sorry for the delayed reply. I was stuck with some writing...
Thanks, Leon 



        
    
     

    On 9/20/2018 15:13，Juliane Dannberg<notifications@github.com> wrote： 


Hi Leon,
did that fix your problem?
It would be great if you could let us know so that we can close the issue.
Thank you!
Juliane

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by jdannberg** [comment]
Hi Leon, 

> the time step became very small, let's say 10^-5 yr...

if your time step becomes very small, that typically means that the velocity is very large in some part of your domain. Have you looked at the velocities and pressures in the graphical output and made sure that they are what you would expect, and where these high velocities occur?

> could you also please help me to find a way to access the composition, which can be used as the reference for prescribing internal velocity?

You'll have to write a little bit of code for that. Here's what I think might be the easiest and most general way (but everyone else, please chime in if there's a better way). 
In the `constrain_internal_velocities` function, you'll see that there is an object called `fe_values` (line 216). Through this object, you will be able to access the values of the compositional fields. For an example of how that code would look like, you can have a look at the file `source/postprocess/composition_statistics.cc`, around line 50. It also creates an `fe_values` object, and you will need all the additional arguments passed to the constructor in composition_statistics.cc. In addition you will need a vector to store the values of your compositional field in, as created in line 57 in prescribed_velocity.cc, and you want that to have as many entries as you have velocity support points, so in your case `quadrature.size()`). The `fe_values` object will allow you to access the values of the compositional field stored in the solution vector, as it's done in lines 73-74 in composition_statistics.cc (and you will want to do a call like this inside of your loop over all cells, so after line 225 in prescribed_velocity.cc). You can then use these values however you want to prescribe your velocities.

**Comment by LeonLiu18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Many thanks! I will have a try soon :)
        Kindly regards, Leon
    



        
    
     

    On 9/21/2018 17:36，Juliane Dannberg<notifications@github.com> wrote： 


Hi Leon,

the time step became very small, let's say 10^-5 yr...

if your time step becomes very small, that typically means that the velocity is very large in some part of your domain. Have you looked at the velocities and pressures in the graphical output and made sure that they are what you would expect, and where these high velocities occur?

could you also please help me to find a way to access the composition, which can be used as the reference for prescribing internal velocity?

You'll have to write a little bit of code for that. Here's what I think might be the easiest and most general way (but everyone else, please chime in if there's a better way).
In the constrain_internal_velocities function, you'll see that there is an object called fe_values (line 216). Through this object, you will be able to access the values of the compositional fields. For an example of how that code would look like, you can have a look at the file source/postprocess/composition_statistics.cc, around line 50. It also creates an fe_values object, and you will need all the additional arguments passed to the constructor in composition_statistics.cc. In addition you will need a vector to store the values of your compositional field in, as created in line 57 in prescribed_velocity.cc, and you want that to have as many entries as you have velocity support points, so in your case quadrature.size()). The fe_values object will allow you to access the values of the compositional field stored in the solution vector, as it's done in lines 73-74 in composition_statistics.cc (and you will want to do a call like this inside of your loop over all cells, so after line 225 in prescribed_velocity.cc). You can then use these values however you want to prescribe your velocities.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by jdannberg** [comment]
Hi Leon, 

did this work for you, and can I close the issue?

Thank you!
Juliane

**Comment by tjhei** [comment]
Questions and discussions like this are probably better handled on the mailing list. I am closing this but feel free to ask questions if you have any.
