### ISSUE TITLE
Update all references to the mailing list by the new forum address

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2682]
Over the next weeks we should replace all references to the mailing list by the forum address.
Places that need to be updated:
- [x] Manual
- [x] Website
- [x] Newsletter now needs to be send to the forum
- [x] Readme.md
- [x] Contributing.md
- [ ] geodynamics.org

Everyone is welcome to tackle one (or more) of these. Makes for a nice first pull request or 20 min gap-fill activity :smile:.

**Comment by naliboff** [comment]
@gassmoeller - Should we include references in various documents to the archived discussions on aspect-devel? Even if these discussions are transferred to the forum, perhaps it would still be worth mentioning this in various places?

**Comment by tjhei** [comment]
Can we list the locations (and old discussions) in one central location and refer all other locations just to this one location to avoid duplication? One example would be to make a section on the homepage (see #2686 ) or something like https://github.com/geodynamics/aspect#more-information and use that everywhere else.

**Comment by naliboff** [comment]
@tjhei - Referring to the old aspect-devel discussions in just one place and referring to this location everywhere else sounds good to me. The #more-information page seems like a logical place. There is also already link at the [CIG mailing list page](https://geodynamics.org/cig/about/mailing-lists/), which I imagine will be preserved.
