### ISSUE TITLE
Better document how to add publications using ASPECT to the list on our website

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#2762]
This is currently done using a Mendeley group https://www.mendeley.com/community/aspect-1/ which is exported and shown on our website. Document this process on our website https://aspect.geodynamics.org/publications.html, or find a simpler way.

**Comment by tjhei** [comment]
We would need a volunteer to try to add to the group, who is not an admin. If this does work, we can document it that way. If not: we could just create a github issue where we ask people to post a comment for a new entry...

**Comment by ljhwang** [comment]
I volunteer!  But  I think I will need further instructions and discussions with you.

**Comment by tjhei** [comment]
> I will need further instructions

Go to https://www.mendeley.com/community/aspect-1/ and try to add some publication to the group. I assume you will need to sign up for a mendeley account as a first step. See if you can find a button to add an entry after clicking on "group documents".

**Comment by tjhei** [comment]
Oh, it looks like this is an "invite only" group. Not sure how to change this...

**Comment by tjhei** [comment]
closing this in place of #2831
