### ISSUE TITLE
The  morency_doin.prm couldn't be execute

### ISSUE THREAD

**Issue by cgw0814** [geodynamics/aspect#2859]
I found the  morency_doin.prm in cookbooks couldn't be execute because of ./libmorency_doin.so doesn't exist in that file

**Comment by tjhei** [comment]
You need to compile the shared library, see section "5.4.1 Running benchmarks that require code" in the manual.

**Comment by tjhei** [comment]
I am closing the issue. Let us know if you need further help.

**Comment by cgw0814** [comment]
I did as you said "cmake . and then make" but still run fail as following massage

![screenshot 2019-03-27 10 59 32 a m](https://user-images.githubusercontent.com/38973778/55047375-842b2700-507f-11e9-8082-49a64b38cb6a.png)

**Comment by cgw0814** [comment]
There is another problem for executing benchmarks/buiter_et_al_2008_jgr/figure_6_1e20.prm

The massage appeared
`Line <153> of file <input string>: No entry with name <Start strain weakening intervals> was declared in the current subsection. `

I read the manual and found there is no variable named `Start strain weakening intervals` in the section Material model/Visco Plastic but have  `Start plasticity strain weakening intervals` and `Start prefactor strain weakening intervals`

I modified `Start strain weakening intervals`  and then the massage appeared

`An error occurred in line <998> of file </home/dealii/aspect/source/material_model/visco_plastic.cc> in function
    void aspect::MaterialModel::ViscoPlastic<dim>::parse_parameters(dealii::ParameterHandler&) [with int dim = 2]
The violated condition was: 
    this->introspection().compositional_name_exists("total_strain")
Additional information: 
    Material model visco_plastic with total strain weakening only works if there is a compositional field called total_strain.`

and then I modified the eii in the composition field into `total strain` and it could be executed.

about the information buiter_et_al_2008_jgr/figure_6_1e20.prm is less in manual @@"

I thought it should be modified in docker or github @@

**Comment by naliboff** [comment]
@cgw0814 - good catch on the buiter_et_al_2008 benchmark. I'll put in a fix for that tomorrow.

**Comment by tjhei** [comment]
> I did as you said "cmake . and then make" but still run fail as following massage

Can you post the commands you typed in and the output that got produced? Is there a libmorency_doin.so in the directory?

**Comment by naliboff** [comment]
@cgw0814 - see pull request #2863 for updates to the Buiter et al. benchmarks. Thanks for catching those issues and let us know if you have any other questions. 

Also happy to discuss these benchmarks in detail or any related topics. Feel free to contact one of us by email or asking a question on the aspect forum: https://community.geodynamics.org/c/aspect.

**Comment by cgw0814** [comment]
Hi~ @tjhei I make a video about typing command and executing result, the linkage as following
[https://drive.google.com/file/d/1DHNac01Oftx6-uFReuY7X3b2BAzANxgK/view?usp=drivesdk](url)

@naliboff thank you.  the modified figure_6_1e20.prm is running now!!

**Comment by tjhei** [comment]
The .prm references
```
set Additional shared libraries            = ./libmorency_doin.so
```
This means you need to run ASPECT in the same directory for it to find the library (in this case go into cookbooks/morency_doin_2004). Note that we automatically create a symbolic link to your aspect binary in that folder, so this should work:
```
cd cookbooks/morency_doin_2004
mpirun -n 8 ./aspect morency_doin.prm
```

**Comment by cgw0814** [comment]
Still run fail @@ but different problem
[https://drive.google.com/file/d/1DjX9kHlT0DJ-4sxk6uq74mP_WZjsDre4/view?usp=drivesdk]()

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cgw0814** [comment]
@tjhei  still run fail @@" but different problem
[https://drive.google.com/file/d/1DjX9kHlT0DJ-4sxk6uq74mP_WZjsDre4/view](url)

**Comment by tjhei** [comment]
Can you run other aspect cookbooks without a shared library? It looks like you are running into an issue with the filesystem mount I have seen before. You are using docker? What is your setup precisely?

**Comment by cgw0814** [comment]
I'm using docker now, I can run other cookbooks, I just wonder the output of morency. it's ok. I'll install the aspect in the local host later and running other script. sorry to disturb you @@"

**Comment by gassmoeller** [comment]
Since the original issue was solved, I will close this issue.
