### ISSUE TITLE
missing file or readme in benchmarks/nonlinear_channel_flow

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2861]
I know that this plugin is used inside ``newton_solver_benchmark_set/nonlinear_channel_flow/`` but there is no readme to explain that. Ideally, we would put a simple test .prm file in here.

**Comment by gassmoeller** [comment]
Shouldnt we just move the `nonlinear_channel_flow` plugin into the `newton_solver_benchmark_set` directory? I do not see the point in having them in separate directories (I think this is just a legacy, because nonlinear_channel_flow was merged before the newton solver benchmarks). @MFraters can you take care of this during the hackathon?

**Comment by tjhei** [comment]
> Shouldnt we just move the `nonlinear_channel_flow` plugin

that would work as well. I let @MFraters decide if there is value in having it separately.

**Comment by MFraters** [comment]
sure, I will deal with this issue at the hackaton.

**Comment by tjhei** [comment]
@MFraters any updates? 😉

**Comment by MFraters** [comment]
hmm, I should check my assignments more often I guess, thanks for reminding me :) Luckily for me no one, including me, ever mentioned which hackaton I needed to deal with this ;)

Looking at the files I see no reason why the `benchmarks/nonlinear_channel_flow` would still need to be there, so yes, it should be removed and move to the  `benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow` folder. I just have to relearn how to work with these share libraries again, without breaking stuff all the time, although it should not be much more than just moving two files and updating the `input_v.prm` and `input_t.prm` files.
