### ISSUE TITLE
Release 2.1.0 planning

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2867]
I discussed with @gassmoeller yesterday, that we should try to make a release in the near future and then switch to requiring deal.II 9.0 (#2738). This would allow us to iron out issues and help transitioning to the new version for the participants of the hackathon in May. Dragging it out to after the hackathon sounds like a bad idea and we need to make sure the testers are running...

Things we need to do or look at before the release:
- [x] ~~#1455~~
- [x] test on newest gcc, clang
- [x] test on intel
- [x] compile with deal.II master, 9.0, 8.5
- [x] cotire: #2314
- anything else?

**Comment by gassmoeller** [comment]
We need to take a look at the 2.1 milestone issues. I think many of them are not critical for 2.1. though.
https://github.com/geodynamics/aspect/milestone/5

**Comment by tjhei** [comment]
I looked through all of them and none are urgent and some require deal.II 9.0, so they have to wait.

**Comment by tjhei** [comment]
master builds cleanly with:
- deal.II 8.5.1, 9.0.1, master
- gcc 5.4, clang 6, gcc 8.3, clang 8
- PETSc works
- clang-tidy

TODO: intel compiler

otherwise, I think we are good to go...

**Comment by tjhei** [comment]
I noticed we get compile warnings with the world builder: https://github.com/GeodynamicWorldBuilder/WorldBuilder/issues/118

**Comment by tjhei** [comment]
rc1 in case you want to try it out: https://github.com/geodynamics/aspect/releases/tag/v2.1.0-rc1

**Comment by bangerth** [comment]
Not related to the release, but I think we ought to just require the current deal.II dev version. Or maybe wait for deal.II 9.1 (hopefully not all that far in the future either) and then require that. People will have to update anyway, might as well have to update to 9.1.

**Comment by tjhei** [comment]
> I think we ought to just require the current deal.II dev version.

The hackathon will be before the 9.1 release and I would prefer to have the CI testers run with a release instead of a dev version. What is in the current dev version that is not in 9.0?
My suggestion:
- release 2.1.0 (branch is already created)
- switch to require 9.0 and switch CI machines (before the hackathon)
- during the hackathon: help people transition, clean up the code base (remove 8.5 hacks)
Then, before we release the next version of ASPECT we can decide to require 9.1 instead. This way, we move away from 8.5 soon and we never require a dev version for an ASPECT release. Thoughts?

**Comment by gassmoeller** [comment]
> Thoughts?

I agree with your timeline Timo. I think that a number of people would feel uncomfortable switching to deal.II-dev. Also think of the Mac users who currently use the 9.0 dmg image (I know a number). They could not easily update to 9.1.pre.

**Comment by bangerth** [comment]
If you require 9.0 right after the release, people will have to update because invariably some patch will go in that relies on 9.0. Then you'll have to require people to upgrade to 9.1 again. Why not stick with 8.5 until after 9.1 comes out?

(I suspect you have good reasons, in addition to "clean up the code base (remove 8.5 hacks)", but can't quite figure them out :-) )

**Comment by bangerth** [comment]
I agree that cleaning up would make for good hackathon projects. There are 112 occurrences of `DEAL_II_VERSION_GTE`.

**Comment by gassmoeller** [comment]
> Thoughts?

I agree with your timeline Timo. I think that a number of people would feel uncomfortable switching to deal.II-dev. Also think of the Mac users who currently use the 9.0 dmg image (I know a number). They could not easily update to 9.1.pre.

**Comment by tjhei** [comment]
> Why not stick with 8.5 until after 9.1 comes out?

- cleanup hackathon projects
- helping people move from 8.5 to 9.0, fix problems in the process
- moving forward instead of being stuck with 8.5 even longer
- we can not test/merge matrix-free solver stuff because it requires 9.0
Also, I think the 9.0->9.1 move should be pretty painless.

**Comment by gassmoeller** [comment]
Timo did you already create a release announcement in `doc/release-tasklist`? If not I am happy to do that (collect the most important changes and paste them into the template).

**Comment by tjhei** [comment]
No, I did not. If you want to go through the list of changes, that would be very helpful. You can post it here or open a PR! Thanks.

**Comment by tjhei** [comment]
I just compiled successfully with intel 18.0.2, which concludes my testing.

Can I get others to test the aspect-2.1 branch and report back any issues? Anything else holding us up to make the release?

**Comment by gassmoeller** [comment]
I tested it on Ubuntu 18.04 with gcc 7.3 and it seems to work. Will test on Stampede2 today or tomorrow.

**Comment by naliboff** [comment]
I tested it on Stampede2 with gcc 7.1 and deal.II v.9.0.1. No compiler warnings and one quick model ran without issue.

**Comment by bangerth** [comment]
I checked with current deal.II dev and GCC 8.1. It all works.

**Comment by tjhei** [comment]
great, I will do the release this weekend, then.

**Comment by tjhei** [comment]
cherry-picked the change in #2896.

**Comment by tjhei** [comment]
https://github.com/geodynamics/aspect/releases/tag/v2.1.0

**Comment by tjhei** [comment]
well, zenodo failed with
```
{
    "errors": "Unknown error occured."
}
```
and I don't know how to fix that. This means we don't have a zenodo DOI at this point.

**Comment by gassmoeller** [comment]
Ok, everything seems ready on our side. The CIG website is updated: https://geodynamics.org/cig/software/aspect/

We discussed this morning that CIG would appreciate if this link appeared in the release message. No need to modify the release on github, but when sending out the emails it should be added before the github link to the release.

If no one beats me to it I will send out the release message tomorrow morning.

**Comment by gassmoeller** [comment]
Ok, the announcement is out. Thanks everyone (in particular Timo) for the work and testing. Closing this issue.

**Comment by tjhei** [comment]
Thanks for sending out the announcements, @gassmoeller !

**Comment by gassmoeller** [comment]
I just remembered we still need to update the docker image and the virtual machine. Timo can you take care of the VM and I rebuild the docker image? Should I base the image on `tjhei/dealii:v9.0.1-full-v9.0.1-r5-gcc5` to be consistent with the tester?

**Comment by tjhei** [comment]
> Timo can you take care of the VM

yes, I started the update a while ago already. Will finish it up soon.

> and I rebuild the docker image?

Sure, it makes sense because it is under your user right now. By the way, do you have a cig dockerhub organization we could use?

> Should I base the image on `tjhei/dealii:v9.0.1-full-v9.0.1-r5-gcc5` to be consistent with the tester?

The whole docker stuff turned out to be opinionated. I was unhappy with the way the official images are done. I don't feel strongly either way, but I guess it makes sense to be consistent (if nothing else but the test output).

**Comment by gassmoeller** [comment]
> By the way, do you have a cig dockerhub organization we could use?

No we do not at the moment. We discussed building docker images for all software packages, but since they will not be easily usable on clusters, we postponed the idea. I do not know how much help it would be for users wanting to test a software, I have the feeling someone who can figure out how to install and use docker will also have no problems installing the software itself.

**Comment by tjhei** [comment]
> We discussed building docker images for all software packages, but since they will not be easily usable on clusters, we postponed the idea.

I agree. I was thinking that you could allow the maintainers to use the organization to host their images (so you could push to geodynamics/aspect instead of using gassmoeller/aspect).

**Comment by tjesser-ucdavis-edu** [comment]
> By the way, do you have a cig dockerhub organization we could use?

We do: [https://hub.docker.com/u/geodynamics](https://hub.docker.com/u/geodynamics). I should be able to give you access.

We currently use the DockerHub autobuild settings to create build environments for VirtualQuake, BurnMan, Rayleigh, and Calypso.

**Comment by gassmoeller** [comment]
This happens if you moslty communicate via github while sitting in the same room :smile:. I was not aware. I think the geodynamics organization would be great for the aspect image (Tyler can you give Timo and me access?). We could also host the deal.II image we use for testing if you want (to make the dockerfile more transparent).

**Comment by tjesser-ucdavis-edu** [comment]
Sure, please email me your account names.

**Comment by tjhei** [comment]
https://cloud.docker.com/u/tjhei

**Comment by tjhei** [comment]
> We could also host the deal.II image we use for testing if you want (to make the dockerfile more transparent).

We should talk about that first. One thing that I find important is that we use versioned images. We made the mistake in the past to not do it, which makes it difficult to upgrade, etc..
