### ISSUE TITLE
Free-surface problem: cell giving non-positive volume fraction

### ISSUE THREAD

**Issue by kristofporkolab** [geodynamics/aspect#2915]
Dear All, 

I am working on a 2D subduction setup with a continental block in the lower plate, using a free surface, adaptive mesh refinement, and visco-plastic rheology. I have encountered a problem where one of the cells at the top of the model returns a non-positive volume fraction and crashes the simulation: 

"An error occurred in line <2727> of file </trinity/opt/apps/software/aspect/aspect-2.0.1/candi/DEAL2/tmp/unpack/deal.II-v9.0.1/source/fe/mapping_q_generic.cc> in function
    dealii::CellSimilarity::Similarity dealii::MappingQGeneric<dim, spacedim>::fill_fe_values(const dealii::Triangulation<dim, spacedim>::cell_iterator &, dealii::CellSimilarity::Similarity, const dealii::Quadrature<dim> &, const dealii::Mapping<dim, spacedim>::InternalDataBase &, dealii::internal::FEValuesImplementation::MappingRelatedData<dim, spacedim> &) const [with int dim = 2, int spacedim = 2]
The violated condition was:
    det > 1e-12*Utilities::fixed_power<dim>(cell->diameter()/ std::sqrt(double(dim)))
Additional information:
    The image of the mapping applied to cell with center [1.16145e+06 658711] is distorted. The cell geometry or the mapping are invalid, giving a non-positive volume fraction of -42785.9 in quadrature point 3."

The problem occurs where the free surface is rapidly deforming, so perhaps it is related to one of the elements getting "bow-tied" between two re-meshing. Could anyone advise me on how to tackle this issue? 

Thank you and best, 
Kristof Porkolab

**Comment by naliboff** [comment]
@kristofporkolab - Thanks for posting the issue, which I imagine a number of groups will likely encounter at some point!

To make the discussion as visible as possible to a wider ASPECT-user group, would you be opposed to moving the discussion over the ASPECT user forum?: https://community.geodynamics.org/c/aspect

One of the intents of the forum is to provide a location for model discussion, while code issues (errors, bugs) remain here. I think this discussion falls in the former category, but happy to keep the discussion here if you prefer.

Regardless of location, to start here a few follow-up questions:
1. Can you provide an image of the distorted cells?
2. What type of free surface projection and associated parameters are you using?
3. What type of AMR are you using?
4. How close are the distorted cells to the model boundary?

I'm also running oceanic-continental subduction models and have yet to come across this specific issue (plenty of others, though). Hopefully this means a few tweaks to the model setup will resolve the problem.

- John

**Comment by kristofporkolab** [comment]
Thank you very much for your answer. I have moved the discussion with the requested supplementary information to the user forum. 
Best, Kristof

**Comment by naliboff** [comment]
@kristofporkolab - Thank you for moving the discussion over the forum and I replied there as well. Closing this issue for now, but feel free to re-open if there turns out to be a bug in the code related to the results you posted.
