### ISSUE TITLE
reorganize folders/scripts in doc/

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#2929]
We place all kind of scripts and utilities in the doc/ folder. I think this is an unfortunate situation and I would like to move things around.
Suggestion:
./contrib/utilities/ for indent, update_prm_files.sh, update_source_files.sh
./contrib/release/ for update_copyright, release-tasklist, bump_version.sh
./contrib/docker/ for the docker files (from ./docker)

**Comment by gassmoeller** [comment]
I like it. `/contrib/utilities` will also be useful for other scripts like mentioned in #1234

**Comment by bangerth** [comment]
On 5/11/19 5:34 PM, Timo Heister wrote:
> 
> ./contrib/utilities/ for indent, update_prm_files.sh, update_source_files.sh
> ./contrib/release/ for update_copyright, release-tasklist, bump_version.sh
> ./contrib/docker/ for the docker files (from ./docker)

Good idea.
