### ISSUE TITLE
potential bug: make_pressure_rhs_compatible

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#298]
It looks to me that we are calling ```make_pressure_rhs_compatible``` more then once:
first in compute_initial_stokes_residual()
and then in solve_stokes(). I assume this breaks the correction as ```int_Gamma u \cdot n ``` is applied twice.  

I would suggest we move the call directly after assemble_stokes_system().

@jdannberg what do you think?

**Comment by jdannberg** [comment]
Okay, so it seems this is only a problem in compressible models that use the iterated IMPES solver scheme and prescribed normal velocities at the boundaries

I looked at this together with @gassmoeller, and we thought that maybe we could move it inside assemble_stokes_system()? There is a place in line assembly.cc:1248 where we have an if-statement `if (do_pressure_rhs_compatibility_modification)` where we could add `make_pressure_rhs_compatible`. In this way we would have to include it only in that place, and not in all the different solver schemes in core.cc Or is there any reason why we would want to have it outside of the assembly?

**Comment by tjhei** [comment]
I don't see a reason to ever look at the RHS without the modification. Can you prepare a PR?
