### ISSUE TITLE
Extract and visualize the surface mesh

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#2982]
Extract the surface mesh from the volume mesh and output it to vtk for visualizing things like the heat flux on the free surface, as discussed with @bangerth

**Comment by anne-glerum** [comment]
@bangerth Out of curiosity, have you given this any more thought?

**Comment by anne-glerum** [comment]
After talking to @bangerth, it might be worth finishing these PRs:
* #4061
* #4054
The discussion in #4054 concerns the duplication of code, i.e., each volume mesh postprocessor will need to be copied for the corresponding surface mesh postprocessor. Instead of waiting on a restructuring of the visualization interface, we could merge the PRs in the mean time and remove them again after restructuring.

**Comment by bangerth** [comment]
@anne-glerum Tag me in these PRs once you think they're ready for review.

**Comment by anne-glerum** [comment]
As both PRs mentioned above are now merged (ie base variables, strain rate and stress can all be outputted on a surface mesh), I'm closing this issue.
