### ISSUE TITLE
Update muparser cookbook

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#3003]
@mibillen added the muparser cookbook in #2577, which also included some .prm fragments in `doc/manual/cookbooks/muparser-temperature-example/`. These were committed in commit f161fe3fcb06888d4ee43b9341bc53c4bfdc7af2. But then the next commit on that branch, f3976e8129af70fe97c1e1563a0ca87d6435116e, still before #2577 was merged, made some changes to the cookbook .prm files but forgot to keep the ones in the manual synced.

We should re-sync everything.

@sibiaoliu was working on this :-)

**Comment by sibiaoliu** [comment]
I finished the re-sync work of the muparser cookbook. Please take a look at #2973

**Comment by tjhei** [comment]
@bangerth can this issue be closed now?
