### ISSUE TITLE
Use proper markup for units in parameter descriptions

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#3046]
We have many parameter descriptions like this:
```
          prm.declare_entry ("Melting entropy change", "-300",
                             Patterns::Double (),
                             "The entropy change for the phase transition "
                             "from solid to melt. "
                             "Units: $J/(kg K)$.");
```
The problem is in the last line: The units `J`, `kg`, and `K` are in math mode (surrounded by dollar signs) and so are printed in italics. But units should really be printed in upright characters. In addition, latex ignores whitespace, so the denominator is really just printed as `kgK`, without a space.

The solution to this can come in two ways:
* We explicitly mark up units with `\text` so that the symbols are shown in uprights. #3044 is an example of doing this in a bunch of places. We would then also have to provide a space by hand: `\text{kg}\,\text{K}`.
* Maybe better, there are latex packages that do all of this for us. A good overview is given here: https://tex.stackexchange.com/questions/2248/what-package-should-i-use-to-typeset-units

**Comment by bangerth** [comment]
Related: Instead of using `${}^\circ$` for the degree symbol, we should be using the `\degree` command from the `gensymb` package: https://www.overleaf.com/learn/latex/Questions/How_can_I_write_a_%C2%B0_(degree)_symbol_in_LaTeX%3F

**Comment by bobmyhill** [comment]
Happy to attack this in brain-downtime unless anyone else has a burning desire :)

**Comment by bangerth** [comment]
That would be outstanding! Can also be done in small increments :-)

**Comment by bobmyhill** [comment]
> That would be outstanding! Can also be done in small increments :-)

Only just saw this. Ooops :D

**Comment by bangerth** [comment]
Fixed by @bobmyhill 's monster patch!
