### ISSUE TITLE
Add missing #DEAL_II_VERSION_GTE

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#3144]
#3048 and https://github.com/dealii/dealii/pull/8294 have now both been merged. As a consequence, we should put the `#ifdef DEAL_II_VERSION_GTE(9,2,0)` back into the code. There is really no hurry in this, and maybe we should give people a bit of time to update their deal.II versions if they work from deal.II dev, but we should do it before the next release.

@bobmyhill -- FYI.

**Comment by gassmoeller** [comment]
Closed by #3145.
