### ISSUE TITLE
Fix "Boundary temperature model" documentation 

### ISSUE THREAD

**Issue by melaniegerault** [geodynamics/aspect#3222]
A minor thing, but I have noticed that the "box with lithosphere boundary indicators" option that is indicated on the website (see below) and in the manual is not included in the source code anymore. It seems like it could be the same as two_merged_boxes.cc
![Screen Shot 2019-09-17 at 12 45 16 PM](https://user-images.githubusercontent.com/53456257/65062299-bee48c80-d949-11e9-95fe-72c4a2241907.png)

**Comment by naliboff** [comment]
@melaniegerault - Thanks for brining this up. The `box with lithosphere boundary indicators` initial composition, initial temperature and geometry models are in fact the same as the `two_merged_boxes` models (e.g. same files, the name `box with ...` is only assigned when the model is registered).

The original naming scheme may have been kept within the `two_merged_boxes` models to avoid confusion regarding loss of a feature?

**Comment by melaniegerault** [comment]
I see, thanks. That was just in case it wasn't on purpose :)
