### ISSUE TITLE
System prerequisites in manual

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#324]
Maybe we should provide in the manual a list of necessary tools that should be available on the system for the installation of ASPECT and all of its prerequisites. We encountered some obscure error messages on a newly installed opensuse system, because zlib was missing, and it is not stated explicitly anywhere that zlib is a dependency (although one might think of it, if you consider how we compress our output). I would offer to contribute a small section, including an exemplary list of packages that fulfil the dependencies in ubuntu.

(apt-get install build-essential \
                        gcc \
                        g++ \
                        gfortran \
                        libblas-dev \
                        liblapack-dev \
                        libopenmpi-dev \
                        openmpi-bin \
                        cmake \
                        git \
                        zlib1g-dev)

**Comment by bangerth** [comment]
Yes, I think that would make sense.

**Comment by tjhei** [comment]
Yes, makes sense. My list for 14.04: https://github.com/tjhei/docker-playground/blob/master/docker-deal-base/Dockerfile

**Comment by gassmoeller** [comment]
Closed by #325
