### ISSUE TITLE
Resume computation fails

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#3253]
@Djneu and I hit restart issues for recent ASPECT versions and -it seems- dealii 9.1.1:
`Cannot open snapshot mesh file or read the triangulation stored there.`

I hit it on my mac for:
--     . version 2.2.0-pre (mesh_def_initial_topo, 3f87d8fa0)
--     . using deal.II 9.1.1
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.14.1
--     . using p4est 2.0.0
--     . running in DEBUG mode
--     . running with 1 MPI process

Checkpointing produces the following restart files:
`restart.resume.z.old`
`restart.resume.z`
`restart.mesh.old`
`estart.mesh.new_fixed.data`
`restart.mesh.info.old`
`restart.mesh.info`
`restart.mesh`

`restart.mesh.new_fixed.data` is unfamiliar to me. Also, for these results I used the `resume_free_surface.prm` test. It also happens without a free surface.

I do not hit the error on the cluster: 
--     . using deal.II 9.0.1
--     .       with 32 bit indices and vectorization level 2 (256 bits)
--     . using Trilinos 12.10.1
--     . using p4est 2.0.0
--     . running in OPTIMIZED mode
--     . running with 20 MPI processes
for 
ASPECT_VERSION:            2.2.0-pre
GIT REVISION:              f31718bfc (master)

I don't have time to investigate it further now. @Djneu do you have additional info?

**Comment by Djneu** [comment]
Not much to add, I've tried on both my office computer and a cluster using dealii 9.1.1 and aspect 2.2.0-pre (a856e796c) and get the same error. On the cluster, I also tried using the same dealii version but with aspect 2.1.0 (d5dfc36b9), and in that case the restart works fine.

**Comment by tjhei** [comment]
There were a lot of changes in deal.II after 9.0 with respect to snapshots. It is likely that this is broken because of that: restart.mesh.new_fixed.data is new for example.

**Comment by tjhei** [comment]
I think #3256 should fix the broken checkpointing since deal.II 9.1. Give it a test please?

**Comment by Djneu** [comment]
With #3256 the resume_free_surface test worked on both my office computer and the cluster. Thanks for the fix!

**Comment by anne-glerum** [comment]
Thanks @tjhei !
