### ISSUE TITLE
Restart does not take into account initial topography of the mesh.

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#3254]
When restarting a model that had initial topography added to the mesh, this topography is not taken into account and thus you'll have a different mesh upon restart. See the figure of a model with an initial hill that is or is not restarted at the second timestep. I have a PR coming up to remedy this that adds the initial topography to the stored mesh displacements.

![image](https://user-images.githubusercontent.com/7631624/66401517-8cc3c900-e9e3-11e9-945d-111ef4a52ab7.png)

**Comment by gassmoeller** [comment]
I think this was fixed in #3265.
