### ISSUE TITLE
Exception when outputting multiple additional visualization fields

### ISSUE THREAD

**Issue by ian-r-rose** [geodynamics/aspect#331]
This is a strange one. It seems that somewhere in the visualization postprocessor there is a bug in counting the number of visualization fields to output.  This leads to an ExcDimensionMismatch.  I do not know how easily reproducible this is, but for me this happens when

(a) there are compositional fields, and
(b) there is more than one additional output field.

I can trip this behavior by adding 'viscosity' to the 'List of output variables' parameter in the visualization subsection of, for instance, cookbooks/composition-active.prm.

It is not immediately clear to me what could be going on, but maybe somebody who is more familiar with the visualization postprocessor could weigh in.

**Comment by ian-r-rose** [comment]
Hmm, I see that by updating deal.ii, the error goes away.  It appears to me that dealii/dealii#918 fixes the issue.  Is this expected?  If so, feel free to close.

**Comment by bangerth** [comment]
Yes, you beat me to pointing out the recent fix. There was only about a one-day window where you could have encountered this problem.
