### ISSUE TITLE
remove PETSc support

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3338]
We currently do not have sufficient test coverage, no CI, and no developer using PETSc instead of Trilinos. In fact, we currently don't compile at all (even after #3337). Should we disable/remove it or is there a compelling reason/demand for improving things?

**Comment by gassmoeller** [comment]
I am not opposed to removing it. As you said it is insufficiently tested and used, and since we are moving toward using the GMG preconditioner more widely it makes sense to remove an unused alternative to the AMG preconditioner (this was the only place where we used PETSc, right? we should confirm this).

**Comment by tjhei** [comment]
> this was the only place where we used PETSc, right? we should confirm this

Well, all linear algebra would use PETSc instead of Trilinos. The most striking different is that the PETSc AMG is different than Trilinos ML, everything else is somewhat similar.

Note that we can not use GMG with PETSc right now (we copy vectors between Trilinos<->deal.II matrix free and that is only implemented for Trilinos).

**Comment by tjhei** [comment]
> I am not opposed to removing it

How about I disable it for now and we decide later if we want to remove the code as well?

**Comment by gassmoeller** [comment]
sounds good

**Comment by tjhei** [comment]
Should we remove petsc support? I think that makes sense at this point.

**Comment by tjhei** [comment]
@gassmoeller starter project?

**Comment by gassmoeller** [comment]
Yes, good idea.
