### ISSUE TITLE
Invalid link for contributing template

### ISSUE THREAD

**Issue by masterleinad** [geodynamics/aspect#3345]
The contributing template for pull requests points to https://github.com/geodynamics/aspect/CONTRIBUTING.md which doesn't exist. It should be https://github.com/geodynamics/aspect/blob/master/CONTRIBUTING.md.

**Comment by tjhei** [comment]
huh, it works when looking at https://github.com/geodynamics/aspect/blob/master/.github/PULL_REQUEST_TEMPLATE.md but not inside the PR.
