### ISSUE TITLE
Should initial topography be part of the mesh deformation module?

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#3399]
Following the discussion between @gassmoeller, @tjhei and me during the last user meeting, I'd like to open up the following discussion:

1. **Should the `initial topography` functionality become part of the `mesh deformation` modules, instead of being its own module?** In the end, both `initial topography` and `mesh deformation` want to modify the mesh. The former is only restricted to a specific point in time. 
  Some context: To diffuse the free surface, I need access to the current height of the surface points. Mesh displacements are stored and can thus be queried for any topography gained over time. However, they do not include the initial topography. My lengthy workaround was 1) to store the initial topography similarly to the mesh displacements; or 2) to apply a mesh displacement at t1 instead of initial topography at t0. Rene however suggested making the whole `initial topography` module part of `mesh deformation`.

2. **If so, should we change/expand the interface of the `mesh deformation` plugins?** Currently, one has to specify a boundary velocity, which is internally translated to a mesh displacement based on the timestep. However, specifying an initial topography through a boundary velocity (with the timestep unknown) is cumbersome. One would like to directly prescribe the displacement.

**Comment by tjhei** [comment]
1. Yes, I think that makes a lot of sense to me.
2. I find it more natural if the mesh deformation returns a displacement, not a velocity. Going from velocity to displacement is easy enough.

**Comment by gassmoeller** [comment]
1. I agree. Reducing the number of plugin systems while keeping the functionality sounds great and is more intuitive as well (any kind of mesh deformation is a mesh deformation plugin then :-)).
2. Displacement is more intuitive, but I think there was a reason why it prescribes velocity at the moment (possibly, because for the free surface we need to correct for mesh movements in the advection equation). For the initial topography that is not relevant, so maybe we can offer both functions in the interface and do something like: `total_displacement = plugin_displacement + plugin_velocity * timestep` in the calling function? Not sure that will work, but I would want to at least check.

**Comment by anne-glerum** [comment]
> 2. Displacement is more intuitive, but I think there was a reason why it prescribes velocity at the moment (possibly, because for the free surface we need to correct for mesh movements in the advection equation). For the initial topography that is not relevant, so maybe we can offer both functions in the interface and do something like: total_displacement = plugin_displacement + plugin_velocity * timestep in the calling function? Not sure that will work, but I would want to at least check.

Mesh deformation plugins have to supply a velocity that is used as a boundary condition to solve for the internal mesh velocity. This velocity is interpolated to the Stokes FE mesh to be used in the advection equations. 

Afterwards, the mesh displacements are also stored for use in the Mapping of the real to the reference cell. These are computed as timestep*mesh_velocity. 

So far the mesh deformation plugins have only supplied the mesh velocity boundary conditions to compute the internal mesh velocities through solving the Laplace equation. The initial topography plugins modify the whole mesh directly through a displacement. To be able to set both would be great. Then at t0, the stored mesh velocity would be zero, but mesh displacement non-zero and mesh.

**Comment by anne-glerum** [comment]
Now that we have initial mesh displacements as part of the mesh deformation module, I think we can close this issue.

We could still transfer the existing initial topography plugins to initial mesh deformation plugins, but that is a separate discussion.
