### ISSUE TITLE
Effects of prescribing an initial tpography

### ISSUE THREAD

**Issue by UfrancoU** [geodynamics/aspect#3452]
Hi all,

    I wish everyone happy healthy days during these complicated times.

    I am using ASPECT 2.1.0, for a 3D model. I am trying to load an initial topography (x,y, z(x,y)), expecting among other things see its effects underneath..

    On the manual, I read that among the requirements for loading an initial topography and expect ASPECT to do something physical, the topography needs to be small.. I read ‘Also, initial topography is supposed to be small, as it is not taken into account when depth or a representative point is computed.’ 

    I assume that this means small compared with the model vertical/depth dimensions, and also, having small slopes in order not to violate some physical approximations.
 
    That being said, my question:

   Does ASPECT computes a variable lithostatic/hydrostatic pressure inside the model as a consequence of the topography?

cheers,
Felipe

**Comment by naliboff** [comment]
Hi Felipe,

> Does ASPECT computes a variable lithostatic/hydrostatic pressure inside the model as a consequence of the topography?

Yes, ASPECT does calculate a variable lithostatic pressure due to imposed topography. Are you running a model that does not give an expected result? If not, perhaps we can close this issue and move the discussion over the forum?

Thanks!
John

**Comment by UfrancoU** [comment]
Thanks John Naliboff !

   That is what I needed to know.

   Now I have a problem when trying to load topography, but I will open that in a dedicated issue.

many thanks many,
Felipe
