### ISSUE TITLE
 problem loading initial topography

### ISSUE THREAD

**Issue by UfrancoU** [geodynamics/aspect#3454]
Hi all,

 I am using ASPECT 2.1.0, for a 3D model. I am trying to load an initial topography, but I am unable to succeed.

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

   Loading Ascii data boundary file ./MyIniTopo.txt.

   Loading new data file did not succeed.
   Assuming constant boundary conditions for rest of model run.

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

In my .prm file, my model definition and topo loading look like this:

subsection Geometry model
  set Model name = box

  subsection Box
    set X extent = 4e5
    set Y extent = 2e5
    set Z extent = 2.5e5
  end

  subsection Initial topography model

    set Model name = ascii data

    subsection Ascii data model
       set Data directory = ./
       set Data file name = MyIniTopo.txt
    end
  end

end
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

And my topography file MyIniTopo.txt has the right format (after having passed the error), and describes a 501x51 horizontal grid, with a total of 25551 topography points. 

# POINTS: 501 51 25551
 0.0 0.0 2000.000000
 800.0 0.0 2000.000000
 1600.0 0.0 2000.000000
 2400.0 0.0 2000.000000
 ...

"MyIniTopo.txt" 25552L, 754949C

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

So I think the data (‘ nxi nyj zij ’) which ascends first in x, has the right format..

I think the error may come from the fact that the topography grid is not the same as the model grid (which is decided/constructed later by ASPECT).  But,  as far as I understood from this forum, the initial topography loading should be done by ASPECT once the finest refinement level has been carried out, at time 0.

What should I do to successfully load my initial topography?

cheers,
Felipe

**Comment by naliboff** [comment]
@UfrancoU - sorry, I should have been more specific. Can you post the question on the CIG forum within the ASPECT forum?: https://community.geodynamics.org/c/aspect/13

Thanks!
John

**Comment by UfrancoU** [comment]
Hi John, Julianne, Wolfgang,

    Thanks for replying. I hope you guys are doing well.

    I haven’t been able to succeed in loading the topography.

    I modified my file for it to have the exact format as the one of the example (I had to program strings to build a format like that). Btw, the example format seems a bit peculiar (variable spacing, no decimal digits..):

  ‘x._y._ _ z.’  that is: ‘no space, x-value., space, y-value., space-space, z-value.

The numbers have floating point, but no decimal digits.. odd !

Anyway, before all this problem, I expected Aspect, to eat different number formats, as Dealii is based on programs like ‘numdiff’, etc.

3) I changed the directory from ./ to the full path (which had worked for me in previous projects, but in a different cluster though).

4) I expect Aspect to read and assimilate this geometry model first, then construct the grid/mesh, then refine it, and then to approximate the topography I loaded.

5) My current model topography is simple: a platform cosine-tapering-off to a basal plane. But I expect to load complex topographies in the near future.

6) I have tested loading an intentionally wrong filename (to test location logic), it says file not found. Good.  Then I have tested with the correct filename: its simply says ‘ Loading new data file did not succeed. Assuming constant boundary conditions for rest of model run.’ Which I interpret as that it actually finds the file, but does NOT like the file. My file ‘MyIniTopo.txt’ starts like this:

# POINTS: 501 51
# Columns: x z Topography[m]
0. 0.  2000.
800. 0.  2000.
1600. 0.  2000.
2400. 0.  2000.
3200. 0.  2000.
4000. 0.  2000.
4800. 0.  2000.
..

I also tried loading the example topography file and modifying my model-box lengths to make them 660 km as in that example file. It does not work, it posts the same  ‘Loading new data file did not succeed. Assuming constant boundary conditions for rest of model run’.

7) I have all the files in the same directory..

I think that there may be something more basal that I am doing wrong.

I have a question: If my box height is DZ, does that length needs to include the maximum topography as added to the depth range? Somehow having the reference base ground-air interface level not at max(z), but at z = DZ -max(topo) ? That would be too much to ask for a model setting, I don’t think aspect was programmed that way..  
 
cheers,
Felipe

**Comment by UfrancoU** [comment]
# POINTS: 501 51
# Columns: x z Topography[m]
0. 0.  2000.
800. 0.  2000.
1600. 0.  2000.
2400. 0.  2000.
3200. 0.  2000.
4000. 0.  2000.
4800. 0.  2000.
..
