### ISSUE TITLE
resume computation fails with particles 

### ISSUE THREAD

**Issue by EstherHeck** [geodynamics/aspect#3463]
I get the error described here https://github.com/geodynamics/aspect/issues/3253
when I want to restart a model that uses _particles_ in the _list of postprocessors_. 

The first run where the snapshot is created works fine, but when restarting the model, the error message is: "Cannot open snapshot mesh file or read the triangulation stored there." 
When I outcomment the _particles_ in the _list of postprocessors_, the model restarts as  it should. The error appears both, when restarting from a snapshot from time 0 and from later times. 

I atttach an input file that produces the error: 
[particle_generator_random_uniform_restart.txt](https://github.com/geodynamics/aspect/files/4503420/particle_generator_random_uniform_restart.txt)
It is the particle_generator_random_uniform test where I added the lines to restart it. I also tried it with several other tests and the same error appears when adding _particles_ in the _list of postprocessors_.

I use: 
--     . version 2.2.0-pre (master, 767fb667f)
--     . using deal.II 9.1.1
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.10.1
--     . using p4est 2.2.0

--     . running in DEBUG mode
--     . running with 1 MPI process

**Comment by gassmoeller** [comment]
Hi Esther,
Thanks for reporting, i will have look as soon as possible. In the meantime, could you check if the problem exists with deal.II 9.0, and with a recent development version of deal.II? We have tests for the particle restart functionality for deal.II 9.0 and they pass, so hopefully it is only broken for certain deal.II versions.

**Comment by anne-glerum** [comment]
>  In the meantime, could you check if the problem exists with deal.II 9.0

This combination restarts fine with the prm provided above:

-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.2.0-pre (test_restart, 70e84287d)
--     . using deal.II 9.0.1
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.14.1
--     . using p4est 2.2.0
--     . running in DEBUG mode
--     . running with 1 MPI process

**Comment by gassmoeller** [comment]
Thanks for checking, I tested with a recent deal.II (1cb414ed69) and it does not work there either. Deal.II changed serialization of the particles between 9.0. and 9.1, I will try to figure out what happened.

**Comment by gassmoeller** [comment]
It was a problem with renaming the checkpoint data files. ASPECT initially writes the checkpoint data as restart.mesh.new to keep the working old file and then rename the file after writing has succeeded, but we forgot to rename the particle data (which is stored in a separate file since deal.II 9.1). Can you check if #3468 fixes the problem for you (it worked for me with deal.II-dev and the file you provided)?

**Comment by EstherHeck** [comment]
I tried several models that restart with particles and they all worked fine. Thanks for taking care of it!
