### ISSUE TITLE
No normal flux GMG parallel issues

### ISSUE THREAD

**Issue by tcclevenger** [geodynamics/aspect#3512]
I have found a bug  using no normal flux boundary conditions with spherical shell mesh and block GMG Stokes solver in parallel. If we take the test `tests/shell_3d_gmg.prm`, using 1 processor, we have the computation on 28K DoFs requires 36 iterations (compared to 113 for AMG). But switching to 2 processors requires 106 iterations (112 for AMG) and switching to 4 processors requires 100 iterations.

The implementation should be equivalent for any number of processors for GMG (I expect differing by only a few iterations). Obviously something is going wrong. This bug could be in a few places:
- Creating the no normal flux constraints in `stokes_matrix_free.cc` function `internal::TangentialBoundaryFunctions::compute_no_normal_flux_constraints_shell()`
- Creating the diagonal of the A block GMG matrices for preconditioning (computed in `build_preconditioner()`)
- deal.II bug: incorrect use of constraints in `MGTransferMatrixFree`

It is clearly a preconditioning problem since the solutions between AMG and GMG match for all runs/all processor counts. I am surprised we wouldn't have found during testing. I'll continue looking, but let me know if anyone else has seen unusually high iterations counts for GMG with spherical shells.

**Comment by tcclevenger** [comment]
Simple fix (see https://github.com/geodynamics/aspect/pull/3514).

**Comment by gassmoeller** [comment]
Fixed in #3514
