### ISSUE TITLE
Release 2.2.0 planning

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3518]
Let's start talking about the planned 2.2.0 release.

TODO list:
- [x] go through milestone https://github.com/geodynamics/aspect/milestone/7
- [x] test on newest gcc and clang for warnings
- [x] test on  Intel
- [x] test with deal.II 9.0.0, 9.1.1, 9.2.0, master
- [x] follow doc/release-tasklist
- [ ] post-release: #3451 , bump deal.II version

**Comment by gassmoeller** [comment]
I went through the milestone issues and postponed a bunch of them (documentation issues or enhancements that are not likely to be done soon and not critical). I think the remaining issues are worth a closer look.

**Comment by tjhei** [comment]
I am working on testing the cookbooks and benchmarks right now. Lots of small fixes incoming...

**Comment by tjhei** [comment]
I recompiled 9bee701b268fb using clang 10, gcc 10.1, intel 19.0.5 with various deal.II versions and things all look good.

**Comment by tjhei** [comment]
well, I forgot clang-tidy: #3518

**Comment by tjhei** [comment]
I created the release branch: https://github.com/geodynamics/aspect/tree/aspect-2.2

**Comment by tjhei** [comment]
I am closing this now as the release is done and we have other issues that track the follow-up.
