### ISSUE TITLE
incomplete viscosity-grooves benchmark

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3534]
viscosity-grooves introduced in #3077 by @cedrict is missing the plugin required by the prm.

@cedrict can you take a look please?

**Comment by gassmoeller** [comment]
I just sent an email to Cedric, lets see how easy this is to fix. If it does not make it in time I dont think we should delay the release because of this.

**Comment by tjhei** [comment]
agreed. But he also got an email from me a couple of days ago. :-)

**Comment by cedrict** [comment]
Hi guys sorry it took so long to answer ... I went digging and found the .cc file.

**Comment by cedrict** [comment]
ok, just made a new CMakeLists.txt , compiled and ran it with up-to-date Aspect . What do you want me to do next ?

**Comment by tjhei** [comment]
> What do you want me to do next ?

share the .cc and the CMakeLists.txt file with us? :-) If you can create a pull request, that would be awesome.

**Comment by tjhei** [comment]
closed by #3568
