### ISSUE TITLE
incomplete benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3535]
I am struggling to run the benchmark benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016

It seems that I need a file called input.prm that is not part of the repository.

@MFraters can you please take a look?

**Comment by MFraters** [comment]
this should to be fixed as soon as #3183 is done

**Comment by gassmoeller** [comment]
This seems to be fixed for me. Closing.
