### ISSUE TITLE
More control on timestepping logic

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#3549]
As discussed in the biweekly ASPECT meeting, it would be great to have a plugin structure for timestepping control. An example would be @tjhei 's implementation to redo a timestep if the mesh resolution in the shear bands is not the same throughout the bands. Another application would be to assess the solution for a specific timestep size and recompute the timestep for a smaller timestep size if a certain threshold was exceeded.

**Comment by tjhei** [comment]
Thanks for the reminder Anne.
I put things on hold to work on the release for now, but I should put my ideas down before I forget:

- related is #2744 (redo timestep if nonlinear solver fails)
- scenario: if a check determines that refinement is needed (run every time step?), refine and redo timestep
- scenario: if the solution (for example stresses exceed threshold) redo using smaller time step
