### ISSUE TITLE
spack instructions don't work

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3577]
I tried to follow the instructions in .``/contrib/spack`` to install, but this doesn't work:
1. spack now wants you to specify ``./spack.yaml`` instead of just running ``spack install``
2. Even then I get ``==> Error: 'spec'`` as the error mesage.

I have no idea and no time to look at it right now. @gassmoeller do you have an idea?

**Comment by gassmoeller** [comment]
I will take a look.

**Comment by tjhei** [comment]
I have the spack PR for the new release ready. Just wanted to test first...

**Comment by gassmoeller** [comment]
"Fixed" by #3588.
