### ISSUE TITLE
periodic adaptive refinement can cause infinite loop in deal.II 9.2.0

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3604]
observed in deal.II 9.2.0 and ASPECT 2.2 and current master (also see #3583).

To reproduce, run ``tests/periodic_box2.prm`` (even with 1 processor) and observe that we hang in time step 10 (when adaptive refinement happens). The test passes with older deal.II versions.

It looks like we end up in an infinite loop in the following code section:
https://github.com/dealii/dealii/blob/f29b68a2829ecdccb1c2753c7e290505901b02ad/source/distributed/tria.cc#L3442-L3450

**Comment by tjhei** [comment]
simplified file:
[hang.prm.txt](https://github.com/geodynamics/aspect/files/4932815/hang.prm.txt)

**Comment by gassmoeller** [comment]
Uh oh, not good. Do you think we need a known issues page, or think about a point release? Do you know if it happens to all periodic boundaries or just sometimes?

**Comment by gassmoeller** [comment]
Oh I just realized, if this is in deal.II 9.2. is there even anything we can do on the ASPECT side?

**Comment by tjhei** [comment]
> is there even anything we can do on the ASPECT side?

The only possible change that likely works is to turn off mesh smoothing (or some of it) like in https://github.com/geodynamics/aspect/pull/3556

**Comment by tjhei** [comment]
I can confirm that this hang does not happen without mesh smoothing as in #3556.

**Comment by tjhei** [comment]
I have a work-around in deal.II: https://github.com/dealii/dealii/pull/10723
