### ISSUE TITLE
CI: test timeout not respected

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3605]
discovered in #3583.
We are prebuiilding and running tests using ``ninja -k 0 tests || true`` but this will ignore the ctest timeout options of 600s for each test. The whole thing will abort after 2.5 hours, but this way you can not tell which test is broken.
We should fix that somehow. Maybe have a shorter timeout for the prebuild so we at least see the hanging tests when we go to the second phase?

**Comment by gassmoeller** [comment]
I see some timeouts in our reference tests at the moment, likely related to #3583. We should make fixing this a priority to have reliable tests during the hackathon (also it slows down our testing at the moment). I will try to take a look tomorrow.

**Comment by tjhei** [comment]
> I see some timeouts in our reference tests at the moment

Is this on branches created before #3607 by any chance? I know that this fixes the deadlocks.

> I will try to take a look tomorrow.

I have an idea on how to address this to have it respect the timeout in the "precompile tests". Do you want to take a look at which of the tests are problematic?

**Comment by tjhei** [comment]
> I see some timeouts in our reference tests at the moment,

Hm, this is not explained by #3618, I think. Maybe the new image is slower with over-subscription of MPI ranks? How many cores do the machines have?

**Comment by gassmoeller** [comment]
Yes I confirmed that the oversubscription is the problem. We have two tests that allocate 7 and 9 MPI ranks respectively, and exceeding the local ranks triggers the timeout inside the test docker image (I increased them to 13 for my 6core/12 threads system). The 9 rank test (vof_mpi_amr_no_dof.prm) is a problem for all CIG testers, the 7 rank test (parallel_refine_crash.prm) only for the older 2core/4thread machines.

Options:
1. Reduce the MPI ranks for the tests. I think both tests are designed to investigate cases where one rank has no dofs, and that is hard to reproduce with lower MPI ranks.
2. Disable the 2core/4thread testers, which would still leave a problem with the 9 MPI rank test, and reduce our test throughput.
3. Enable the oversubscription MPI option for the test image. The only mention for MPICH about this topic I found was that it requires compiling MPICH with a certain flag? That seems weird. I know OpenMPI has a command line option. I think this is the best option as long as it does not increase overall test runtime too much. But most time for tests is spent compiling shared libs, starting models and comparing files, so maybe the influence on the tester time is actually not very big?

**Comment by tjhei** [comment]
mpich requires a compile option:
https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_Why_does_my_MPI_program_run_much_slower_when_I_use_more_processes.3F
This means I would have to build a new docker image from scratch. :-(

Alternatively, switch back to OpenMPI but I switched to mpich because of several issues (running as root, BTL warnings, other weirdness). Again, rebuilding images.

I think we run into over-subscription even with a machine with more than 9 cores as our prebuild step potentially runs many parallel runs at the same time (we might be lucky that this is typically not the case).

Not sure. :-(

**Comment by tjhei** [comment]
Another option would be to switch to the official deal.II docker image temporarily to see if that works. I think we are using OpenMPI there. Worth a try?

**Comment by gassmoeller** [comment]
Just for reference I just found #2919, last year we decided to run the tests on less MPI ranks. I think OpenMPI had the problem that we need to modify the CMake file for the tests to include the `--oversubscribe` option, but that one is specific to OpenMPI (therefore breaking the testsuite for systems with MPICH).
