### ISSUE TITLE
Move documentation generation to cmake

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#3652]
It has bothered me for many years now (I'd say for (n-1) of the n years that we've used cmake) that the documentation generation is driven by `doc/Makefile` and not part of the cmake machinery. What do people think about fixing this wart?

Upsides:
* More systematic
* Keeping the source tree free of the artifacts of running latex, doxygen, etc
* We can actually install the documentation

Downsides:
* When adding new files that need to be processed (specifically, `.prm` fragments), one has to run cmake to pick them up
* Output ends up in the build directory where people may not expect it (yet -- that's an educational question)
* Need to update website generation scripts
* Might require fiddling with the graphics path if compiling `manual.tex` from a different directory (see https://texblog.org/2017/12/05/the-path-to-your-figures/)

Opinions?

**Comment by tjhei** [comment]
That makes sense to me. Would it make sense to do the markdown conversion first?

**Comment by bangerth** [comment]
No longer relevant.
