### ISSUE TITLE
Move cookbooks and their documentation into folders

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3657]
- Like done in #3422, move each cookbook into a folder under ``cookbooks/`` like ``convection-box``
- Move the latex including pictures/etc. from the manual into a doc/ folder 
- Also pay attention to use underscores instead of dashes #3255

**Comment by alarshi** [comment]
I will work on this if noone else has already started it.

**Comment by tjhei** [comment]
> I will work on this if noone else has already started it.

Sure, please start with a single .prm and get it reviewed. After that, it also make sense to work in smaller batches to make it easier to review.

**Comment by jdannberg** [comment]
There's one more thing I noticed: We also have to update the section in the manual that describes how to contribute a cookbook. It should explain the new directory structure, and how to create the symbolic link in the doc/manual/cookbooks folder. 

- [ ] update section in the manual

**Comment by bangerth** [comment]
I believe that this is finished.
