### ISSUE TITLE
Provide recommended dependency versions

### ISSUE THREAD

**Issue by maxrudolph** [geodynamics/aspect#366]
I think that it would be helpful for new users to provide a list of known working versions of ASPECT dependencies including Trilinos, p4est, hdf5, netcdf, and deal.ii. I understand that it's not possible to guarantee success in installing ASPECT on any computer, but it would be nice to know at least one known working configuration, for instance whatever is currently being used on the automated test server.

**Comment by tjhei** [comment]
The recommended versions of libraries (in my opinion) should be the ones I am using for the deal-vm, the automated tester, and the ones used in candi. See here for the list:

https://github.com/tjhei/docker-files/blob/cfa37bd4b3f1904369bf7ddde423fd829a10370b/full-deps/Dockerfile#L38

**Comment by gassmoeller** [comment]
Related to #1818 and #1821. When we advertise candi as default installer, whatever version is used by candi will be the default version. I also added a paragraph to the new install section, therefore this issue can be closed when #1821 is merged.

**Comment by maxrudolph** [comment]
Great! I am really happy with candi as a solution to this problem.
