### ISSUE TITLE
Keep some kind of manifold also for free surface simulations

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#369]
#368 detaches the manifold descriptions for meshes when using free surfaces.

This makes sense in the current framework, but I think there is a better long-term solution: We should, in the free surface handler, somehow keep track of the overall deformation of the mesh -- we compute the incremental deformation as a Q1 or Q2 function, so let's keep track of the sum (total deformation) and then invent a way to use this to create a manifold description based on these cumulative deformations.

@ian-r-rose ?

**Comment by ian-r-rose** [comment]
There are a number of reasons why keeping track of the integrated displacement would be a nice thing to do.  I don't quite see the path to constructing a manifold description from a Q2 or Q1 description at the moment, but this is something I will keep in mind.

**Comment by bangerth** [comment]
I think it should be possible to do this with the `MappingFEField` class in deal.II.

**Comment by ian-r-rose** [comment]
Interesting. Can I get a rundown of how this works sometime in the next few days?

**Comment by bangerth** [comment]
Yes, talk to me. Put it on your list.

**Comment by ian-r-rose** [comment]
This can be closed.

**Comment by jdannberg** [comment]
This was addressed by #1011.
