### ISSUE TITLE
Update 'in preparation' References in manual.bib

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/aspect#3695]
@bangerth 
In reviewing the manual.bib file, I came across 2 references: BAK08 and ABK08 with you as first and second author in which year is indicated as '2008, in preparation'.  Can you update?

**Comment by bangerth** [comment]
I bet there are lots of zombies like those in this file. I believe that we imported manual.bib from the one used for the first aspect paper, which was in turn imported from one I had been using for my publications (in other fields) before and so it contains a lot of entries that have nothing to do with geophysics.

None of these should actually be cited in the manual. Regardless, I'm removing them in #3697.

**Comment by ljhwang** [comment]
Thanks. That actually explains the wide-range of topics that the references contain.
