### ISSUE TITLE
Correct 'Casey and Wesnousky' in manual references.

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/aspect#3696]
In manual.bib, the following entry is woefully incomplete.

  @Article{CW97,
    author =       {\textbf{???} Casey and Wesnousky, S. G.},
    title =        {\textbf{???}},
    journal =      {\textbf{???}},
    year =         1997,
    volume =       {\textbf{???}},
    pages =        {\textbf{???}}

**Comment by bangerth** [comment]
I don't find a use for this -- just remove it.
