### ISSUE TITLE
fix morency/doin cookbook .prm

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#374]
Please extend the cookbook to work again and figure out why it explodes after a couple of time steps.

**Comment by tjhei** [comment]
@jperryhouts ?

**Comment by jperryhouts** [comment]
I remember having trouble exactly reproducing the paper, but the solver at least converged! I'll look in to it.

**Comment by bangerth** [comment]
What's the status of this?

**Comment by jperryhouts** [comment]
This came up during the hackathon, and I think it was fixed in #548

**Comment by bangerth** [comment]
Ah, great, many thanks!
