### ISSUE TITLE
New Xcode 12.0.1 incompatibility on mac OS

### ISSUE THREAD

**Issue by kchotalia** [geodynamics/aspect#3867]
Recent update to xcode (12.0.1) on macOS Catalina prevents compiling of aspect, resulting in the error below. @tjhei @gassmoeller - let me know if more information would be useful.

> bash-3.2$ make
> [  1%] Building CXX object CMakeFiles/aspect.dir/Unity/unity_38_cxx.cxx.o
> error: PCH file uses an older PCH format that is no longer supported
> 1 error generated.
> make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_38_cxx.cxx.o] Error 1
> make[1]: *** [CMakeFiles/aspect.dir/all] Error 2
> make: *** [all] Error 2

**Comment by tjhei** [comment]
Can you please delete your build directory and start over? If things are still broken, post your detailed.log
