### ISSUE TITLE
Solve problem with Newton solver with heat flux boundaries

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#3869]
This is a follow up issue to pull request #3868 (see that pull request for an initial discussion). The same needs to be fixed for the Newton solver, but it would make sense to do this in a way which is a bit more sustainable for future changes to the assembly. 

I don't think it should be too much work to just separate the stokes part and then for the normal and Newton assembles we can then just call `set_default_assemblers`. @tjhei suggested that we can also just set the assemblers and then replace them later. I am not sure how this would work since we push them somewhere in a assembly vector without knowing exactly where. @tjhei could you expand a little bit on that?

**Comment by tjhei** [comment]
As discussed today, it might be easier to just factor out the identical code into a common function that is called in all places.
