### ISSUE TITLE
Possible factor 2 error in elasticity.cc

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#3887]
On line 378 of rheology/elasticity.cc (in function calculate_viscoelastic_strain_rate), should the line 
`const SymmetricTensor<2,dim> edot = 2. * (deviator(strain_rate)) + stress / (shear_modulus * elastic_timestep());`
instead read
`const SymmetricTensor<2,dim> edot = deviator(strain_rate) + 0.5 * stress / (shear_modulus * elastic_timestep());`
?

**Comment by bobmyhill** [comment]
At the moment this function is only used in visco_plastic.cc, which corrects the factor two error on line 319.

**Comment by naliboff** [comment]
@bobmyhill - sorry, just saw this. For some reason I've recently only been getting selected GitHub notifications via email.

Short answer - @dansand and I had multiple discussions about how this should be defined a while, but off the top of my head I can't think of a reason to support one formulation over the other. While your proposed method is indeed consistent with how the strain rate is defined normally in ASPECT, the current formulation matches benchmarks. Let's see how the tests change with #3888 :-)

**Comment by bobmyhill** [comment]
Resolved by #3888 (now merged).
