### ISSUE TITLE
Stop keeping manual.pdf in the git repository

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#395]
The file is generated and too big. It's also a binary, making it really awkward to check into the repository.

We should just remove it from the git repository and only put it into the tarballs. We then need to figure out a way to generate it nightly and put it somewhere so that it can be linked to from the website.

**Comment by tjhei** [comment]
We still need to link it from aspect.dealii.org but I am now generating the manual every night and post it at http://www.math.clemson.edu/~heister/manual.pdf

**Comment by bangerth** [comment]
This seems to be fixed now.
