### ISSUE TITLE
Temperature strategy needs more explanation

### ISSUE THREAD

**Issue by rrgrove6** [geodynamics/aspect#400]
In the "Parameters in section mesh refinement" (believed to be 5.59) of the manual, under parameter name: strategy, there was a request from Shangxin to elaborate the 'temperature' strategy.

Him and I think that it is too brief comapred to the others and could use a little more explanation as to what it does.

**Comment by bangerth** [comment]
Patch would of course be very welcome! The text comes from `source/mesh_refinement/temperature.cc`. There are likely other mesh refinement strategies with similar deficiencies. The text is indeed very short.

**Comment by gassmoeller** [comment]
This was not put forward for a long time. I will close it for now. Feel free to fix it any time.

**Comment by bangerth** [comment]
@Shangxin-Liu 's observation is not wrong -- we should document this better.

**Comment by gassmoeller** [comment]
Thanks for fixing this! I was not implying this issue would be wrong, merely that it was open for 3 years without being important enough to be fixed. We have a number of 'nice to have' issues that have not been addressed for a long time, and they distract from more important bugs. Some github projects have a policy about how to handle 'stale' issues (e.g. close them 6 months after the last comment was made if it is not clear who is working on this), just to keep the list up to date. Maybe we can have a discussion at the hackathon about how we want to handle these cases.

**Comment by bangerth** [comment]
You did entirely the right thing when you close the issue -- nothing was forthcoming. I just thought I should spend a 5-minute hole on something like this.
