### ISSUE TITLE
Bug in particle parallelization

### ISSUE THREAD

**Issue by sac-bsa** [geodynamics/aspect#4028]
@egpuckett and I were working on creating a new particle interpolator, and ran into this error. The error also occurs with the cell average interpolator (although at a diffent timestep), which makes me think that either this vector is not getting safely operated on or that my parameter file is problematic. So far at least we have only encountered this error in 3D.
[The .prm used](https://drive.google.com/file/d/1ZfVVYAClYtLp_L0yk8-Ll9wnVQOMD2hB/view?usp=sharing)
```
--------------------------------------------------------
An error occurred in line <626> of file </mnt/data/Libraries/Ubuntu/dealii-9.2-nopetsc/tmp/unpack/deal.II-v9.2.0/source/lac/trilinos_vector.cc> in function
    void dealii::TrilinosWrappers::MPI::Vector::compress(dealii::VectorOperation::values)
The violated condition was: 
    result.max - result.min < 1e-5
Additional information: 
    Not all processors agree whether the last operation on this vector was an addition or a set operation. This will prevent the compress() operation from succeeding.

Stacktrace:
-----------
#0  /mnt/data/Libraries/Ubuntu/dealii-9.2-nopetsc/deal.II-v9.2.0/lib/libdeal_II.g.so.9.2.0: dealii::TrilinosWrappers::MPI::Vector::compress(dealii::VectorOperation::values)
#1  aspect: dealii::BlockVectorBase<dealii::TrilinosWrappers::MPI::Vector>::compress(dealii::VectorOperation::values)
#2  aspect: aspect::Simulator<3>::interpolate_particle_properties(aspect::Simulator<3>::AdvectionField const&)
#3  aspect: aspect::Simulator<3>::assemble_and_solve_composition(bool, std::vector<double, std::allocator<double> >*)
#4  aspect: aspect::Simulator<3>::solve_single_advection_single_stokes()
#5  aspect: aspect::Simulator<3>::solve_timestep()
#6  aspect: aspect::Simulator<3>::run()
#7  aspect: void run_simulator<3>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
#8  aspect: main
--------------------------------------------------------
```

**Comment by gassmoeller** [comment]
Thanks for reporting! Can you attach a full log file of the run that produced the error? In particular: Does this happen with a recent development version?

**Comment by sac-bsa** [comment]
[screen output.txt](https://github.com/geodynamics/aspect/files/6449984/screen.output.txt)

**Comment by gassmoeller** [comment]
I am currently looking into a different issue, but also encountered this one. I think it is related to having too few particles in a cell. In theory it should trigger other asserts instead of this one, but it seems it is running into this anyway. Could you check if making sure there are enough particles per cell fixes the issue? I will look into it more separately.

**Comment by gassmoeller** [comment]
see #4033.

**Comment by egpuckett** [comment]
Hey @gassmoeller! It works in 3D!  And looks pretty good as well ...

Thanks!
