### ISSUE TITLE
cmake documentation?

### ISSUE THREAD

**Issue by VictorEijkhout** [geodynamics/aspect#4031]
I'm finding installation instructions using `candi` which I gather installs all sorts of stuff I already have. Is there documentation of the cmake installation directly?

**Comment by tjhei** [comment]
Did you see https://github.com/geodynamics/aspect#installation-instructions ?
If you have all dependencies you just need ``cmake . && make install``

**Comment by VictorEijkhout** [comment]
On , 2021May11, at 20:33, Timo Heister ***@***.******@***.***>> wrote:

If you have all dependencies you just need cmake . && make install

If I have multiple trilinos installations and such I’d like to specify which one to load.

Also: what other dependencies are there? I’ve seen mention of p4est. Dealii? Other?

Victor.

**Comment by tjhei** [comment]
The only dependency is deal.II specified using DEAL_II_DIR. Trilinos etc is found through that.

**Comment by naliboff** [comment]
@VictorEijkhout - Is this for installation on Stampede2? I've tried building deal.II using the Intel compilers and existing Trilinos compilers multiple times with no success. 

We have had consistent success using the gcc compilers:

**Comment by VictorEijkhout** [comment]
This is for both stampede2 and frontera.

Victor.

On , 2021May20, at 13:48, naliboff ***@***.******@***.***>> wrote:



@VictorEijkhout<https://github.com/VictorEijkhout> - Is this for installation on Stampede2? I've tried building deal.II using the Intel compilers and existing Trilinos compilers multiple times with no success.

We have had consistent success using the gcc compilers:

**Comment by naliboff** [comment]
@VictorEijkhout - Great, good to know. Please let us know if you have success with intel on Stampede2, it would be great to have that option. I know @tjhei has compiled and tested quite a bit with intel on Frontera.
