### ISSUE TITLE
Surface stress postprocessor gives different results in 3d

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#4056]
For #4054 I added a 3D test with also the surface stress visualization postprocessor, and the stress on some sides of the cube differs in pattern, not just value. It also happens away from the edges of he sides, so it's not some boundary effect. I've attached an input file.

<img width="1440" alt="Screenshot 2021-06-07 at 11 02 46" src="https://user-images.githubusercontent.com/7631624/120993157-9175ed00-c783-11eb-8c41-daa05d26d12b.png">

[stress_vs_surface_stress.txt](https://github.com/geodynamics/aspect/files/6607659/stress_vs_surface_stress.txt)

**Comment by gassmoeller** [comment]
I looked through the code paths for surface and volume visualization and did not see an immediate candidate for why this would be happening. Could you check if this happens also for a property that is not a derivative of the solution? E.g. velocity or temperature itself? The reason I am asking is that derivatives of the solution on the boundaries of the domain are significantly less accurate than inside the domain, which is also the reason why the dynamic topography plugin uses a consistent boundary flux method to compute the stresses instead of calculating the derivative of the solution. Maybe the stress postprocessor needs to do the same? But I first want to make sure that is the reason. Could you share a profile of the stress on the surface that is different? Is the stress 0 for most of the boundary, or is it just small?

**Comment by anne-glerum** [comment]
There doesn't seem to be a difference for velocity and pressure, so your idea could be correct. The stress is smaller, the velocity is the same:
<img width="1440" alt="Screenshot 2021-06-14 at 12 44 56" src="https://user-images.githubusercontent.com/7631624/121880878-d1524c80-cd0e-11eb-9413-f333c45d59b6.png">
<img width="1440" alt="Screenshot 2021-06-14 at 12 46 14" src="https://user-images.githubusercontent.com/7631624/121880894-d6170080-cd0e-11eb-8762-504c52cb6131.png">
<img width="1440" alt="Screenshot 2021-06-14 at 12 47 03" src="https://user-images.githubusercontent.com/7631624/121880899-d6af9700-cd0e-11eb-8c47-8bb615d4a50c.png">

**Comment by anne-glerum** [comment]
Diagonal stress components:
<img width="1440" alt="Screenshot 2021-06-14 at 12 54 45" src="https://user-images.githubusercontent.com/7631624/121881565-bd5b1a80-cd0f-11eb-8693-60a57e79f6a4.png">

**Comment by bangerth** [comment]
As just discussed, switch off the averaging and see whether that still yields a difference.

**Comment by anne-glerum** [comment]
With 
```
set Interpolate output = false
set Write higher order output = false
set Point-wise stress and strain = true
```
the differences persist for several 3d models. 
Same for 
```
set Interpolate output = true
set Write higher order output = true
set Point-wise stress and strain = true
```

**Comment by anne-glerum** [comment]
For example:
<img width="1440" alt="Screenshot 2021-07-12 at 17 25 37" src="https://user-images.githubusercontent.com/7631624/125314312-5e9cb700-e336-11eb-968f-1fa22eadd816.png">
where left is the full mesh and right the surface mesh.
The full mesh outputs a full tensor, while the surface mesh outputs only the independent components of a symmetric tensor. But both are computed as symmetric tensors, so the only difference lies in the unrolling into the `computed_quantities`.

**Comment by bangerth** [comment]
The difference between the stress and surface stress viz postprocessors seems accidental. I seem to have just forgotten to convert the latter in #3703. See #4181 now.

That said, the two pictures you show are radically different :-) They can't be showing the same quantity, right?

**Comment by anne-glerum** [comment]
Yes they are very different. Perhaps my interpretation of the components is not correct. E.g. above I show stress_1 versus stress_xy, they are not the same. Some of the other stress components (e.g. stress_0 and stress_xx) are the same. I'll redo the comparison after #4181 to be sure I'm comparing apples with apples.

**Comment by bangerth** [comment]
Sounds good!

**Comment by gassmoeller** [comment]
The figure looks like one postprocessor is including the pressure, while the other is only computing shear stress. Maybe give that a check.

**Comment by gassmoeller** [comment]
Oh, and I think the unrolled components of a symmetric tensor follow the main diagonal first, so `stress = {stress_xx,stress_yy,stress_xy}` for a 2d symmetric tensor. So you want to compare stress_xy to stress_2.

**Comment by bangerth** [comment]
That makes sense -- and then the diagonal components indeed contain the pressure.

**Comment by anne-glerum** [comment]
I've checked again now that #4181 is merged, and with point-wise values, the output on the surface mesh and the volume mesh is the same 🥳 . I'll close this issue, but I'd like to suggest two small changes:
1. Make the the stress_vs_surface_stress test output point-wise values, so that the output is actually the same (as stated that it should be in the test description: "The two ought to agree on their results at the boundary.")
2. Add a comment to the surface_stress visualization plugin that the results will only be the same as the volume mesh output when point-wise values are outputted.

**Comment by gassmoeller** [comment]
Great to hear, and yes both changes sound very reasonable.

**Comment by bangerth** [comment]
Good news indeed! I'm in favor of both changes, though I would suggest that we *clone*, rather than *replace* the existing test and do what you suggest.
