### ISSUE TITLE
release 2.3.0

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4069]
- [x] send out an email about problems or outstanding patches
- [ ] go through the list of TODOs in the source code and see what can be done
- [ ] make sure the description of the interfaces that need to be updated are up to date in the manual
- [x] update the used deal.II version for the Docker container in docker/Dockerfile and in the manual
- [x] check that README.md and https://aspect.geodynamics.org/ReadMe.html are okay and the links to the mailinglists are working (also in manual.pdf)
- [x] run (and be patient):
    ```
      cd benchmarks && make -f check.mk BUILD=$BUILDDIR -j4
      cd cookbooks && make -f check.mk BUILD=$BUILDDIR -j4
    ```
- [x] determine new version roughly following semantic versioning: http://semver.org/, format is X.Y.Z for a release, X.Y.Z-pre for the dev version or X.Y.Z-rcW for release candidates, backwards incompatible changes require incrementing X, adding features incrementing Y
- setup for tasks below:
    ```
      export OLDVER=2.2.0;export VER=2.3.0;export VERSHORT=2.3;export NEXTVER=2.4.0-pre
      export DEALSRCDIR=/ssd/deal-git/
      export BUILDDIR=`pwd`
    ```
- [x] fix doxygen errors:
    ```
      find include -name "*h" -print | xargs -n 1 $DEALSRCDIR/contrib/utilities/checkdoxygen.py
    ```
    and commit.
- [x] manual, check for missing labels:
    ```
    cd doc
    make manual.pdf
    grep undefined manual/manual.log    # try to remove some
    make aspect.tag # check for warnings
    ```
- [x] fix formatting:
    ```
      find . -name "*.h" -print | while read file;do $DEALSRCDIR/contrib/utilities/wrapcomments.py $file >temp;mv temp $file;done
    ```
    Note: we started ignoring the rewrapping of comments, but we should still fix wrong indentation or other problems
- [x] copyight:
    ```
      ./contrib/release/update_copyright.sh
    ```
- [x] create branch for master PR to update changes.h in doc/modules:
    ```
      git checkout -b post-release-$VER
      cd doc/modules; rm -f changes/*~; ./increment_version.sh $OLDVER $VER;cd ../..
      cd contrib/release;./bump_version.sh $NEXTVER; cd ..
      git commit -m "release task: update version and changes.h"
      # create a PR
    ```
- [x] create a branch, bump version (note, make sure the PR above is included)
    ```
      git checkout post-release-$VER && \
      git checkout -b aspect-$VERSHORT && \
      cd contrib/release && ./bump_version.sh $VER && cd ../.. && \
      git commit -m "release task: update version info"
    ```
  . compile aspect, make sure you have a symlink in the main directory for the next step
    - make sure the WorldBuilder is found! (git submodule init)
- [x] update doc/manual/parameters.tex and documentation:
    ```
      cd doc && ./update_parameters.sh && make manual.pdf && cp manual.pdf manual-$VER.pdf && cd .. && \
      git add doc/manual/parameters.tex && \
      git commit -m "release task: update manual"
    ```
  . Tag an RC:
    ```
      export TAG=$VER-rc1
      cd contrib/release && ./bump_version.sh $TAG && cd ../.. && \
      git commit -m "version $TAG" && \
      git tag -s v$TAG -m "version $TAG"
    ```
  . Tag the release:
    ```
      export TAG=$VER
      cd contrib/release && ./bump_version.sh $TAG && cd ../.. && \
      git commit -m "version $TAG" && \
      git tag -s v$TAG -m "version $TAG"
    ```
  . create a tar file:
    ```
      cd doc && make manual.pdf && cp manual.pdf ../aspect-manual-$TAG.pdf && cd ..
      export PREFIX=aspect-$TAG && rm -rf $PREFIX.tar.gz && \
      git archive --format=tar.gz --prefix=$PREFIX/ HEAD >$PREFIX.tar.gz
    ```
  . final testing by extracting tarball, compiling, and running:
    ```
      tar xf $PREFIX.tar.gz
      cd $PREFIX
      docker run --rm -it -v `pwd`:/home/dealii/aspect \
      	     dealii/dealii:v8.5.0-gcc-mpi-fulldepscandi-debugrelease /bin/bash

      mkdir build; cd build
      cmake -G "Ninja" -D ASPECT_RUN_ALL_TESTS=ON -D \
            ASPECT_PRECOMPILE_HEADERS=ON ~/aspect
      ninja; ctest -j 8 -V
    ```
- [x] make public (branch and tag):
    ```
      git push cig aspect-$VERSHORT
      git push cig v$TAG
    ```
  . sign:
    ```
      gpg --detach-sign --armor aspect-$TAG.tar.gz
      gpg --detach-sign --armor aspect-manual-$TAG.pdf
      sha1sum aspect-$TAG.tar.gz aspect-manual-$TAG.pdf >sha1sum-$TAG.txt
    ```
  . create a release on github, upload .tar.gz and manual-$VER.pdf
- [x] update website (www repo):
    - header.include: add link to changes
    - index.html: add news entry
    - cite.html: change to current version (2x)
- [x] create zenodo release for source code:
    - https://zenodo.org/deposit?page=1&size=20
    - title: ASPECT v2.0.0
    - license: GPL 2
    - check CIG comments: https://github.com/geodynamics/best_practices/blob/master/ZenodoBestPractices.md
    - cig community!
    - update zenodo badge in README.md to newest version (see badge button on the right of zenodo page)
    - add zenodo badge also to the release on github (on top, see 2.0.1 for an example)
    - readme / release notes: add zenodo DOI button
    - manual/manual.bib: add new zenodo entry
- [x] create figshare DOI for manual (just upload a new version as the same entry)
    - update manual/manual.bib entry
  . update doc/manual/manual.bib with src and manual doi
  . update aspect.geodynamics.org/cite.html and citing.html in www repo:
    - add new version in citing.html, search for "<option"
    - doc/make_cite_html.py:
      - add new version, update doc/zenodo dois
    - run aspect/doc/ python3 make_cite_html.py add to www
- [x] update http://geodynamics.org/cig/software/aspect/:
       update current release number
       create entry for the new release
       update the list of contributors
       ...
- [x] update docker image geodynamics/aspect:
    - modify docker/Dockerfile and docker/build.sh to checkout the release
    ```
      cd docker && ./build.sh
      docker push geodynamics/aspect:v$TAG
    ```
- [x] update the spack installation package with the latest tarball, 
    see https://github.com/spack/spack/pull/13830 for an example
- [x] announce on
    ```
       cig-all@geodynamics.org
       https://community.geodynamics.org/c/aspect
       dealii@googlegroups.com
    ```
- [x] celebrate!

**Comment by tjhei** [comment]
I just created https://github.com/geodynamics/aspect/tree/aspect-2.3

@geodynamics/aspect-developers 
1. Please test if everything works.
2. Bring to my attention if there is anything else that is important to have in the release.

**Comment by gassmoeller** [comment]
Awesome, thanks! I went through the list of open issues and PRs.
I would like #4033 to be part of the release, as it fixes error messages for several particle related crashes. And we should try to figure out #4088 as it looks like a genuine bug in the checkpointing system, I can take a look today. Everything else is probably post 2.3 as far as I can see.

**Comment by zjiaqi2018** [comment]
No errors or warnings  were found in both debug and release modes for the following combinations:
dealii-9.2 + aspect-2.3.0-rc1 + Intel 19.1
dealii-9.3 + aspect-2.3.0-rc1 + Clang 10.0.0
dealii-9.3 + aspect-2.3.0-rc1 + gcc (GCC) 8.3.1

**Comment by naliboff** [comment]
No errors on Mac OS X Catalina (10.15) with the deal.II 9.3.0 Mac dmg (clang), but two warnings:
1. warning: unknown warning option '-Wno-psabi' [-Wunknown-warning-option]
2. ld: warning: dylib (inter specific library) was built for newer macOS version (11.0) than being linked (10.15)

The second warning is related to me not using OS X 11 (Big Sur), which the deal.II dmg was built with. I assume this will go away with an upgrade to 11.0.

**Comment by naliboff** [comment]
No errors or warnings on Stampede2 for:
dealii-9.3 + aspect-2.3 + gcc 7.1.0

**Comment by anne-glerum** [comment]
Same warning for the dealii-9.3 image on Mac OS Big Sur (Clang 12.0.0.12000032 on platform Darwin x86_64), otherwise smooth sailing:
`warning: unknown warning option '-Wno-psabi' [-Wunknown-warning-option]`

**Comment by tjhei** [comment]
What is the compiler info in detailed.log from ASPECT? This warning is a bit weird.

**Comment by tjhei** [comment]
This looks like the ASPECT compiler is different than the deal ii one...

**Comment by anne-glerum** [comment]
ASPECT detailed log:
```
CMAKE_CXX_COMPILER:        Clang 12.0.0.12000032 on platform Darwin x86_64
                                  /Applications/deal.II.app/Contents/Resources/spack/opt/spack/openmpi-4.0.5-yh6r/bin/mpic++
```
deal.II detailed log:
```
CMAKE_CXX_COMPILER:     AppleClang 12.0.5.12050022 on platform Darwin x86_64
                               /Applications/deal.II.app/Contents/Resources/spack/opt/spack/openmpi-4.0.5-yh6r/bin/mpic++
```
So different clang versions reported, but from same

**Comment by anne-glerum** [comment]
I've updated XCode to 12.5.1, Apple clang version 12.0.5 (clang-1205.0.22.11), and now ASPECT installs without warnings.

**Comment by tjhei** [comment]
Thank you, Anne. This is what I expected.

I had a conversation with Luca offline and everything is working as intended.

**Comment by tjhei** [comment]
``cd cookbooks; make -f check.mk BUILD=$BUILDDIR crustal_deformation/`` fails with
```
    The iterative Stokes solver did not converge. It reported the                                                   
    following error:  
                  Additional information:                                                                                         
    Iterative method reported convergence failure in step 5000. The                                                 
    residual in the last step was 1.69553e+15.                                                                      
                                                                                                                    
    The required residual for convergence is: 50735275.339261.
    See output-crustal_model_2D/solver_history.txt for convergence
    history.
                                                                                
```

**Comment by tjhei** [comment]
``cd benchmarks; make -f check.mk BUILD=$BUILDDIR advection/`` fails with
```
--------------------------------------------------------
An error occurred in line <444> of file </home/heister/aspect-git/source/simulator/helper_functions.cc> in function
    double aspect::Simulator<dim>::compute_pressure_scaling_factor() const [with int dim = 2]
The violated condition was: 
    out.viscosities[q] > 0
Additional information: 
    The viscosity needs to be a positive quantity.

Stacktrace:
-----------
#0  /home/heister/aspect-git/build64/aspect: aspect::Simulator<2>::compute_pressure_scaling_factor() const
#1  /home/heister/aspect-git/build64/aspect: aspect::Simulator<2>::start_timestep()
#2  /home/heister/aspect-git/build64/aspect: aspect::Simulator<2>::run()
#3  /home/heister/aspect-git/build64/aspect: void run_simulator<2>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
#4  /home/heister/aspect-git/build64/aspect: main
--------------------------------------------------------

```

**Comment by tjhei** [comment]
I need help with the following two remaining tasks:
1. update http://geodynamics.org/cig/software/aspect/:
update current release number
create entry for the new release
update the list of contributors
2. update docker image geodynamics/aspect:

@ljhwang and @gassmoeller can you help?

**Comment by ljhwang** [comment]
The database for building the attribution has just been (manually) updated. Please let me know if there is an error.

**Comment by gassmoeller** [comment]
References look correct, thanks!

So only thing left is the announcement.

**Comment by tjhei** [comment]
Done! :champagne:

**Comment by gassmoeller** [comment]
Awesome, thanks!
