### ISSUE TITLE
Online doxygen documentation is not complete

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#410]
See the list of modules:
http://aspect.dealii.org/doc/doxygen/modules.html

This should contain all of the groups that are defined in `doc/modules/groups.h`, but many of them are missing :-(

**Comment by tjhei** [comment]
both have 7 groups if I count correctly?!

**Comment by bangerth** [comment]
Ah, I confused myself. I though that the material model group should contain the words "material model". That's not the case. Need to fix this.

Also: we use a number of other groups via `@ingroup` statements in the code that apparently lack a `@defgroup` in `groups.h`. Need to fix this too.

**Comment by gassmoeller** [comment]
Is this fixed by #453?
