### ISSUE TITLE
shell_simple_3d cookbook error with opening angle 90

### ISSUE THREAD

**Issue by erinheilman** [geodynamics/aspect#4129]
When running the shell_simple_3d cookbook and adding an opening angle of 90 degrees, the model reaches the first timestep before failing to converge on the temperature residual. The cookbook runs as it should when not using the opening angle, so it may be a geometry issue.
<img width="1320" alt="Screen Shot 2021-07-07 at 12 27 42 PM" src="https://user-images.githubusercontent.com/69014916/124804156-9b744280-df1f-11eb-9fb1-1cee127747b1.png">
<img width="932" alt="Screen Shot 2021-07-07 at 12 28 13 PM" src="https://user-images.githubusercontent.com/69014916/124804202-a4651400-df1f-11eb-934d-f746b9afd0be.png">
[log.txt](https://github.com/geodynamics/aspect/files/6779043/log.txt)
[shell_simple_3d.txt](https://github.com/geodynamics/aspect/files/6779062/shell_simple_3d.txt)

**Comment by anne-glerum** [comment]
Could it be that the model now needs Boundary velocity conditions for the radial boundaries? The cookbook is a full shell right? There are no conditions specified for left and right, which means zero stress, so flow out of the model probably occurs.

**Comment by erinheilman** [comment]
You're right, I just added the radial boundaries to the tangential boundary velocity conditions and it got past that error.
