### ISSUE TITLE
Two stress visualization tests are the same

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#4177]
The tests
`visualization_stress.prm`
and 
`visualization_stress_pointwise.prm`
are actually the same as
`set Point-wise stress and strain = true` is set in both.
Output (only gnuplot) is the same. 
The first test should not output point-wise stress and strain.

**Comment by bangerth** [comment]
Did the default for that parameter change at some point?

**Comment by anne-glerum** [comment]
I don't know, but both tests literally set 
`set Point-wise stress and strain = true` in the prm

**Comment by bangerth** [comment]
Ha, yes, this makes no sense :-)
