### ISSUE TITLE
Error: Negative diffusion viscosity detected;  but only use dislocation in VP material model

### ISSUE THREAD

**Issue by sibiaoliu** [geodynamics/aspect#4193]
I set " Viscous flow law = dislocation" in the material model of Visco Plastic. The model crashes with an error message: 

"The violated condition was: 
    viscosity_diffusion > 0.0
Additional information: 
    Negative diffusion viscosity detected. This is unphysical and should
    not happen. Check for negative parameters."

I think that the diffusion calculation should not be implemented or it is calculated with default values since the 'diffusion viscous flow' option is not enabled. Can anyone give me some advice on the reason behind this error? Has anyone encountered the same problem before? Thanks!

<img width="1191" alt="iShot2021-07-13 13 32 26" src="https://user-images.githubusercontent.com/36626697/125445830-235f1e42-9393-4a80-a4ef-4ba2609f6e31.png">

**Comment by anne-glerum** [comment]
Hi @sibiaoliu, looking at /material_model/rheology/visco_plastic.cc, the diffusion viscosity is still computed (line 150) even if it's not used later on (in the switch starting from line 161).

Did you set the diffusion creep parameters in the input file? The defaults seem ok.

**Comment by sibiaoliu** [comment]
> Hi @sibiaoliu, looking at /material_model/rheology/visco_plastic.cc, the diffusion viscosity is still computed (line 150) even if it's not used later on (in the switch starting from line 161).
> 
> Did you set the diffusion creep parameters in the input file? The defaults seem ok.

Hi Anne, I did not set the diffusion parameters. I thought that the values of the pressure or temperature solutions may cause this error. However, When I check the output, the values look correctly. It is weird.

**Comment by sibiaoliu** [comment]
Find the reason for this issue: the temperature in a few points is negative, which should be wrong.
