### ISSUE TITLE
config.h not found when trying to build shared library from installed version of ASPECT

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#4194]
When trying to build a shared library from an installed version of ASPECT (built with `sudo make install` or `ninja install`), cmake . runs fine, but make yields the following error:

`/usr/local/include/aspect/global.h:25:10: fatal error: aspect/config.h: No such file or directory`
`25 | #include <aspect/config.h>`

This is only a problem with an installed version; there is not a problem when building the shared library against a version of ASPECT built using the standard `cmake .. ; make` formula. Furthermore, the installed version of ASPECT works fine; it's only building shared libraries (such as that in `cookbooks/prescribed_velocity/` that's a problem.

@anne-glerum kindly reproduced the issue on her machine.

**Comment by tjhei** [comment]
I will take a look. We probably forgot installing the file.

**Comment by tjhei** [comment]
#4195 should fix this. I can compile and use a user plugin with this change.
