### ISSUE TITLE
Add Bob and Cedric to the correct sections of AUTHORS.md and README.md

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#4208]
@bobmyhill @cedrict Want to propose patches that add your names to the right sections? :-)

**Comment by cedrict** [comment]
sure, I'll do it :) which brings me to a topic I wanted to bring up: the list of names at the bottom of the manual frontpage is not up to date (eg Paul, Arushi & Agi missing), and contains names who have not contributed in >5 years (geenen, kronbichler, ...).

**Comment by ljhwang** [comment]
This is an interesting question and one that also pertains to how the code is cited.  Is activity a measure or the fact that they have made substantial contributions at some point. With respect to the latter, I have seen removal when the project has substantially drifted from the original instantiation and or the contribution is no longer part of the code base.
So, in essence, I am arguing for their names to be retained.

**Comment by bobmyhill** [comment]
I'd also argue that all names should be retained.
As for the missing developers in the contributions list, we have historically added a name when a user/developer has contributed a section to the manual (rather than adding code to the code base). It was a good driver for me to add something substantial to the manual :D

**Comment by ljhwang** [comment]
But perhaps someone has contributed substantially, and has not contributed to the manual. I can think of a example.

**Comment by cedrict** [comment]
@tjhei @jdannberg @jaustermann @gassmoeller @naliboff @anne-glerum @MFraters  any thoughts on this matter?

**Comment by cedrict** [comment]
I have just surveyed the manual. 4 people are listed as (co-)authors of cookbooks/benchmarks and are not on the front page list: Robey, Rudolf, Richards and Sparks.

**Comment by bangerth** [comment]
If someone contributes to the manual, they are authors, regardless of whether that contribution was recently or further in the past. I think we should only ever add names to the list of people there. I believe that's how the PETSc manual also operates.

As for the missing people: Thanks, @cedrict, for going through the cookbooks! I think we should add them. Would someone be willing to write a patch to this effect?

@ljhwang What other name do you have in mind?

**Comment by ljhwang** [comment]
@bangerth - Conrad

**Comment by cedrict** [comment]
Should I then add these 6 ppl at the bottom of the page ? anybody else ?

**Comment by bobmyhill** [comment]
Closed by #4213 and #4242
