### ISSUE TITLE
Unused function warning when building initial_conditions/interface.cc.o

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#422]
warning: ‘void aspect::{anonymous}::extract_composition_values_at_q_point(const std::vector<std::vector<double> >&, unsigned int, std::vector<double>&)’ defined but not used [-Wunused-function]
     extract_composition_values_at_q_point (const std::vector<std::vector<double> > &composition_values,

**Comment by bangerth** [comment]
Fixed by #429
