### ISSUE TITLE
document shear heating term in the manual

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#424]
There was a derivation in the assembly for the shear heating terms in the energy equation, but this part was removed when introducing the new heating plugin structure. Anyway, it probably should be in the manual rather than in the code. Also, I don't know why we make this simplification...

// add the term 2*eta*(eps - 1/3*(tr eps)1):(eps - 1/3*(tr eps)1)
 //
// we can multiply this out to obtain
//   2*eta*(eps:eps - 1/3*(tr eps)^2)
// and can then use that in the compressible case we have
//   tr eps = div u
//          = -1/rho u . grad rho
// and by the usual approximation we make,
//   tr eps = -1/rho drho/dp u . grad p
//          = -1/rho drho/dp rho (u . g)
//          = - drho/dp (u . g)
//          = - compressibility rho (u . g)
// to yield the final form of the term:
//   2*eta [eps:eps - 1/3 (compressibility * rho * (u.g))^2]

**Comment by bangerth** [comment]
Yea, I don't recall it either. @tjhei : Do you recall?

**Comment by tjhei** [comment]
Nope, I have never seen this before.

**Comment by jdannberg** [comment]
Closed by #498
