### ISSUE TITLE
Remove reference viscosity parameter from material models?

### ISSUE THREAD

**Issue by naliboff** [geodynamics/aspect#4339]
A follow-up question regarding PR #3681, which added a function to automatically compute a reference viscosity at each time step. 

After discussion with @anne-glerum, we are wondering if the reference viscosity parameter should be removed from each material model. @gassmoeller - is there a motivation to keep these parameters in each material for the time being?

**Comment by tjhei** [comment]
I don't think it is used anymore, so we should remove it.

**Comment by gassmoeller** [comment]
Agreed this can be removed. When doing this we will have to check if there are individual plugins that still use it, so the process would be:
1. Only remove it from the interface, but keep the implementation in individual plugins. This will fail for all places that still use the reference viscosity from outside the functions. I am think of composite material models or postprocessors that may still call the function. During this step we need to test benchmarks and cookbooks as well.
2. Remove it from all plugins. This step is optional, if there are some plugins that make use of the reference viscosity function for internal purposes, we can also keep the function in those plugins.

**Comment by jdannberg** [comment]
This was addressed by #4722 and #4733.
