### ISSUE TITLE
incorrect transformation of cartesian to spherical coordinates 

### ISSUE THREAD

**Issue by elodie-kendall** [geodynamics/aspect#4368]
I was wanting to analyze spherical velocity components in my models but I realised that v_r and v_phi that are outptted for visualisation are not the same as when computed directly in paraview e.g., v_phi=((-coordsY/sqrt(coordsX^2 + coordsY^2))*velocity_X)+ ((coordsX/sqrt(coordsX^2 + coordsY^2))*velocity_Y). This is the same equation as in source/postprocess/visualization/spherical_velocity_components.cc but it is written in terms of theta not X,Y. So I realised the problem is theta. You can see in line 534 of source/utilities.cc that scoord (theta) is not computed correctly (we should not add 2PI if theta is negative). I attach the example I ran for the test "viz_spherical_velocity_components.prm". Would you like me to fix this?
  

<img width="1162" alt="Screen Shot 2021-09-27 at 18 06 20" src="https://user-images.githubusercontent.com/75854106/134944844-da6aa02e-1c06-44ef-9a55-0abaddf5cea8.png">

**Comment by gassmoeller** [comment]
Fixed in #4385
