### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4380]
There are a few known issues with the current master version of ASPECT. If you have any questions about this, feel free to comment here or in the respective issues:
 - checkpointing/resume with large files (>4GB) fail, see #4349. Workaround: use deal.II 9.3.2 or newer
 - rand_seed() always returns the same value (#5114)
- crashes related to periodic boundaries and adaptive refinement (#3262 https://github.com/dealii/dealii/pull/10604 ). No known workaround
- system error crashes with the deal.II development version on some machines, see #4040. Workaround: use ``DEAL_II_NUM_THREADS=1``
- large vtu files fail to write with Intel MPI, see https://github.com/geodynamics/aspect/issues/4037#issuecomment-970717298
- an installation of ASPECT version 2.3 (``make install`` or using spack) can not be used to compile plugins, see #4498. Build ASPECT manually and/or switch to the development version.
- If you encounter linking issues of ASPECT or deal.II (especially with Intel compilers, seen on TACC Stampede2 and Frontera) in the form "bad symbol offset", please specify ``-D DEAL_II_LINKER_FLAGS='-fuse-ld=bfd'`` as deal.II option.

**Comment by bangerth** [comment]
Would the wiki be a better place to document these sorts of things?

**Comment by tjhei** [comment]
I prefer this as it is much more visible.

**Comment by tjhei** [comment]
updated to include #4040 and updated checkpointing workaround from 10.0 to 9.3.2.

**Comment by tjhei** [comment]
added issues with ld.gold linker above, @naliboff

**Comment by bangerth** [comment]
Let me close this issue. It currently really only points to one open issue, but we haven't kept this issue here up to date. I think a better scheme would be to use labels on issues to indicate important bugs or issues.
