### ISSUE TITLE
Cookbook shell_simple_2d stops during time step 47

### ISSUE THREAD

**Issue by rclam** [geodynamics/aspect#4392]
After cloning the source code to both my local and remote drives, I attempted to run a trial using the shell_simple_2d.prm in cookbooks. Both times I ran the program, it terminated at time step 47 (see attached screenshot of terminal output). The output from ASPECT suggested to change the number of iterations, but I haven't tried that yet
<img width="1467" alt="Screen Shot 2021-10-31 at 6 48 35 PM" src="https://user-images.githubusercontent.com/75513951/139720291-6cf8836f-23ef-4550-b43d-3e618bbfc941.png">
.

**Comment by gassmoeller** [comment]
Hi @rclam, thanks for reporting this. I just tried the cookbook on my system and it continues after step 47. Can you attach the files `log.txt` and `original.prm` from the output directory? Maybe it is a problem with the specific combination of deal.II and ASPECT version you used. It looks like you are using the deal.II .dmg package for Mac?

**Comment by rclam** [comment]
I'm attaching the original prm as a text file (it wouldn't let me upload it as a .prm file). Yes, I am using dealii for Mac.

[log.txt](https://github.com/geodynamics/aspect/files/7456862/log.txt
[original_prm.txt](https://github.com/geodynamics/aspect/files/7456869/original_prm.txt)
)

**Comment by rclam** [comment]
If it helps to know, I am using a Docker Image and using the dealii library it had in it. I was following the latest user manual instructions.

**Comment by rclam** [comment]
After editing the original .prm file by adding:

```
subsection Solver parameters
  subsection Stokes solver parameters
    set Maximum number of expensive Stokes solver steps = 10000
  end
end
```

The solver is able to continue past time step 47

**Comment by gassmoeller** [comment]
Thanks for following up. I havent gotten to testing this yet, but another option could be to set the following option in `Stokes solver parameters`:
```
set Use full A block as preconditioner = true
```
This typically results in better convergence in less iterations (but each iteration is more costly). Could you report back if this helps? Maybe we should just set this option for the cookbook.

**Comment by rclam** [comment]
When I use only 
`set Use full A block as preconditioner = true
`
in the Stokes solver parameters, the solver aborts at time step 47. 

Using both: 
` 
   set Maximum number of expensive Stokes solver steps = 10000`
and
  `  set Use full A block as preconditioner = true`
the solver is able to continue until timestep 241

**Comment by gassmoeller** [comment]
Thanks for testing, I tried reproducing your crash with my version of ASPECT 2.3.0 and deal.II 9.2.0 but was unsuccessful, the model runs fine for me (logfile attached, I also tried debug mode, same result). I did not have a version with the same trilinos and p4est available, so it could be caused by one of those libraries, or it is something specific to the deal.II 9.2 MacOS image. I think your best bet is to try the deal.II 9.3 release .dmg image for Mac (https://github.com/dealii/dealii/releases) unless you are limited to using 9.2 because of some of your own modifications.

[log.txt](https://github.com/geodynamics/aspect/files/7571388/log.txt)

**Comment by tjhei** [comment]
@rclam Did you check the graphical output of the solution variables to see if you see artifacts or over/undershoots especially in the temperature right before it crashes? You might need to set ``set Time between graphical output = 0`` to get graphical output after every step.
