### ISSUE TITLE
Wrong assert throw for radiogenic heating

### ISSUE THREAD

**Issue by elodie-kendall** [geodynamics/aspect#4412]
Hello,

I get the attached assert throw for the radiogenic heat section attached. I have no compositional fields and I have specified I want radiogenic heating to be dependent on depth not composition. So this assert throw should only be evaluated if the crust is defined by compostion.

<img width="2000" alt="2" src="https://user-images.githubusercontent.com/75854106/142617286-42beea50-d5e2-4bc0-800b-94acd7c5c65b.png">

<img width="625" alt="1" src="https://user-images.githubusercontent.com/75854106/142617296-da862d8b-68e2-4b90-8990-3b827c1d05d9.png">

**Comment by gassmoeller** [comment]
Was this fixed by #4446?

**Comment by elodie-kendall** [comment]
Yes! :)
