### ISSUE TITLE
Maximum viscosity in the visco_plastic module

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#4417]
Currently, the Maximum viscosity is set as a fixed value in the visco_plastic module. As we have options for phases with lots of the other parameters, I want to make this one as well as the "Minimum viscosity" also having options for phases. One specific reason is we tend to model the shear zone in the subduction modeling by including either as a composition or a phase and setting a smaller maximum viscosity on it. It would be helpful to also have this feature here.
I believe I can open a small pull request and get this done, would you be willing to see this done and give a kindly review? @gassmoeller

**Comment by anne-glerum** [comment]
@lhy11009 Thanks for being willing to make a pull request for this feature. I don't fully understand the need for setting smaller maximum viscosity for the subduction channel/weak zone though. What kind of rheology do you use for the weak zone? Can't you reduce it through the other parameters, i.e. the yield stress or the prefactor?

**Comment by bobmyhill** [comment]
To add a little background to @anne-glerum's comment, parameters like minimum strain rate and maximum viscosity are typically there to improve numerical stability, rather than simulate some aspect of the material properties.

**Comment by lhy11009** [comment]
Hi Anne and Bob

Thanks for your replies. I think for the 'rheology' question, there are many possible ways to make a weak zone, but the new feature that I asked for may while being part of it. I can give some examples:
a. In Arredondo & Billen 2017, they wrote "the crustal layer (which is tracked with particles) is defined to be a low-viscosity layer with a fixed maximum viscosity (1020 to 1021 Pa s). "
So here, they use the same composite rheology for the rest of the model on the crust. However, the maximum is different, so a weak zone could be the result.
b. In Holt & Condit 2021, they wrote this paragraph:
![Selection_566](https://user-images.githubusercontent.com/28665365/143486625-a10cea6f-a67b-44d1-a3e2-f57ccfac5a63.png)
So here, what they did actually fit Anne's suggestion, that they reduce it through the other parameters, namely the prefactor. But notice that they need to apply a "minimum viscosity" on their crust as well.
To bob's question, I think this feature would be backward compatible, and won't change the use of it otherwise. The purpose is only to adjust the flexibility for shear zone in a 2-D subduction model.

**Comment by anne-glerum** [comment]
@lhy11009 Okay, I understand the use-cases. I'd make sure to add comments to the changed max/min viscosity parameter descriptions to explain that generally the viscosity limits are used to ensure solver convergence, but they can be used to limit viscosities of specific compositions for other purposes as well, even though other parameters like prefactors, the maximum yield stress etc can be used to tune/limit viscosities. What do you think @bobmyhill ?

**Comment by bobmyhill** [comment]
@lhy11009 thanks for explaining! I can certainly understand the motivation behind a lithology-dependent lower limit.
@anne-glerum I think that's a great idea. I will be happy to (co)review a backwards-compatible PR with such comments.

**Comment by lhy11009** [comment]
@anne-glerum , @bobmyhill, thanks for the feedback. I'll make sure that I explain this feature in comments when I work on the pull request. In that way, I'll close this issue and start the pull request. I think I'll get this done next week and ask both of you for review.
