### ISSUE TITLE
solver types

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#445]
The naming and implementation of the various solver schemes is somewhat inconsistent:
- "Stokes only" should have been called "iterated Stokes, no advection"
- there should be a "Stokes, no advection"
- "iterated Stokes" should have been called "iterated Stokes, single advection"

etc.

How do we change this in a backwards compatible way?

**Comment by bangerth** [comment]
Multiple names in the input file can map to the same element of the enum that chooses the solver type. The only trouble you get is if you want to change the meaning of a name such as "Stokes only". I think it should be possible to avoid the latter situation.

**Comment by gassmoeller** [comment]
related to #1279 and #1969

**Comment by gassmoeller** [comment]
Closed by #2162
