### ISSUE TITLE
Run aspect even if test/testname directory is empty

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#449]
If you set up a test/testname.prm and a test/testname/ directory, you don't know yet what to put into the latter because you may not yet have a probably correct output. The problem is that if test/testname/ is empty, aspect is not run (because there is nothing to compare, so the test/testname makefile target has no dependencies and is not run). The target still succeeds.

This is awkward because one can't bootstrap. We should change this to ensure that even if there are no saved output files to compare against, we still run aspect so that we can get an initial population of input files.

**Comment by bangerth** [comment]
...output files.

**Comment by tjhei** [comment]
I am happy to look at this (ctest stuff is still in short term memory).

**Comment by bangerth** [comment]
Fixed by #519
