### ISSUE TITLE
Limit the growth of the time step size

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#4496]
@tjhei dug up a masters thesis at https://dc.uwm.edu/cgi/viewcontent.cgi?article=1405&context=etd that is about time step choices for BDF2. Among the conclusions there is that one should not let the time step size grow by too much from one time step to another. They call this grow the "amplification factor", and reference a number of papers that apparently show that it should not grow by more than either a factor of 1+sqrt(2) or 1.86 or 1.91 (pages 15 and 16), depending on who you trust. We should probably incorporate a limit in our code base to that end as well.

**Comment by tjhei** [comment]
We can basically just change the default of 
https://github.com/geodynamics/aspect/blob/edad8df4dacd0d43afbd8d57e0914d683630cea4/source/simulator/parameters.cc#L170-L179
