### ISSUE TITLE
Evaluate min/max refinement level function at the center of a cell.

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#4521]
In #4507, we figured out that one awkward spot in the min/max refinement level scheme is that we look at the min/max function at the *vertices* of cells, but that that is of course not unique across a cell: the function might have different values for different vertices, in particular in view of round-off deciding whether a particular vertex is on one side of a line or another.

We should instead be looking at the center of the cell.

**Comment by anne-glerum** [comment]
Fixed by #4523.
