### ISSUE TITLE
make_pressure_rhs_compatible needs to consider the interpolated, not the exact normal velocity

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#455]
The current version of the function considers the compatibility condition that
```
  \sum G_i = \int_{partial Omega} u . n
```
where the right hand side is computed from the *exact* boundary values. But this is not what we can match -- the thing that matters is the values that we can discretely reproduce, i.e., we should choose
```
  \sum G_i = \int_{partial Omega} u_h . n
```
where `u_h`  on `partial Omega` are the *interpolated* known boundary conditions, not the exact ones.

This seems to always have worked because in all cases that we have considered, the exact boundary values happened to lie in the finite element space's trace space. It should be easy enough to create a test where this is not the case.

**Comment by jdannberg** [comment]
As we do not use the interpolated velocities any more ( #458 ), this should not be a problem. #458 also included a test case that demonstrated this.
