### ISSUE TITLE
Description of peierls rheology in the user manual

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#4555]
Hi all

This is an open quesiton. I am just wondering how you find the description of the Peierls rheology in the user manual? 

Personally, I think everything is covered but the context might be confusing. For example, we have different implementation "exact" and "viscosity approximation", as well as things like "Peierls fitting parameters", "Peierls strain rate residual tolerance", "Cutoff stresses for Peierls creep", etc. Maybe it's also I am not very familiar with the manual, but I think these components are not straightforward when one thinks of the peierls rheology, let alone some of them are only used in one specific implementation.

So I want to learn what you think of the description. As I am running tests on different schemes of the peierls creep, I might be able to address some of your comments plus my own in the manual.

**Comment by bobmyhill** [comment]
Did the manual answer your questions in the end? If you think improvements can be made to the docs, let us know what your questions are and we'll make some changes.

Peierls is a gnarly flow law, and we've made various tweaks to improve efficiency and stop unphysical behaviour.

**Comment by lhy11009** [comment]
Hi Bob, thanks for your reply. I closed this issue since I found a more practical one to ask, but didn't have time to organize it yesterday evening. So I am testing the "exact" implementation of the Peierls with the set of parameters taken from Idrissi. I know Daniel Douglas has tested it in his model, so it's feasible. But I am stuck with adjusting the "Peierls strain rate residual tolerance" parameter, where the "exact" implementation doesn't converge.

`----------------------------------------------------
Exception 'ExcMessage("No convergence has been reached in the loop that determines " "the Peierls creep viscosity. Aborting! " "Residual is " + Utilities::to_string(strain_rate_residual) + " after " + Utilities::to_string(stress_iteration) + " iterations. " "You can increase the number of iterations by adapting the " "parameter 'Maximum Peierls strain rate iterations'.")' on rank 0 on processing: 

--------------------------------------------------------
An error occurred in line <230> of file </home/lochy/Softwares/aspect/source/material_model/rheology/peierls_creep.cc> in function
    double aspect::MaterialModel::Rheology::PeierlsCreep<dim>::compute_exact_viscosity(double, double, double, unsigned int, const std::vector<double, std::allocator<double> >&, const std::vector<unsigned int>&) const [with int dim = 2]
The violated condition was: 
    !abort_newton_iteration
Additional information: 
    No convergence has been reached in the loop that determines the
    Peierls creep viscosity. Aborting! Residual is -nan after 9
    iterations. You can increase the number of iterations by adapting the
    parameter 'Maximum Peierls strain rate iterations'.
--------------------------------------------------------

Aborting!
----------------------------------------------------`
