### ISSUE TITLE
Does make_pressure_rhs_compatible sense at all?

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#456]
It seems to us (@tjhei, @jdannberg, myself) that when you go through `distribute_local_to_global` with nonzero velocity boundary conditions, that one does a Gaussian elimination step that already shoves the boundary values onto the right hand side vector. We currently make the rhs compatible by requiring that
```
\sum G_i = \int_{partial Omega} u . n
``` 
where `G_i` are the elements of the right hand side vector. (But see also #455 .) This assumes that the `G_i` are the elements of the right hand side vector not caring about boundary values. But after `distribute_local_to_global`, it seems to us that the right hand side vector we get *already* contains the boundary values, and that the correct compatibility condition should be
```
\sum G_i = 0
``` 
regardless of what the flux over the boundary is (because that flux should already be part of `G`).

Someone should try this out once...

**Comment by jdannberg** [comment]
Closed by #458.
