### ISSUE TITLE
Documentation: Problems with section on Arbitrary Lagrangian-Eulerian implementation

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/aspect#4653]
We noticed multiple issues with the page in the documentation for Arbitrary Lagrangian-Eulerian implementation:

https://aspect-documentation.readthedocs.io/en/latest/user/methods/freesurface/arbitrary-le-implementation.html

1. The header repeats. This has brought up the issue of what the proper header levels should be throughout the document as level 1 etc headers look like they are used inconsistently and the next header used is level 4.
2. The page is incomplete. Text and equations are missing from the bottom of the page (in comparison to the pdf).
3.

**Comment by MFraters** [comment]
https://github.com/geodynamics/aspect/pull/4663 stated that that pull request fixed this issue, so I will close it.
