### ISSUE TITLE
xargs warnings during indent

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#4657]
I get the following warnings when running `make indent`:

xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
git dixargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value

**Comment by bangerth** [comment]
Same issue as here: https://github.com/dealii/dealii/issues/13089 . I suspect the solution from https://github.com/dealii/dealii/pull/13093 will work here as well, but maybe wait till #4575 is merged.

**Comment by bangerth** [comment]
#4575 is now merged. This could be a nice small project for someone :-)
