### ISSUE TITLE
MaterialModelInputs::reinit vs Simulator::compute_material_model_input_values

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4712]
https://github.com/geodynamics/aspect/blob/e4c2d6204fdbcb3b1d47da81316a30150bcfb09b/source/simulator/assembly.cc#L55-L60

https://github.com/geodynamics/aspect/blob/e4c2d6204fdbcb3b1d47da81316a30150bcfb09b/source/material_model/interface.cc#L356-L360

On first glance they look identical to me.

**Comment by tjhei** [comment]
@jdannberg or @gassmoeller ?

**Comment by gassmoeller** [comment]
Looks identical to me. We probably introduced MaterialModelInputs<dim>::reinit long after compute_material_model_input_values was created and forgot it existed. I would vote for removing `compute_material_model_input_values` and replacing it with a call to `MaterialModelInputs<dim>::reinit`. @jdannberg mentioned she can do that later today.

**Comment by bangerth** [comment]
On it.

**Comment by bangerth** [comment]
There is this completely bizarre place where we call *both functions* here: https://github.com/geodynamics/aspect/blob/main/source/simulator/stokes_matrix_free.cc#L1859-L1868
```
                  face_material_inputs.reinit(fe_face_values,
                                              simulator_cell,
                                              sim.introspection,
                                              sim.solution);

                  sim.compute_material_model_input_values(sim.solution,
                                                          fe_face_values,
                                                          simulator_cell,
                                                          false,
                                                          face_material_inputs);
```
One can only wonder what the author might have thought here :-)

There is, however, a fairly good question what the goal here is. The first call uses `compute_strainrate=true`, the second one uses `false`. So strictly speaking, we are filling the strain rate field in the first call and then reset it to the empty array in the second call. I assume that the latter is intended.
