### ISSUE TITLE
[CI] Github runner artifacts are overwritten

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4897]
It looks like we no longer have the .diff files for updating test results since we switched to the new matrix testing in #4878. I assume this is because the files get overwritten.

Example: https://github.com/geodynamics/aspect/actions/runs/2647098191

@gassmoeller We should make the artifact upload conditional on test comparison. Do you have time to look into that?

**Comment by gassmoeller** [comment]
See #4911.
