### ISSUE TITLE
missing aspect tutorial link

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4898]
Our readme and the website links to
https://geodynamics.org/cig/events/calendar/2016-cig-all-hands-meeting/aspect-tutorial/tutorial/

which no longer exists.

**Comment by gassmoeller** [comment]
These files are now available at https://geodynamics.org/projects/aspect/notes/Tutorials, but unfortunately this link is only available when you are logged in to the new CIG site and a member of the ASPECT project so a global link is less useful. What should be we do about this? For the moment a legacy version is available, but this will go away eventually: https://wiki.archive.geodynamics.org/software:aspect:start#cig16_aspect_tutorial

**Comment by tjhei** [comment]
I would suggest we link to a wiki page here for learning resources and then we can adjust links as needed.

**Comment by tjhei** [comment]
@ljhwang suggested to use https://geodynamics.org/courses/ASPECT/CIG16 ?

**Comment by gassmoeller** [comment]
Oh, that is better yes. Maybe link directly to https://geodynamics.org/courses/ASPECT/CIG16/outline, which already has links to all the individual videos (your link above looks empty, because the course has no description for me).

**Comment by tjhei** [comment]
See https://github.com/geodynamics/aspect/wiki/Tutorial-Materials (placeholder for now)
