### ISSUE TITLE
Solve for temperature diffusion only.

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#4949]
Hi all. 
I'd like to start a model by only solving the temperature diffusion for 1Ma, without advection. Which is the solver scheme to use? I want to use the "Nonlinear solver scheme" with "no advection", but the description in the manual doesn't tell me if temperature diffusion is solved. Moreover, I see this PR by https://github.com/geodynamics/aspect/pull/4530 by @jdannberg. Does this work with the temperature imported from the World Builder? Looking forward to hearing back on this question.

**Comment by anne-glerum** [comment]
Hi @lhy11009 , would the scheme `single Advection, no Stokes` work for you? Here you have to provide a velocity field (which you can set to zero) and then only the temperature and composition equations are solved. If the velocity field is zero, this would mean (if no other heating terms are included) that only temperature diffusion is solved for.

**Comment by lhy11009** [comment]
Hi Anne. That's a solution, I'll bear that in mind for similar situations in the future. On the other hand, I have worked out the issue I have by adding diffusion in my temperature profile. Thanks anyway.
