### ISSUE TITLE
switch to Tpetra

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4989]
Also see https://github.com/dealii/dealii/issues/14368

We should try how easy is it to (conditionally, if enabled in deal.II) switch to Tpetra instead of Epetra. This should be easy to do as we have the vector/matrix/etc. types in a central location:
https://github.com/geodynamics/aspect/blob/029548bd742d75a4de27e124f2983adfe54fb58a/include/aspect/global.h#L223

If this works without difficulties and the performance is similar, we can switch to Tpetra if detected (``#ifdef DEAL_II_TRILINOS_WITH_TPETRA``).

@zjiaqi2018 Can you give this a try?

**Comment by zjiaqi2018** [comment]
I added Tpetra, but some functions are not implemented in `LinearAlgebra::TpetraWrappers::Vector< Number > Class`, for example  `
void  reinit (const IndexSet &locally_owned_entries, 
                  const IndexSet &ghost_entries, 
                  const MPI_Comm &communicator=MPI_COMM_WORLD, 
                  const bool vector_writable=false)`




```
#ifdef DEAL_II_TRILINOS_WITH_TPETRA
    using Vector = dealii::LinearAlgebra::TpetraWrappers::Vector<double>;
#else
    using Vector = dealii::TrilinosWrappers::MPI::Vector;
#endif
```

**Comment by tjhei** [comment]
I would suggest we make it work with deal.II master first (before worrying about backwards compatibility). We can always keep using Epetra with 9.3 and 9.4. This way we can just add missing functions to deal.II itself.
@zjiaqi2018 Can you look into this function first? We will probably need some ifdefs around PreconditionML, but everything else should work.

**Comment by bangerth** [comment]
I think we need to wait until @masterleinad has converted the deal.II `master` branch for us. I don't think that we should try to replicate this work in ASPECT.
