### ISSUE TITLE
Install Trilions on Macbook pro with ARM m1

### ISSUE THREAD

**Issue by HanyMKhalil** [geodynamics/aspect#4991]
Hi all I followed the instructions to install deal.II and every thing went well I was able to install using the packages:
./candi.sh -j 8 --packages="hdf5 p4est dealii" successfuly
however when I try to install trilions using the line:
./candi.sh -j 8 --packages="trilinos"

I got this error:
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stratimikos/adapters/belos/src/libstratimikosbelos.13.2.dylib] Error 1
make[1]: *** [packages/stratimikos/adapters/belos/src/CMakeFiles/stratimikosbelos.dir/all] Error 2
make: *** [all] Error 2
Failure with exit status: 2
Exit message: There was a problem building trilinos 13-2-0.
Hanys-MacBook-Pro:candi hanykhalil$

**Comment by tjhei** [comment]
Can you try ``git checkout v9.4.0-r2`` and then run ``candi.sh`` with the same options again? I wonder if I broke the MacOS build with the Trilinos update.

**Comment by tjhei** [comment]
I am keeping track of the issue here: https://github.com/geodynamics/aspect/issues/4991

**Comment by HanyMKhalil** [comment]
Hi Timo, it works 
,
Thanks so much, now after I installed all the libraries how can I proceed to install ASPECT?

To export environment variables for all installed libraries execute:

    source /Users/hanykhalil/dealii-candi/configuration/enable.sh


Build finished in 33 seconds.

Summary of timings:

trilinos: 31 s
Hanys-MacBook-Pro:candi hanykhalil$

**Comment by tjhei** [comment]
Now you can follow the normal installation instructions, see https://aspect-documentation.readthedocs.io/en/latest/user/install/local-installation/obtaining.html

**Comment by HanyMKhalil** [comment]
Hi Timo,
I followed the instructions and installed ASPECT but I cannot access it, I went inside to create CMAke as follow:

Hanys-MacBook-Pro:debug hanykhalil$ ls
CMakeCache.txt	CMakeFiles
Hanys-MacBook-Pro:debug hanykhalil$ cmake .... -DDEAL_II_DIR=/Users/hanykhalil/dealii-candi/deal.II-v9.4.0 
CMake Error: The source directory "/Users/hanykhalil/candi/aspect/debug/...." does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Hanys-MacBook-Pro:debug hanykhalil$ 

How is that possible I created the directory and it is valid, here is access to all my files:

Hanys-MacBook-Pro:~ hanykhalil$ cd dealii-candi
Hanys-MacBook-Pro:dealii-candi hanykhalil$ ls
configuration			p4est-2.3.2
deal.II-v9.4.0			tmp
hdf5-1.10.8			trilinos-release-12-18-1
Hanys-MacBook-Pro:dealii-candi hanykhalil$ cd ..
Hanys-MacBook-Pro:~ hanykhalil$ ls
Applications				Pictures
Creative Cloud Files			Public
Desktop					candi
Documents				dealii-candi
Downloads				opt
Dropbox					test_RedSea_model3_vertical.ipynb
Library					underworld2
Movies					uw2_virtualenv
Music
Hanys-MacBook-Pro:~ hanykhalil$ cd candi
Hanys-MacBook-Pro:candi hanykhalil$ ls
AUTHORS			VERSION			candi.cfg
LICENSE			aspect			candi.sh
README.md		candi			deal.II-toolchain
Hanys-MacBook-Pro:candi hanykhalil$ cd aspect
Hanys-MacBook-Pro:aspect hanykhalil$ ls
AUTHORS.md		README.md		doc
CITATION		VERSION			include
CMakeFiles		benchmarks		prmfiles
CMakeLists.txt		cmake			release
CODE_OF_CONDUCT.md	contrib			source
CONTRIBUTING.md		cookbooks		tests
Jenkinsfile		data			unit_tests
LICENSE			debug
Hanys-MacBook-Pro:aspect hanykhalil$ cd debug
Hanys-MacBook-Pro:debug hanykhalil$ ls
CMakeCache.txt	CMakeFiles
Hanys-MacBook-Pro:debug hanykhalil$

**Comment by tjhei** [comment]
> cmake ....

This doesn't look right. Try following the instructions from the ASPECT documentation. You also don't need to set the DEAL_II_DIR if you ``source /Users/hanykhalil/dealii-candi/configuration.enable.sh``.

**Comment by bobmyhill** [comment]
@HanyMKhalil, did @tjhei's suggestions work for you? 
If so, we can close this issue.

**Comment by HanyMKhalil** [comment]
Dear Bob,
I think we can close the issue I still do the steps as I was busy last days, it seems working but if further thing happens I can reopen the issue no worries 

Thanks so much
Hany
