### ISSUE TITLE
ASPECT 3: Remove deprecated code blocks, fix and document breaking changes

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/aspect#5026]
The ASPECT 3.0 release will be an opportunity to break backwards compatibility. 
This should ideally just involve dealing with code blocks commented with `TODO ASPECT_3` and documenting each breaking change, with the usually guidance / scripts to update prm files. Some tests may also need to be updated / removed.

Related PRs:
- #5023

**Comment by gassmoeller** [comment]
All the deprecated functionality that can be removed has been removed. Everything still in the code will have to wait for one of the next releases.
