### ISSUE TITLE
Impossible to run aspect on M1 Pro with MacOs Ventura

### ISSUE THREAD

**Issue by Francyrad** [geodynamics/aspect#5036]
Dear Users
I installed aspect with MacOS 12, i could run tests.

Now that i installed MacOs Ventura (13), i can't run the exe anymore:
<img width="1701" alt="Screenshot 2023-01-23 alle 18 34 05" src="https://user-images.githubusercontent.com/51544149/214109264-e9889bc4-aec6-4758-8301-423172d99fe8.png">

This is not related only to aspect, i could not run another simulator with a very similar message error. I tried to update homebrew, but nothing. 
Can you help me to solve? Am i missing something? Thanks in advance

**Comment by bobmyhill** [comment]
The system update also updated some libraries. ASPECT goes looking for the old ones and can't find them, so it can't run.

I recommend reinstalling ASPECT (and probably deal.II and its dependencies beforehand).

**Comment by tjhei** [comment]
Agreed. Make sure you delete all temporary files before reinstalling. Note that the error message above mentions libgmsh, but you will not need gmsh for ASPECT.
