### ISSUE TITLE
Issue on page /user/cookbooks/cookbooks/composition_passive_particles/doc/composition_passive_particles.html

### ISSUE THREAD

**Issue by ryanstoner1** [geodynamics/aspect#5046]
Some code blocks in the "particles" section of the documentation are empty.

**Comment by gassmoeller** [comment]
Thanks for the report that must have been lost during the conversion. Someone will take a look.

**Comment by ljhwang** [comment]
I found 11 places that need to be updated. See attachment
[prmfile_updates.txt](https://github.com/geodynamics/aspect/files/10591120/prmfile_updates.txt)
