### ISSUE TITLE
Error when make the manual.pdf

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#5123]
I am starting a  new cookbook and I tried to compile the manual.pdf under the doc folder by:
`make manual.pdf` 
and the error shows:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex)
   \write18 enabled.
  entering extended mode
  This is BibTeX, Version 0.99d (TeX Live 2020/Debian)
  The top-level auxiliary file: manual.aux
  I couldn't open style file abbrvurl.bst
  ---line 4836 of file manual.aux
   : \bibstyle{abbrvurl
   :                   }
  I'm skipping whatever remains of this command
  I found no style file---while reading file manual.aux
  (There were 2 error messages)

  
      Error: There were errors compiling manual.tex.
             Check manual/manual.log for details
  
  make: *** [Makefile:94: manual.pdf] Error 1
```

The  manual/manual.log says:

```
  ! LaTeX Error: File `subfigure.sty' not found.
  
  Type X to quit or <RETURN> to proceed,
  or enter new name. (Default extension: sty)
  
  Enter file name: 
  ! Emergency stop.
  <read *> 
           
  l.9 \usepackage
                 {textpos}^^M
  *** (cannot \read from terminal in nonstop modes)
```

As I just start a new branch and haven't done any change yet, I am not sure why this  `subfigure.sty' file is missing. Does anyone have a lead?

**Comment by gassmoeller** [comment]
`make manual.pdf` is the correct command and it works fine for me and for our testers, so the problem is likely on your system. Take a look at this reply and check if you have the correct latex packages installed https://tex.stackexchange.com/a/32936?

**Comment by lhy11009** [comment]
@gassmoeller. Thanks for your previous answer. I am able to fix this issue after installing the package texlive-science and texlive-latex-extra.
