### ISSUE TITLE
viscous_dissipation_statistics does not set in.position

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#521]
The viscous dissipation statistics does not set the material model input position. This is only problematic if the material model uses the position, but still we should fix this at some point. Maybe the whole postprocessor is obsolete, since the new heating_statistics postprocessor generates the same output with all the other heating terms as well.

**Comment by bangerth** [comment]
@gassmoeller : I don't have a testcase, but would #522 address the problem?
