### ISSUE TITLE
Import global topography.

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#5421]
We should have a way to impose global topography from an existing data set, which we may want to store somewhere in the data directory. Candidates could be gtopo30 (0.5 km resolution) or etopo5 (5km resolution), with intermediate resolutions available.

One could put this into the "initial topography" plugin system. It would be nice to make this work also with dynamic mesh refinement somehow, i.e., for new vertices to be placed in a way that respects the topography.

**Comment by bangerth** [comment]
Here's what I see. At least for the chunk geometry, we can use `InitialTopographyModel::Interface` objects to add an initial topography that is then given to a manifold object like this:
```
      template <int dim>
      class ChunkGeometry : public ChartManifold<dim,dim>
      {
          [ ... ]

          /*
           * An initialization function to make sure that the
           * manifold has access to the topography plugins.
           */
          void
          initialize(const InitialTopographyModel::Interface<dim> *topography);
```
This manifold is then used to describe the deformed mesh. The initial deformation happens here:
```
    template <int dim>
    void
    Chunk<dim>::
    create_coarse_mesh (parallel::distributed::Triangulation<dim> &coarse_grid) const
    {
      const std::vector<unsigned int> rep_vec(repetitions.begin(), repetitions.end());
      GridGenerator::subdivided_hyper_rectangle (coarse_grid,
                                                 rep_vec,
                                                 point1,
                                                 point2,
                                                 true);

      // Transform box into spherical chunk
      GridTools::transform (
        [&](const Point<dim> &p) -> Point<dim>
      {
        return manifold.push_forward(p);
      },
      coarse_grid);
...
```

So this could already facilitate using real, global topography: We just need to funnel one of these data sets into an `InitialTopographyModel::AsciiData` object.

**Comment by bangerth** [comment]
The files for topography can be obtained from here:

- https://www.ncei.noaa.gov/products/etopo-global-relief-model for the ETOPO model. These files are not small. For the 1 arc-minute (60 arc-second) data set, the NetCDF file has 483 MB. It cannot be compressed any further.

- GTOPO is here: https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-30-arc-second-elevation-gtopo30 It is a data set at 30 arc-second spacing, so presumably 4x as large as the one above. It is distributed in a number of tiles, so making it global is going to involve a bit of a hassle. This is also a data set from 1996 that does not appear to have been updated since then.

My suggestion is to somehow go with the ETOPO models. We might have to downsample this if we want to include it in the distribution.

**Comment by bangerth** [comment]
A good first step would be to make sure the `SphericalShell` model can also deal with initial topographies, in the same way as the `Chunk` currently already can.

**Comment by jdannberg** [comment]
Looking into the `SphericalShell` and `Chunk` geometries, from my understanding this would involve creating a new manifold in the `SphericalShell` geometry which uses the existing `SphericalManifold` but then also takes into account the initial topography. This could look similar to the custom manifold in the `Chunk` geometry in the sense that we would have to implement `push_forward` and `pull_back` functions that could look the same as in the `Chunk` geometry, but we would have to make our own `push_forward_sphere` and `pull_back_sphere` functions because the `SphericalManifold` does not have one, so this would require a bit more thought.

**Comment by bangerth** [comment]
The underlying issue is that a spherical shell is a manifold but cannot be described by a single chart -- and so the `SphericalManifold` class cannot be derived from `ChartManifold` but is instead derived from the base class `Manifold`.

What we need to do is have a class derived from `Manifold` that for each of the required member functions (i) performs the pull back -- i.e., remove the initial topography -- from all provided points, (ii) calls the corresponding function in `SphericalManifold`, (iii) applies the push forward -- i.e., re-apply the initial topography to the returned points. The pull back and push forward operations will look essentially the same as for the Chunk geometry. 

The only tricky questions are how to deal with the functions that compute normals and tangents. A simplistic implementation, appropriate if one considers the topography to be small, is to just return the vectors computed by the `SphericalManifold` class. This is probably fine for Earth with its relatively small topography compared to its radius, but will fail for [Hyperion](https://en.wikipedia.org/wiki/Hyperion_(moon)).

**Comment by bangerth** [comment]
Current status -- with relatively minor additional edits, and @alarshi's data file in #5567, I can get this picture:
![image](https://github.com/geodynamics/aspect/assets/7504421/005943d4-f0da-4197-b166-9d0e9ed925b2)

The other hemisphere is still wrong, though:
![image](https://github.com/geodynamics/aspect/assets/7504421/ef571377-a954-4aa1-a10b-44a1a7ac6caf)
I think this is the case because I'm currently passing longitudes between -pi and +pi, and the ASCII reader wants 0...2*pi -- or the other way around, have to check.

**Comment by bangerth** [comment]
I will need some help with this issue. What is happening is this:
* In the spherical shell geometry, we call the initial topography model to query the topography. We pass it a point in spherical coordinates.
* We come out in `AsciiData<dim>::value (const Point<dim-1> &surface_point)` where for spherical models we first convert back to Cartesian coordinates and then call `Utilities::AsciiDataBoundary<dim>::get_data_component()`:
```
    double
    AsciiData<dim>::value (const Point<dim-1> &surface_point) const
    {
      // In a first step, create a global 'dim'-dimensional point that we can pass to the
      // function expression as input -- because the function is a dim-dimensional
      // function.
      //
      // Different geometry models pass the surface point in in different ways.
      // In the following, we will first normalize the input to a dim-dimensional
      // point with a dummy vertical/radial coordinate that, one would hope,
      // the AsciiDataBoundary class will then simply ignore.
      Point<dim> global_point;
      if (...)
      else if (Plugins::plugin_type_matches<const GeometryModel::Sphere<dim>> (this->get_geometry_model()) ||
               Plugins::plugin_type_matches<const GeometryModel::SphericalShell<dim>> (this->get_geometry_model()) ||
               Plugins::plugin_type_matches<const GeometryModel::Chunk<dim>> (this->get_geometry_model()))
        {
          // AsciiDataBoundary always expects to get the input
          // parameters for its functions in Cartesian
          // coordinates. The get_data_component function then changes
          // the coordinate system, or more precisely it asks the
          // geometry model to convert the point into its natural
          // coordinate system, before doing the table lookup.
          //
          // This is of course all not very efficient (TODO: Think
          // about a better scheme), but the first step then needs to
          // be to convert what we have into Cartesian coordinates...
          std::array<double, dim> point;
          point[0] = 6371000.0;
          for (unsigned int d=0; d<dim-1; ++d)
            point[d+1] = surface_point[d];

          global_point = Utilities::Coordinates::spherical_to_cartesian_coordinates<dim>(point);
        }
       ...

      const double topo = this->Utilities::AsciiDataBoundary<dim>::get_data_component(surface_boundary_id,
                                                                                      global_point,
                                                                                      0);

      return topo;
    }
```

* That latter function first converts the Cartesian coordinates back into spherical coordinates (`data_coordinates_from_position()`) and then strips out the radial coordinate (`boundary_coordinates_from_data_coordinates()`) and looks as follows:
```
    double
    AsciiDataBoundary<dim>::
    get_data_component (const types::boundary_id             boundary_indicator,
                        const Point<dim>                    &position,
                        const unsigned int                   component) const
    {
      const Point<dim> data_coordinates = data_coordinates_from_position(position, this->get_geometry_model());
      const Point<dim-1> boundary_coordinates = boundary_coordinates_from_data_coordinates(data_coordinates, boundary_indicator);

      const double data = lookups.find(boundary_indicator)->second->get_data(boundary_coordinates,component);
```

* As a last step, it calls into the `StructuredData::get_data()` function to actually query the topography.

In this string of conversions, the problem is that `data_coordinates_from_position()` computes longitudes in the range 0...2*pi. But the input file uses longitudes -pi...pi, and so we look up points outside the data range -- which is why the area left of the prime meridian in the picture in my previous comment is constant in the east-west direction: It simply continues the data from longitude=pi forward by a constant value.

Among the things I could do to fix this are:
* Change `data_coordinates_from_position()` to convert from its output from `0...2pi` to `-pi...pi` if the geometry model in use is `spherical shell`.
* `data_coordinates_from_position()` calls `geometry_model.cartesian_to_natural_coordinates(position);` which comes out in the spherical shell model where we have 
```
std::array<double,dim>
    SphericalShell<dim>::cartesian_to_natural_coordinates(const Point<dim> &position) const
    {
      return Utilities::Coordinates::cartesian_to_spherical_coordinates<dim>(position);
    }
```
and we can here, too, convert from `0...2pi` to `-pi...pi`.
* We change the ascii data input file to use longitudes `0...2pi` instead of `-pi...pi`.

All of these seem equally much of a hack. In the end it is question of *expectations* that we have never properly addressed and documented: What do we mean when we say "spherical coordinates"? And what is the convention we want ascii data files to conform to?

Thoughts?

@alarshi @gassmoeller @jdannberg @naliboff FYI

**Comment by bangerth** [comment]
For the record, with one of these hacky changes, I get the right results: 
![image](https://github.com/geodynamics/aspect/assets/7504421/889bd9e3-942a-415c-8208-bc7603f25117)

**Comment by bangerth** [comment]
Conclusion of the discussion just now: We should use the convention that longitudes are provides in the range 0...2pi, and that input files should be provided in that format. I will document this.

**Comment by bangerth** [comment]
As mentioned in #5577, the initial surface topography is not correct. In fact, this can also be seen in the picture above where West Africa seems to have an elevation of more than 3000 m. Europe appears too low in the water. That's not right. But the *overall* pattern is roughly correct. So *locally* the elevations seem correct, just globally something is going on that appears to add to the correct elevations a smooth but spatially variable offset.

I'm running low on ideas regarding where else to look, so I thought I'd at least document what I have tried:

- One might think that perhaps we are applying surface elevations more than once. To test this, I simple let `SphericalManifoldWithTopography::topography_for_point()` return a topography of 1000 meters. If we apply the topography correctly, we should get images like the above where the elevation is uniformly 1000 meters, and that should continue to be the case after some mesh refinement cycles. Indeed that is the case: So we really only apply the displacement once as otherwise we would add up the 1000 meters of elevation more than once.
- One might think that perhaps the data file has the wrong values, or the right values but with regards to a different reference height. Alas, that is also not the case. The pictures in #5577 show surface elevations that are in the range of -11 to +12 km. But as also reported there, the min and max of the data in the input file is in the range of -6.5 to +5.2 km, and in fact these are also the values returned by `SphericalManifoldWithTopography::topography_for_point()`. In other words, we read the data correctly, interpolate correctly, and return it correctly from that function. Something happens downstream.
- One could also think that perhaps the `surface elevation` postprocessor is wrong and that the values we have within the program are in fact correct, just wrongly output or wrongly visualized. So I put a piece of code into `Simulator::run()` just after the global refinement step about 40 lines down the function that for each vertex of the mesh calls `geometry_model->height_above_reference_surface(triangulation.get_vertices()[i])` and computes the maximum over all vertices. With 3 global and 0 adaptive refinement steps in the input file, the visualization shows a maximum elevation of 11140 meters, and indeed my piece of code also reports this height (it says 11136; Visit must be rounding to 4 digits).
- It could of course also be that `geometry_model->height_above_reference_surface(triangulation.get_vertices()[i])` is wrong, so I replaced that by `triangulation.get_vertices()[i].norm() - 6336000.`. This reported a maximal elevation of 11136.

What I conclude from this is that the function that returns the topography from the data file, `SphericalManifoldWithTopography::topography_for_point()`, is correct and that the function that for a given point computes the elevation is correct and that the postprocessor that outputs this information into a VTK file is correct.

The problem must be somewhere in the functions that take a mesh and refine it.

**Comment by bangerth** [comment]
Another idea at reducing the possibilities of where the issue is:

The `surface_elevation_spherical_shell_ascii_data_global_3d.prm` has the following mesh refinement section:
```
subsection Mesh refinement
  set Initial adaptive refinement        = 0
  set Initial global refinement          = 1
```
So we create the coarse mesh and then we refine it once global in `Simulator::run()`. With this, I get the following output (when switching the .prm file to create VTU files instead):
![image](https://github.com/geodynamics/aspect/assets/7504421/824f38d4-9a7a-427d-b398-91be9d4de638)
Note how West Africa is still too high.

I should be able to get the exact same result if I do `set Initial global refinement          = 0` and in `SphericalShell::create_coarse_mesh()` add a call to `coarse_grid.refine_global()` at the end. Indeed, I get the same result: Even there points are already too high, implying that it isn't anything that happens in `Simulator`. The problem is purely restricted to the `SphericalShell` geometry class and how it interacts with the triangulation.

**Comment by bangerth** [comment]
To elaborate a bit on that last point: If I edit the tail of `SphericalShell::create_coarse_mesh()` to the following:
```
      auto show_max_elevation =
          [&]() {
        double max = 0;
        for (unsigned int i=0; i<coarse_grid.n_vertices(); ++i)
          max = std::max(max, height_above_reference_surface(coarse_grid.get_vertices()[i]));

        std::cout << "--- max elevation = " << max << std::endl << std::endl;
      };

      std::cout << "------------------- After coarse grid generation" << std::endl;
      show_max_elevation();

      // Then add the topography to the mesh by moving all vertices from the
      // undeformed sphere to the sphere with topography:
      GridTools::transform (
        [&](const Point<dim> &p) -> Point<dim>
      {
        return manifold->push_forward_from_sphere(p);
      },
      coarse_grid);

      std::cout << "------------------- After deformation" << std::endl;
      show_max_elevation();

      // Use a manifold description for all cells. Use manifold_id 99 in order
      // not to step on the boundary indicators used below.
      coarse_grid.set_manifold (my_manifold_id, *manifold);
      set_manifold_ids(coarse_grid);

      std::cout << "------------------- After attaching manifolds" << std::endl;
      show_max_elevation();

      coarse_grid.refine_global();
      std::cout << "------------------- After global refinement" << std::endl;
      show_max_elevation();

      coarse_grid.refine_global();
      std::cout << "------------------- After global refinement" << std::endl;
      show_max_elevation();

      coarse_grid.refine_global();
      std::cout << "------------------- After global refinement" << std::endl;
      show_max_elevation();
```
then it shows this output:
```
------------------- After coarse grid generation
--- max elevation = 9.31323e-10

------------------- After deformation
--- max elevation = 2700

------------------- After attaching manifolds
--- max elevation = 2700

------------------- After global refinement
--- max elevation = 7765.06

------------------- After global refinement
--- max elevation = 9828.43

------------------- After global refinement
--- max elevation = 11136.6
```
With `set Initial global refinement          = 0` in the .prm file (i.e., no more mesh refinement after coarse mesh creation), I get this picture:
![image](https://github.com/geodynamics/aspect/assets/7504421/1c03581f-9241-4917-9f3e-e2754c12547d)

In other words, final picture (after running through a whole time step) and coarse mesh information (before doing the time step) agree. I had thought that perhaps we do a free surface, or apply dynamic topography to the mesh during the time step, etc., but that is not it. The problem really is confined to `SphericalShell:create_coarse_mesh().`

**Comment by bangerth** [comment]
I think I've found the issue, see https://github.com/dealii/dealii/pull/16741
![image](https://github.com/geodynamics/aspect/assets/7504421/8932a4a4-0909-4066-b06f-cbe4c5c8c872)

This looks right to me. Thanks for letting me have my stream of consciousness here.

So this is a bug in deal.II. We need to let this propagate forward to see an effect on the tester. In the meantime, I will make the same change in the ASPECT copy of the class, and update the tests.
