### ISSUE TITLE
Can petsc replace trilinos?

### ISSUE THREAD

**Issue by LemonBoy68** [geodynamics/aspect#5459]
Hello everyone!
Does aspect now support petsc as a replacement for trilinos? I have tried to install a lot of dealii (bound with trilinos) using different methods but without success, if you use petsc combined with dealii, this can easily succeed. So I want to ask if I can use dealii (petsc) as a dependency of aspect?

Thanks

**Comment by tjhei** [comment]
> Does aspect now support petsc as a replacement for trilinos?

No, we used to have PETSc support a long time ago, but not with recent versions. Did you follow the instructions in the manual? https://aspect-documentation.readthedocs.io/en/latest/user/install/index.html

**Comment by LemonBoy68** [comment]
Thank you very much for your attention to this issue.

At present, I have used candi to install many times and will get similar errors. I can find mpicc and mpif90 but not mpicxx. It is strange. I conclude that mpi is intact.

----------------------------------------
-- Found MPI_C: /opt/intel/oneapi/mpi/2021.9.0/lib/release/libmpi.so (found version "3.1")
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
-- Found MPI_Fortran: /opt/intel/oneapi/mpi/2021.9.0/bin/mpif90 (found version "3.1")
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
-- Found MPI_MPI_H
-- Performing Test MPI_UNDERLINKAGE_OK
-- Performing Test MPI_UNDERLINKAGE_OK - Success
-- Processing MPI variables and targets
-- Unable to process MPI
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_10_mpi.cmake:68 (message):
 

    Could not find any suitable mpi library!

----------------------------------------

Even though mine is explicitly specified in the candi.cfg file:

DEAL_II_CONFOPTS="-DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DMPI_C_COMPILER=/opt/intel/oneapi/mpi/2021.9.0/bin/mpicc \
-DMPI_CXX_COMPILER=/opt/intel/oneapi/mpi/2021.9.0/bin/mpicxx \
-DMPI_Fortran_COMPILER=/opt/intel/oneapi/mpi/2021.9.0/bin/mpif90"
But still getting the above error.

Thanks

> > Does aspect now support petsc as a replacement for trilinos?
> 
> No, we used to have PETSc support a long time ago, but not with recent versions. Did you follow the instructions in the manual? https://aspect-documentation.readthedocs.io/en/latest/user/install/index.html

**Comment by bangerth** [comment]
The error message says that it can't find `MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS` which suggests that either `/opt/intel/oneapi/mpi/2021.9.0/bin/mpicxx` does not exist, or does not work.

Regardless, since this is a part of installing deal.II (not ASPECT), please bring this up in the deal.II or candi forums if the issue persists.

As for the original question: As @tjhei already mentioned, we have abandoned using PETSc instead of Trilinos several years ago.
