### ISSUE TITLE
temperature ascii output plugin produces segmentation fault in blankenbach benchmark

### ISSUE THREAD

**Issue by ilusii** [geodynamics/aspect#5462]
Hi~

I am a beginner in aspect. I encountered a problem when running the benchmark/blankenbach example. Error output on my workstation (details are attached in the file error.log)

**Number of active cells: 256 (on 5 levels)
Number of degrees of freedom: 3,556 [(2,178+289+1,089)]

*** Timestep 0: t=0 seconds, dt=0 seconds
    Solving temperature system... 0 iterations.
[error.log](https://github.com/geodynamics/aspect/files/13060517/error.log)

    Rebuilding Stokes preconditioner...
    Solving Stokes system... 31+0 iterations.**

**Postprocessing:**
**[nzbz-7920:63673:0:63673] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[nzbz-7920:63674:0:63674] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))**

When I remove the temperature ascii output, mpirun -np 8... multi-core runs successfully. I'd love to know what aspect-related dependencies I missed when configuring the aspect.

Thanks.

**Comment by tjhei** [comment]
Can you run the same model in debug mode and report if you see a different error? Thanks.

**Comment by ilusii** [comment]
> Can you run the same model in debug mode and report if you see a different error? Thanks.

@tjhei I did not install the debug version because my installation using candi failed. Everything was compiled manually and there was only the release version.

**Comment by tjhei** [comment]
Assuming you have a working normal deal.II installation, switching to debug mode is as simple as typing ``make debug`` followed by ``make`` in the build directory.
Being able to run debug and release mode of ASPECT is one of the important first lessons for your usage of ASPECT. Debug mode allows you to investigate issues like the one you posted about, so I don't think there is a way around that.

What system are you on and how did you install deal.II and ASPECT?

**Comment by ilusii** [comment]
> Assuming you have a working normal deal.II installation, switching to debug mode is as simple as typing `make debug` followed by `make` in the build directory. Being able to run debug and release mode of ASPECT is one of the important first lessons for your usage of ASPECT. Debug mode allows you to investigate issues like the one you posted about, so I don't think there is a way around that.
> 
> What system are you on and how did you install deal.II and ASPECT?

Thank you for your attention to this issue. I remember trying make debugRelease, but it seemed to fail. System information: Linux, ubuntu22. I will try building the debug version again (make debug) and will come back with the results.

**Comment by ilusii** [comment]
> > Assuming you have a working normal deal.II installation, switching to debug mode is as simple as typing `make debug` followed by `make` in the build directory. Being able to run debug and release mode of ASPECT is one of the important first lessons for your usage of ASPECT. Debug mode allows you to investigate issues like the one you posted about, so I don't think there is a way around that.
> > What system are you on and how did you install deal.II and ASPECT?
> 
> Thank you for your attention to this issue. I remember trying make debugRelease, but it seemed to fail. System information: Linux, ubuntu22. I will try building the debug version again (make debug) and will come back with the results.

Sorry, I found that I only built the release version of dealii without debugging, so I may not be able to directly execute make debug on the aspect now. It seems I can only reinstall it?

**Comment by ilusii** [comment]
> > > Assuming you have a working normal deal.II installation, switching to debug mode is as simple as typing `make debug` followed by `make` in the build directory. Being able to run debug and release mode of ASPECT is one of the important first lessons for your usage of ASPECT. Debug mode allows you to investigate issues like the one you posted about, so I don't think there is a way around that.
> > > What system are you on and how did you install deal.II and ASPECT?
> > 
> > 
> > Thank you for your attention to this issue. I remember trying make debugRelease, but it seemed to fail. System information: Linux, ubuntu22. I will try building the debug version again (make debug) and will come back with the results.
> 
> Sorry, I found that I only built the release version of dealii without debugging, so I may not be able to directly execute make debug on the aspect now. It seems I can only reinstall it?



> Assuming you have a working normal deal.II installation, switching to debug mode is as simple as typing `make debug` followed by `make` in the build directory. Being able to run debug and release mode of ASPECT is one of the important first lessons for your usage of ASPECT. Debug mode allows you to investigate issues like the one you posted about, so I don't think there is a way around that.
> 
> What system are you on and how did you install deal.II and ASPECT?

Hi @tjhei 
This is the result when I run it in debug mode.
[debug.log](https://github.com/geodynamics/aspect/files/13066714/debug.log)

**Comment by tjhei** [comment]
Try to use the latest deal.II release (9.5.1) instead of the development version.

**Comment by tjhei** [comment]
ASPECT 2.5 is not compatible with deal.II newer than 9.5.

**Comment by ilusii** [comment]
> ASPECT 2.5 is not compatible with deal.II newer than 9.5.
Thank u. I have considered this problem. I used the same method to build dealii 9.5.1 on the cluster before, but I also got the same error message. I think I may have accidentally missed something during compilation, but I don't know because I tried candi, but the effect was not ideal. If I get it I'll report it here.

**Comment by gassmoeller** [comment]
Hi Ilusii,
thanks for raising this report. I have no good explanation at the moment, but it is worth pointing out that the temperature ascii output plugin is an optional postprocessor for this benchmark, i.e. you can run the benchmark without it and it should still give you good results. 

Does the error also occur if you run the model without multiple MPI processes? Maybe it is a parallelization issue inside that plugin.

**Comment by tjhei** [comment]
@gassmoeller The explanation is using ASPECT 2.5 with deal.II master. They are not compatible. See the debug.log above.
