### ISSUE TITLE
depth average postprocessor interpolation issue

### ISSUE THREAD

**Issue by jperryhouts** [geodynamics/aspect#547]
It looks like if some of your depth average "zones" (bins) don't happen to have any nodes in them, the postprocessor will just return zeros for all values in those bins. That's annoying. I'm opening this issue mostly as a reminder to myself to look in to this later, unless anyone has an answer off the top of their head?

**Comment by bangerth** [comment]
Good point. Would throwing an exception ("You need fewer zones or higher mesh resolution") be the right solution? Or just averaging between adjacent zones? My preference would be the former -- if you have one empty zone, the others are likely underpopulated with points as well...

**Comment by jperryhouts** [comment]
I think it might be best to interpolate and print a warning if interpolation is necessary, or something like that. An exception could be problematic if AMR decides to remove important nodes half way through a model run.

**Comment by gassmoeller** [comment]
Is this also fixed with #590?

**Comment by jperryhouts** [comment]
Damn it. I thought I could get to this before you said anything.

**Comment by gassmoeller** [comment]
Too fast :smile:. I am just looking through old issues to make the list look shorter with as little effort as possible.

**Comment by class4kayaker** [comment]
Currently working on basic solution, however handling the more general case of lateral_average being overly fine when used by another plugin is beyond the planned scope.
