### ISSUE TITLE
documentation: weird double scrollbars

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5494]
The list of authors at the bottom of the documentation page is too long, which creates an additional scroll bar:

![image](https://github.com/geodynamics/aspect/assets/1531285/9bc8364b-20eb-48f8-a705-bf99bd74d80f)

**Comment by gassmoeller** [comment]
I am fine either way. Feel free to prepare a patch.

**Comment by tjhei** [comment]
This is now fixed with #5758.
