### ISSUE TITLE
Build deal.ii 9.5.1 with gcc 13.2.0, an error while building trillinos 13.2.0

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#5566]
I am having a similar issue to the one by @MFraters 
https://github.com/geodynamics/aspect/issues/5186

While building deal.ii 9.5.1 on a ubuntu 23.10 with gcc 13.2.0 and openmpi 4.1.5, there is an error building trilinos 13.2.0.

I have recently built deal.ii 9.5.1 on another ubuntu 23.04 machine with gcc  11.2.0 and openmpi 4.1.0 successfully. Thus I take this as an issue from the gcc major version 13.

Here are the error messages from candi_build.log in mp/build/trilinos-release-13-2-0

        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/DDirectory/DD_Set_Hash_Fn.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/DDirectory/DD_Set_Neighbor_Hash_Fn2.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/DDirectory/DD_Set_Neighbor_Hash_Fn1.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/Memory/mem.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/shared/zoltan_align.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/shared/zoltan_id.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_coord.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_gen_files.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_hash.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_map.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_heap.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_init.c.o
        [ 16%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_obj_list.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_rand.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_set_fn.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_sort.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_struct.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_back_trace.c.o
        [ 17%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_util.c.o
        [ 17%] Linking C shared library libzoltan.so
        [ 17%] Built target zoltan
        make: *** [Makefile:166: all] Error 2

**Comment by lhy11009** [comment]
For now, I will switch to gcc major version 11, but I'll be happy to see this fixed with version 13.

**Comment by bangerth** [comment]
@lhy11009 If you still have the output for which you show the end above: The actual error must have happened further up in the log; the lines you show are simply ones of some additional files successfully compiling, but there is going to be an error message higher up above. Unless we see the actual error, there is little we can help with.

**Comment by lhy11009** [comment]
@bangerth

I looked at the actual cause of the issue in the same file ([candi_build.log](https://github.com/geodynamics/aspect/files/14203192/candi_build.log)):

    /home/lochy/Softwares/dealii/Deal.ii-9.5.1-native-32-candi-gcc-13.2.0-openmpi-4.1.5/tmp/unpack/Trilinos-trilinos-release-13-2-0/packages/kokkos/core/src/impl/Kokkos_MemoryPool.cpp:112:48    : error: ‘uint32_t’ has not been declared


    132   112 | void _print_memory_pool_state(std::ostream& s, uint32_t const* sb_state_ptr,
    133       |                                                ^~~~~~~~


There are similar problems with gcc 13 in other communities, includeing how other communities fixed this issue:

https://github.com/pulsar-edit/superstring/pull/7/files

**Comment by MFraters** [comment]
You can either fix this yourself in trilinos by adding `#include <cstdint>` in the relevant files and restarting the compulation manually, or try Trilinos 14, I think this was fixed there.

**Comment by lhy11009** [comment]
@MFraters Thanks for your reply. I think these are good choices.

For now, I bypass the issue by compiling with gcc11.

For compilation on a server, the solution is to load a module with gcc major version 11.

For compilation on a local machine, the solution is to have both g++-11 and gfortran-11 installed and then use the command of "update-alternatives" to set these as default options for the system.

for example, to set the gcc-11 as default:

    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20

**Comment by lhy11009** [comment]
Thanks again for your time, I'll close the issue for now.
