### ISSUE TITLE
ASPECT cannot compile without WorldBuilder

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#5591]
With the cmake flag `-DASPECT_WITH_WORLD_BUILDER=OFF`, building throws the following error:

    In file included from ...:
    ... /aspect/source/particle/property/crystal_preferred_orientation.cc:23:10: fatal error: world_builder/grains.h: No such file or directory
      23 | #include <world_builder/grains.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [CMakeFiles/aspect-release.dir/Unity/unity_24_cxx.cxx.o] Error 1
    make[1]: *** [CMakeFiles/aspect-release.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 46%] Building CXX object CMakeFiles/aspect.dir/Unity/unity_24_cxx.cxx.o
    In file included from ...:
    ... /aspect/source/particle/property/crystal_preferred_orientation.cc:23:10: fatal error: world_builder/grains.h: No such file or directory
    23 | #include <world_builder/grains.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

Setting `-DASPECT_WITH_WORLD_BUILDER=ON` does successfully compile. I think adding

    #ifdef ASPECT_WITH_WORLD_BUILDER
    #endif

around the includes should fix it. @MFraters I haven't checked if there are more places that need these directives.

**Comment by gassmoeller** [comment]
Adding the include guard would have fixed the issue, but since the headers seem to not be used at the moment removing them seemed like the better solution. See #5593. @anne-glerum can you review that PR?

**Comment by anne-glerum** [comment]
Thanks for the fix Rene!
