### ISSUE TITLE
[CI] Jenkins tester is timing out / OOM / slow

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5630]
It seems that with a recent change the Jenkins tester is having some issues. I see internal compiler errors, timeouts after 30 minutes, or much slower performance (build time increased from <5 minutes to 20+). See:
https://ci.tjhei.info/job/aspect/job/main/

**Comment by gassmoeller** [comment]
Looks like this was fixed by #5634. Since then we are back to 5 min compile time on the Jenkins tester (see e.g. https://github.com/geodynamics/aspect/pull/5635).
