### ISSUE TITLE
velocity along the wall

### ISSUE THREAD

**Issue by hanybit** [geodynamics/aspect#5633]
Hello all, 
I need your help to write a velocity function to vary the velocity magnitude along the wall instead of having it of the same magnitude? I tried many times but always got an error, any ideas on how to implement it?

I used to implement it in underworld in this way
velFunc = -Model.y / GEO.nd(Model.maxCoord[1]) * GEO.nd(vmax-vmin) + GEO.nd(vmax)
where 
vmax=1.5 cm/yr
vmin=0.15 cm/yr

in ASPECT I have the same velocity along the boundary?

 subsection Function
    set Coordinate system   = cartesian
    set Variable names      = x,y,z,t

    # 0 deg obliquity, 10 mm full extension rate
    #set Function constants  = mm=0.001, yr=1, vx_full=10.000 , vy_full=0.0000, DZ=200e3, DX=450e3  

any ideas??

**Comment by gassmoeller** [comment]
Hi @hanybit,
this should absolutely be possible with the function syntax. Take a look at [this example cookbook](https://aspect-documentation.readthedocs.io/en/latest/user/cookbooks/cookbooks/platelike-boundary/doc/platelike-boundary.html), which implements both a variable velocity (a step function with variable transition position), and a smooth variable initial temperature using function plugins. [This page](https://aspect-documentation.readthedocs.io/en/latest/user/run-aspect/parameters-overview/muparser-format.html#a-note-on-the-syntax-of-formulas-in-input-files) also describes the syntax in more details.
Let us know if you have any remaining questions or if something on the pages is unclear.

**Comment by hanybit** [comment]
Hi Rene,
I have tried the solution you sent me, I came up with this way, is it correct to construct the function in this way?I wonder if I make v= -1*ymax / y * (vmax-vmin) + vmax will this recall the vmin and vmax and calculate v for all the points along the y coordinates? 
my model dimension is 3D where x=200km and y=400km and I vary velocity in x direction along left and right so that it varied from 5 mm/yr at max y  to 15 mm/yr at min y 

# Velocity on boundaries characterized by functions
# Outflow in the upper half is balanced by inflow in the bottom half
subsection Boundary velocity model
  set Tangential velocity boundary indicators = bottom
  set Prescribed velocity boundary indicators = left: function, right:function

  subsection Function
    set Variable names      = x
    set Function constants  = ymax= 400.e3, xmin=0.e3, xmax=200.e3, vmax=15*mm/yr, vmin=5*mm/yr, v= -1*ymax / y * (vmax-vmin) + vmax
    set Function expression = if (x=xmax, v, -v);
  end
end
