### ISSUE TITLE
master github-actions tester is broken

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5649]
I am seeing
```
/__w/_temp/c567fb68-12c8-4a2c-bff5-5a37c02e7d31.sh: 3: cmake: not found
Error: Process completed with exit code 1[27](https://github.com/geodynamics/aspect/actions/runs/9286521577/job/25553408240?pr=5647#step:4:28).
```
with the image geodynamics/aspect-tester:focal-dealii-master
See https://github.com/geodynamics/aspect/actions/runs/9286521577/job/25553408240?pr=5647#step:4:27

@gassmoeller was there a recent change to that docker image?

**Comment by tjhei** [comment]
I found a cmake binary at /opt/cmake-3.26.4-linux-x86_64/bin but that is not in the path.

**Comment by gassmoeller** [comment]
I just saw this now. I guess the cmake version installed by candi changed, so that is why the path in the container changed. It will take a day until the tester image is rebuilt online (I dont want to rebuild and push through our connection here).
