### ISSUE TITLE
equations in the manual

### ISSUE THREAD

**Issue by cedrict** [geodynamics/aspect#5673]
It looks like all equations in the manual are not processed adequately (anymore). 
For example:
https://aspect-documentation.readthedocs.io/en/latest/user/benchmarks/benchmarks/solcx/doc/solcx.html

**Comment by tjhei** [comment]
It works for me in Chrome but fails on Firefox with:
```
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://readthedocs.org/api/v2/sustainability/data/?callback=jQuery36305710563357391775_1717082392907&format=jsonp&project=aspect-documentation&_=1717082392908 [jquery.js:1:83595](https://aspect-documentation.readthedocs.io/_/static/vendor/jquery.js)
```

**Comment by tjhei** [comment]
actually, this might be the error:
```
Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js”.
```

**Comment by tjhei** [comment]
This is fixed by turning on VPN, so I think this is our local wifi blocking the URL...

**Comment by tjhei** [comment]
You can try it out by visiting https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

**Comment by cedrict** [comment]
I click on the link and I get 

Unable to connect
An error occurred during a connection to cdn.jsdelivr.net.

**Comment by tjhei** [comment]
Alright, nothing we can do about this...
