### ISSUE TITLE
Depth average postprocessor is kind of clunky

### ISSUE THREAD

**Issue by ian-r-rose** [geodynamics/aspect#570]
I had a couple of questions/comments about the DepthAverage postprocessor, which may or may not be worth addressing.

* I wanted to add a new statistic to the postprocessor (see #569) and had to make a surprising number of changes to the ``Simulator`` and ``SimulatorAccess`` classes.  This seems kind of antithetical to the postprocessor architecture.  Might there be a better way to do this? 

* I noticed that the gnuplot output (which is the default format) can have some I/O synchonization problems which can be annoying (specifically, some entries from later timesteps can be written to file before entries from earlier timesteps).  This should only be a problem for simulations that are I/O bound, but it does make testing more difficult.

* The name DepthAverage is confusing to me.  That seems to suggest averaging a quantity in depth, when in reality it is doing a series of lateral averages, each at a different depth.

Anyhow, I do not have specific suggestions for these at the moment, but am open to ideas.

**Comment by jperryhouts** [comment]
I also have some beef with the DepthAverage postprocessor. See #547 

Some upgrades might be in order. Or maybe a full rewrite? I don't know, it seems easy enough to redo it with improvements, but some thought should go in to it first. Most of the issues seem to stem from lack of foresight when writing the plugin the first time.

**Comment by bangerth** [comment]
You both have good points about the implementation and the name of the thing -- and in particular about the lack of foresight when writing the original implementation. I don't have good suggestions other than someone having to spend the time to re-implement the whole thing :-(

@ian-r-rose : Can you point out more specifically what the synchronization problems are? Are these just annoying, or could they lead to actual wrong output?

**Comment by ian-r-rose** [comment]
I think that I was misinterpreting the structure of the depth average output file as synchronization errors, though the output is pretty confusing.

I expected the output to be a list of line something like
```
depth1 time1 a1 b1 ...
depth2 time1 a2 b2 ...
depth3 time1 a3 b3 ...
```

However, since it is represented by a 1D finite element internally (as far as I can tell), it is instead output by iterating over the elements, and the finite element values are output sort of interleaved in time.  I don't think it is wrong, but is difficult to understand and parse.

Running the cookbook ```shell_simple_2d.prm``` reproduces confusing output for me.

**Comment by ian-r-rose** [comment]
I also took a look at at what it would take to reorganize the depth averaging as currently implemented.
 You are correct, Wolfgang, that it can't go entirely into the postprocessor architecture, since a couple of places in the code also want some depth-averaged information (though not the adiabatic conditions, as far as I can tell).

A compromise solution might be to move all the logic into the ```SimulatorAccess``` base class.  All the ```SimulatorAccess``` functions for depth averaging just immediately redirect to the implementation in ```Simulator```, but that needn't be the case, since ```SimulatorAccess``` has all the access it needs to calculate the averages.  One could argue that this falls outside of the scope of an "accessor" class, though.

**Comment by ian-r-rose** [comment]
Another note on the DepthAverage postprocessor, as long as I am making a wishlist :-)
The actual process of depth averaging is kind of expensive.  It would be nice to not have to calculate all of the quantities if you only want one or two.

I am of course willing to help on this, as soon as there is a plan for a way forwards.

**Comment by jperryhouts** [comment]
Yes, there should be a subsection in the prm where it's possible to select from a list of possible computed quantities! I'd also be willing to help with this, if there's anything I can do.

**Comment by bangerth** [comment]
> I expected the output to be a list of line something like
>
> |depth1 time1 a1 b1 ...
> depth2 time1 a2 b2 ...
> depth3 time1 a3 b3 ...
> |
>
> However, since it is represented by a 1D finite element internally (as
> far as I can tell), it is instead output by iterating over the elements,
> and the finite element values are output sort of interleaved in time. I
> don't think it is wrong, but is difficult to understand and parse.

Correct. The format works in a way to make sure you can plot the depth 
averages as a space-time function in gnuplot. You can output the depth 
averages in any of the other formats as well (e.g., in VTU) which will 
also reproduce the space-time plot.

**Comment by bangerth** [comment]
> You are correct, Wolfgang, that it can't go entirely into the
> postprocessor architecture, since a couple of places in the code also
> want some depth-averaged information (though not the adiabatic
> conditions, as far as I can tell).

I must have misremembered then. Anyway, there are different places in 
the code that call this function. Do you recall where the others were?

> A compromise solution might be to move all the logic into the
> |SimulatorAccess| base class. All the |SimulatorAccess| functions for
> depth averaging just immediately redirect to the implementation in
> |Simulator|, but that needn't be the case, since |SimulatorAccess| has
> all the access it needs to calculate the averages. One could argue that
> this falls outside of the scope of an "accessor" class, though.

Another option would be to have a class derived from `SimulatorAccess` 
(but not part of the postprocessor system), let's say `LateralAveraging` 
(to choose a better name if the previous one was too confusing :-) that 
classes using the depth averages could either derive from themselves, or 
keep an object of this type around. This would keep SimulatorAccess free 
of additional functionality while achieving the same goal.

**Comment by bangerth** [comment]
On 08/09/2015 02:07 PM, Ian Rose wrote:
> Another note on the DepthAverage postprocessor, as long as I am making a
> wishlist :-)
> The actual process of depth averaging is kind of expensive. It would be
> nice to not have to calculate all of the quantities if you only want one
> or two.

Yes, that too. We should let the depth average postprocessor take a list 
in the parameter file that lists the quantities you'd like to have 
computed. Back when it was written originally, there were only two or 
three quantities so it didn't matter. Now it does.

**Comment by ian-r-rose** [comment]
>
>
> I must have misremembered then. Anyway, there are different places in
> the code that call this function. Do you recall where the others were?
>
> ​They were in the steinberger material model and in the seismic wave speed
visualization modules.​

**Comment by gassmoeller** [comment]
@ian-r-rose Did your PR already fix this issue?

**Comment by ian-r-rose** [comment]
Mostly. I believe that #547 has still not been fixed. But otherwise I am happier with the postprocessor. @jperryhouts, did you intend to close the issue?

**Comment by jperryhouts** [comment]
No, I should have left it open, but I was in such a hurry to beat Rene to commenting on it that I wasn't thinking.
