### ISSUE TITLE
remove parameter-gui?

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5706]
I vote to remove cmake support for the QT based parameter GUI https://github.com/dealii/parameter_gui. Or is anyone using it?

**Comment by bangerth** [comment]
I thought I saw someone use it recently (on a Zoom call?). Isn't this a separate program now?

**Comment by bangerth** [comment]
In other words, what would we have to remove?

**Comment by tjhei** [comment]
https://github.com/geodynamics/aspect/blob/70e161d7b5ea5daf13680271f42e2ddd65c53d5d/CMakeLists.txt#L815-L844

**Comment by bangerth** [comment]
I don't think it's an issue that bothers me too much. Take a poll tomorrow morning!

**Comment by tjhei** [comment]
poll results: nobody uses the parameter gui.

**Comment by gassmoeller** [comment]
see my comment in #5735. What you are proposing is removing the configuration of ASPECT-GUI as part of ASPECT build. ASPECT-GUI works just fine separately.
