### ISSUE TITLE
unity build compile issues

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5728]
In #2744 I am running into build issues with duplicate instantiations from source/volume_of_fluid/handler.cc and source/volume_of_fluid/solver.cc

We do have a special rule for it, see
https://github.com/geodynamics/aspect/blob/ba21b38dd15986ae26edd94951f4b775cbb107d4/CMakeLists.txt#L78-L84
but I think moving the file to the end is not enough to avoid having both .cc files listed above ending up in the same unity file. 

If they end up in the same file, the ordering actually matters. I think the ordering should be the other way around, see
https://godbolt.org/z/G7rcbrnen

**Comment by tjhei** [comment]
So I think we need to either skip unity build for these files or reverse the ordering. Thoughts?

**Comment by gassmoeller** [comment]
I would say exclude it from the unity build. You can do so by setting the file property `SKIP_UNITY_BUILD_INCLUSION` (https://cmake.org/cmake/help/latest/prop_sf/SKIP_UNITY_BUILD_INCLUSION.html).
