### ISSUE TITLE
Improve particle code

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#58]
The current state of particles has two things that I’d like to improve:

Particles are distributed throughout the domain. It would be useful if we could provide a density function so that one can place them only in a single region (e.g., a LLSVP at the base of the mantle) and see where they go.

Right now, particles only carry a single attribute: their ID, which is essentially a random number. What one would like to have is one (or more) attribute one can assign to each particle. This way, one could (using the same example) assign one particular value to particles in an LLSVP and another value to all of the other particles, and see where they go with the advection.

**Comment by gassmoeller** [comment]
Both of your points are addressed in #411. Should we close this issue, and if necessary open new ones, when we find other things to improve in the new implementation? I am just eager to close old issues :-)
