### ISSUE TITLE
Splitting particle worlds

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#5877]
We had a discussion on what is the best approach of splitting the particles so that we can have multiple sets of particles, for example one set for compositional particles, one set for CPO particles and one set for melt particles.

We discussed the following option: 
1. Adding the functionality to the dealii particle handler
2. Adding the functionality to the aspect particle handler/world. This would allow to use a 1 to n parameter approach within the current particle parameter section.
3. Make a vector of particle worlds. This would duplicate the particle sections (1 to n). We are thinking of making this a cmake variable. 

Option 3 seems the easiest option, and this is what I will try first. This is dependent on pull request #5394.

**Comment by gassmoeller** [comment]
So we decided on option 3 to have multiple particle worlds in ASPECT. 

@mfraters and I discussed things that still need to be implemented and tested and came up with this list:
1. Creating multiple particle words and reading their input parameters.
2.  Create a cmake variable that controls the maximum number of particle worlds. Add an input parameter for how many particle worlds to create. Document in that input parameter how the cmake variable works.
3. During initialization create the particles of all worlds.
4. During timestepping backup/restore all particle worlds.
5. During timestepping call `advance_timestep()` for all particle worlds
6. When mapping particle properties to fields:
  - assert each particle property is only owned by one world
  - store which world own which particle property
  - during interpolation, interpolate from the correct world
7. During postprocessing: Loop through all particle worlds and create separate output directories for each of them:
  - starting at `particles`, then `particles-2`, `particles-3`, ...
8. Check Checkpointing
9. Check load balancing: Only particle world 0 is allowed to add the base weight.

None of these steps looks too complicated, so maybe we can handle them in one (or just a few) PRs. We will keep this issue open to track the progress.

**Comment by tjhei** [comment]
I think this would be great to have in 3.0.

**Comment by gassmoeller** [comment]
Agreed. @MFraters will try to make a WIP PR before I visit him in Potsdam in two weeks. We will then try to fix remaining issues and have this ready soonish.

**Comment by gassmoeller** [comment]
that would be appreciated. Could you introduce a cmake variable like `ASPECT_N_PARTICLE_WORLDS` that we can use as preprocessor define inside the code? The reason we think we need this is that we would like to limit the input parameter declarations to only this number of particle worlds and that happens inside the static `declare_parameters`. Declaring a fixed number would duplicate all the input parameters and we do not want this to appear in the online documentation or in the `parameters.prm` output. In practice there will still be an input parameter `Number of particle worlds` that controls how many sets of particles are actually active, the cmake variable would act more like a maximum number that will be possible.

**Comment by gassmoeller** [comment]
But if you dont have the time dont worry, I am sure @mfraters and I can figure it out too.

**Comment by tjhei** [comment]
> that would be appreciated. Could you introduce a cmake variable like `ASPECT_N_PARTICLE_WORLDS` that we can use as preprocessor define inside the code? The reason we think we need this is that we would like to limit the input parameter declarations to only this number of particle worlds and that happens inside the static `declare_parameters`. Declaring a fixed number would duplicate all the input parameters and we do not want this to appear in the online documentation or in the `parameters.prm` output. In practice there will still be an input parameter `Number of particle worlds` that controls how many sets of particles are actually active, the cmake variable would act more like a maximum number that will be possible.

Sure. This is exactly how we discussed it.

**Comment by tjhei** [comment]
see #6025

**Comment by MFraters** [comment]
I turned @gassmoeller in a checklist, so it is easier for me to keep track:

- [ ] Creating multiple particle words and reading their input parameters.
- [ ] Create a cmake variable that controls the maximum number of particle worlds. Add an input parameter for how many particle worlds to create. Document in that input parameter how the cmake variable works.
- [ ] During initialization create the particles of all worlds.
- [ ] During timestepping backup/restore all particle worlds.
- [ ] During timestepping call advance_timestep() for all particle worlds
- [ ] When mapping particle properties to fields:

    assert each particle property is only owned by one world
    store which world own which particle property
    during interpolation, interpolate from the correct world

- [ ] During postprocessing: Loop through all particle worlds and create separate output directories for each of them:

    starting at particles, then particles-2, particles-3, ...

- [ ] Check Checkpointing
- [ ] Check load balancing: Only particle world 0 is allowed to add the base weight.

**Comment by gassmoeller** [comment]
#6045 implements most of the remaining pieces. Now we need to add tests, in particular:

I think we are now at a stage where we need to add a lot of tests to this PR. We can split the work and check off the items we are working on in the following list. I think these are the tests we would need:

- [ ] particle generation and advection in multiple particle worlds
- [ ] having different particle properties in different particle worlds
- [ ] particle property interpolation from multiple particle worlds into compositional fields
- [ ] checkpointing/restart with multiple particle worlds
- [ ] load balancing, making sure it combines the weights of multiple worlds correctly
- [ ] output: writing the correct particle world in the correct output folder, making sure that description files like .pvd are not overwritten if multiple worlds are present
- [ ] statistics output: make sure columns are not duplicated or overwritten
- [ ] Timing output: are timings from multiple worlds added in the same timing categories? Is this what we want?
- [ ] check the code one more time for every instance of `this->get_particle_world` and make sure we use the correct world. Do we need a way to find out which particle world owns a particular property (in case a plugin needs one)?
- ...

**Comment by gassmoeller** [comment]
I think this issue can be closed now. If problems appear we can make separate issues for them.
