### ISSUE TITLE
MPI error installation main

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#6009]
Our cluster has migrated to Rocky Linux 9 and I'm trying to install dealii 9.5.2 and ASPECT main.
With the attached candi.cfg, dealii installs without issue. However, aspect-debug install fails with the following message:
```
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  PML add procs failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_mpi_instance_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
[blogin7:00000] *** An error occurred in MPI_Init_thread
[blogin7:00000] *** reported by process [1682374656,0]
[blogin7:00000] *** on a NULL communicator
[blogin7:00000] *** Unknown error
[blogin7:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[blogin7:00000] ***    and MPI will try to terminate your MPI job as well)
make[2]: *** [CMakeFiles/aspect.exe.debug.dir/build.make:1080: aspect-debug] Error 14
make[2]: *** Deleting file 'aspect-debug'
make[1]: *** [CMakeFiles/Makefile2:503: CMakeFiles/aspect.exe.debug.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
aspect-release is created, but when run gives the same error. I've attached the detailed.log as well. I've loaded the following modules:

` 1) NHRZIBenv   2) sw.clx.el9   3) slurm   4) gcc/13.3.0   5) openmpi/gcc/5.0.3   6) anaconda3/2023.09 `

I don't know what to make of the error message, does anyone have an idea?

PS I had to set `USE_DEAL_II_CMAKE_MPI_COMPILER=OFF` to avoid ASPECT compiling errors for functions with openmpi. It seemed dealii used a mix of gcc and intel compilers with this flag ON.

PPS I also had to use bundled boost to avoid missing links to libicu.

**Comment by anne-glerum** [comment]
[candi_cfg.txt](https://github.com/user-attachments/files/16614174/candi_cfg.txt)
[dealii_detailed_log.txt](https://github.com/user-attachments/files/16614189/dealii_detailed_log.txt)
[ASPECT_detailed_log.txt](https://github.com/user-attachments/files/16614190/ASPECT_detailed_log.txt)

**Comment by anne-glerum** [comment]
Downgrading the gcc version to 11.4.1 20231218 solves the problem, so I'll close this issue for now.

**Comment by gassmoeller** [comment]
Good to hear you found a solution. So do you think this is a problem with the cluster configuration, possibly MPI? I have a desktop system with gcc 13.2.0 and openmpi 4.1.6 and it seems to work, so at least it doesnt seem to be a general problem with gcc 13.
