### ISSUE TITLE
Assistance Needed with LAPACK Build Issue on Peloton

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#6048]
I am currently facing an issue while building LAPACK with deal.ii-9.5.2 on Peloton using GCC 11.3.0 and OpenMPI 4.1.5. The versions of ScaLAPACK and LAPACK built are 2.1.0 and 3.10.1, respectively.

The error arises during the final linking step of the Fortran static library. I suspect that the GCC version may have triggered this issue. Could you advise on the appropriate GCC version to use? Alternatively, if there are other potential causes for this error, I would appreciate your insights.

For your reference, I have included the build log of LAPACK below (tmp/build/scalapack-2.1.0/candi_build.log):

        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/zgesvdq.f.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/la_xisnan.F90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/slartg.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/dlartg.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/zlartg.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/clartg.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/slassq.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/dlassq.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/zlassq.f90.o
        [ 99%] Building Fortran object SRC/CMakeFiles/lapack.dir/classq.f90.o
        [100%] Linking Fortran static library ../lib/liblapack.a
        make[1]: *** [CMakeFiles/Makefile2:1424: BLACS/TESTING/CMakeFiles/xCbtest.dir/all] Error 2
        make[1]: *** [CMakeFiles/Makefile2:1450: BLACS/TESTING/CMakeFiles/xFbtest.dir/all] Error 2
        [100%] Built target lapack
        [ 71%] Performing install step for 'lapack'
        [  7%] Built target blas
        [100%] Built target lapack
        Install the project...
        -- Install configuration: "Release"
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/cmake/lapack-3.10.1/lapack-targets.cmake
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/cmake/lapack-3.10.1/lapack-targets-release.cmake
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/pkgconfig/lapack.pc
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/cmake/lapack-3.10.1/lapack-config.cmake
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/cmake/lapack-3.10.1/lapack-config-version.cmake
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/pkgconfig/blas.pc
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/libblas.a
        -- Installing: /group/billengrp/Software/deal.ii/deal.ii-9.5.2-LAPACK-Native-32bit-candi-gcc-11.3.0-openmpi4.1.5-mpi-io/tmp/build/scalapack-2.1.0/lib/liblapack.a
        [ 71%] Completed 'lapack'
        [ 71%] Built target lapack
        make: *** [Makefile:166: all] Error 2

**Comment by lhy11009** [comment]
@mibillen Forwarded.

**Comment by tjhei** [comment]
I don't see the actual error in the message you posted.

Are you using candi to install scalapack? I don't think you need it for ASPECT. Instead, can you compile the ``openblas`` package inside candi?

**Comment by lhy11009** [comment]
Yes, I can install the OpenBLAS package. I’m also planning to install the SCALAPACK package because I’d like to test using the "bilinear least squares" method as the "Interpolation scheme" for particles in ASPECT. According to the user manual, deal.II must be configured with BLAS and LAPACK to support this operation.

Would you be able to confirm if there are any specific steps or considerations I should be aware of when configuring deal.II with BLAS and LAPACK, especially for testing this interpolation scheme? Any guidance on setting up SCALAPACK would be greatly appreciated.

**Comment by tjhei** [comment]
> deal.II with BLAS and LAPAC

``openblas`` contains BLAS and LAPACK, there is no need to install SCALAPACK.

**Comment by lhy11009** [comment]
Oh, I didn't know that. Thanks for actually addressing this here. Maybe I can add one line in the documentation.
