### ISSUE TITLE
Free surface does not resume

### ISSUE THREAD

**Issue by jperryhouts** [geodynamics/aspect#614]
Pretty much as the subject line says, resuming a model with a free surface seems to reinitialize with a flat surface.

**Comment by ian-r-rose** [comment]
Yes, this has been on my todo list for a while...now I have the push needed to do it. PR incoming.

**Comment by gassmoeller** [comment]
@jperryhouts : Does the PR fix this issue?

**Comment by jperryhouts** [comment]
Um, apparently. I'll trust that Ian tested it, and close this.
