### ISSUE TITLE
Inconsistency in the meaning of "phase_index" in source/material_model/utilities.cc

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#6140]
@gassmoeller. Hi Rene, I noticed that the variable "phase_index" is used in a couple of places in the source/material_model/utilities.cc file. First, it appears in the PhaseFunction.compute_value function as in.phase_index, where it’s used as an input. Then, it shows up in the phase_average_value function, where "phase_index" is used to loop over all the phases.

From the way these variables interact with phase_function_values, it seems like they might have slightly different meanings—one potentially indicating the index of the phase transition and the other referring to the index of the phase.
In the first case, here is a piece of the code [link](https://github.com/geodynamics/aspect/blob/47299696ea872b8a4df9d90fb499ce5f52d77b3d/source/material_model/visco_plastic.cc#L127)

          for (unsigned int j=0; j < phase_function.n_phase_transitions(); ++j)
            {
              phase_inputs.phase_index = j;
              phase_function_values[j] = phase_function.compute_value(phase_inputs);
            }

And in the second case [link](https://github.com/geodynamics/aspect/blob/47299696ea872b8a4df9d90fb499ce5f52d77b3d/source/material_model/utilities.cc#L1131C21-L1131C163)

                    averaged_parameter += phase_function_values[phase_index-composition_index] * (std::log(parameter_values[phase_index+1]) - averaged_parameter);

Does this interpretation align with your understanding as well? If so, perhaps we could rename in.phase_index to in.phase_transition_index for clarity.

**Comment by gassmoeller** [comment]
Hi @lhy11009,
I think you are right, the variable `PhaseFunctionInputs::phase_index` should correctly have been called `phase_transition_index`.

There is a problem in simply renaming the variable though. It is a public member variable of the struct `PhaseFunctionInputs`. I.e. even though there are currently only 2 material models inside ASPECT that directly access the variable `in.phase_index` (`grain_size` and `visco_plastic`) there could be many material models from users out there. Simply renaming the variable would break all those models. I think there are two options:
1. We could document for this variable that `phase_index` in this context means phase transition index.
2. We rename the variable anyway and accept that there will be broken models out there. We can write a good changelog entry that explains the change.

What are your thoughts?

**Comment by lhy11009** [comment]
Hi Rene

I think I’ll go with approach 2 and make the change. From my experience, even when we implement these ourselves, I often find myself having to figure out which index corresponds to the phase and which one refers to the phase transition whenever I revisit the code or make modifications. Renaming these properly would make future changes much easier and more intuitive.

I also completely agree with your concern, and we should address it better in the changelog. Let me know what you think and whether you’d prefer to handle this or want me to take it on.

**Comment by gassmoeller** [comment]
I am ok with approach 2. It would be great if you could give it a go, as always I am happy to provide comments ;-).

**Comment by gassmoeller** [comment]
I think this was adressed in #6169
