### ISSUE TITLE
Problems rerunning models based on automatically generated .prm's

### ISSUE THREAD

**Issue by jperryhouts** [geodynamics/aspect#635]
If you try to run aspect on a .prm saved by a previous run, it crashes because several of the "Model name" fields are empty by default. Not sure why it runs in the first place if this is a problem. I'll look into it soon.

**Comment by jperryhouts** [comment]
So, apparently the problem here is that certain fields (like the Model name for the boundary composition model) which aren't necessarily used in every model can be unspecified and still produce a valid model setup, but if they are included in the .prm, and assigned an empty string (per default configuration), the ParameterHandler object throws an error.

My suggestion would be to set the default value of these fields to something like "null", which could then be a valid configuration as far as the ParameterHandler is concerned, and would only throw an exception *if* the value is ever used.

**Comment by jperryhouts** [comment]
Does anyone have a better idea, or should I go ahead and make that patch?

**Comment by tjhei** [comment]
I am not particularly fond of the current design where we catch an exception in the definition anyways, so yeah, I would suggest:
1. plugins.h get_pattern_of_names adds "null"
2. default value in each declare_entry is now "null" not "" (remove the try/catch ExcValueDoesNotMatchPattern in all files)
3. plugins.h create_plugin can catch "null" and present a nice error message

Want to give it a try?

**Comment by jperryhouts** [comment]
Thanks for the details, that saved me some poking around. This seems to work, I can actually run my generated .prm's now!

**Comment by gassmoeller** [comment]
This means this issue can be closed?

**Comment by jperryhouts** [comment]
Oh, yes it does. Thanks for reminding me.
