### ISSUE TITLE
Deal with the reference_ functions in the material model interface

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#64]
The functions get_reference_ ... in the material model are somewhat strange since they are either only important for postprocessing (reference_thermal_expansivity, reference_density) or are used for things not really related to the material model (reference_viscosity for pressure scaling). Still in the current state they need to be implemented. We should find a consistent way to use them or discard them straight away and handle the cases when they are called in a different way.

**Comment by gassmoeller** [comment]
Gotcha Github. "Resolve #64 in a follow-up pull request" does not mean to close this issue right away. I was so looking forward to closing this issue and now it has been taken away from me :cry:

**Comment by bangerth** [comment]
Here, I'll reopen it for you so you can close it again!

**Comment by gassmoeller** [comment]
Yay :smile:
