### ISSUE TITLE
Be more careful with the term "Boussinesq approximation"

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#653]
ASPECT (and the ASPECT manual) uses the term "Boussinesq approximation" as equivalent to "take the full equation, omit inertia terms and time derivatives in the mass and momentum equations". This is not how the term is actually used in the geodynamics community (and likely other communities as well).

This led to an interesting conversation I had with Scott King in which we talked about the hierarchy of approximations where I thought the "Boussinesq approximation" is the most general whereas he thought that it is the least general. I need to go through the manual and discuss this in more detail, along with the fact that the equations we use can not actually be used directly to represent the ALA, TALA, and BA because in all of them, the mass conservation equation uses a reference density whereas we use the full density.

(Reference for my notes: Thread with subject "King et al. benchmark - HALT". This was preceded by an email with subject "benchmark for ASPECT cookbook" by Sarah Stamps that contains a benchmark paper by King et al. that provides a nice listing of the various approximations; I need to copy this hierarchy into the manual and explain how they fit/don't fit into the equations we use.)

**Comment by gassmoeller** [comment]
The largest part of this issue is addressed by #1275. We might need to go over the manual one more time and look for wrong references to the Boussinesq approximation, but otherwise this should be fixed.

**Comment by jdannberg** [comment]
I had a look at the manual, and some of the wrong references to the Boussinesq approximation that are left are in the cookbooks. In these cases, do we want to modify the input files so that they use the real Boussinesq approximation? In particular for convection box, where we have this strange workaround...
On the other hand, we probably don't want to rerun all the computations and make new figures, and the results might be slightly different with a new input file. So we could also just add a note that this can now be done in a different way, but leave the input files as they are.

**Comment by tjhei** [comment]
My vote: make a release as is and then replace convection box to use the Boussinesq approximation.

**Comment by bangerth** [comment]
I would just replace the wording (don't say Boussinesq, just say thermal convection equations (1)-(3), or similar) where this is convenient, and otherwise leave the input files untouched.

This should work for all cases where we do not try to follow any particular benchmark or setup that others have already used. In those cases where we work around our previous limitations, it may be worthwhile trying to really changing the input files.

**Comment by gassmoeller** [comment]
Fixed by #1381. There is another issue that tracks the transition of cookbooks to other approximations (#1321)
