### ISSUE TITLE
Approximation of preconditionor of A

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#656]
This is a follow up to the aspect devel discussion on the speed of aspect. I have been timing some of the parts of the solver and found out that in some cases (cases with a nonlinear rheology and a lot of nonlinear iterations), the approximation of the A^-1 matrix (with a CG solver with a 'loose' tolerance of 1e-2) is by orders of magnitude the largest time consumer. The S^-1 matrix and the solving the system take compared to that a negligible amount of time.

I did some tests with the crustal_model_3D and found that it is possible to speed it up to about 2.5 times without significantly changing the solution by setting the tolerance from 1e-2 to 5e-1. What happens is that more linear iterations are required, but they become a lot cheaper. I am not saying that this value of the tolerance will be ideal for all cases, but I think that this value should become available as a parameter, since a speed up of 2.5 times is quite significant. 

I think it is safe because it only changes the preconditioner. Furthermore the results are practically the same (both the nonlinear residual and visually). But before I invest time in making this available in the form of a pull request, I would like to make sure that this is actually safe and desirable to do.

**Comment by bangerth** [comment]
I think that's a reasonable approach. You'll pay in terms of outer iterations, but the accuracy of the solution of the linear system should be unaffected.

If you write such a patch, please add a paragraph also to the section of the manual that talks about speeding up simulations.

**Comment by tjhei** [comment]
What is the number of inner A solver iterations per outer iteration that your test problem requires? (see statistics file and divide the two numbers). I assume AMG is a very poor preconditioner in your case.

**Comment by MFraters** [comment]
With normal tolerance it goes from about 10 to about 50 at non-linear iteration 100 (see table below).  With the adjusted tolerance it is about 1.5 to 5.5 at nonlinear iteration 100. I also noticed that the crustal_model_3D.prm doesn't use the material averaging, which may help a lot, so I can also look into that.

Should I also make the tolerance for the schur complement available as a parameter while I am at it? It might be interesting to also perform tests with this parameter.

Table with tolerance 1e-2:

timestep | it. number | it. stokes | velo it. Stokes prec. | it. schur c. Stokes prec. | it. st. / velo it. st. prec.
----------- | ------------- | ------------- | ------------------------- | -------------------------------- | ---------------------------
0 | 1 | 17 | 102 | 244 | 6
0 | 2 | 111 | 1274 | 1818 | 11.5
0 | 3 | 26 | 275 | 435 | 10.6
0 | 4 | 23 | 258 | 393 | 11.2
... | ... | ... | ... | ... | ...
0 | 100 | 2 | 101 | 49 | 50
1 | 1 | 17 | 108 | 213 | 6.3
1 | 2 | 126 | 1634 | 1831 | 13.0
1 | 3 | 27 | 299 | 449 | 11.1
1 | 4 | 24 | 263 | 350 | 11.0
... | ... | ... |  ... | ... | ...
1 | 100 | 4 | 220 | 78 | 55
2 | 1 | 22 | 654 | 298 | 29.7
2 | 2 | 19 | 565 | 298 | 29.7
2 | 3 | 16 | 513 | 254 | 32.1

Table with tolerance 5e-1:

timestep | it.number | it. stokes | velo it. Stokes prec. | it. schur c. Stokes prec. | it. st. / velo it. st. prec.
----------- | ------------- | ------------- | ------------------------- | -------------------------------- | ---------------------------
0 | 1 | 48 | 49 | 742 | 1
0 | 2 | 250 | 437 | 4084 | 1.7
0 | 3 | 52 | 78 | 893 | 1.5
0 | 4 | 46 | 50 | 771 | 1.1
... | ... | ... | ... | ...
0 | 100 | 6 | 33 | 117 | 5.5
1 | 1 | 50 | 54 | 708 | 1.1
1 | 2 | 250 | 657 | 5245 | 2.6
1 | 3 | 53 | 71 | 881 | 1.3
1 | 4 | 43 | 68 | 649 | 1.6
... | ... | ... |  ... | ... | ...
1 | 100 | 9 | 29 | 154 | 3.2
2 | 1 | 60 | 209 | 939 | 3.5
2 | 2 | 42 | 110 | 648 | 2.6
2 | 3 | 36 | 103 | 555 | 2.9

**Comment by tjhei** [comment]
> With normal tolerance it goes from about 10 to about 50 at non-linear iteration 100 (see table below). With the adjusted tolerance it is about 1.5 to 5.5 at nonlinear iteration 100.

As expected, 50 iterations for a tolerance of 1e-2 is pretty bad.

> I also noticed that the crustal_model_3D.prm doesn't use the material averaging, which may help a lot, so I can also look into that.

Yes, I assume this will help a lot in your case.

**Comment by MFraters** [comment]
The material averaging helps a lot, but this with this trick the Stokes solver is still more than twice as fast as without this trick. It is actually interesting to see that the solver Stokes system is only the third time consumer with 7.3% of the total time, far behind the assembly of the system with 67% of the total time and build stokes preconditioner with 25%.

**Comment by bangerth** [comment]
Is this in debug or release mode?

**Comment by MFraters** [comment]
good point, this was in debug mode. In release mode Solve stokes is the second time consumer togheter with Build stokes preconditioner with 25% of the total time, behind Assemble Stokes system with 49%.

**Comment by bangerth** [comment]
Hm, this is then either a very expensive material model to evaluate, or a particularly cheap problem to solve... But this is not relevant for the current PR.

**Comment by bangerth** [comment]
Fixed by #660.
