### ISSUE TITLE
Deprecation warnings with recent deal.II

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#665]
Deal.II https://github.com/dealii/dealii/pull/1352 marks a function of VectorBase (deal.II/lac/trilinos_vector_base.h:1674) as deprecated that we currently use in ASPECT (namely `add(scalar s)`, used in helper_funtions:634 and 724). This leads to warnings at compile-time for recent deal.II versions. We should think about what to use instead.

**Comment by bangerth** [comment]
Hm. I think I never saw the purpose of that function, but I realize now that there may be more to its usefulness when adjusting the pressure. Maybe we need to undo the deprecation. What do you think, @tjhei ?

**Comment by tjhei** [comment]
Yes, I was thinking about that too. There is no easy way to do this except writing a loop over individual elements, so maybe we shouldn't have deprecated it.

**Comment by bangerth** [comment]
I've opened https://github.com/dealii/dealii/issues/1848

**Comment by gassmoeller** [comment]
#668, #675 and dealii/dealii#1881 should have removed all warnings. I will close this.
