### ISSUE TITLE
Hide stupid warnings

### ISSUE THREAD

**Issue by jperryhouts** [geodynamics/aspect#669]
#668 got me thinking about annoying warnings. I think it should be somewhat of a priority to eliminate them in release versions, and it occurred to me that I've had the `-Wno-literal-suffix` flag in my compilation script for a while because of this ancient version of openmpi, and maybe it would be worth just making it a default option (or at least recommended in the installation instructions).

The problem is that Debian (and presumably Ubuntu) have a pretty old version of openmpi, and compiling anything with C++11 features throws a lot of warnings like:
```
invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
_STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
```
It's been discussed on the Debian mailing list (https://lists.debian.org/debian-science/2015/10/msg00079.html) and doesn't seem like there's a whole lot of enthusiasm about fixing it any time soon.

So, since so many people who use Aspect run Debian/Ubuntu, is it worth making `-D CMAKE_CXX_FLAGS="-Wno-literal-suffix"` a default option in the releases for the sake of shielding new users from this?

**Comment by bangerth** [comment]
Just for reference, I use mpich on by ubuntu laptop.

I'd be ok with a patch to deal.II that adds this switch if we use openmpi. It's a rather unusual warning anyway, so I'm not overly concerned that we accidentally miss something.

**Comment by bangerth** [comment]
For reference, in deal.II the handling of flags for GCC is done in `cmake/setup_compiler_flags_gnu.cmake`. MPI is set up in `cmake/configure/configure_1_mpi.cmake`. I don't recall which runs earlier. Depending on this you might have to set flags in one or the other.

Out of curiosity, do you see these issues also when compiling deal.II?

**Comment by jperryhouts** [comment]
Yes, and Trilinos if I remember correctly, but not much we can do there.

**Comment by gassmoeller** [comment]
At least on my laptop with Ubuntu 14.04 and openmpi I do not see anything. Which Debian are you using? Anyway, if the warning is useless, lets remove the flag for now in that case.

**Comment by tjhei** [comment]
I have seen the warning before. I normally just go into the system header and remove the whitespace. This might be ubuntu 15.4 or .10 only?

**Comment by jperryhouts** [comment]
Last I saw it was in Debian testing, which is usually ahead of Ubuntu in versions, but sometimes has different patches (in this case I don't think the version has changed in a long time, so I assume the only difference is patches). I can't reproduce it in Ubuntu 15.10, so I guess it's been patched there. I'll check again in Debian later.

**Comment by jperryhouts** [comment]
Although frankly, if it's patched in Ubuntu I assume that will cover most of the new users who would want to be shielded from this sort of thing anyway. Maybe I should close this issue?

**Comment by jperryhouts** [comment]
I haven't seen these warnings recently so I'm going to close this issue for now. (I haven't tried a `make distclean` on that machine in a while either, though).

**Comment by jperryhouts** [comment]
`make distclean` did indeed make the warnings return (I guess cmake's variables are more persistent than I thought). I submitted a PR to deal.II to handle this case (https://github.com/dealii/dealii/pull/1961)
