### ISSUE TITLE
compilation on mac

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#715]
I am suddenly getting the following error on my mac when compiling aspect:

make[2]: *** No rule to make target `/Applications/deal.II.app/Contents/Resources/opt/petsc-38ae631/lib/libHYPRE.a', needed by `aspect'.  Stop.

The compilation on the linux cluster is still fine (but it had a newer version of deal.ii). Did some requirements (or required options) of deal.ii change?

**Comment by bangerth** [comment]
Did you upgrade the deal.II package? What is in your `/Applications/dea.II.app/Contents/Resources/opt` directory?

**Comment by MFraters** [comment]
No, but I think I have found the problem. It looks like the deal.ii I set up on my mac has for a few of the petsc directories setup incorrectly. I just don't understand yet why it became only now a problem, because as far as I can see there where no petsc related stuff in the changes of the last few days. 

But since it seems to be a problem on my setup I will close the issue.
