### ISSUE TITLE
[Post deal.II 8.4] Let deal.II handle prm file continuation lines

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#721]
With the patches referenced in https://github.com/dealii/dealii/issues/333 deal.II can now handle continuation lines in prm files (i.e., lines ending in a backslash). This allows us to remove the corresponding code in ASPECT (see `main.cc`). Let's do that after we switch to deal.II 8.4.

**Comment by class4kayaker** [comment]
In progress

**Comment by gassmoeller** [comment]
Fixed by #1046
