### ISSUE TITLE
MPI run failed but deal.ii works

### ISSUE THREAD

**Issue by laurentang001** [geodynamics/aspect#731]
Deal.ii successfully installed as well as its compilation and tests (in progress : success for up to step-16 but step-5).

ASPECT 1.3 successfully build but run fails (PETSC set ON or OFF). See log files.

Snow Leopard (OS X 10.6.8). Inetl Core 2 Duo. GNU cc 5.3.0, OpenMPI 1.8.8 (NB currently Xcode and GNU CC and Open MPI totally rebuilt to verify correct installation).

[my-make-error-1_2-1_3.log.zip](https://github.com/geodynamics/aspect/files/106967/my-make-error-1_2-1_3.log.zip)
[my-make-error-1_2-1_3.log.zip](https://github.com/geodynamics/aspect/files/106968/my-make-error-1_2-1_3.log.zip)

**Comment by tjhei** [comment]
> ASPECT 1.3 successfully build

In your logfile it looks like you do not compile correctly.

For OSX I can recommend using the binary packages. Can you try https://github.com/luca-heltai/dealii/releases please?

**Comment by bobmyhill** [comment]
In case this is still a problem for anyone, homebrew does an excellent job (brew install dealii), with the exception of zlib warnings when trying to compile aspect (for me, anyway). As I wanted to build deal.II for source anyway, I then built from the github repo (8.4.0-pre) using the dependencies installed by homebrew. Aspect then compiled perfectly (no zlib warnings).

Only issue I came across was a bunch of tests failing with ctest -V, apparently due to a difference in the number of Schur complement iterations in the Stokes preconditioned (mostly smaller) or small differences in depth averages (last decimal point).

**Comment by bobmyhill** [comment]
(Update to previous message)
In case this is still a problem for anyone, homebrew does an excellent job (brew install dealii --HEAD). The --HEAD flag installs the latest version from the github repository (8.4.0-pre), which includes a patch related to zlib warnings.

**Comment by laurentang001** [comment]
Dear Sir : 

In fact, I found that two mpirun existed in my APPLE computer : one the one hand, mpi installation via Xcode ; on the other hand, the mpi installation I build myself with to my own GNU cc compiler suite. 

I build deal.ii with my own OpenMPI software, but run Aspect with the Xcode mpirun, and it failed. Besides, I had to fix some issues with the STEP tutorial. For example, a STEP file needed METIS that was not installed in my computer, and I had to build it to incorporate in dela.ii. Next, STEP-34 needs OpenCascade to be incorporated in deal.ii too. However, SETP-34 with OpenCascade compiled as serial. I am currently building deal.ii with OpenCascade as MPI-compiled, and I will try it. 

Eventually, I will try all these with ASPECT. A quick guide installation of deal.ii will probably written and issued by myself, dedicated to Mac OS X platform, with informations of third-party software needed by deal.ii. 

Kind regards, 


Laurent Delphin 


!=========================================== 


----- Mail original -----

De: "Timo Heister" <notifications@github.com> 
À: "geodynamics/aspect" <aspect@noreply.github.com> 
Cc: "laurentang001" <space-eu.delphin@laposte.net> 
Envoyé: Mercredi 27 Janvier 2016 18:50:33 
Objet: Re: [aspect] MPI run failed but deal.ii works (#731) 





ASPECT 1.3 successfully build 



In your logfile it looks like you do not compile correctly. 

For OSX I can recommend using the binary packages. Can you try https://github.com/luca-heltai/dealii/releases please?

**Comment by tjhei** [comment]
Yes, you need to have a single mpi library and use it to compile deal.II, all the dependencies, and finally also use the mpirun/mpiexec wrapper from this library.

I am closing this issue.
