### ISSUE TITLE
[Meta] Make assembly more modular

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#733]
The equations we assemble used to be hard-coded in assembly.cc (with the exception of the free surface terms). After discussion in December, we have a plan forward.

**Comment by gassmoeller** [comment]
This was achieved in a lot of pull requests. While there is still one issue open (about the documentation), the core part is essentially resolved. Lets not keep to many issues open, just because small things could be improved (having hundreds of issues is not helping keeping them relevant).
