### ISSUE TITLE
Move temperature/composition assemblers to the new scheme

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#743]
Do the same as we already do for the Stokes system.

Related to #733.

**Comment by bangerth** [comment]
@gassmoeller -- I think you already did this for all parts, right?

**Comment by gassmoeller** [comment]
Yes, give me a day or two to clean up the parts, but I can open the PR then.

**Comment by gassmoeller** [comment]
Forget my last comment, I was confused (currently cleaning up my old branches and PRs). Yes, this should already be closed by #775 and #769.

**Comment by bangerth** [comment]
Then let's close it indeed.
