### ISSUE TITLE
Introduce AdvectionField::scalar_extractor

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#755]
#661 has code like this, that I suspect is repeated in other places as well:
```
     const FEValuesExtractors::Scalar solution_field
       = (advection_field.is_temperature()
          ?
          introspection.extractors.temperature
          :
          introspection.extractors.compositional_fields[advection_field.compositional_variable]
         );
```
The `AdvectionField` class already has a number of convenience functions that together with `Introspection` yield components, blocks, etc, that correspond to a particular advection field. We should also add such a function that creates an FEValues extractor to make code such as the one above simpler.

**Comment by yinghe616** [comment]
so I think this issue is OK to close?

**Comment by bangerth** [comment]
Yes. Thank you!
