### ISSUE TITLE
S40RTS and SAVANI initial temperature models use "vs to density scaling" as parameter names

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#760]
We almost always use parameter names whose first letter is capitalized. In this case I think there isn't even much of an argument that it might be a symbol because people will probably have an easier time reading Vs over vs when thinking of the shear wave velocity.

It should be possible to rename these parameters in a backward compatible way by using the parameter aliases that were introduced a while back.

**Comment by Shangxin-Liu** [comment]
Just recalled this discussion from Newsletter on mailing list. I also changed the vs to Vs in the last commit patch controlling the max order. @bangerth

**Comment by bangerth** [comment]
OK. In general, keep each patch self-contained and to one issue. In other words, the correct procedure for the future would be to have one patch for the "vs vs. Vs" issue, and one for the issue discussed in #759 .

**Comment by gassmoeller** [comment]
I think this issue was solved by #759, and can be taken of the list for 1.4 . I will close it for now. If someone objects, feel free to reopen.

**Comment by Shangxin-Liu** [comment]
Yes. This has been solved.
