### ISSUE TITLE
Disappearing Particles

### ISSUE THREAD

**Issue by hlokavarapu** [geodynamics/aspect#762]
I have accidentally stumbled on this "bug" while investigating the convergence rate of particle integration scheme, Euler using Richardson extrapolation. The input data for my script are the particle position data generated with variable CFL numbers: 1.0, 0.5, 0.25, 0.125, and 0.0625. 

The particles are vanishing when the CFL >= 1.0

![vanishingparticles](https://cloud.githubusercontent.com/assets/1869576/13193481/e1895c10-d72d-11e5-9056-4f920f9ea0b0.gif)

Because of the numerical error of Euler, the particles are being pushed outside of the domain and are being "lost."

Should this be the expected behavior of a flow such as this?

To reproduce:
        mpirun -np 1 circular_tracer_flow_1.0.prm

[circular_tracer_flow_1.0.prm.zip](https://github.com/geodynamics/aspect/files/138892/circular_tracer_flow_1.0.prm.zip)

**Comment by hlokavarapu** [comment]
After reconvening with Dr. Puckett, it is clear that this is expected.

**Comment by gassmoeller** [comment]
Ah, you were too fast, I was about to write an answer :smile:. Yes this is expected. The forward euler integration accumulates errors over time and in this flow field they all increase the distance of the particles to the center. Increasing the CFL number increases the accumulated error.
But the animation is still nice to watch.
