### ISSUE TITLE
Exception error on MPI process while running postprocessor

### ISSUE THREAD

**Issue by Shangxin-Liu** [geodynamics/aspect#773]
When I'm running the time-dependent cases with ASPECT, sometimes the jobs will fail at the post processing part of one time step after several or dozens of hours with the following error information (for example on one case):

Exception on MPI process <9> while running postprocessor <N6aspect11Postprocess13VisualizationILi3EEE>: 8> while running postprocessor <N6aspect11Postprocess13VisualizationILi3EEE>:

---

An error occurred in line <6156> of file </home/shangxin/sources/dealii_newest/dealii/source/base/data_out_base.cc> in function
    void dealii::DataOutInterface<dim, spacedim>::write_vtu_in_parallel(const char_, MPI_Comm) const [with int dim = 3; int spacedim = 3; MPI_Comm = ompi_communicator_t_]
The violated condition was:
    err==0
The name and call sequence of the exception was:
    ExcMessage("Unable to open file with MPI_File_open!")
Additional Information:
Unable to open file with MPI_File_open!

---

Aborting!

This error doesn't always appear and maybe has ~50% percent probability to happen. Any idea what causes this error?

**Comment by trajaona** [comment]
I also have the exact same issue as Shangxin. Does anyone has suggestion to solve it?

**Comment by tjhei** [comment]
> maybe has ~50% percent probability to happen

You say 50% but it only happens after dozens of hours, how can that be? Does this happen with a simple 2d problem? Does it happen on a single node? In order for me to reproduce it, I need to know the exact setup.

**Comment by gassmoeller** [comment]
Other questions to think about: Does that problem also happen when you set 'Number of grouped files = 0' (It should not, if it does then it is likely a problem with your filesystem, e.g. to many files)? Which version of ASPECT and deal.II do you use (before or after the recent changes to the visualization output of ASPECT?)?

**Comment by Shangxin-Liu** [comment]
Indeed.. The 50% actually means that after a long time running, the job will fail either with this postprocess error or the out of boundary error I also posted… The test of simple 2d problem can finish fast, I’m setting up a long running time for it. I haven’t tried on single node.

**Comment by Shangxin-Liu** [comment]
Yes. I’m now also thinking of this probability. Now my “Number of grouped files = 1” . Previously the 1 doesn’t work but recently when I made test of the newest git hub ASPECT the 1 worked so I just reset this parameter from 0 to 1:-). However, Grant tole me his job has been running 30 hours with no error and the only difference I can see is that he still uses “Number of grouped files = 0”. Now I just submitted jobs with "0 grouped files”. Let’s see.

I’m using the newest version of ASPECT and dealii from fit hub.

**Comment by bangerth** [comment]
@Shangxin-Liu -- any news about this?

**Comment by gassmoeller** [comment]
If there are no news about this issue I would assume it does not longer occur, and I would close it in a few days. The output seems to work stable for any given number of grouped files on the clusters I use. If there are any problems for other people please let us know.
