### ISSUE TITLE
"index out of bound" error when building Stokes preconditioner

### ISSUE THREAD

**Issue by Shangxin-Liu** [geodynamics/aspect#774]
Another "sometimes" error also puzzles me. This error can happen after a long running time when building Stokes preconditioner in one time step. **Here is the error information in the record file**:

**\* Timestep 3101:  t=1.74956e+18 seconds
   Solving temperature system... 1 iterations.
   Rebuilding Stokes preconditioner...0 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
1 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
3 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
4 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
25 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
23 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
24 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)
26 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound              = 1840174(160) 1167 2147483647(0)

**And the error information in the error file**:

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

---

[br236:114595] 7 more processes have sent help message help-mpi-api.txt / mpi-abort
[br236:114595] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

---

mpirun has exited due to process rank 1 with PID 114597 on
node br236 exiting improperly. There are two reasons this could occur:
1. this process did not call "init" before exiting, but others in
   the job did. This can cause a job to hang indefinitely while it waits
   for all processes to call "init". By rule, if one process calls "init",
   then ALL processes must call "init" prior to termination.
2. this process called "init", but exited without calling "finalize".
   By rule, all processes that call "init" MUST call "finalize" prior to
   exiting or it will be considered an "abnormal termination"

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

---

I somewhat feel that this is a cluster technical issue but I'd like to make sure.
Any idea why this error happens?

**Comment by tjhei** [comment]
How many unknowns do you have in this problem?

**Comment by Shangxin-Liu** [comment]
Copied from the record file:

Number of active cells: 202634 (on 5 levels)
Number of degrees of freedom: 7270083 (5280402+229547+1760134)

**Comment by tjhei** [comment]
I haven't seen that before but it could be that you are running out of RAM. Is this error reproducible?

**Comment by tjhei** [comment]
I found the code inside the multigrid preconditioner in ML that triggers the abort: https://searchcode.com/codesearch/view/51641210/
The index 2147483647 looks like a signed integer overflow. @bangerth do you have an idea?

**Comment by bangerth** [comment]
Yes, this vaguely looks like -1 when represented as an `unsigned int`. I have no idea where that may come from.

That would correspond to the `external[i]` value in the error message. For reference: The error message is generated in the following context:
```
  for (i = 0; i < N_external; i++) {
    neigh_proc  = external[i]/max_per_proc;
    if ( neigh_proc >= nprocs ) {
       printf("%d : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound \
             = %d(%d) %d %d(%d)\n", proc, neigh_proc, nprocs, max_per_proc, 
             external[i], i);
       exit(1);
    }
```
And for comparison, this is the output:
```
1 : ML_CommInfoOP_GenUsingGIDExternals warning : index out of bound = 1840174(160) 1167 2147483647(0)
```

**Comment by Shangxin-Liu** [comment]
Yes. This error happened several times already after a long running time
(10~25 hours). If I'm running out of memory, how do I prevent this error?
Using more nodes?

**Comment by bangerth** [comment]
If I see this right, you have about 7M unknowns on 160 processors. That seems like a totally reasonable number and shouldn't be a problem. Of course, it may be that somewhere deep down in one of the libraries, there could be a memory leak and in that case over many time steps you would accumulate enough lost memory to run out of. 

But this doesn't look to me like one of those cases. If you run out of memory, the operating system typically kills your job, you don't run into an assertion...

**Comment by Shangxin-Liu** [comment]
Another phenomenon about this problem which is a bit weird: This error doesn't happen on our another smaller cluster that uses gcc/4.9.2 and openmpi/1.10.1, but will usually happen on our main cluster Blueridge, which is using gcc/4.7.2 and openmpi/1.6.4. I can not conclude this is the gcc/openmpi version  problem because it's running on different clusters. But I'll try also building ASPECT with gcc/4.9.2 and openmpi/1.10.1 on Blueridge.. 

btw, as for the Trilinos, we're using the version 11.4.3, is it ok?

**Comment by bangerth** [comment]
As we talked about when I was in Virginia, none of the versions of software you mention triggers any memory of "this version is bad". I really don't know what to do about this.

Does this still happen occasionally? Is it repeatable and reproducible in exactly the same place?

**Comment by Shangxin-Liu** [comment]
I have not made the new time-dependent tests. Our clusters were all just updated from the mainteinence and we are rebuilding ASPECT on it. I'll keep you informed when we perform the new tests. @bangerth @tjhei @gassmoeller

**Comment by gassmoeller** [comment]
Any news on this issue after the update of your clusters? I am currently doing some cleanup for old issues, and if there are no news, I would close this issues in a few days. Let us know if the bug reappears.
