### ISSUE TITLE
[Meta] Initialize reaction terms to zero in material models that don't explicitly set them.

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#777]
#776 fixes a case where we don't initialize the reaction terms in the 'Simpler' material model to zero. This is likely also the case for the other material models that do not explicitly use/set the reaction rates for anything. Not setting them to zero leads to trouble with FPEs if someone is using such a material model with compositional fields (which in those cases are not used for the material description at all, but only for tracking).

Go through all of them to fix this.

**Comment by gassmoeller** [comment]
I have actually checked all models in source/ for #776. 'Simpler' was the only one that did not set them. Some others do not set them explicitly, but use the old interface, in which case the `Interface::reaction_terms()` will set them to zero. So we should be fine.

I have not checked benchmarks/ and tests/ though.

**Comment by bangerth** [comment]
Let's see that we take a look at this before the 1.4 release. I think we only really need to look into benchmarks/ as that's the only user-facing part.
