### ISSUE TITLE
'Run postprocessors on initial refinement' only outputs visualization once

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#802]
The option 'Run postprocessors on initial refinement' should execute all postprocessors after every initial adaptive refinement step. However, currently it only writes the visualization output once. This might have been introduced accidentally in #236. Anyway it should be fixed (and the particle output which currently behaves the same way should be changed as well).

**Comment by bangerth** [comment]
How do you want to change it? Create visualization data only for the last pre-refinement step? I think that's what you already do for the particle postprocessor, and that seems like the right solution.

**Comment by gassmoeller** [comment]
I was thinking of actually writing output every refinement step, as was @tjhei's suggestion in #801

>  "Run postprocessors on initial refinement" should run tings after every adaptive step.

I now realize that this works for paraview, where the output time is stored in the .pvd file so the first output files would all be associated with a time of 0, but would be confusing for visit. But since this option is rarely used, and usually people that use it actually want to see the development over the first initial refinement steps I would think writing one output file per initial adaptive refinement is exactly what these users expect to happen.

**Comment by bangerth** [comment]
Yes, I think that's a fair approach.
