### ISSUE TITLE
Make Aspect virtual machine compatible to VMWare

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#82]
The current Aspect virtual machine uses a file format .ova, which in principle is compatible with most virtualization software. Currently however, there are Oracle specific extensions included that seem to prevent the image from running for example with an VMware software (I just got a question from a potential new aspect user about this, have not checked it myself). Is it possible to remove these extensions in future releases to increase compatibility of the image? I am too less involved in the process of creating these images to know the problems/work related, but Jonathan or Timo could you take a look at this at some point?

**Comment by tjhei** [comment]
Rene, can this be closed?

**Comment by gassmoeller** [comment]
I think so. I never heard again from somebody who wanted to use VMware for the virtual machine (maybe it even works now? I can not test that.). Lets close it for now, and if somebody complains, we can reopen or create a new issue.
