### ISSUE TITLE
Implement the RK4 particle integration method so it is fourth-order in time

### ISSUE THREAD

**Issue by egpuckett** [geodynamics/aspect#831]
See #828 for a discussion of the current accuracy of RK4 and #829 for further discussion concerning current development work in general on particle 'tracing' in ASPECT.

**Comment by egpuckett** [comment]
It now occurs to me that in order to have a fourth order Runge-Kutta method to integrate along the  particle paths, the underlying velocity field is going to have to be at least fourth order in time and space. As I understand ASPECT, one can make it fourth order in space simply by using the appropriate FEM basis functions, such a Q_4.  However, my understanding is that at the moment there is only one time stepping method and (I believe) it is (globally) second-order. Is this correct?

**Comment by gassmoeller** [comment]
I think our agreement is that it is possible to make the existing algorithm 4th order in space by increasing the velocity element degree, and making it 4th order in time would require a rewriting of the whole ASPECT time integration scheme, with limited knowledge what would happen to all other parts of the code, so I will close this issue for now.
