### ISSUE TITLE
Initialization and computation on additional variables

### ISSUE THREAD

**Issue by class4kayaker** [geodynamics/aspect#834]
I have currently been working on adding an auxiliary model, and after being pointed at the signals for the solution computation I have noted there is no way to initialize the variable and that there is no way to compute the update matrix.

As an overly simplistic test case that reveals the extent of the current problem, consider an additional location dependent, non-composition variable that is only time dependent. To trivialize the matrix solve, a DGQ(0) element may be assumed. The current design obviously does not make initialization simple, much less the necessary time update.

**Comment by bangerth** [comment]
Did you find a solution, or why did you close this again?

The signals mechanism is relatively new. I'm not surprised we lack signals for specific tasks, simply because nobody needed them so far. But they're easy to add -- patches welcome!

**Comment by class4kayaker** [comment]
Issue was closed due to wanting to check on wording as the issue was originally posted while intending to work on a better description elsewhere and hitting enter in the title field.

I have not currently found a solution, and due to the nature of the problem any solution would benefit from some design iteration as it is closely tied to the internals of the model.

Initialization is likely the simpler of the two aspects of the given problem, though even there the question is how much of the initialization can/should the simulator handle and how much needs to be general. 

For the update section, there is a question of how best to handle cases like iterative level set reinitialization (more computationally expensive/non-ideal method, but a standard approach) where the solution cannot necessarily be obtained using a single matrix solve in a standard part of the timestep.

Both problems are likely to require write access to the current solution, and the update step would have a smaller general memory footprint if it has access to the system matrix.

**Comment by bangerth** [comment]
OK. These are concrete design questions that are best answered in small increments. How about we close the current issue for now, and if you hit a concrete question about one aspect of the implementation, open a separate issue?

**Comment by class4kayaker** [comment]
Sounds good.

Closing issue for being overly complex.
