### ISSUE TITLE
Initial topography for free surface is only applied to coarse mesh

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#897]
There is a shared library in the Crameri benchmark folder that allows to have a perturbed surface (specified by a function) as initial condition. This is a very useful feature to have, however, the perturbation of the surface is only applied to the coarse mesh (so if i.e. for the box geometry, if `set X repetitions = 0`, and instead a number of global refinements are used, the initial topography is not applied). 
Maybe we can extend this functionality to also work on global refinements (in the first time step), or at least document better that this is how it works.

**Comment by tjhei** [comment]
Agreed. Another (temporary) solution would be to add an ``assert`` the triggers if global refinements is >0.

**Comment by ian-r-rose** [comment]
I agree, Juliane. Part of the reason that I kept this as a plugin was that
I did not see an easy way to extend this to the case with initial mesh
refinement.

Perhaps there could be a do-nothing virtual function in the base class
(something like ``perturb_surface()``) which is only overridden when we
have a well defined way to do that. This would need to be called after all
the initial refinement.

Another thing we could do is define a boundary manifold that matches the
perturbation we want. This may be cleaner, and would have the correct
behavior on refinement. The manifold would then be detached later (as is
already done, see line 2097 of ``core.cc``)

**Comment by jdannberg** [comment]
Thanks for the suggestions!
It is not something that is super urgent for me right now, for my model I just needed some time to figure out that I had to use the X repetitions instead of global refinements. So I thought I'd write it down somewhere so that we have it on the to-do list.

**Comment by gassmoeller** [comment]
This is now possible using a signal mechanism (see #1187). While it is not implemented for the Crameri benchmark (that one uses a modified geometry model right now) it is possible for 'normal' box models. I will therefore close this issue.
