### ISSUE TITLE
composition solver scheme is different in Advection_only compared to other solver schemes

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#905]
In the all other solver schemes, we solve all of the compositional fields before we update the `current_linearization_point` with the solution, but in the `Advection_only` scheme we update the `current_linearization_point` after each individual solve.

**Comment by bangerth** [comment]
This only affects the rhs of the composition equations, right? The left hand side operators for the composition equations are all independent of the material model, and so independent of whether or not we have already updated individual composition components.

**Comment by gassmoeller** [comment]
Closed by #1136. Thanks @class4kayaker!
