### ISSUE TITLE
postprocessors crash on MPI with deal.ii 8.5.0-pre

### ISSUE THREAD

**Issue by MFraters** [geodynamics/aspect#909]
I noticed this when I updated aspect and deal.ii yesterday. When I switch to 8.4.1, it worked again, but I thought it would be a good idea to highlight the problem. 

I noticed the problem for the heat flux statistics and the velocity boundary statistics. The output I got was: 

-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 1.5.0-pre
--     . running in DEBUG mode
--     . running with 1 MPI process
--     . using Trilinos

-----------------------------------------------------------------------------

Number of active cells: 64 (on 2 levels)
Number of degrees of freedom: 5490 (2295+135+765+765+765+765)

Number of free surface degrees of freedom: 405
*** Timestep 0:  t=0 years
   Solving mesh velocity system... 0 iterations.
   Solving temperature system... 0 iterations.
   Solving C_1 system ... 0 iterations.
   Solving C_2 system ... 0 iterations.
   Solving C_3 system ... 0 iterations.

   Postprocessing:

--------------------------------------------------------
An error occurred in line <141> of file </home/aspect/deal.ii/deal.ii_2016-06-07/dealii/include/deal.II/base/mpi.templates.h> in function
    void dealii::Utilities::MPI::internal::all_reduce(ompi_op_t* const&, const std::vector<T>&, ompi_communicator_t* const&, std::vector<T>&) [with T = double; MPI_Op = ompi_op_t*; MPI_Comm = ompi_communicator_t*]
The violated condition was: 
    values.size() == output.size()
The name and call sequence of the exception was:
    ExcDimensionMismatch(values.size(), output.size())
Additional Information: 
Dimension 6 not equal to 0

Stacktrace:

-----------
#0  /home/aspect/deal.ii/deal.ii_2016-06-07/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: void dealii::Utilities::MPI::internal::all_reduce<double>(ompi_op_t* const&, std::vector<double, std::allocator<double> > const&, ompi_communicator_t* const&, std::vector<double, std::allocator<double> >&)
#1  /home/aspect/deal.ii/deal.ii_2016-06-07/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: void dealii::Utilities::MPI::max<double>(std::vector<double, std::allocator<double> > const&, ompi_communicator_t* const&, std::vector<double, std::allocator<double> >&)
#2  ./aspect: aspect::Postprocess::VelocityBoundaryStatistics<3>::execute(dealii::TableHandler&)
#3  ./aspect: aspect::Postprocess::Manager<3>::execute(dealii::TableHandler&)
#4  ./aspect: aspect::Simulator<3>::postprocess()
#5  ./aspect: aspect::Simulator<3>::run()
#6  ./aspect: main

--------------------------------------------------------

[gaia:50281] *** Process received signal ***
[gaia:50281] Signal: Aborted (6)
[gaia:50281] Signal code:  (-6)
[gaia:50281] [ 0] /lib64/libpthread.so.0[0x31a1a0f7e0]
[gaia:50281] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x31a1232625]
[gaia:50281] [ 2] /lib64/libc.so.6(abort+0x175)[0x31a1233e05]
[gaia:50281] [ 3] /home/aspect/deal.ii/deal.ii_2016-06-07/dealii/build/lib/libdeal_II.g.so.8.5.0-pre(_ZN6dealii18deal_II_exceptions9internals5abortERKNS_13ExceptionBaseEb+0x3b)[0x7ffff5ae6b48]
[gaia:50281] [ 4] ./aspect(_ZN6dealii18deal_II_exceptions9internals11issue_errorINS_18StandardExceptions20ExcDimensionMismatchEEEvNS1_17ExceptionHandlingEPKciS7_S7_S7_T_+0x34)[0x9d08fc]
[gaia:50281] [ 5] /home/aspect/deal.ii/deal.ii_2016-06-07/dealii/build/lib/libdeal_II.g.so.8.5.0-pre(_ZN6dealii9Utilities3MPI8internal10all_reduceIdEEvRKP9ompi_op_tRKSt6vectorIT_SaIS9_EERKP19ompi_communicator_tRSB_+0xa7)[0x7ffff5b9456f]
[gaia:50281] [ 6] /home/aspect/deal.ii/deal.ii_2016-06-07/dealii/build/lib/libdeal_II.g.so.8.5.0-pre(_ZN6dealii9Utilities3MPI3maxIdEEvRKSt6vectorIT_SaIS4_EERKP19ompi_communicator_tRS6_+0x26)[0x7ffff5b9463b]
[gaia:50281] [ 7] ./aspect(_ZN6aspect11Postprocess26VelocityBoundaryStatisticsILi3EE7executeERN6dealii12TableHandlerE+0xad9)[0xaba279]
[gaia:50281] [ 8] ./aspect(_ZN6aspect11Postprocess7ManagerILi3EE7executeERN6dealii12TableHandlerE+0x38)[0xa9eb7a]
[gaia:50281] [ 9] ./aspect(_ZN6aspect9SimulatorILi3EE11postprocessEv+0x94)[0xb884a4]
[gaia:50281] [10] ./aspect(_ZN6aspect9SimulatorILi3EE3runEv+0x3ea)[0xbb266a]
[gaia:50281] [11] ./aspect(main+0x575)[0xd04eeb]
[gaia:50281] [12] /lib64/libc.so.6(__libc_start_main+0xfd)[0x31a121ed5d]
[gaia:50281] [13] ./aspect[0x7fb279]
[gaia:50281] *** End of error message ***
Aborted (core dumped)

**Comment by tjhei** [comment]
can you try out the following fix?
```
--- a/source/postprocess/velocity_boundary_statistics.cc
+++ b/source/postprocess/velocity_boundary_statistics.cc
@@ -129,9 +129,9 @@ namespace aspect
             local_min_values.push_back (local_min_vel[*p]);
           }
         // then collect contributions from all processors
-        std::vector<double> global_max_values;
+        std::vector<double> global_max_values (local_max_values.size());
         Utilities::MPI::max (local_max_values, this->get_mpi_communicator(), global_max_values);
-        std::vector<double> global_min_values;
+        std::vector<double> global_min_values (local_min_values.size());
         Utilities::MPI::min (local_min_values, this->get_mpi_communicator(), global_min_values);
 
         // and now take them apart into the global map again
```

**Comment by MFraters** [comment]
Yes, that helps!

**Comment by MFraters** [comment]
The same trick works for the heat flux statistics postprocessor

**Comment by tjhei** [comment]
great, would you mind opening up a pullrequest?

**Comment by MFraters** [comment]
sure, I will also check the other post-processers
