### ISSUE TITLE
Non-convergence of advection solver in parallel

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#938]
The attached parameter file crashes with 2 MPI processes in the 7th time step (mesh refinement happens in 5th timestep), but runs in serial.

[spherical_shell.txt](https://github.com/geodynamics/aspect/files/330989/spherical_shell.txt)

**Comment by bangerth** [comment]
Can you show the error?

**Comment by gassmoeller** [comment]
*** Timestep 7:  t=2.96465e+07 years
   Solving temperature system... 

----------------------------------------------------
Exception on processing: 

--------------------------------------------------------
An error occurred in line <477> of file </home/rengas/Software/Aspect-Versionen/aspect/source/simulator/solver.cc> in function
    double aspect::Simulator<dim>::solve_advection(const aspect::Simulator<dim>::AdvectionField&) [with int dim = 2]
The violated condition was: 
    false
The name and call sequence of the exception was:
    ExcMessage (std::string("The iterative advection solver " "did not converge. It reported the following error:\n\n") + exc.what())
Additional Information: 
The iterative advection solver did not converge. It reported the following error:


--------------------------------------------------------
An error occurred in line <1109> of file </home/rengas/Software/deal.II-dev/include/deal.II/lac/solver_gmres.h> in function
    void dealii::SolverGMRES<VectorType>::solve(const MatrixType&, VectorType&, const VectorType&, const PreconditionerType&) [with MatrixType = dealii::TrilinosWrappers::SparseMatrix; PreconditionerType = dealii::TrilinosWrappers::PreconditionILU; VectorType = dealii::TrilinosWrappers::MPI::Vector]
The violated condition was: 
    iteration_state == SolverControl::success
The name and call sequence of the exception was:
    SolverControl::NoConvergence (accumulated_iterations, last_res)
Additional Information: 
Iterative method reported convergence failure in step 1000. The residual in the last step was 1.94167e+19.

This error message can indicate that you have simply not allowed a sufficiently large number of iterations for your iterative solver to converge. This often happens when you increase the size of your problem. In such cases, the last residual will likely still be very small, and you can make the error go away by increasing the allowed number of iterations when setting up the SolverControl object that determines the maximal number of iterations you allow.

The other situation where this error may occur is when your matrix is not invertible (e.g., your matrix has a null-space), or if you try to apply the wrong solver to a matrix (e.g., using CG for a matrix that is not symmetric or not positive definite). In these cases, the residual in the last iteration is likely going to be large.
--------------------------------------------------------

--------------------------------------------------------

Aborting!
----------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
[log.txt](https://github.com/geodynamics/aspect/files/331014/log.txt)

**Comment by gassmoeller** [comment]
Whatever the problem was it is gone in the current development version. Closing this issue for now.
