### ISSUE TITLE
Use correct axes labels in depth average output files

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#945]
Right now, depth average output files using gnuplot format explain the columns in the output files as `<x> <y> ...`, despite the fact that the first two columns are time and depth.

This can now be changed following the merge of https://github.com/dealii/dealii/pull/2710 in deal.II.

**Comment by bobmyhill** [comment]
On it!

**Comment by bobmyhill** [comment]
Finishing this will require the next release of deal-ii, as data_out_stack.write() doesn't currently allow the use of gnuplot_flags. See [dealii/dealii#4393](https://github.com/dealii/dealii/pull/4393)

**Comment by bobmyhill** [comment]
Implementation here: https://github.com/bobmyhill/aspect/tree/correct_gnuplot_labels

**Comment by bobmyhill** [comment]
Back on it!!!

**Comment by jdannberg** [comment]
This was fixed by #2320.
