### ISSUE TITLE
ASPECT compiling issue on Mac OS

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#950]
Help needed!
The compilation failed for the most resent ASPECT git development version with both dealii-8.4.1.dmg  and dealii-8.4.0.dmg  on a Mac OS machine.

Below are the error messages
[100%] Linking CXX executable aspect
Undefined symbols for architecture x86_64:
  "std::__1::pair<dealii::parallel::distributed::Triangulation<2, 2>::active_cell_iterator, dealii::Point<2, double> > dealii::GridTools::find_active_cell_around_point<2, dealii::parallel::distributed::Triangulation, 2>(dealii::Mapping<2, 2> const&, dealii::parallel::distributed::Triangulation const&, dealii::parallel::distributed::Triangulation<2, 2>::active_cell_iterator<2, double> const&)", referenced from:
      aspect::Particle::Generator::Interface<2>::generate_particle(dealii::Point<2, double> const&, unsigned int) const in interface.cc.o
      aspect::Particle::Interpolator::FirstParticle<2>::properties_at_points(std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<2>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<2> > > > const&, std::__1::vector<dealii::Point<2, double>, std::__1::allocator<dealii::Point<2, double> > > const&, dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&) const in first_particle.cc.o
      aspect::Particle::Property::Manager<2>::initialize_late_particle(aspect::Particle::Particle<2>&, std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<2>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<2> > > > const&, aspect::Particle::Interpolator::Interface<2> const&, dealii::Vector<double> const&, std::__1::vector<dealii::Tensor<1, 2, double>, std::__1::allocator<dealii::Tensor<1, 2, double> > > const&) const in interface.cc.o
      aspect::Particle::World<2>::sort_particles_in_subdomains_and_cells() in world.cc.o
      aspect::Particle::World<2>::move_particles_back_into_mesh(std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<2>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<2> > > >&, std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<2>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<2> > > >&, std::__1::multimap<unsigned int, aspect::Particle::Particle<2>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, aspect::Particle::Particle<2> > > >&) in world.cc.o
      aspect::Particle::World<2>::send_recv_particles(std::__1::multimap<unsigned int, aspect::Particle::Particle<2>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, aspect::Particle::Particle<2> > > > const&) in world.cc.o
  "std::__1::pair<dealii::parallel::distributed::Triangulation<3, 3>::active_cell_iterator, dealii::Point<3, double> > dealii::GridTools::find_active_cell_around_point<3, dealii::parallel::distributed::Triangulation, 3>(dealii::Mapping<3, 3> const&, dealii::parallel::distributed::Triangulation const&, dealii::parallel::distributed::Triangulation<3, 3>::active_cell_iterator<3, double> const&)", referenced from:
      aspect::Particle::Generator::Interface<3>::generate_particle(dealii::Point<3, double> const&, unsigned int) const in interface.cc.o
      aspect::Particle::Interpolator::FirstParticle<3>::properties_at_points(std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<3>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<3> > > > const&, std::__1::vector<dealii::Point<3, double>, std::__1::allocator<dealii::Point<3, double> > > const&, dealii::TriaIterator<dealii::CellAccessor<3, 3> > const&) const in first_particle.cc.o
      aspect::Particle::Property::Manager<3>::initialize_late_particle(aspect::Particle::Particle<3>&, std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<3>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<3> > > > const&, aspect::Particle::Interpolator::Interface<3> const&, dealii::Vector<double> const&, std::__1::vector<dealii::Tensor<1, 3, double>, std::__1::allocator<dealii::Tensor<1, 3, double> > > const&) const in interface.cc.o
      aspect::Particle::World<3>::sort_particles_in_subdomains_and_cells() in world.cc.o
      aspect::Particle::World<3>::move_particles_back_into_mesh(std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<3>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<3> > > >&, std::__1::multimap<std::__1::pair<int, int>, aspect::Particle::Particle<3>, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, aspect::Particle::Particle<3> > > >&, std::__1::multimap<unsigned int, aspect::Particle::Particle<3>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, aspect::Particle::Particle<3> > > >&) in world.cc.o
      aspect::Particle::World<3>::send_recv_particles(std::__1::multimap<unsigned int, aspect::Particle::Particle<3>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, aspect::Particle::Particle<3> > > > const&) in world.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [aspect] Error 1
make[1]: *** [CMakeFiles/aspect.dir/all] Error 2
make: *** [all] Error 2

**Comment by gassmoeller** [comment]
We should find a way to consistently test ASPECT and Deal.II (set up a tester for it). Unfortunately, it is not possible to run MacOS in a virtual machine, so we need a physical machine for it. Somebody volunteering to sponsor a machine?

**Comment by bangerth** [comment]
@tjhei already suggested the solution (update compiler), but I'd like to add that this looks like a compiler bug (in the mangler or demangler): it complains about the function 
```
GridTools::find_active_cell_around_point<2, parallel::distributed::Triangulation, 2>
  (Mapping<2, 2> const&, 
   parallel::distributed::Triangulation const&, 
   parallel::distributed::Triangulation<2, 2>::active_cell_iterator<2, double> const&)
```
but there is no such function in deal.II...

**Comment by yinghe616** [comment]
I am not sure if this is the only way to do but it does work after updating the OS to the newest one EI Capitan and updating the Xcode to the newest version 7.3.0. Thanks @tjhei

**Comment by trajaona** [comment]
It seems working for me as well.
