### ISSUE TITLE
number of depth slices in seismic_anomalies

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#96]
The computation of seismic anomalies in seismic_anomalies.cc is confusing and, currently, uses a fixed number of 50 depth slices. Document this better, make n_slices a parameter.

**Comment by bangerth** [comment]
Whoever implements it, be mindful of the issues discussed in #547

**Comment by bobmyhill** [comment]
I can take care of this little guy

**Comment by gassmoeller** [comment]
Fixed by #1545
