### ISSUE TITLE
Cannot output the initial adaptive refinement

### ISSUE THREAD

**Issue by jrglez** [geodynamics/aspect#964]
Hello,
I am trying to run a model with 5 initial global refinements and 2 initial adaptive refinements. I am trying to visualize each step of the the initial adaptive refinement, so I have set "set Run postprocessors on initial refinement = true". However, the output files include the globally refined mesh, and the last adaptively refined mesh, but not all the adaptive refinement cycles.
I have attached the parameter file.

Thanks,

Juan

[spherical_shell.txt](https://github.com/geodynamics/aspect/files/333347/spherical_shell.txt)

**Comment by gassmoeller** [comment]
Hi Juan,
this is definitely a problem, and is currently already tracked as #802. I will open a pull request soon that should fix the issue.

**Comment by gassmoeller** [comment]
Juan can you check with a recent developer version if your problem has been solved? #969 should have solved it. If so, feel free to close the issue.

**Comment by jrglez** [comment]
I was trying that on the CIG workshop virtual machine. I will not be able to check with a developer version for a while, but I will close the issue anyway.
Thanks.
