### ISSUE TITLE
Entropy stabilization when shearing

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#967]
We apply standard entropy viscosity to a shear bands test and see oscillations where the velocity is small. This is because the stabilization is scaled with the maximum velocity in a cell, and does not see shearing. 
@tjhei suggests to use `max(max_velocity, strain_rate*h)`.

**Comment by bangerth** [comment]
This is a duplicate of #293.

**Comment by tjhei** [comment]
Not quite, because we have a nonzero but small velocity in every cell.

**Comment by bangerth** [comment]
But aren't these both symptoms of the same underlying cause?
