### ISSUE TITLE
formatting of .cc files in the manual

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#968]
Some of the .cc files that are used in cookbooks in the manual (for example `Prescribed internal velocity constraints`) have very long lines that go over the margin of the page. What can we do to automatically format this better?

**Comment by bangerth** [comment]
I suspect that we should simply wrap these lines in the files that we include. Might also want to wrap these lines in the files the manual snippets come from.

**Comment by jdannberg** [comment]
This was addressed by #970.
