### ISSUE TITLE
Modularize Nonlinear solvers

### ISSUE THREAD

**Issue by class4kayaker** [geodynamics/aspect#972]

**Comment by tjhei** [comment]
- move solvers into separate file
- make them plugins
- use better names for the solvers
- put parameters into subsections
- add new schemes: "Stokes once" for example
- backwards compatibility?

**Comment by tjhei** [comment]
I am sketching a solution right now...

**Comment by gassmoeller** [comment]
A part of this issue has been addressed by #1850, and the other part is described in more detail in #1279, therefore I will close this issue to avoid duplication.
