### ISSUE TITLE
Mac OS X: Check that .dmg compiler equals the one used for ASPECT

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#988]
We've run into problems with several people who happened to have a different compiler on their system than the one used to build the .dmg. We should figure out a way to ensure that they are the same, during cmake time for aspect.

@luca-heltai -- is there a way to export the compiler version from the .dmg, so that we can test it somewhere?

**Comment by bangerth** [comment]
See the discussion in #986.

**Comment by luca-heltai** [comment]
If they installed the dmg, they also have the compiler used to build the dmg. 

If the plan is to use the dmg and compile aspect afterwards, they should make sure they set the paths correctly...

**Comment by bangerth** [comment]
Hm, interesting. We had at least a couple of cases where this must have happened. Next time we have one of these cases, we ought to investigate the issue with the paths then...
