### ISSUE TITLE
Reuse the compositional matrix if more than one compositional filed need to be solved?

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#990]
When solve the compositional advection equations for multiple compositional fields, the left hand side matrix in most of time will be the same (mass matrix+dt *advection matrix), so only the right hand sides vector will be differ. Currently the codes just reassemble the matrix for each compositional field and then solve. 
Maybe we could only assemble LHS matrix once and save some assembling time for solving the multiple compositional filed case... ?

**Comment by bangerth** [comment]
That's not true. The left hand side matrix contains the artificial viscosity term, which is dependent on the solution (i.e., the specific compositional field we solve for). At least this term has to be re-assembled for each field, and that negates almost all of the benefit of avoiding some assembly.

**Comment by yinghe616** [comment]
ah, I see what you meant. But for DG with upwind-flux, it's all the same...

**Comment by bangerth** [comment]
I suppose so, assuming that the upwind flux only depends on the velocity field and not on the compositional field. (I.e., if the flux operator is linear.)
